### ISSUE TITLE
Add Watcher V3

### ISSUE THREAD

**Issue by valantislevas** [Ombi-app/Ombi#1793]
Hello is possible to know when ombi v3 can communicate with watcher3?

thanks for the great job

**Comment by tidusjar** [comment]
in around 4-6.

**Comment by Flopon** [comment]
Any news about Watcher support in Ombi v3 ?

anyway, thank you for the job, the new version is much more stable on linux than the old one.

**Comment by tidusjar** [comment]
No plans, only you guys have requested this.

**Comment by Flopon** [comment]
OK, sad, I started using Ombi only because of this integration with Watcher.

I would try to fix that myself when I have some time.

**Comment by Flopon** [comment]
As an alternative, is it possible to send an unmonitored request to Radarr / Sonarr?
It's one of the reasons that made me prefer Watcher over Radarr.

Regards.

**Comment by chet-manley** [comment]
Can we revisit this as a legitimate feature request? CouchPotato is basically dead, and most people have moved to its spiritual successor, Watcher3. It seems this integration was available in v2, but not v3 (#844), and I imagine there were minimal (if any) breaking changes to the API, making re-integration of the feature a low-hanging fruit? With 21 upvotes so far, [feature request 251](https://feathub.com/tidusjar/Ombi/+251) is now the 15th highest requested feature out of 287.

**Comment by tidusjar** [comment]
Not stale

**Comment by jandreaucodes** [comment]
+1, I'd love to see this integration in Ombi v3, too!

**Comment by tidusjar** [comment]
Currently concentrating on V4, but this can be added as part of that.

**Comment by ridizy** [comment]
FYI - This is an active fork of Waatcher 3 that many people have switched to: https://github.com/barbequesauce/Watcher3

**Comment by jandreaucodes** [comment]
Is still still planned for v4? I don't see a card on either the 4.0 or 4.1 projects.

**Comment by tidusjar** [comment]
Does anyone still want this

**Comment by jandreaucodes** [comment]
Yea. Me. Forever. Please and thank you.

**Comment by forkwhilefork** [comment]
bump, I want this

**Comment by moonbuggy** [comment]
If anyone's interested, I did a thing: https://github.com/moonbuggy/watcher3-api-adapter

It needs some more work in a few places I'm already aware of, and there's probably some problems I haven't noticed yet, but it looks like it's doing at least the bare minimum that's required without it or Ombi throwing exceptions around like confetti. (There was a bit of a party initially. :))

Anyway, it's fairly well behaved at this stage and should be usable. If things go to plan I'll find and fix any significant issues that pop up in the next few weeks, as I continue testing beyond the bare minimum.
