### ISSUE TITLE
Self un-subscribe link in bottom of newsletter for users to unsubscribe themselves. 

### ISSUE THREAD

**Issue by pironic** [Ombi-app/Ombi#2137]
As directed in discord... i should make a github issue to track the request for this feature request. Would be great if users who receive the newsletter can unsubscribe themselves.

**Comment by tidusjar** [comment]
Ohhh opt in is a good idea. Not sure where to place it. In the update details I guess.

**Comment by tidusjar** [comment]
Not stale

**Comment by 40b0a3cd** [comment]
My servers (and gmail for this reason presumably as well) are classifying ombi mail as spam due to the lack of unsubscribe link. I tend to agree with the classification.

Newsletter-type mail really needs an unsubscribe link in my opinion.

**Comment by controlol** [comment]
Is it possible to do this through the api? I looked at the swagger API documentation but didn't find anything on changing the roles of a user...

**Comment by ePHDiSK** [comment]
Just allowing something like a mailto:{adminemail} would be a really big help.  

`<a href="mailto:{adminemail}?subject=Remove Me&body=Please remove me from this list">Unsubscribe</a>`

**Comment by mrjohnpoz** [comment]
Yeah even ability to click a link to send email to admin would be great addition.

**Comment by shawngrimes** [comment]
Is there a way to turn the newsletter off per user?

**Comment by Maregas** [comment]
Hi, still no solution on this topic ?

**Comment by ePHDiSK** [comment]
> 
> 
> Hi, still no solution on this topic ?

In Ombi v4 you can use HTML in your message.  That helps lower the SPAM score. No actual Unsubscribe link has been implemented.  

This is what I use.
`
Please click here to: <a href="mailto:yourreply@email.com?subject=Remove Me&body=OPT-OUT">Unsubscribe</a>`

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈
