### ISSUE TITLE
[Feature Request] Sonarr tags

### ISSUE THREAD

**Issue by Do-while-Bacon** [Ombi-app/Ombi#2306]
Love the addition of a separate root folder for anime. Thanks for that! I find that anime is hard for Sonarr because there are so many different subtitle styles, languages, and fansubbing groups. It's the only media that I utilize Sonarr tags for so I can restrict downloads to the fansubbers that I want on my server.

I would be thrilled to have a way for anime imported from Ombi to be automatically tagged accordingly. Not sure how difficult this would be to add, but I would guess it could be handled very similarly to the way root folder assignment is handled?

**Comment by tidusjar** [comment]
Note to self: `/api/Restriction` GET to get the tags available.
There is a `tags[]` on the series to POST over.

@Do-while-Bacon How would you expect this to work for existing series. 

e.g. You have series in Sonarr with no tags, you request season 5. Would it leave the tags alone, or would it add it?

Would you only expect it to add the tags to brand new series requested?

**Comment by Do-while-Bacon** [comment]
@tidusjar I never considered how individual season would handle the addition of tags because, admittedly, my users rarely ever request anything but full series. Nevertheless, I suppose it's possible that I could have a partial series on Plex that is not being tracked by Sonarr, and, a request comes in for another season. In that case I would want the tag to be applied.

So, perhaps the ideal logic would be:

If the request is for a full series, apply the default tag (unless manually overridden?).
If the request is for a partial series that is not monitored by Sonarr, apply the default tag.
If the request is for a partial series that is monitored by Sonarr and currently un-tagged, do not apply the default tag.

Of course, that would depend on Ombi being "aware" of a series pre-existing in Sonarr, and I don't know if it works that way.

**Comment by majora2007** [comment]
From my perspective, the way I use tags in Sonarr is to make my Anime (aside from root path change) which allows me to restrict to containing certain Fansubber tags. 

If I were to expand Ombi to add the ability to set a tag, such as "anime", I would expect that:
On a full series, it applies the tag. 
On a partial series, it adds the tag to any existing tags.

It is important to note, Ombi is not a tag manager for -arr products. It should just allow a tag to be added with the request.

**Comment by SCRPD** [comment]
This would be a great feature now for anime. Sometimes arr software downloads sub groups that are just terrible. I mostly prefer release groups like HorribleSubs because they're usually out the night of airing since they don't do any of the translation.

**Comment by tidusjar** [comment]
My proposed solution.

In the sonarr settings there will be a set of tags you can assign for regular TV and Anime (Similar to how the root folder is done and quality profiles).

The tag will be appled to every request to Sonarr for example if the series already exists then we will add the tag.

We would allow multiple tags to be selected in the settings for regular and anime.

Any objections/suggestions?

**Comment by GiowGiow** [comment]
> My proposed solution.
> 
> In the sonarr settings there will be a set of tags you can assign for regular TV and Anime (Similar to how the root folder is done and quality profiles).
> 
> The tag will be appled to every request to Sonarr for example if the series already exists then we will add the tag.
> 
> We would allow multiple tags to be selected in the settings for regular and anime.
> 
> Any objections/suggestions?

That would be awesome!

**Comment by tidusjar** [comment]
Not stale

**Comment by mbc0** [comment]
Hi, 

Any news on this? I use the tag "x265" to ensure sonarr only downloads HEVC releases rather than X264 Many Thanks!

**Comment by savi6566** [comment]
I would also really like this feature. I have to manually add each show to Sonarr so that my release profiles are correct. I have one for tv shows and one for anime. If I let it go through as is, it would most likely download episodes that I don't want (wrong subs, wrong release group, etc)

Much like how you can select quality profiles for TV or Anime, I'd like another dropdown for Release Profiles.

I see this was proposed about 2 years ago, what happened?

**Comment by Popupkiller** [comment]
Hey. I have content loaded into Sonarr/Radarr through Trakt/IMDB lists on my own content. so I can add tags to those.
I use Ombi mostly so friends can request stuff. I would have liked it if it could apply a tag to content so that I can see that this show came from Ombi, and not one of my Trakt/imdb lists. 
Did this feature request ever end up being worked on?

**Comment by sephrat** [comment]
Implemented in v4.31.0
