### ISSUE TITLE
Add option to select libraries in Emby

### ISSUE THREAD

**Issue by bozrdang** [Ombi-app/Ombi#2389]
#### Ombi build Version:

V 3.0.347

#### Update Branch:

Dev

#### Media Server:

Emby

#### Media Server Version:

3.4.1.0

#### Operating System:

Docker/Linux

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

N/A

#### Problem Description:

When Emby has multiple libraries, Ombi seems to select the one to cache on it's own.  So media in the other libraries is not seen by Ombi.  For example:  I have both a Movies and All Movies library in Emby and Ombi seems to have cached the Movies library because Ombi does not see movies that are in the All Movies library but missing in the Movies library.

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by bozrdang** [comment]
I am confused.  I see this says closed and link to another issue that says closed because it is a dupe of this one?  Has this issue been sorted?  If so I don't see how to enable it.

**Comment by tidusjar** [comment]
No it's not been done yet. This issue is still open.

**Comment by tidusjar** [comment]
Not stale

**Comment by mbc0** [comment]
Hi,

Any news on this? :-)

**Comment by MLWeber** [comment]
It would be nice to have this as it is the only reason I'm still running Plex next to emby.

**Comment by bozrdang** [comment]
I would like to bump this request as it is sorely missing in my opinion.  I have dual libraries for both movies and TV shows in Emby.  The reason is that friends and family request movies and shows that I am not interested in and I don't want all of their stuff showing up in my library.  It works fine except that Ombi arbitrarily selected my library as THE library so any media that goes to their library doesn't  show as already existing or as available to them.  

It would be awesome if Onbi would allow the admin to select the library to use.

**Comment by harrv** [comment]
Although perhaps not a solution for everything that is being asked for, one quick way to give Ombi admins more flexibility in which items get cached by the EmbyCacher would be to change the way the EmbyCacher queries Emby for content. I assume that currently that is done by sending a GET request with query parameters to the /Items API endpoint. There is another, almost identical endpoint at /Users/{UserId}/Items that takes the same query parameters but limits the results to those that the identified user has permission to see. If you implemented it that way, and asked the admin to provide an Emby user that has the privileges that they way the Emby content cacher to have, then Ombi would only see what the admin wanted it to see.

Of course, that is still one global view of Emby content, not individualized to each user, but at least it would give the admin a bit more control and flexibility and isn't a huge change from how it works now. Just a suggestion, in case you find it useful. Thanks.

**Comment by vw-kombi** [comment]
Either this enhancement, or the change to use a user would solve my issue that I dont want ombi to read specific libraries.  No point sending out a newsletter to end users when they dont have access to certain stuff - specifically recorded TV - My PVR is for internal use only, and Emby uses the built in library 'Recordings' for this, which is read by ombi and hence included in the newsletter.  My dad saw this and then deleted all the same shows from his PVR, thinking they would remain in Emby like normal TVShows/Movies - hence the confusion.

**Comment by vw-kombi** [comment]
I have had to remove the newsletter option due to this issue with Emby.
My father saw a load of my TV recordings that went out with the newsletter, so he assumed he did not have to keep his and deleted them.
But no access to my TV recordings outside my home.
It is just confusing to remote users to see all this bundled in with the 'New TV Shows'
I would be happy with the above option of a user to be used to access emby and that user only has access to the shows you want to be sent out.  That would be all the control I need.

**Comment by harrv** [comment]
Thanks @tidusjar , I'm looking forward to trying this new feature. Unfortunately, whenever I try to configure it by clicking the "Load Libraries" button I get an onscreen message that says [Object object] and then never see any Libraries appear for selection. I've tried with current versions of Firefox and Edge.

![image](https://user-images.githubusercontent.com/7154372/126217590-5064657d-aed1-460d-938c-10f696229928.png)

**Comment by tidusjar** [comment]
Oh that’s odd!

mind sharing the API response from the browsers developer console?

press F12 and then go to the Network tab, then press Load libraries and there should be an entry. Click that and then press the response tab. 

If it contains any personal information you do not want to share feel free to email it to me at tidusjar@gmail.com

**Comment by bozrdang** [comment]
I get the same thing.  Here is the info you requested:

`{"error":"Object reference not set to an instance of an object."}`

**Comment by harrv** [comment]
Yes, I get the same as bozrdang. In case you want more context, Firefox let me export the whole request/response as JSON so you can see the details about both the request and the response, including headers, etc., in the attached file. Wherever you see all caps such as MYDOMAIN or BEARERTOKEN that was just me replacing sensitive data, but there were real values there.

[request-response.txt](https://github.com/Ombi-app/Ombi/files/6844044/request-response.txt)

**Comment by harrv** [comment]
I got the same as bozrdang. In case you want more context, Firefox let me export the whole request-response as JSON, including the request and response headers and bodies, etc. File containing the JSON is attached. 

Wherever you see all caps, such as MYDOMAIN or BEARERTOKEN, there were real values there that I replaced to remove sensitive data. Thanks.

[request-response.txt](https://github.com/Ombi-app/Ombi/files/6844080/request-response.txt)

**Comment by tidusjar** [comment]
Just pushed an update that will hopefully fix this issue! Give it a go and let me know!

**Comment by bozrdang** [comment]
The latest update now allows me to load libraries and select them, but the submit button stays greyed out so there is no way to save the selections.  Reloading the page just show the load libraries button again and doing that shows then all unselected.

**Comment by tidusjar** [comment]
Press the discover button and then save. I'm aware of that bit

**Comment by bozrdang** [comment]
That worked.  Thanks!

**Comment by vw-kombi** [comment]
Yay - I have waited so long for this - Fantastic.  Now the newsletters can go back out without all the 'extra' media on them that users cant see.

**Comment by cavemandaveman** [comment]
> Wait, so you are not monitoring a library and a movie in that library is appearing as available?

Correct

> This could have be available before the changes? Deleting your OmbiExternal.db and then running the Emby sync would be useful to do in this case

What is in OmbiExternal.db? Would current requests, history of requests, configured users, etc. be deleted? Or would it be only references to what is in the jellyfin library that is deleted?

**Comment by tidusjar** [comment]
It's documented here https://docs.ombi.app/info/faq/#database-uses

But basically it only stores a cache of data from your media server so we don't have to keep querying it

**Comment by cavemandaveman** [comment]
Ok thank you @tidusjar that worked!

**Comment by harrv** [comment]
OK, my issue was the same. I use Maria DB so couldn't just delete the OmbiExternal.db file. I had previously tried using the "Clear Data And Resync" button and that did not work (things from non-selected libraries still showed as available). But I managed to use phpmyadmin to drop the OmbiExternal db and that took care of it.

I previously reported that things I delete from my Emby server never get removed from the OmbiExternal items cache (unless I manually drop the table, of course), and that is still an ongoing problem, but not directly related to this issue. Thanks Jamie.
