### ISSUE TITLE
Slack notification agent, with discord webhook url not working as expected.

### ISSUE THREAD

**Issue by goldenpipes** [Ombi-app/Ombi#2448]
#### Ombi build Version:

V 3.0.3567

#### Update Branch:

Develop

#### Media Sever:

Plex

#### Operating System:

Win 10 x64 1803

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

```

#### Problem Description:

using a discord webhook as a slack webhook with /slack appended should function properly

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

create a webhook on discord, enter it in slack notifications on ombi settings appending `/slack`

submit and hit test. NOTHING!

**Comment by grambo1980** [comment]
I am also having issues.  I know slack is moving away from webhooks so maybe it has something to do with that.  My test works and Ombi posts in the slack channel, but when something is requested it doesn't.  Then today out of no where when I approved a few things it posted once.  But then I marked something as available again it said nothing. 

soooo I have no idea what it's deal is.

**Comment by tidusjar** [comment]
@grambo1980 This is to do with using the Discord notification...

**Comment by grambo1980** [comment]
apparently it is.  I guess i should read better next time, my apologies.

**Comment by Wdavery** [comment]
Also having this issue. Following the same process for notifications from Radarr to Discord and it works flawlessly

**Comment by Snipey** [comment]
Has this issue been resolved?

**Comment by goldenpipes** [comment]
So i think i figured it out.

Ombi is adding a trailing slash to the webhook url. i looked in the logs and it give the webhookurl with a trailing "/" at the end, if you copy and paste the url into a browser with the slash it 404's without the slash if succeeds.

**Comment by goldenpipes** [comment]
this is in ombi log:
`Line 80 : 2019-12-11 11:45:50.968 -06:00 [Error] StatusCode: NotFound, Reason: NOT FOUND, RequestUri: https://discordapp.com/api/webhooks/589962433691385866/fmfN4ExFRTWJ6SKqKULoUzXriI-e70fvBQcvaZlLc-sMR_guz_8tkcNMRglbkqr37nT3/`

that trailing slash leads to a NOT FOUND.

url without the slash works as expected.
