### ISSUE TITLE
Pushover not sending messages correctly

### ISSUE THREAD

**Issue by phairplay** [Ombi-app/Ombi#2463]
#### Ombi build Version:

V 3.0.3587

#### Update Branch:

Master

#### Media Sever:

Plex

#### Operating System:

Windows 10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

no error in log relating to pushover

```

#### Problem Description:

Pushover not sending message when issue reported or new film requested.

#### Reproduction Steps:

confirmed the pushover settings are correct hit test and the test message came through, logged in as one of my users and made a request, yet no message come through.

**Comment by tidusjar** [comment]
What does your message look like? The notification template

**Comment by phairplay** [comment]
I've not changed it from the default one

Issue

Hello! The user '{UserName}' has reported a new issue for the title {Title}! </br> {IssueCategory} - {IssueSubject} : {IssueDescription}

Request
Hello! The user '{UserName}' has requested the {Type} '{Title}'! Please log in to approve this request. Request Date: {RequestedDate}

**Comment by tidusjar** [comment]
Can you try and take out the `'` and then see if it sends?

**Comment by phairplay** [comment]
Yep that solved it.
Many thanks for the quick reply

**Comment by gold007eye** [comment]
Would this issue be considered fixed as part of #2385 that was fixed in Dev?
