### ISSUE TITLE
Request - TV episode air date on Newsletter

### ISSUE THREAD

**Issue by ePHDiSK** [Ombi-app/Ombi#2676]
#### Ombi build Version:

V 3.0.3988

#### Update Branch:

Master

#### Media Sever:

Plex

#### Problem Description:

It would be nice to have the episode(s) air date in the Newsletter next to the respective episode.  Currently it only shows the Show launch release year.  

#### Badly edited example: 

![image](https://user-images.githubusercontent.com/45718819/49689229-1ebd2580-fae4-11e8-8e33-ab7c24a3bf24.png)

#### Reproduction Steps:

Look at a generated newsletter with new TV episodes.

**Comment by mariombaltazar** [comment]
Hi,
can i contribute with this issue?

**Comment by tidusjar** [comment]
Yeah sure!!

**Comment by peterszeles** [comment]
Hello,
i would like to contribute with this issue but I see @mariombaltazar took it on 28 august. Is it still actual or are you working on it?

**Comment by tidusjar** [comment]
Nope, no one is working on this! 

If you have any issues or questions please feel free to reach out on discord.

**Comment by peterszeles** [comment]
Ok, than I will try to fix this issue :) I have already cloned it to my pc. Are there any recommendations how to run this app?

**Comment by tidusjar** [comment]
So the best way would be to run Visual Studio, you can use the Community Edition which is free.
And just set the Ombi.csproj as the startup project and Visual Studio will do all of the work for you.

I do have a more detailed guide on how to debug Ombi when the next major release comes out (due to slightly different frameworks).

**Comment by AdamWorley** [comment]
I see this has been around for over year, mind if I try to fix it?

**Comment by AdamWorley** [comment]
What would be the best way to format the air date?

I was thinking that for:
* single date - YYYY-MM-DD
* run of episodes start-end:
  * Same date - YYYY-MM-DD
  * Same month - YYYY-MM
  * Same year - YYYY-MM - MM
  * Multiple years - YYYY-MM - YYYY-MM

**Comment by tidusjar** [comment]
Sure!

I would say for a run of episodes Same Month would be the best option

**Comment by Abhi441** [comment]
I want to fix this bugs. Kindly Arange  zoom meating for give kt.

**Comment by tidusjar** [comment]
@Abhi441 what?

**Comment by sephrat** [comment]
This has been part of Ombi for quite some time now. Closing.
