### ISSUE TITLE
"All seasons" request bug when the last season is already available.

### ISSUE THREAD

**Issue by pyto00** [Ombi-app/Ombi#2709]
#### Ombi build Version:

V 3.0.4093

#### Update Branch:

Develop
#### Media Sever:

Plex

#### Operating System:

(Place text here)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

No logs for this problem

```

#### Problem Description:

All seasons request doesnt process requests when the last or any one other season of that show is already available. You will have to manually request the remaining seasons one by one.

#### Reproduction Steps:

Take any random Tv Show with multiple seasons and request the last or any other one season.

When available on the server then make a "All Seasons" request for the same show.
It gives you this "notification"

""We already have episodes requested from series The Big Bang Theory""

But it doesn't request the other remaining seasons to be fetched.
You will have to manually request the remaining season per season.
And for shows with +20 seasons, this is a pain in the ass xD

--

**Comment by tidusjar** [comment]
Not stale

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈
