### ISSUE TITLE
Not recognizing movies as available from mobile app

### ISSUE THREAD

**Issue by roborobp** [Ombi-app/Ombi#2861]
**Describe the bug**
Ombi will add movies and TV shows as available from the web view but not showing the same within the mobile app (requestable)

**To Reproduce**
Searched movies within the web app to see they are available, then from the mobile app and see requestable.

**Expected behavior**
All available movies within the mobile app to match what is in web view

**Screenshots**
https://i.imgur.com/I0gONjh.png
https://i.imgur.com/AeveEm7.png

**Logs (Logs directory where Ombi is located)**
Log folder is empty

**Desktop (please complete the following information):**
 - OS: Windows 10
-  Pixel 2 XL Android 9 Feb 2019 patch 

**Ombi Version (please complete the following information):**
 - Server Version 3.0.4256 (clean installation)
- Phone version 1.8 build 106
- Plex Media Server 1.14.1.5488

**Additional context**
.

**Comment by krisklosterman** [comment]
I am having the same issue

**Comment by mariotacke** [comment]
Could this be related to my issue in #2985? The web client actually makes a `GET` request for every movie after you received the search results. If the mobile version only relies on the search results, I can see why this would be happening.

**Comment by tidusjar** [comment]
That is correct

**Comment by Po0wnage** [comment]
Im facing the same issue on android. Tv shows are marked as available but movies arent and making a request will download the movie again.

**Comment by gdtms247** [comment]
Is there any update or fix for this issue? If not do we have a way to disable users from having mobile access? I can't support having movies submitted that already exist and having to filter through them.

**Comment by jrb84780** [comment]
I am also having this issue

**Comment by thomasbiddle** [comment]
Is there a public repo for the mobile apps?

**Comment by twanariens** [comment]
This issue was fixed a long time ago and should no longer exist with the new Ombi app
