### ISSUE TITLE
Notifications for resolving Issues do not work with Enable In Progress State (Telegram)

### ISSUE THREAD

**Issue by enchained** [Ombi-app/Ombi#2906]
**Describe the bug**
I want to be notified of issue creation and resolving, but I use the "in progress" option for my issues, and when I use it I don't get notified when I resolve it. When I stop using it I get notified about resolve event.

**To Reproduce**
1. Set up Telegram notifications with a successful test (probably same with any other agents but I don't have any other notification agents set up).
2. In **Settings** - **Configuration** - **Issues** check **Enable**.
3. Create Issue and get notification.
4. Resolve issue and get notification.
5. In **Settings** - **Configuration** - **Issues** check **Enable In Progress State**.
6. Create Issue and get notification.
7. Mark In progress and then Resolve issue and get no notifications at all.

**Expected behavior**
There should be a notification for Resolve with In Progress option checked.
Also it would be nice if there was some trigger for Issue In progress notifications.

**Logs (Logs directory where Ombi is located)**
There is no file for that day in the Logs folder. Probably notifications need more logging? Or are there different logging level settings hidden somewhere?

**Ombi Version (please complete the following information):**
 - Version - 3.0.4256
- Media Server - Plex

**Comment by tidusjar** [comment]
Thanks for the report, don't worry about the logs, it seems that it's probably something i've missed in code rather than it erroring on the server.

**Comment by sephrat** [comment]
Seems to work fine with webhooks now. Closing.
