### ISSUE TITLE
User last login times are incorrect\off

### ISSUE THREAD

**Issue by muffpistol** [Ombi-app/Ombi#2925]
**Describe the bug**
The last login times for the users in the User Management tab are incorrect and are about 3 hours off (ahead) of the actual logged in time.  I have not found any customizable setting in Ombi which could be responsible for this, like time zones that are set incorrectly, etc.  

**Expected behavior**
User login times should be accurate to the time zone that is used by the server\PC where Ombi is installed, or perhaps the Plex server that its connected to (both are the same in my case).  

**Desktop (please complete the following information):**
 - OS: Windows Server 2012 R2

**Ombi Version (please complete the following information):**
 - Version 3.0.4256
- Media Server: Plex

**Comment by tidusjar** [comment]
IIRC it is using your browser's settings.

**Comment by muffpistol** [comment]
Im using Chrome and to my knowledge it has no time zone settings anymore, but instead pulls from the OS.  I could not find any time settings in the Chrome settings either.  My OS is set to the correct time zone and displays the correct time.

**Comment by tidusjar** [comment]
so what is displayed? Can you please provide an example>

**Comment by muffpistol** [comment]
I have attached screenshots.  I created a test account and logged in a few
minutes ago.  The server time was 8:37am EST but Ombi shows that the user
logged in at 12:37pm.

Test account before logging in
[image: image.png]

Test account after logging in, with the server time info shown
[image: image.png]

**Comment by tidusjar** [comment]
Unfortunately if you attach images via email, they don't get uploaded into Github, so I cannot see them

**Comment by muffpistol** [comment]
I created a test account and logged in this morning.  The server time was 8:37am EST but Ombi shows that the user logged in at 12:37pm.  

Test account before logging in
![test account before login](https://user-images.githubusercontent.com/49566160/56363393-2095a480-61ba-11e9-8653-d37f297d6980.PNG)

Test account after logging in, with the server time info shown
![test account after login](https://user-images.githubusercontent.com/49566160/56363404-28eddf80-61ba-11e9-8bc6-f91c671ccc5e.PNG)

**Comment by muffpistol** [comment]
sorry didnt mean to close it, hit the wrong button

**Comment by j-remy11** [comment]
Having the same issue as well. Time is correct on my computer. Not sure what else to try.

**Comment by adamNewell** [comment]
I am also seeing this issue

**Comment by davi1td** [comment]
It's using UTC time, has then been fixed to allow a setting to local time zone?

**Comment by dRuEFFECT** [comment]
+1 for wanting this to show local time instead of UTC time
