### ISSUE TITLE
Poster image disappears when selecting root folder or quality override

### ISSUE THREAD

**Issue by bobpullen** [Ombi-app/Ombi#3026]
**Describe the bug**
On the movie requests page of the admin interface, if I select a root folder or quality override next to an unapproved movie request, then the poster image for the movie in question disappears. Looking at the poster image URL it seems to change from, eg:-

https://image.tmdb.org/t/p/w300//4fqXDvdEicQnLTE2tlgqxECVR83.jpg

To:-

https://image.tmdb.org/t/p/w300/https://image.tmdb.org/t/p/w300/https://image.tmdb.org/t/p/w300//4fqXDvdEicQnLTE2tlgqxECVR83.jpg

I am using a reverse proxy (Caddy) and the base URL is set to '/' (the server is accessed at a URL in the format www.domain.tld

**To Reproduce**
1. Go to /requests where there is a pending movie request
2. Click on the root folder or quality override and select a different folder/profile
3. Note the poster URL for the movie disappears

**Expected behavior**
The poster image should remain visible

**Screenshots**
![ombi_1](https://user-images.githubusercontent.com/8457144/59720973-1757a100-9218-11e9-8823-b3572d5f58b8.jpg)
![ombi_2](https://user-images.githubusercontent.com/8457144/59720979-1aeb2800-9218-11e9-8f1c-81f6ab8d3bd0.jpg)

**Logs (Logs directory where Ombi is located)**
Don't seem to be able to locate the current day's logs, only previous days that have been rotated?

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro

**Ombi Version (please complete the following information):**
 - Version 3.0.4256
- Media Server Plex

**Additional context**

**Comment by goldenpipes** [comment]
+1000 this has happened to me as well.

**Comment by bobpullen** [comment]
This is still an issue on the latest build - 3.0.4680.

**Comment by docwho76** [comment]
I have this issue as well

**Comment by twanariens** [comment]
Should be fixed in the latest V4 build
