### ISSUE TITLE
Newsletter lists duplicates if both emby and plex servers are connected

### ISSUE THREAD

**Issue by aptalca** [Ombi-app/Ombi#3093]
**Describe the bug**
I have both an emby and a plex server set up with Ombi. In the gui interface, for each media item, it correctly lists both the plex and emby links. However, in newsletter emails, each new media item is listed twice, one linking to emby and one linking to plex.

**To Reproduce**
1. Set up plex and emby
2. Add new items
3. Enable newsletter

**Expected behavior**
Single listing for each media item. For the main link, perhaps it could allow for one server set as the default link in newsletter settings?

**Screenshots**
N/A

**Logs (Logs directory where Ombi is located)**
N/A

**Desktop (please complete the following information):**
 - OS: Docker stable

**Ombi Version (please complete the following information):**
 - Version 3.0.4680
- Media Server Plex & Emby

**Additional context**
N/A

**Comment by vsc55** [comment]
Hi,
I only have a Plex server configured and the same thing happens to me, duplicate movies arrive in the email.

![imagen](https://user-images.githubusercontent.com/13438676/91654756-f0e3f580-eaab-11ea-88df-1fe539e09fcc.png)

**Comment by Rickth64** [comment]
Same on v4.0.550.0

**Comment by sephrat** [comment]
Connecting Ombi to media servers with duplicate content is not supported for now. You should use multiple media servers only if they have separate content.
The complexity for fixing this isn't worth the edge case. I would suggest to disable one of the media servers.
