### ISSUE TITLE
Ombi - Mobile - Slack notification is sent despite movie already being approved

### ISSUE THREAD

**Issue by callahan22** [Ombi-app/Ombi#3107]
**Describe the bug**
This affects the mobile app on Android.
Slack notification is sent despite movie already being approved. Multiple presses of the "Approve" button cause multiple alerts to be sent.

**To Reproduce**
Steps to reproduce the behaviour:
1. Setup the Slack alert to alert you/user when a movie is available/approved.
2. Set up a user to allow for auto-approve of any movie they want (not required as the same result will happen if you just approve a movie for a user.
3. Request a movie that is available but you don't have in your library.
4. Wait for the movie to download & show as "Approved" in the Requests section of the app.
5. Staying within the "Requests" section of the app, find the movie that just downloaded and tap it.
6. You can now constantly tap the Approve button even though it's already approved and you'll see a warning saying that the movie has already been approved but Ombi will spam your Slack channel (as admin) as well as the user's Slack channel/Ombi app on their phone every time you press the Approve button.

**Expected behaviour**
If a movie is already approved, don't show the "Approve" button as available or grey it out as you've already added an extra button to movies that are available on this screen (a grey box saying "AVAILABLE"), so I don't see the point of allowing users to tap the "Approve" button here. Alternatively, keep the current design so that you get the warning but add a line in the code to check if the notification for available has already been sent and don't resend.

**Ombi Version:**
 - Version: Latest mobile version.
- Media Server: Plex/Radarr/Sonarr

**Comment by tidusjar** [comment]
Oh wow I didn't know that was an issue! Thanks for the report

**Comment by tidusjar** [comment]
!notstale

**Comment by goldenpipes** [comment]
!notstale

**Comment by twanariens** [comment]
No longer an issue with the latest Mobile app of Ombi
