### ISSUE TITLE
 [Enhancement] Delayed searching when creating requests with auto-approve 

### ISSUE THREAD

**Issue by Phault** [Ombi-app/Ombi#3115]
**Describe the bug**
In my experience creating (movie) requests is very slow and takes upwards of 30 seconds for the HTTP request to complete. This leads to a very poor user experience.
I suspect the lengthy response time comes from having Radarr or Sonarr search for the item before returning. I feel like whether searching is successful or not, is irrelevant to whether the request creation itself is.

I propose the request is created and the search for the item itself is added to a queue, that is run async. Or at least that a new thread is spawned to handle the search and the result is not awaited.

The system to do this already seems to be implemented if I understand the "Failed requests" section correctly.

**To Reproduce**
1. Have autoapprove on and a big Radarr library (~1000 items)
2. Search for a movie
3. Click request
4. Notice it takes upwards of 30 seconds before the HTTP request completes

**Expected behavior**
The HTTP request should complete in a reasonable time

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**

**Ombi Version (please complete the following information):**
 - Version 3.0.4723
 - Media Server Plex

**Additional context**

**Comment by tidusjar** [comment]
Adding a request to Radarr takes milliseconds for me. 

If you add a movie via the Radarr UI how long is it taking?

**Comment by Phault** [comment]
Adding to Radarr directly is very fast for me as well. 

I believe the issue might lie [here](https://github.com/tidusjar/Ombi/blob/2773b95906e33fe22f3dd0e98632afcfa98c86f8/src/Ombi.Core/Senders/MovieSender.cs#L156) where it fetches all 1000 movies from Radarr just to check whether it is already monitored.

**Comment by tidusjar** [comment]
Ah ok yeah I get it now. 

Two options really, split it into its own service and have a queue of requests to be sent. There will be a delay in when it is sent to Radarr (not much of a delay). Or look at ombis internal cache, since ombi has a local copy of what is on Radarr, risk being it might be out of date depending on if the user has changes the task schedule time

**Comment by Phault** [comment]
I think overall option 1 is cleanest and would work best. 

There's possibly a third easy option that avoids the Radarr.GetMovies call, which is just assuming the movie doesn't exist and handling the returned error from Radarr in case it does. This however doesn't work if the movie exists but is unmonitored, in which case to set it to monitored, we would need the Radarr movie id which is only retrievable by the GetMovies endpoint.

I thought about using their /movie/lookup endpoint and looking up the tmdbid, but even though it says the payload contains its monitored state, I just tested it and it said the movie was unmonitored, despite that not being true.

**Comment by tidusjar** [comment]
Not stale

**Comment by Omegaforts** [comment]
i'm encountering the same issue or similar issue where i got about 5+ actives users throughout the day. over 1000+ items

Every day i have to restart ombi so request don't take a minutes and sometimes just doesn't want to work at all. after restarting the server it usually works for a full day or close to a day.

when the issue occurs, logins with plex takes about 1 to 5 minutes and sometimes multiple attempts. once logged in, movie searches or request section of the pages takes also a few minutes to load if its loads at all.

**Comment by tidusjar** [comment]
@Omegaforts Your issue is completely different to what is being described in this issue, you sound like you are having DB locking problems. Please see here: https://github.com/tidusjar/Ombi/wiki/Using-a-different-database or open another issue.
