### ISSUE TITLE
Ombi not using localized dates

### ISSUE THREAD

**Issue by TomW1605** [Ombi-app/Ombi#3269]
**Describe the bug**
anywhere that a short date format is used it uses the american format (mm/dd/yyyy) instead of using the local date format (i.e. dd/mm/yyyy or yyyy/mm/dd)

**To Reproduce**
go to anywhere that uses a short date format such as the user settings or tv show air dates and you will see it (if your local format is mm/dd/yyyy then it will be correct for you)

**Expected behavior**
Ombi should retreive the correct date fromat eather from the computer the server is running on or from the brouser it is being viewed in and use that format.

**Screenshots**
![2019-11-16 19 38 32](https://user-images.githubusercontent.com/17092573/68992616-be646580-08a8-11ea-8597-f24047422a98.png)

**Logs (Logs directory where Ombi is located)**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 7

**Ombi Version (please complete the following information):**
 - Version 3.0.4680
 - Media Server Plex

**Additional context**
N/A

**Comment by TomW1605** [comment]
this is not stale i has just been ignored. it still needs to be fixed

**Comment by tidusjar** [comment]
!notstale

It's not being ignored, I am aware of this item. Just not had time to take a look into it.

**Comment by TomW1605** [comment]
sorry it just appeared to be ignored but good to know you are going to look into it.

**Comment by Vlayke** [comment]
I second this issue.
Just installed and configured Ombi on Synology. It seems that there is no apparent way to setup the time/date format in the Ombi backend and OS settings do not seem to be picked up.

**Comment by TomW1605** [comment]
any progress on this?
