### ISSUE TITLE
Media Data Refresh job not working

### ISSUE THREAD

**Issue by harrv** [Ombi-app/Ombi#3410]
Here are the 7 API endpoints for triggering jobs, as documented in /swagger.

POST /api/v1/Job/update
POST /api/v1/Job/plexuserimporter
POST /api/v1/Job/embyuserimporter
POST /api/v1/Job/plexcontentcacher
POST /api/v1/Job/plexrecentlyadded
POST /api/v1/Job/embycontentcacher
POST /api/v1/Job/newsletter

It seems like there should a way to trigger the other jobs through the API too:

/api/v1/Job/refreshmetadata
/api/v1/Job/issuepurgedelete
/api/v1/Job/mediadatarefresh
/api/v1/Job/retryfailedrequests
/api/v1/Job/lidarcacher
/api/v1/Job/sickragecacher
/api/v1/Job/sonarrcacher
/api/v1/Job/radarrcacher
/api/v1/Job/couchpotatocacher

Or maybe to make it easier on you going forward:

GET /api/v1/Job/
   list of jobs that can be triggered is returned with ids
POST /api/v1/Job/{id}

In particular, I'd like to be able to trigger the media data refresh job via the API.

Thanks.

**Comment by tidusjar** [comment]
Why not use the inbuilt CRON schedule?

**Comment by harrv** [comment]
> Why not use the inbuilt CRON schedule?

I can see from your question that you are results-oriented, which is great, and I'm happy to discuss cron and the use case I'm trying to solve. I'll do that in the following paragraphs. Before that, I want to say that I raised the issue to help you make the Ombi API more complete and to improve consistency. Right now, some jobs can be triggered via API and some cannot. You could very easily ask that same question (why not use the inbuilt cron schedule?) about the jobs that *can* be triggered via API. All of the jobs have attached cron, so why have an API to trigger any of them? I think the answer is that you found a reason you wanted to trigger some of them on-demand, so added an API to do it, while others you haven't yet found a reason to need to trigger them via API. That doesn't necessarily mean that others of us won't find reasons we want to trigger those jobs on-demand via API, or even that you yourself won't find a reason to want to do it in the future. That's the reason I created the issue. If you're going to give us two ways to trigger some of the jobs (cron and API) then wouldn't it make sense to extend that model to all of the jobs?

But since you brought it up, I do already have a cron job for "Media Data Refresh" and it doesn't work. I'm using the latest release (Ombi v3.0.4892). Either there is a bug (which I can report in a separate issue), or I don't understand what that particular job is supposed to do, or it only works for Plex and not Emby. Based on the wiki, it looks like when that job gets triggered, it is supposed to clear the previously cached content that is stored in OmbiExternal.db and fetch it again. However, if I delete a movie from Emby, wait to make sure Emby knows it's gone, remove the Radarr entry for it, and also remove the Ombi request for it, and then wait for the cron to trigger the "Media Data Refresh" job, I still can't re-request any movie that the content cacher had previously cached. Ombi claims those movies are already available. Also, after triggering that job, the size of the OmbiExternal.db doesn't change, making me think that the "Media Data Refresh" job didn't do anything.

If, instead of using an in-Ombi cron to trigger "Media Data Refresh", I use a system cron job to stop Ombi, delete the OmbiExternal.db file, then restart Ombi, then it works as I would expect, and the movie can be re-requested. I'm currently doing that as a workaround, but find it messier than if the job in Ombi worked as one would expect.

As an aside, I doubt that triggering the job via API would (or should) give any different results than triggering it via cron. That's not why I asked to be able to trigger it via the API. But it was in researching the "Media Data Refresh" bug that I wondered if cron was really triggering it and then while trying to find a way to trigger it directly I discovered that that job is missing from the API.

While searching about this issue, I found a recent thread on Reddit where you told someone that the case of deleting something from Plex or Emby isn't a common one. I don't have any data to disprove that, but in my own media center workflow it is very common. I have limited storage space for movies. I can store somewhere between 3 and 4 thousand. I hit that limit a long time ago, and since then I routinely cull things from my collection to make room to add more. To me, that makes more sense that just buying another hard drive or NAS every time I fill one up. For the purposes of my personal movie collection, four thousand should be plenty. My users (family) know that any request they make through Ombi will be only kept for four weeks in a User Requests library unless I move it into the library that contains my semi-permanent collection. I tell them that if they want to watch it again in the future, they should request it again.

The problem is figuring out how to allow them to re-request something that I used to have in Emby that has since been deleted. Emby itself is very good at getting rid of references to a movie that I've deleted from the file system. However, because I also have representations of that movie in the form of a Radarr entry, an Ombi request entry, and a cached item from Ombi's Emby-content-cacher, I never just delete the movie from the hard drive. Instead, I've written a Groovy script that will allow me to pick a movie to delete and then the script not only deletes it from the file system but also makes API calls to remove traces of it from Radaar and Ombi as well.

Both Radarr and Ombi have APIs that allow me to remove the Radarr and Ombi request entries. The only problem I'm left with at this point is finding a way to also remove the movie from Ombi's Emby content cacher database in OmbiExternal.db. There appears to be no API visibility into the content cache, so individual things can't be removed that way. The content cacher itself could remove things that are no longer present in subsequent runs of the content cacher, but it doesn't. The "Media Data Refresh" job also doesn't work for this. So I'm left with my shut-down-Ombi-then-delete-OmbiExternal.db workaround.

I know this is long, but I wanted to give you the full picture of what I'm trying to do, since you asked.

Thanks for all of your work and effort on Ombi! I appreciate it!

**Comment by tidusjar** [comment]
I agree adding the jobs to an API would be beneficial. But it does seem that your issue is more around the actual job itself. 

I'll take a look into it.

**Comment by focher** [comment]
I also have experienced issues around the caching of my Plex library and what Ombi recognizes as present. I have numerous movies, for example, that Ombi does not recognize as being in the library even though they are. Forcing rescans in both Plex and Ombi don't resolve the differences. Interestingly, starting with a completely new Ombi server results in exactly the same "missing" content after setup.
