### ISSUE TITLE
Delete User Button does Nothing in V4.0.226

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [Ombi-app/Ombi#3411]
**Describe the bug**
When trying to delete a user off Ombi, pressing the Delete button does nothing. No errors in logs either.

**To Reproduce**
1. Try to delete a user.
2. Nothing happens

**Expected behavior**
Selected user gets deleted.

**Logs (Logs directory where Ombi is located)**
No errors in log file.

**Desktop (please complete the following information):**
 - OS: Firefox/Chrome

**Ombi Version (please complete the following information):**
 - Version 4.0.226

**Comment by smailpouri** [comment]
same here on v4.0.279

**Comment by mrjohnpoz** [comment]
I am running 4.0.392.0 via docker, and same issue..  I even tried just loading up the database in db browser for sqlite.. And trying to delete a user from AspNetUsers throws this error
Error deleting record:
FOREIGN KEY constraint failed (DELETE FROM "main"."AspNetUsers" WHERE _rowid_ IN ('26');)

**Comment by DougParker1992** [comment]
I have a ton of old users that I am unable to delete as well.

**Comment by smailpouri** [comment]
I was able to delete users going through an app called nzbunity (v1.8.125 introduce Ombi support). I'm not sure why it works through the app. All I had to do was add Ombi through API settings. Find the user and delete it. I'm using an iPhone

**Comment by Berserkir-Wolf** [comment]
Confirmed issued resolved.
