### ISSUE TITLE
Issue-Related Discord Notifications Notify Wrong User

### ISSUE THREAD

**Issue by Rojikku** [Ombi-app/Ombi#3475]
**Describe the bug**
When using a format like:
`Hello, There is a new comment on your issue {IssueSubject}, The comment is: {NewIssueComment} <@{UserPreference}>`
It will @ me, who commented on or closed the issue, instead of @ing the issue creator, who is the one who wants this information.

**To Reproduce**
1. Go to Notifications > Discord Notifications
2. Enable everything and set it up with a webhook
3. Setup discord IDs on all the users
4. Add the recommended code to @ someone on discord to the issues.
5. Create an issue, comment on it, and resolve it. It @s the wrong person.
(I hardcoded who it @s for creation since it's always me, so that's not an issue personally.)

**Expected behavior**
When X made an issue, and I close it, it should @X instead of me.

**Screenshots**
![Ombi_Issue](https://user-images.githubusercontent.com/1676068/78573771-17507e00-77f7-11ea-9446-2b19a05c818a.png)

**Logs (Logs directory where Ombi is located)**
(Probably not relevant)

**Desktop (please complete the following information):**
linuxserver/ombi:latest

**Ombi Version (please complete the following information):**
 - Version 3.0.4892
- Media Server Emby

**Additional context**
Asked in Ombi support channel, was told it was probably just a bug.
I have not found any bugs that are similar, closed or open, so I'm opening this.
My mistake if I missed it.

**Comment by goldenpipes** [comment]
+1

**Comment by goldenpipes** [comment]
It's definitely a bug.  I think there is something missing.

**Comment by twanariens** [comment]
This problem exists if Ombi does not have an Alias stored for that specific User. 
`Extra tips:
You can set a channel so nobody can post, and the webhook can still post.
You can @ people by using: <@{Alias}>. Be sure their Discord alias is known in the user profile of Ombi under Alias.`
[https://docs.ombi.app/settings/notifications/discord/](url)
