### ISSUE TITLE
Ombi V4 - No Remember Me for Plex oAuth

### ISSUE THREAD

**Issue by rg9400** [Ombi-app/Ombi#3568]
**Describe the bug**
When using Plex oAuth, Ombi will not remain logged in. The user has to log in with their username and password and hit remember me for the log in to be stored.

**To Reproduce**
1. Log in using Plex oAuth
2. Close the browser or tab, then reopen it

**Expected behavior**
The login should stay logged in, even if using Plex oAuth. Ideally, there should be a way for session/cookie to last more than 7 days in either scenario considering that most websites with even more sensitive data (i.e. Github or Plex or Amazon or any number of non bank websites) basically allow you to remain logged in until the cookie is cleared. 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10

**Ombi Version (please complete the following information):**
 - Version [e.g. 3.0.1158] 4.0.337.0

**Comment by rg9400** [comment]
I actually think the Remember Me button is broken for user/pass logins as well. Or it is expiring way too quickly. I need to relogin every day now. No other subfolder on my domain has this issue, so cookies aren't being deleted client side.

**Comment by twanariens** [comment]
This has been fixed by increasing the cookie time for the authentication
