### ISSUE TITLE
V4 - Issues not working?

### ISSUE THREAD

**Issue by bdschuster** [Ombi-app/Ombi#3765]
**Describe the bug**
When someone reports and issue, i can see the issue, but have no button to mark in progress, marked resolved, add comments, nothing.

**To Reproduce**
1. Create an issue with Movie or TV Show.
2. Go to Issues.
3. Click "Details" beside the issue.
4. At this point, it only takes you to the movie details, no details on what the issue.

**Expected behavior**
Should be able to "Mark In Progress", "Mark Resolved", "Add Comments".

**Screenshots**
Issues page:
![image](https://user-images.githubusercontent.com/38221778/93274462-0e89ae00-f780-11ea-96eb-28cb5fea1959.png)
After clicking details, just takes you to the movie details:
![image](https://user-images.githubusercontent.com/38221778/93274530-337e2100-f780-11ea-94f7-334467847588.png)

**Logs (Logs directory where Ombi is located)**
not applicable 

**Desktop (please complete the following information):**
 - OS: Debian 9 - Docker

**Ombi Version (please complete the following information):**
 - Version 4.0.477.0
- Media Server: Plex
- Database Type: SQLite (Please change if using MySQL)

**Additional context**
None

**Comment by clowrym** [comment]
same problem here. clicking details of an issue, brings me to the movie page
<img width="1211" alt="Screen Shot 2020-11-11 at 10 13 48 PM" src="https://user-images.githubusercontent.com/25108950/98898714-78b28c80-246b-11eb-8d4d-7d56be5df72e.png">
<img width="1287" alt="Screen Shot 2020-11-11 at 10 15 21 PM" src="https://user-images.githubusercontent.com/25108950/98898722-7c461380-246b-11eb-8e7c-d077f3c9e3ff.png">

**Comment by tidusjar** [comment]
Scroll down, there's an issue section at the bottom

**Comment by Navino16** [comment]
Hi,

I think there is an issue with issue imported from V3.
We can only see the ten first issue on issue page and when we go to the detail of one of this issue, we can't see the issue section on the movie/show page.

Maybe I have miss something when migrating from V3 ?

**Comment by Navino16** [comment]
There is no issue section on detail page for issue created in V3. But the section is present for issue created in V4

**Comment by vsc55** [comment]
Hi,
There is a compatibility problem between the data that is saved in the "Issues" table if you migrate from version 3 to version 4.
From what I have seen the problem only affects the movies, the tv shows work correctly.
The problem is that in the column "ProviderId" in version 4 it uses the IMDB ID and in version 3 it is another different ID.

**Comment by intrepidpursuit** [comment]
@vsc55 I'm having the same problem and found that issues with movies cannot be accessed or cleared after an update from V3 to V4. Is there any solution to this?

**Comment by vsc55** [comment]
@intrepidpursuit, I didn't have many movies so I replaced the database IDs by hand and now it works fine.
