### ISSUE TITLE
Movie titles on request secction do not show on language selected (v4)

### ISSUE THREAD

**Issue by joseluislucas** [Ombi-app/Ombi#3796]
**Describe the bug**
Movie/show titles appear on English even tough the setting is set to Spanish, but when I navigate to "Details" page the title is the good one (in Spanish).

**To Reproduce**

Change language to Spanish and check Request List

**Expected behavior**
In V3 the titles appeared all in Spanish (request list), which was the best way to look for the movies (in Spanish language), now instead I have to go to "Details". I think it should be really nice to have the titles also in the selected language on the request section. And easy to accomplish since in "Details" the title is the correct one

**Screenshots**
None

**Logs (Logs directory where Ombi is located)**
None
**Desktop (please complete the following information):**
 - OS: Ubuntu Server 20.04 (docker)

**Ombi Version (please complete the following information):**
 - Version [4.0.509.0]
- Media Server [Plex]
- Database Type: SQLite

**Additional context**
None

**Comment by tidusjar** [comment]
If the requests were requested in English then that is the title used for that page

**Comment by joseluislucas** [comment]
> If the requests were requested in English then that is the title used for that page

When someone puts the original name of the film in the search bar it shows the Spanish (in my case) title right away , so it always shows the Spanish name just before pressing "Request".
I've just tried to request a film directly with the Spanish name, and of course it shows okay on the search bar, but when I request that film and check the list, the name appears in English.

**Comment by joseluislucas** [comment]
I'm attaching some photos so you can see the problem. 

You can see here how all the titles appear in english, even though they were requested in spanish.
![WebSolicitudes](https://user-images.githubusercontent.com/1245624/97315836-65979e00-1869-11eb-8d5a-ffa91e18fcd4.jpg)

On the details page the title shows in the correct language.
![peli](https://user-images.githubusercontent.com/1245624/97315867-6e886f80-1869-11eb-8c45-e4bd1ebc0dd8.JPG)

Thanks!

**Comment by joseluislucas** [comment]
Hi guys! Happy new yearh and merry christmas!

Is anyone looking to fix this?

Many thanks!

**Comment by twanariens** [comment]
Will be continued in #4404
