### ISSUE TITLE
V4 Bug - Display issues

### ISSUE THREAD

**Issue by SmithOnline** [Ombi-app/Ombi#3826]
**Describe the bug**
Display issues using chrome on 
Microsoft Windows 10.0.19041 X64 
Ombi Version: 4.0.530.0
Plex Media Server: 1.20.3.3437
Database Type: SQLite

This is 100% on Chrome
![100 % image1](https://user-images.githubusercontent.com/8896889/96888589-b419f680-147d-11eb-959d-1b1561032b03.png)
![100% image2](https://user-images.githubusercontent.com/8896889/96888593-b4b28d00-147d-11eb-9b62-806c3c9566a6.png)

This is 80% on Chrome
![80% image3](https://user-images.githubusercontent.com/8896889/96888577-b1b79c80-147d-11eb-8d7e-07371e1fb948.png)
![80% image4](https://user-images.githubusercontent.com/8896889/96888581-b3816000-147d-11eb-935a-9977c6baedfc.png)

Here is the display resolution
![res](https://user-images.githubusercontent.com/8896889/96888595-b54b2380-147d-11eb-9ab9-754fb75a0fa2.png)

**Comment by AwesomeAustn** [comment]
This happens for me also and I'm on Firefox version 82.0 and Ombi version 4.0.533.0. My screen resolution is 1366x768.
This screenshot is at 100%.
![Screenshot_2020-10-25 Ombi](https://user-images.githubusercontent.com/6405444/97126581-7541a600-16f4-11eb-8036-bb1b1320c753.jpg)
This screenshot is at 80%.
![Screenshot_2020-10-25 Ombi(1)](https://user-images.githubusercontent.com/6405444/97126669-bafe6e80-16f4-11eb-9b9b-fffdaec12a20.jpg)

**Comment by nickelslol** [comment]
Also the user management page doesn’t resize on iOS/iPadOS so you can’t see anything past here.

![IMG_1779](https://user-images.githubusercontent.com/77177642/104075427-e65e1780-5266-11eb-8515-4ea1ac99bdae.jpeg)

And some other problems on just iOS 
![IMG_0775](https://user-images.githubusercontent.com/77177642/104075628-7734f300-5267-11eb-80b5-8b5873644d66.jpeg)
![IMG_0776](https://user-images.githubusercontent.com/77177642/104075638-7c923d80-5267-11eb-9ab2-b254e3b7936c.jpeg)

**Comment by hirenshah** [comment]
@nickelslol The Discover and Details issues are mentioned here:
https://github.com/tidusjar/Ombi/issues/3893#issuecomment-757037381

@tidusjar The Users view issue @nickelslol just mentioned is on all devices. Overflow CSS not set correctly maybe?

**Comment by tidusjar** [comment]
This should be resolved now
