### ISSUE TITLE
username placeholder not visible

### ISSUE THREAD

**Issue by RobinMM** [Ombi-app/Ombi#3833]
**Describe the bug**
When opening the login screen, and the white theme is selected. Username placeholder is not visible.

**To Reproduce**
Open the login screen.

**Expected behavior**
Show the Username placeholder like its showing for Password

**Screenshots**
![blank-username](https://user-images.githubusercontent.com/1236301/97149250-c7261280-176c-11eb-9ed8-266e47d5d584.PNG)
![blank-username-mobile](https://user-images.githubusercontent.com/1236301/97149281-d3aa6b00-176c-11eb-9aff-2c80009d7878.jpg)

**Desktop (please complete the following information):**
Desktop and mobile

**Ombi Version (please complete the following information):**
 - Version 4.0.533.0

**Comment by twanariens** [comment]
This should be fixed in the latest V4 version
