### ISSUE TITLE
v4 - unable to mark show as available and misreporting only partially available when its fully available

### ISSUE THREAD

**Issue by CanonCan** [Ombi-app/Ombi#3858]
**Describe the bug**
the show Lost (2004-2010) shows up under discovery and says paritally available but I do have the full show as per Sonarr

there is no way to tell Ombi that the show is fully available

**To Reproduce**
1. Go to Have Lost on Sonarr and go to discovery in ombi
2. say Partially available but its fully available
3. no way to force it to fully available as when i try to request it it says all episodes are already available

**Expected behavior**

see attached screenshots

**Screenshots**
![ombi lost](https://user-images.githubusercontent.com/31594024/98335691-abb7d480-1fc2-11eb-93c3-ed7b53b71574.png)
![sonarr lost](https://user-images.githubusercontent.com/31594024/98335694-ac506b00-1fc2-11eb-8570-36d18679e850.png)

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**

**Ombi Version (please complete the following information):**
 - Version 4.0.643.0
- Media Server UnRAID (Docker
- Database Type: SQLite 

**Additional context**

**Comment by tidusjar** [comment]
Please can you attempt to request that show and it will tell you what
episode it thinks is missing

**Comment by dbowles1975** [comment]
> Please can you attempt to request that show and it will tell you what episode it thinks is missing
>
It thinks there's an episode 25 in season 1 titled Exodus (3). No such episode exists according to Sonarr or  TVDB.

**Comment by Silentbob101** [comment]
I'm seeing this too for lost

**Comment by Silentbob101** [comment]
Also seeing Breaking Bad as partially available but with no option to request

Should I log a separate bug for the Breaking Bad Issue (logged in the correct format) ?

**Comment by tidusjar** [comment]
So lost is a known issue that is going to be resolved soon. 

It's a problem where TvMaze is reporting a different episode set to what TvDb use. Breaking bad does not experience this

**Comment by twanariens** [comment]
Since we changed TV providers this issue should be fixed
