### ISSUE TITLE
V4 - comments in issue is not available 

### ISSUE THREAD

**Issue by bison529** [Ombi-app/Ombi#3866]
**Describe the bug**
When i used V3 there is box for comments inside page of a issue, but when i upgrade to V4 is not shown!

**To Reproduce**
1. Go to 'issues'
2. Click on 'details button'
3. Scroll down to 'Issues'
4. See only 'Mark in progress' and 'Delete issue'. 

**Screenshots**
![image](https://user-images.githubusercontent.com/55077641/99070285-fdfb8580-25c0-11eb-9b19-6169a208fb42.png)

**Desktop (please complete the following information):**
 - OS: [Docker ubuntu 18.04]

**Ombi Version (please complete the following information):**
 - Version [4.0.681.0]
- Media Server [PLEX]
- Database Type: Sqlite

**Comment by escservices** [comment]
Same thing here

**Comment by tidusjar** [comment]
I've not added them in yet.

**Comment by twanariens** [comment]
This has been fixed after the rework of issues
