### ISSUE TITLE
Ombi not pulling movies or TV shows in search

### ISSUE THREAD

**Issue by brentw1584** [Ombi-app/Ombi#3877]
**Describe the bug**
OMBI is not allowing me to search for movies or TV shows. Even trying to browse "popular" items does not work. Accessing Ombi thru a browser. Was working as expected on 11/18/2020 but today 11/19/2020 the search is no longer working. I have also confirmed with another individual that they are having the same problem as well and for them it started last night as well.

**To Reproduce**
1. Go to 'Ombi'
2. Click on 'Search'
3. Scroll down to 'Movies or TV shows'

**Expected behavior**
Supposed to present search itmes

**Screenshots**

**Logs (Logs directory where Ombi is located)**

**Desktop (please complete the following information):**
 - Linux 4.4.121-1.el7.elrepo.x86_64 #1 SMP Sun Mar 11 14:33:50 EDT 2018

**Ombi Version (please complete the following information):**
 - Version  3.0.5223
- Media Server Plex
- Database Type: SQLite (Please change if using MySQL)

**Additional context**

**Comment by PotatoQuality** [comment]
Please full-in the full support template

**Comment by twanariens** [comment]
Should be fixed in the latest V4 version
