### ISSUE TITLE
V4 (v3 too!) not removing items after removed from Jellyfin (stuck at available)

### ISSUE THREAD

**Issue by markv9401** [Ombi-app/Ombi#3886]
**Describe the bug**
Connected to Jellyfin, Ombi syncs media availability just fine. However once they're removed from Jellyfin, they don't get removed from Ombi (not even after numerous manual and automatic/timed syncs either). They get stuck at available for ever. Checked the sql db, they indeed remain in there..

**To Reproduce**
1. Connect Ombi and Jellyfin
2. Request a Movie/TV Show and wait until it shows up in Jellyfin
3. Once it's available in Jellyfin and auto sync happened, it's marked available in Ombi too. Now remove the media (delete) and wait till Jellyfin recognizes and removes it from its database too
4. Wait for the next auto sync of Ombi / sync manually and see how nothing happens, media stuck at available in Ombi for ever

**Expected behavior**
To keep a close 1:1 mirror - synced media library with Jellyfin. Add when added, remove when removed. Additionally, I'd love to have the feature to send "delete movie folder" / "delete tv show folder" to radarr/sonarr/etc.

**Screenshots**
Not needed

**Logs (Logs directory where Ombi is located)**
None, not needed

**Desktop (please complete the following information):**
 - OS: Linux + Docker

**Ombi Version (please complete the following information):**
 - Version 4.0.720.0 
- Media Server  Jellyfin
- Database Type: SQLite

**Additional context**
-

**Comment by twanariens** [comment]
The remove functionality is unfortunately a difficult one. Most media servers have API's to detect the "recently added content" but not the "Recently deleted content". Meaning that Ombi doesn't have an easy way of telling what media has been deleted.

For this reason Ombi's only way of knowing what media is no longer available, is to purge the OmbiExternal database and do a full sync. This process has a job for it which runs every 5 days (by default). You can change this to 1 day, every hour, etc via CRON. I believe the job is called "Refresh metadata"

The sync button (on the settings page of Emby) does not purge the database, meaning that deleted items remain as available.
