### ISSUE TITLE
Search not functioning after upgrade from V3

### ISSUE THREAD

**Issue by Rsslone** [Ombi-app/Ombi#3891]
**Describe the bug**
After an upgrade to V4, the homepage will not load and searches do not function. Errors are thrown in logs.

**To Reproduce**
1. Upgrade from V3.0.4xxx to 4.0.721.0
2. Log in
3. Observe homepage / Logs

**Expected behavior**
The homepage to populate with suggested titles and search to function

**Screenshots**
https://i.imgur.com/nb6auaT.png

**Logs (Logs directory where Ombi is located)**
https://puu.sh/GRdqr/171c67ef94.txt

**Desktop (please complete the following information):**
 - OS: Win 8.1

**Ombi Version (please complete the following information):**
- Ombi 4.0.721.0
- Plex 1.21.0.3616
- Database Type: SQLite

**Additional context**

**Comment by tidusjar** [comment]
Tried clearing your cache?

**Comment by Rsslone** [comment]
I've tried on another browsers, and I cleared to be sure just now still the same. Upon clearing the first login looks like this https://i.imgur.com/neRj4u4.png and after a refresh it spins like before.

Are the V3/V4 databases compatible with each other?

**Comment by tidusjar** [comment]
how did you update? Because your interface looks wrong

**Comment by Rsslone** [comment]
Deleted all the files except for the databases and grabbed the V4 zip,

**Comment by twanariens** [comment]
This issue can most likely be fixed by deleting your OmbiExternal.db and restarting Ombi.
If not please provide the logging when the above has been done :D
