### ISSUE TITLE
Discover not loading new Movies/Shows

### ISSUE THREAD

**Issue by damusmf** [Ombi-app/Ombi#3892]
**Describe the bug**
The discover page appears to only load new movies or tv shows when you scroll to the bottom.  If your monitor/screen resolution is large enough that there is no scrollbar, you are unable to get more than the initial 10-14 items that load. Current monitor resolution is 2560x1440, large enough that there is not a vertical scrollbar. 

**To Reproduce**
Go to your ombi page
Discover tab
If you are unable to scroll you cannot load more items

**Expected behavior**
Should be able to load more items even if you do not need to scroll.  Maybe a button to "load more" at the bottom? 

**Screenshots**
![image](https://user-images.githubusercontent.com/31552122/100293310-def9dd80-2f48-11eb-9115-1a6b9fcd8233.png)

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: windows, chrome browser

**Ombi Version (please complete the following information):**
 - Version 4.0.728.0
- Media Server: Plex
- Database Type: SQLite

**Additional context**

**Comment by twanariens** [comment]
This has been fixed
