### ISSUE TITLE
Requesting a TV show that doesn't have any episodes added to it yet will set it to status 'Available'

### ISSUE THREAD

**Issue by PolliSoft** [Ombi-app/Ombi#3896]
**Describe the bug**
When a user requests a TV show that hasn't gotten any episodes added to it yet will add it correclty to Sonarr (in my case), but Ombi will mark it as available directly.

**To Reproduce**
1. Request a show that hasn't gotten any episodes added, e.g. "Loki".
2. Approve the request
Actual result: The show is set to 'Available' directly

**Expected behavior**
The show is set to 'Processing'

**Screenshots**
![bild](https://user-images.githubusercontent.com/563252/100468378-9838ee80-30d4-11eb-960b-30777e37248e.png)

**Logs (Logs directory where Ombi is located)**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64bit

**Ombi Version (please complete the following information):**
 - Version 4.0.728.0
- Plex
- Database Type: SQLite

**Additional context**

**Comment by tidusjar** [comment]
There are no episodes so Ombi thinks it's available, something I probably should improve on
