### ISSUE TITLE
Password Resets add /token lines to the Application URL for each use

### ISSUE THREAD

**Issue by cyphercolt** [Ombi-app/Ombi#3915]
**Describe the bug**
Sending a Password Reset to a user will add " /token?token= " to the end of the application URL for each time a password reset was sent.

So if I send 4 password resets, the end of the application url will appear with /token?token=/token?token=/token?token=/token?token=

Unfortunately, this isn't just a visual field thing, it sends it in the email sent with the password reset and/or welcome email (anywhere the application url field is used in an email).

**To Reproduce**
1. Verify your application url is set correctly
2. Send a password reset to one or more users
3. Check your Application URL
4. Notice the URL now has /token?token= for each time a reset was sent

**Expected behavior**
Application URL remains the same.

**Logs (Logs directory where Ombi is located)**
No relevant log snippets - checked the last 5 minutes of logs and it's just the following - I ran the steps right before opening log file:
2020-12-06 14:27:57.337 -05:00 [Debug] Batch acquisition of 0 triggers
2020-12-06 14:28:25.660 -05:00 [Debug] Batch acquisition of 0 triggers

**Desktop (please complete the following information):**
OS Architecture | X64
OS Description | Linux 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28)

**Ombi Version (please complete the following information):**
- Version | 3.0.5223
- Branch | master
- Media Server - Plex
- Database Type: SQLite

**Additional context**
I just installed Ombi on my new Debian Server yesterday, so I re-created all the users and found the best way was to send them password reset links. Last time I messaged each one individually giving them a password - now doing it through the welcome + reset buttons as there are more users than my first ever installation.

I don't believe this issue was entered with this specific set of steps recently, I did find an older issue and related issue but they're all closed. - https://github.com/tidusjar/Ombi/issues/2865

If this is never going to be fixed, there's a workaround - manually repair the application url field after each password reset link is sent out.

**Comment by jj-uk** [comment]
Any update on this? I've just had this issue and tracked it down to the application URL being messed up by a password reset. Even if the password is not reset, clicking on the reset link seems append ?token= to the application URL field, *each time the password reset link is clicked*, so if ii try to reset the password 5 times, my application url becomes:
https://www.MYDOMAIN.com/token?token=/token?token=/token?token=/token?token=/token?token=

**Comment by twanariens** [comment]
This should be fixed in the latest release V4.15.2
