### ISSUE TITLE
Migration Error

### ISSUE THREAD

**Issue by robinsone** [Ombi-app/Ombi#3918]
**Describe the bug**
Error on startup of ombi. 

**To Reproduce**
1. Go to installation folder
2. Click on ombi.exe (run as administrator)
3. Console windows opens and displays error

**Expected behavior**
Expected it to run and then open localhost:5000

**Screenshots**
![Capture](https://user-images.githubusercontent.com/1637696/101370333-5e57ad00-3877-11eb-81cd-2935caae9cf3.PNG)

**Logs (Logs directory where Ombi is located)**
Doesn't seem to have any logs. 

**Desktop (please complete the following information):**
 - OS: Windows 10

**Ombi Version (please complete the following information):**
 - Version 3.0.5223
- Media Server: Plex
- Database Type: SQLite

**Additional context**

**Comment by tidusjar** [comment]
Is this a new DB or existing?

**Comment by vsc55** [comment]
Hi @robinsone,
Try the following guide, since the current one explains the migration with Ombi v4.
https://github.com/vsc55/ombi_sqlite_mysql/tree/fc550b958fa8fb5b491e13f650f870eaf6999063
