### ISSUE TITLE
V4 - Application Name in Top Left Corner is not Linkified

### ISSUE THREAD

**Issue by aman88** [Ombi-app/Ombi#3921]
**Describe the bug**
Clicking on the Application Name in the top left corner should bring you back to the application home page. Currently, in V4, this is not a linkified item.

**To Reproduce**
1. Navigate to any Ombi page aside from the home page
2. Click on the Application Name in the top left corner
3. It's not a link, so nothing happens.

**Expected behavior**
Clicking the Application Name should redirect you to the application home page.

**Ombi Version (please complete the following information):**
 - Version 4.0.739.0
- Media Server - Plex
- Database Type: SQLite

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈
