### ISSUE TITLE
v4 Overview and v4 card views are linked

### ISSUE THREAD

**Issue by BRTPOB** [Ombi-app/Ombi#3928]
**Describe the bug**
When trying to use the overview view in Ombi v4, the posters are essentially full-sized and only allow you to see one movie per page as opposed to the v3 version that showed quite a few. Screenshots attached.

**To Reproduce**
1. Login to Ombi
2. Click on Overview button.
3. Observe

**Expected behavior**
Expected Overview view to be the same, or at least much more similar to the previous Overview view.

**Screenshots**
Screenshots located here: https://imgur.com/a/Mb2xffS

**Logs (Logs directory where Ombi is located)**
N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Ombi Version (please complete the following information):**
 - Version 4.0.748.0 
- Media Server Plex
- Database Type: SQLite

**Additional context**
N/A

**Comment by JanKleine** [comment]
Just randomly stumbled across this issue and thought I'd add my unqualified comment...

To me, the default views look very different from what your screenshot shows. Using the two buttons at the top right I can switch between the two views shown below. 

Maybe it's an issue with your installation or browser? (I'm running version 4.0.777.0)

<img width="720" alt="image" src="https://user-images.githubusercontent.com/16564943/102357715-ebed7800-3fae-11eb-9a0b-b58397b94bfb.png">

<img width="720" alt="image" src="https://user-images.githubusercontent.com/16564943/102357685-e42dd380-3fae-11eb-83fb-76ee46b2a3ca.png">

**Comment by BRTPOB** [comment]
I'm running Version 4.0.778.0, on Firefox.

**Comment by BRTPOB** [comment]
Downgrading didn't change anything. Maybe it's trying to resize based on resolution?

**Comment by tidusjar** [comment]
Does this happen on Chrome?

**Comment by BRTPOB** [comment]
Yes. Every browser I've tested it's happening on.

**Comment by BRTPOB** [comment]
> Does this happen on Chrome?

Just to confirm, this is happening in Firefox, Chrome, Chromium and Edge. Oddly enough I just tried it in Windows, and it displays just fine, but using Linux it's like my screenshots above. It seems related to resolution size, though, as I'm running 3440x1440 on my main machine, and all of the others are either 1920x1080 or smaller.
