### ISSUE TITLE
Jellyfin api key not working with current version of ombi

### ISSUE THREAD

**Issue by shanehughes1990** [Ombi-app/Ombi#3929]
**Describe the bug**
I apologize if there is already an issue, I was unable to find one that matched my issue.
I noticed a couple weeks ago (I use docker & watchdog to update my containers), that ombi is no longer connecting to my jellyfin instance. Nothing has changed aside from updates (Like nothing config wise, api keys etc.), Looking through ombi logs when trying to setup jellyfin I get the following error. This particular error is me setting up a fresh instance of jellyfin 10.7.0, and a fresh instance of ombi  testing-eb370fa, I have tried this with latest v3 & latest v4 ombi.

**To Reproduce**
Run latest hotio/jellyfin, hotio/ombi containers and try to setup media server to jellyfin
ombi settings:
Server URL: http://jellytest
Port: 8096
API Key: Whatever you generated in jellyfin

**Expected behavior**
Connect to jellyfin server

**Screenshots**
![image](https://user-images.githubusercontent.com/31993465/101985673-8bc99f80-3c57-11eb-8d35-b80e38a5bfb6.png)
![image](https://user-images.githubusercontent.com/31993465/101985694-a6037d80-3c57-11eb-91ab-6ba122719cb6.png)

**Logs (Logs directory where Ombi is located)**
```
fail: Ombi.Api.Api[1000]
      StatusCode: NotFound, Reason: Not Found, RequestUri: http://jellytest:8096/emby/users
fail: Ombi.Controllers.V1.External.TesterController[1000]
      Could not test Emby
      System.ArgumentNullException: Value cannot be null. (Parameter 'source')
         at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
         at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
         at Ombi.Controllers.V1.External.TesterController.Emby(EmbyServers settings)
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20 running Docker version 19.03.6, build 369ce74a3c

**Ombi Version (please complete the following information):**
 - Version 4.0.748.0
- Media Server Jellyfin
- Database Type: SQLite & MySQL (Tested both)

**Additional context**
I may be able to run a few different version to see when it broke, but I do not currently have the time.

As a side note I did test with latest emby that still works.

Also providing relevant docker-compose parts
```
  jellytest:
    container_name: jellytest
    image: hotio/jellyfin:nightly-5959398
    restart: always
    ports:
      - 8096:8096
    environment:
      TZ: $TIMEZONE
      PGID: $PGID
      PUID: $PUID
      DEBUG: "yes"
    volumes:
      - $MEDIA:/data/media
    networks:
      - media_net

  ombi:
    container_name: ombi
    image: hotio/ombi:testing-eb370fa
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=mediacenter_net"

      # Main domain
      - "traefik.http.routers.ombi.rule=Host(`$OMBI_DOMAIN.$DOMAIN`)"
      - "traefik.http.routers.ombi.entrypoints=websecure"
      - "traefik.http.routers.ombi.tls.certresolver=mytlschallenge"
      - "traefik.http.services.ombi.loadbalancer.server.port=5000"
      - "traefik.http.routers.ombi.service=ombi"

      # Watchtower automated update label
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      PGID: $PGID
      PUID: $PUID
      DEBUG: "yes"
    volumes:
      - $PWD/config/ombi/database.json:/config/app/database.json
    # - $APPDATA/ombi:/config
    networks:
      - media_net
      - db_net
```

**Comment by shanehughes1990** [comment]
Would love someone to look at this or point me in the right direction as my ombi is currently not working.

**Comment by tidusjar** [comment]
The connection works fine, must be something to do with your internal routing. All I can suggest is to try a direct IP?

**Comment by shanehughes1990** [comment]
I have since moved from ombi to overseerr and that works great. I will close this issue
