### ISSUE TITLE
Links to imdb from TV shows search have malformed URLs

### ISSUE THREAD

**Issue by chippoman** [Ombi-app/Ombi#3944]
**Describe the bug**
Links to IMDB have a malformed URL when you click on a TV show from the Search page. Example:

https://www.imdb.com/title/http://www.imdb.com/title/tt0212671//
instead of
https://www.imdb.com/title/tt0212671/

**To Reproduce**
1. Click Search
2. Click TV shows
3. Enter any TV show name to perform a search (optional)
4. Click on any of the TV shows from the search result page

**Expected behavior**
Link to IMDB is correctly formed

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**

**Ombi Version (please complete the following information):**
 - Version 3.0.5223
- Media Server Plex
- Database Type: SQLite

**Additional context**

**Comment by jwetzell** [comment]
+1 for this issue. I'm experiencing the same thing so somehow the imdbId of the tv series is being seen as the whole `http://www.imdb.com/title/tt0212671` url.

**Comment by twanariens** [comment]
This has been fixed
