### ISSUE TITLE
Bug In "Hide Available Content On The Discover Page" Function

### ISSUE THREAD

**Issue by gorgarp** [Ombi-app/Ombi#3953]
**Describe the bug**
v4.0.792 (really since the feature was added)
When "Hide Available Content On The Discover Page" is enabled, it oddly breaks some functionality.

If you already have XYZ number of shows and go to, say, TV / Popular, it won't load anything.

I'm assuming this is due to a limit of results loaded, which is a good thing of course.

Without option enabled, and scrolled past first "load / results" limitation.
<img width="777" alt="TV - Popular - No Hide" src="https://user-images.githubusercontent.com/7957736/103465593-f627aa00-4d02-11eb-8a1b-e82ca437689a.png">

With option enabled. (Can't keep scrolling to find shows you _don't_ have)
<img width="800" alt="TV with Hide" src="https://user-images.githubusercontent.com/7957736/103465595-f6c04080-4d02-11eb-9778-5c7d1befc620.png">

The issue is, lets arbitrarily say that limit is 100 shows, and you happen to have those 100 shows already. It never attempts to load the next 100 shows to compare if you have those.

If you look at the screenshots above, you'll see at show (made up number) #110, you see two shows I don't have. These never get loaded due to the way that limit is applied.

Not sure how to get around that but I'd assume it would be some logic of "load 100, check if 100 already had, continue until 100 are displayed". I'm sure there is a more elegant way to achieve this, as that would hammer the hell out of the DB, but just bringing it to your attention.

**Comment by gorgarp** [comment]
Am not a dev like yourself, but best guess at code location:
https://github.com/tidusjar/Ombi/blob/0c97737aabed534bd882d260bb1c1edc29333e21/src/Ombi/ClientApp/src/app/discover/components/discover/discover.component.ts

AmountToLoad?

**Comment by tidusjar** [comment]
I've not had time to look into this yet, but I can confirm it's an issue

**Comment by gorgarp** [comment]
No worries bud. I just wanted to get it on your radar. Thanks!

**Comment by gorgarp** [comment]
Just a heads up, and no pressure, but just so you are up to date where this stand. As of v4.0.1040:
<img width="727" alt="1" src="https://user-images.githubusercontent.com/7957736/106373249-54b16980-633d-11eb-9c73-530c096eee69.png">

**Comment by tidusjar** [comment]
Thanks for the update

**Comment by twanariens** [comment]
This should be fixed in the latest release V4.15.2
