### ISSUE TITLE
V4 - Duplicate movie results in Discover Panel

### ISSUE THREAD

**Issue by kccorl1993** [Ombi-app/Ombi#3959]
**Describe the bug**
Duplicate results under Discover

**To Reproduce**

1. Go to Discover
2. Select Movies
3. Select any option
4. Seemingly random movies are duplicated

**Expected behavior**
Movies only displayed once

**Desktop (please complete the following information):**
- OS: Windows 10, Ombi = Ubuntu 18.04

**Ombi Version (Please complete the following information):**
- Version = 4.0.792.0
- Media Server = Plex
- Database Type: SQLite

**Additional context**
This appears to be when the page dynamically loads the results, so I'm assuming that there isn't some exclusion list to avoid duplicates, but that is not my place to know.

**Comment by tidusjar** [comment]
Sorry your steps to reproduce are a bit vague. What's actually happening?

**Comment by kccorl1993** [comment]
No problem.

When I scroll through the movies in Discover -> Movies -> Popular, for instance, I see the movie "Disclosure" keep popping up.  I am able to get it to show up at least 3 times, and I just got 2 separate movies to show up twice on the same screen in [this screenshot](https://i.imgur.com/pXDeDhE.png).

**Comment by gold007eye** [comment]
I have noticed this same issue and it still persists in the latest 4.0.912 build running on Win10 x64 OS.

Here is how I reproduced:

1. Click Discover on the left hand panel.
2. (Movie tab is already preselected) - Click on Upcoming
3. Scroll through results and there are duplicates of the same movie showing up.  

Here is a screenshot showing my results this morning you can clearly see "Breach" & "Pinnochio" showing 2 times.
![image](https://user-images.githubusercontent.com/4365462/104095881-de9a7500-525e-11eb-97e0-352863a400ea.png)

**Comment by mrjohnpoz** [comment]
Still seeing this in 4.0.991.0 as well.. Not a big issue - but it is odd.. 

![dupe](https://user-images.githubusercontent.com/11797687/105512830-355c7180-5c97-11eb-97a7-66afc1c2b56b.png)

**Comment by tidusjar** [comment]
Is this still an issue on the latest v4?

**Comment by kccorl1993** [comment]
It looks like this was resolved.  Thank you!
