### ISSUE TITLE
Autofill from password manager on iOS not detected as input

### ISSUE THREAD

**Issue by SosthenG** [Ombi-app/Ombi#3964]
**Describe the bug**
Using Bitwarden to autofill the form fields on firefox iOS was not detected as an input and the message "Username is required" showed up while the fields were already filled.
I'm guessing the validation is waiting for a proper input but that prevent such password managers to work, at least on iOS. as Bitwarden on other platforms does work with Ombi from what I was able to test.

**To Reproduce**
1. Try to login with a password manager on iOS (Bitwarden to reproduce exactly, but the bug might concern others)
2. Use the iOS autofill functionality and try to log in
3. The error message should appear beside the fields being filled

**Expected behavior**
User should be logged in

**Screenshots**
![image](https://user-images.githubusercontent.com/22033159/103803532-99045f00-5048-11eb-9c07-fef55f42a8c2.png)

**Desktop (please complete the following information):**
 - OS: Firefox on iOS 14.2

**Ombi Version (please complete the following information):**
- Version 4.0.890.0 
- Media Server : Jellyfin
- Database Type: SQLite

**Comment by tidusjar** [comment]
That's odd, I use 1Password and it works fine

**Comment by SosthenG** [comment]
Hi, just tried with the most recent iPad air and I confirm the issue but only on firefox. I tried on safari and it works fine. But there is actually two problems :
- when being in the username field when using the autofill, both fields are detected as submitted but I get an invalid credentials message. Adding a random letter to the password then removing it do the trick, I can log in.
- when being in the password field when using the autofill, I get the "empty" message. In this case, adding a letter to the username do the trick.

For other password manager I don't know, but I suppose that on iOS they all work the same, from the keyboard, but I can be wrong, I'm not much of an Apple user...
