### ISSUE TITLE
Unable to add a specific TV Show "Madagascar: A Little Wild"

### ISSUE THREAD

**Issue by harroguk** [Ombi-app/Ombi#3984]
**Describe the bug**
Unable to add a specific TV Show "Madagascar: A Little Wild"

**To Reproduce**
1. Go to 'Discover'
2. Type 'Madagascar: A Little Wild'
3. click the TV Show that Appears
4. Infinite spinning circle

**Expected behavior**
Show details should appear

**Logs (Logs directory where Ombi is located)**
No error events appearing in logs

**Desktop (please complete the following information):**
 - OS: Windows Server 2008 R2

**Ombi Version (please complete the following information):**
 - Version 4.0.991.0
- Media Server Plex
- Database Type: SQLite

**Comment by spuniun** [comment]
I get this same behavior with the show Full Bloom. Only detail I can add is that this show did not have the TVDb ID present in TMDb earlier this week so I added it. Now it comes up in search but still cannot be requested in Ombi

**Comment by tidusjar** [comment]
All sorted now
