### ISSUE TITLE
mobile view

### ISSUE THREAD

**Issue by iPwnWolf** [Ombi-app/Ombi#3987]
Hi, I guess it is already being worked on, just wanted to report.
I would love for the mobile view that the grid view has multiple elements in a row like the desktop view and much smaller than currently. I would love to be able to see more than one movie only.

Thank you for your awesome developing, you rock! 👍🏽
![Screenshot_20210119_113524_com android chrome](https://user-images.githubusercontent.com/31454341/105023315-18cbf980-5a4b-11eb-99db-f1e124d202a0.jpg)

**Comment by tidusjar** [comment]
THanks, yeah this is a work in progress!
