### ISSUE TITLE
Ombi colors not working on first load

### ISSUE THREAD

**Issue by virusperfect** [Ombi-app/Ombi#3988]
**Describe the bug**
When I load up Ombi in a new browser or in an incognito tab then the very first time I log in, the site is not being displayed correctly. After reloading once everything works perfectly fine.

**To Reproduce**
1. Open a new incongnito tab
2. Log in with your account
3. The site will look different (lots of white)

**Expected behavior**
The site should load normally on the first try.

**Screenshots**
https://imgur.com/a/WIosV75

**Desktop (please complete the following information):**
- OS: Windows, Android

**Ombi Version (please complete the following information):**
- Version 4.0.991.0
- Media Server: Jellyfin
- Database Type: SQLite

**Comment by virusperfect** [comment]
Also I forgot to mention the "Change Theme" button doesn't work either on first load. And it looks like it's loading the light theme instead of the dark theme.

**Comment by VP-EN** [comment]
Just wanted to chip in, I have the exact same issue as described 👍  
I'm on v4.0.999, fresh install (except the leftover .db-files `Ombi.db | OmbiExternal.db | OmbiSettings.db`) ..

**Comment by virusperfect** [comment]
Fixed in 4.0.1009.0
