### ISSUE TITLE
Can't create account on ombi.io

### ISSUE THREAD

**Issue by teckel12** [Ombi-app/Ombi#3989]
**Describe the bug**
ombi.io only allows you to login, doesn't allow you to create a login

**To Reproduce**
1. Go to 'ombi.io' 
2. No create account link

**Expected behavior**
A create account link so account can be created. 

**Desktop (please complete the following information):**
 - OS: Android

**Ombi Version (please complete the following information):**
 - None, can't create account

**Additional context**
Written in haiku:

Ombi interesting, 
try creating account, 
no joy.

**Comment by tidusjar** [comment]
Ombi.io is a demo site, you need to host ombi yourself.

**Comment by teckel12** [comment]
Fail to understand,
Looking for readme, 
Confusion ensues.

**Comment by tidusjar** [comment]
You need to download ombi and host it yourself
