### ISSUE TITLE
Sonarr|Radarr|Lidarr Configuration dropdowns not populating...

### ISSUE THREAD

**Issue by monigala** [Ombi-app/Ombi#3990]
**Describe the bug**
When clicking either dropdown for Profile or Root Folder they are non existent.

**To Reproduce**
1. Click on Request from sidenav.
2. Click on Details button from any Movie|Tv Show|Album tab
3. Click the Gear Icon and the [Radarr|Sonarr|Lidarr] Configuration dropdown option
4. On Advanced Options modal, click either 'Select A Quality Profile' or 'Select a Root Folder' dropwdown.
5. Nothing shows up...

**Expected behavior**
When reviewing a request to approve. I want to set the quality profile and root folder. But the dropdowns don't populate robustly.

**Screenshots**
![image](https://user-images.githubusercontent.com/9090923/105130243-e4385c00-5aa3-11eb-8053-b2644b11dd1d.png)
![image](https://user-images.githubusercontent.com/9090923/105130266-ee5a5a80-5aa3-11eb-8190-91c5ba42b482.png)
![image](https://user-images.githubusercontent.com/9090923/105130284-f6b29580-5aa3-11eb-9bdd-a3f03d84932d.png)
![image](https://user-images.githubusercontent.com/9090923/105130296-fd410d00-5aa3-11eb-80f8-24675d92544a.png)
![image](https://user-images.githubusercontent.com/9090923/105130188-c834ba80-5aa3-11eb-8741-0f3c2240b314.png)
![image](https://user-images.githubusercontent.com/9090923/105130393-30839c00-5aa4-11eb-8e5a-4274ce5cc8ae.png)
![image](https://user-images.githubusercontent.com/9090923/105130439-45f8c600-5aa4-11eb-8897-0737ab77b067.png)
![image](https://user-images.githubusercontent.com/9090923/105130539-75a7ce00-5aa4-11eb-9263-44cb04e7d4f2.png)

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Window 10

**Ombi Version (please complete the following information):**
 - Version: 4.0.999.0
- Media Server: Plex
- Database Type: MySQL

**Additional context**
I am using Brave Browser... provided screenshot if version

**Comment by tidusjar** [comment]
Is your settings correct for those providers?

**Comment by twanariens** [comment]
This should be fixed in the latest Ombi V4 version. If not, check your configuration of Sonarr/Radarr on the configuration pages of Ombi (test the connection)
