### ISSUE TITLE
Email Deny Message Missing

### ISSUE THREAD

**Issue by gorgarp** [Ombi-app/Ombi#3992]
**Describe the bug**
If you deny a request, and include a message, the message is not present in the denied notification for the users.

**To Reproduce**
Create user account.
Request as that account
Login as admin
Deny request with message "something something reason"

**Expected behavior**
User gets denied notification and sees message as to why. Does not currently

Basically, the message isn't included in the denied email.

**Comment by tidusjar** [comment]
You've deleted half the template 
What version are you in, what's your template setup currently?

Need more information.

**Comment by twanariens** [comment]
Closed due to inactivity
