### ISSUE TITLE
Newsletter is triggering on days other than Friday

### ISSUE THREAD

**Issue by Seabmoby** [Ombi-app/Ombi#3998]
**Describe the bug**
According to the wiki, the newsletter should, "By default this is scheduled to run every Friday at 12GMT". But I have been getting newsletters most days of the week. I have received newsletters on the following days during January 2021: 1st, 2nd, 8th, 9th, 11th, 13th, 15th, 18th, 20th, 21st, and 22nd (today). All of these emails have been received at 12GMT. 

**To Reproduce**
1. Set up newsletter in the notifications section.
2. Download new movie or tv show
3. Wait for newsletter to trigger (usually within 24 hours of a new movie or show being added)

**Expected behavior**
No newsletter should trigger until Friday at 12GMT.

**Desktop (please complete the following information):**
 - OS: Windows 10.0.19041

**Ombi Version (please complete the following information):**
 - Version 4.0.739.0
- Media Server: Plex
- Database Type: SQLite 

**Additional context**

**Comment by tidusjar** [comment]
What's the CRON value in the Newletter job? (In settings under the jobs)..

You are also on a very old version of V4, i suggest you upgrade

**Comment by Seabmoby** [comment]
The newsletter section reads:
0 12 * * 5

**Comment by Seabmoby** [comment]
I have been copying my settings file over from old versions, and this old CRON value came with it.
