### ISSUE TITLE
Mobile Browser search view cuts off request button.

### ISSUE THREAD

**Issue by allenderj** [Ombi-app/Ombi#4000]
**Describe the bug**
When searching in a mobile browser on a phone if many rows of results are returned the request button can become unusable.

**To Reproduce**
1. 'Search for something that would result in multiple rows of results'
2. 'Tap on result that has a large synopsis that also has a result in the second row'
3. The green request button is placed behind the image of the result in the second row and become unusable.

**Expected behavior**
The request button should remain on top of the cover art or clicking the synopsis should navigate to the detail page for the media.

**Screenshots**
![ombi error](https://user-images.githubusercontent.com/21324000/105640968-6e3f4680-5e4f-11eb-994b-215c5654f9f8.jpg)

**Logs (Logs directory where Ombi is located)**
N/A

**Desktop (please complete the following information):**
N/A

**Ombi Version (please complete the following information):**
 - Version [e.g. 4.0.1014.0]
- Media Server [e.g. Plex]
- Database Type: SQLite (Please change if using MySQL)

**Additional context**
The expected behaivor appears to work fine on desktop browsers.

**Comment by shaggyze** [comment]
this happens on desktop versions as well if the synopsis is too long

**Comment by allenderj** [comment]
This looks to have been fixed in 4.0.1032.0.
