### ISSUE TITLE
Unable to click on movies on the right part of the image

### ISSUE THREAD

**Issue by virusperfect** [Ombi-app/Ombi#4001]
**Describe the bug**
Opening the movie detail page from the discovery page is very hard to do and counterintuitive. You can't click on the right side of the movie picture and almost everything is blocked by the text that pops out when you hover the image.

**To Reproduce**
1. Open the discovery page
2. Try to open the movie detail page
3. It won't work unless you click on the top left of the image

**Expected behavior**
It should be obvious how to open the movie detail page but it is not. I would also remove the text that appears when hovering on an image because it blocks the clickable area.

**Screenshots**
https://imgur.com/nZAQag1
In the Screenshot I marked the only place where you can click to get to the movie details page (and even there it sometimes doesn't work).

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Windows

**Ombi Version (please complete the following information):**
 - Version 4.0.1014.0
- Media Server: Jellyfin
- Database Type: SQLite

**Additional context**
I don't understand why the UI in v4 keeps getting changed. I'd rather have an app that is polished and works instead of one that looks fancy but breaks every week. I feel like focusing on the user experience (UX) would really help the project.

**Comment by shaggyze** [comment]
as a temporary solution I'm removing the layers above the movie so they can be clicked.

`#main-container\ dark > mat-sidenav-container > mat-sidenav-content > ng-component > div > div > div > discover-card > div > a > div.middle > div.small-text.ellipsis { display: none; }
#main-container\ dark > mat-sidenav-container > mat-sidenav-content > ng-component > div > div > div > discover-card > div > div { display: none; }
#main-container\ dark > mat-sidenav-container > mat-sidenav-content > ng-component > div > div > div > discover-card > div > a > div.middle > div.title { display: none; }
#main-container\ dark > mat-sidenav-container > mat-sidenav-content > ng-component > div > div > div > discover-card > div > a > div.middle { display: none; }`

**Comment by allenderj** [comment]
This looks like it may have been fixed in 4.0.1032.0

**Comment by virusperfect** [comment]
Fixed in 4.0.1035.0

**Comment by virusperfect** [comment]
The text is again blocking the clickable area in 4.0.1067.0. At least everything else is clickable.

**Comment by shaggyze** [comment]
this actually started happening again in 4.0.1040.0, so the details anchors just need to be added to top layers again or they can be removed.
`#main-container\ dark > mat-sidenav-container > mat-sidenav-content > ng-component > div > div > div > discover-card > div > div.middle > a > div > div.small-text.ellipsis { display: none; }
#main-container\ dark > mat-sidenav-container > mat-sidenav-content > ng-component > div > div > div > discover-card > div > div.middle > a > div > div.title { display: none; }`

**Comment by tidusjar** [comment]
Fixed in latest version
