### ISSUE TITLE
Sometimes movies on the discovery page keep on loading

### ISSUE THREAD

**Issue by virusperfect** [Ombi-app/Ombi#4002]
**Describe the bug**
When opening the discovery page some movies never load and the loading animation keeps on playing.

**To Reproduce**
1. Open discovery page
2. Some movies never load

**Expected behavior**
All images should load and not be stuck on the loading animation.

**Screenshots**
https://imgur.com/4DWVICG
On the bottom left the movie didn't load.

**Desktop (please complete the following information):**
 - OS: Windows

**Ombi Version (please complete the following information):**
 - Version 4.0.1014.0
- Media Server: Jellyfin
- Database Type: SQLite

**Comment by mrjohnpoz** [comment]
Just moved from preview version to the new development tag, v1032.. Seems to be more in the upcoming section.. A refresh of the page seems to clear it sometimes.  Maybe its a browser thing?  Using firefox 85.

**Comment by intrepidpursuit** [comment]
I have the exact same problem with TV shows. It is certain ones because they show up consistently in the same spot on discovery and always show up in search results. I was searching for the show "The Hustler" and both results are blank grey rectangles. Lots of random blanks in discovery though all show as TV shows as well. It is debilitating because these show can never be added.

**Comment by mrjohnpoz** [comment]
Yeah I just tried searching for that.. And while movies come up, if you set it for TV shows only.. You get boxes that never finish and can not even see what they are, etc..

**Comment by mrjohnpoz** [comment]
Just to update.. Currently running v1067, and still seeing this.. Specific example is searching for show bobby and giada.. It looks to find something.. But show never actually loads.. 

![imgr](https://user-images.githubusercontent.com/11797687/106574317-61ca8600-6500-11eb-8294-78e6472bd782.png)

**Comment by BonzTM** [comment]
Same for me, but for TV shows.  I am on containerd/k3s.  I was previously on linuxserver/ombi:latest v3x and it just randomly started happening.  Blew away everything and went with linuxserver/ombi:development fresh v4.  Same things.  I wonder if there are some limits being imposed on the destination side?

**Comment by mrjohnpoz** [comment]
Yeah not seeing this on actual "movies" its TV.. But it really only seems like its in the upcoming section.. Other sections popular and trending seem fine for TV

![tv](https://user-images.githubusercontent.com/11797687/107121294-3d9bdb80-6857-11eb-8914-6b904cb9c127.png)

Its becoming quite annoying.. Running 4.0.1090.0

**Comment by mrjohnpoz** [comment]
Just updated to 4.0.1116.0, and still seeing this issue on Upcoming for TV.

Is there any other info to provide - is there something that could be wrong.. I am not seeing anything in the logs to point to anything that could be the problem.

**Comment by tidusjar** [comment]
TV is because we don't have all the data, i'm currently switching TV providers so this will be resolved.
