### ISSUE TITLE
Combined / Movies / TV buttons don't work

### ISSUE THREAD

**Issue by virusperfect** [Ombi-app/Ombi#4004]
**Describe the bug**
On the discovery page the Combined / Movies / TV buttons don't work. When you press them nothing changes and the same movies / shows are still displayed.

**To Reproduce**
1. Open the discovery page
2. Click on Combined / Movies / TV
3. Nothing will change

**Expected behavior**
The buttons should work like in the previous versions.

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Windows

**Ombi Version (please complete the following information):**
 - Version 4.0.1036.0
- Media Server: Jellyfin
- Database Type: SQLite

**Additional context**

**Comment by tidusjar** [comment]
What browser are you using and can you show me a screenshot? For example of movies selected?

**Comment by virusperfect** [comment]
Sure, I'm using chrome:
https://imgur.com/1iGRZI8

I also just realised that after reloading the page everything is updated. But only clicking the button doesn't change anything.

**Comment by StevePearson-AIT** [comment]
I can confirm the same issue, on the "Discover" tab there are 3 sections (Popular/Trending/Upcoming), each with a selection slider for Combined/Movies/TV.
changing any of these has no immediate effect, you have to manually refresh the page to see the changes. I have tested this in both Chrome and Edge with the same result.

**Comment by virusperfect** [comment]
Fixed in 4.0.1037.0
