### ISSUE TITLE
Placement of download button isn't consistent

### ISSUE THREAD

**Issue by virusperfect** [Ombi-app/Ombi#4005]
**Describe the bug**
When you hover a movie / show the placement of the download button isn't consistent. Depending on how long the text of the description is, the button sometimes is placed higher or lower (and gets cut off).

**To Reproduce**
1. Go to the discovery page
2. Hover over a movie / tv show
3. Depending on the length of the description the download button placement is off

**Expected behavior**
The placement of the download button should always be in the same position.

**Screenshots**
https://imgur.com/qZBDBme
https://imgur.com/RlRoZvv
One screenshot shows the button lower than normal, the other screenshot shows the button higher than normal.

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Windows

**Ombi Version (please complete the following information):**
 - Version 4.0.1036.0
- Media Server: Jellyfin
- Database Type: SQLite

**Additional context**

**Comment by twanariens** [comment]
Is fixed in commit: https://github.com/Ombi-app/Ombi/commit/6b38d6e339f5529d694c6695b7d9e5c84f659171
Will be available when commit is accepted and merged with the build

**Comment by virusperfect** [comment]
Thank you
