### ISSUE TITLE
Jellyfin's filepath change breaks 'View on emby' 

### ISSUE THREAD

**Issue by kominoshja** [Ombi-app/Ombi#4008]
**Describe the bug**
Hi there

The view on emby button doesn't work for Jellyfin. The reason why is fairly straightforward.

Ombi assumes the path should look like `https://*************/#!/itemdetails.html?id=f45e463f074317d323d3c6893b1d3177`
However, the path actually looks like `https://*************/web/#!/details?id=f45e463f074317d323d3c6893b1d3177`

The lack of `/web` is not the problem, when using Jellyfin's nginx proxy it works fine, however `itemdetails.html` would need to be changed to `details`

**To Reproduce**
1. Click the 'View on Emby' button
2. Have an endless loop take place

**Expected behavior**
The correct item should show in Jellyfin

**Screenshots**
N/A

**Logs (Logs directory where Ombi is located)**
N/A

**Desktop (please complete the following information):**
 - OS: N/A

**Ombi Version (please complete the following information):**
 - Version 3.0.5223
- Media Server Jellyfin
- Database Type: MySQL

**Additional context**
N/A

**Comment by kominoshja** [comment]
Closing based on https://github.com/Ombi-app/Ombi/issues/3691

**Comment by tidusjar** [comment]
This should be resolved in v4, jellyfin has been completely split out from emby now.

**Comment by kominoshja** [comment]
> This should be resolved in v4, jellyfin has been completely split out from emby now.

Thanks! When is v4 planned to come out?
