### ISSUE TITLE
Run Importer Button does nothing

### ISSUE THREAD

**Issue by zotflix** [Ombi-app/Ombi#4010]
**Describe the bug**
Run Importer button seems to do nothing. 

**To Reproduce**

1. Click Configuration
2. Click User Management
3. Enable Import Plex Admin or Import Plex Users or both
4. Choose Permissions (I enabled request Music, Movie, TV) 
5. Click Submit
6. Get confirmation that Info was saved
7. Click Run Importer
8. Nothing. No error or confirmation. 

**Expected behavior**
Should import Plex users

**Screenshots**

**Logs (Logs directory where Ombi is located)**
Attached
[log-20210129.txt](https://github.com/Ombi-app/Ombi/files/5897372/log-20210129.txt)

**Desktop (please complete the following information):**
 - OS: WIndows Server 2016

**Ombi Version (please complete the following information):**
 - Version 4.0.1040.0
- Media Server Plex
- Database Type: SQLite (Please change if using MySQL)

**Additional context**
I checked around the web for a few suggestions. Only one I found for this issue was to open my firewall. I did. Port 5000 is open on the local network. 

Thank you for your time in advance.

**Comment by tidusjar** [comment]
Are there users in the user management section?

**Comment by zotflix** [comment]
There are now. I went to bed after I posted this and when I woke up it was populated. Guess it took some time for it to import them? Either way there was no acknowledgement than a task had started.
