### ISSUE TITLE
Mobile view not showing titles for each section V4

### ISSUE THREAD

**Issue by phairplay** [Ombi-app/Ombi#4012]
**Describe the bug**
Mobile view doesn't show what each section is.

**To Reproduce**
Photo provided

**Expected behavior**
Show titles for the three section
Popular
Trending
Upcoming

**Screenshots**
![ombi](https://user-images.githubusercontent.com/9025847/106356922-ec419880-62fa-11eb-8743-c5a8f42d49ac.jpg)

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Ombi Version (please complete the following information):**
 - 4.0.1037.0

**Comment by virusperfect** [comment]
Still not fixed in 4.0.1067.0

**Comment by phairplay** [comment]
Hi,
I've installed v4.0.1080 and the issue is still there
I've tried Iphone and another android phone.

**Comment by tidusjar** [comment]
Yes we have not yet fixed this

**Comment by twanariens** [comment]
Has been fixed in https://github.com/Ombi-app/Ombi/commit/2e5d5180083380cd0971d60bff2f172c6fefd127
Still need to wait for the commit to be accepted and merged into the build
