### ISSUE TITLE
V4 - Section issues no show all registers

### ISSUE THREAD

**Issue by vsc55** [Ombi-app/Ombi#4014]
**Describe the bug**
When accessing the issues section, only the first 10 records are shown. The buttons to navigate between pages do not appear. 

**To Reproduce**
1. Go to 'issues'
2. Only the first 10 results are displayed. 

**Expected behavior**
To be able to navigate between the pages to see all the records. Or to be able to select how many records we want to see. 

**Screenshots**
![imagen](https://user-images.githubusercontent.com/13438676/106379422-2e76e280-63ac-11eb-8b5b-d11c58251081.png)

**Desktop (please complete the following information):**
 - OS: Win10 (Firefox)

**Ombi Version (please complete the following information):**
 - Version 4.0.1040.0 
- Database Type: MySQL

**Comment by tidusjar** [comment]
This has been fixed
