### ISSUE TITLE
Width of menu sidebar depends on the length of the application name

### ISSUE THREAD

**Issue by virusperfect** [Ombi-app/Ombi#4024]
**Describe the bug**
Depending on how long your application name is the menu sidebar will be wider than it should be.

**To Reproduce**
1. Go to customization settings and choose a long application name
2. After saving the menu sidebar will be too wide

**Expected behavior**
The menu sidebar should have a fixed width that doesn't depend on the application name. The width of the menubar becomes especially a problem on mobile devices because it covers the whole screen making it impossible to close the sidebar.

**Screenshots**
https://imgur.com/0FXdd1J
In the screenshot I marked the offset between the normal width and the new width.

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Windows, Chrome

**Ombi Version (please complete the following information):**
 - Version 4.0.1067.0
- Media Server: Jellyfin
- Database Type: SQLite

**Additional context**

**Comment by twanariens** [comment]
Has been fixed in https://github.com/Ombi-app/Ombi/commit/88376eae6d81550b395f80c60140f8f43e74be42
Still need to wait for the commit the be accepted and merged into the build

**Comment by virusperfect** [comment]
It's happening again but it's now only a little margin.
https://imgur.com/Ei9rt0b

**Comment by twanariens** [comment]
That is how it should look
