### ISSUE TITLE
Medusa's quality profiles not recognized

### ISSUE THREAD

**Issue by bmn001** [Ombi-app/Ombi#4025]
**Describe the bug**
I understand that Medusa may not be officially supported, but it does work - sort of - when you tell Ombi to configure it as SickRage.

One thing that doesn't work as expected is Quality Profiles.  Ombi will present you with what (I presume is) a list of SickRage's quality profiles.  These don't really match up with Medusa's quality profiles.

Ombi will only let you select "HD" from various sources.  Medusa provides further granularity and lets you specify 720 vs 1080, for example.

**To Reproduce**
1. Set up Medusa as a source in Ombi as a SickRage server.
2. In Ombi's SickRage setting page, confirm that you can successfully connect to Medusa.
3. You'll see the Ombi's dropdown of Quality Profiles does not match what appears in Medusa.

**Expected behavior**
I would expect Ombi to retrieve a listing of quality profiles from Medusa before populating this dropdown box.

**Screenshots**

Quality profiles reported by Ombi:
![image](https://user-images.githubusercontent.com/4766836/106645794-af1b1780-6541-11eb-9179-7379ca6b0e06.png)
![image](https://user-images.githubusercontent.com/4766836/106645823-be01ca00-6541-11eb-9038-31bbd40cb957.png)

Medusa's quality profiles:
![image](https://user-images.githubusercontent.com/4766836/106645513-50559e00-6541-11eb-8ce0-5311b77cb5de.png)

**Logs (Logs directory where Ombi is located)**
n/a

**Desktop (please complete the following information):**
 - Raspbian 10 (buster)

**Ombi Version (please complete the following information):**
 - Version 4.0.1014.0
- Media Server: Plex Windows
- Database Type: SQLite
- Medusa Version: 0.5.6

**Comment by MatthK** [comment]
Is there a solution to this?
