### ISSUE TITLE
Ombi not adding requests to Radarr

### ISSUE THREAD

**Issue by Mascalerino** [Ombi-app/Ombi#4026]
**Describe the bug**
When requests to add movies are made Ombi is not adding the movies to Radarr. I do not see sync jobs running in the logs. I have double-checked both my Plex and Radarr integrations in Ombi. Both are configured correctly and testing connections is successful. I've attempted to schedule the Radarr job to run every minute in hopes I can observe it run in the logs, but to no avail I do not see any activity.

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Ombi Version (please complete the following information):**
 - Version: 4.0.779.0
- Media Server Plex
- Database Type: SQLite 

**Additional context**
I have Ombi in a VPS and I have Radarr in a Rbpi

**Comment by tidusjar** [comment]
Is radarr enabled in the Ombi settings?

**Comment by tidusjar** [comment]
You are also on a very old version of v4 please upgrade

**Comment by Mascalerino** [comment]
> You are also on a very old version of v4 please upgrade
I upgrade to V4.0.1067.0 and works!

Thank you!
