### ISSUE TITLE
titles with comma not showing up if the comma not present in search

### ISSUE THREAD

**Issue by xfouloux** [Ombi-app/Ombi#4028]
**Describe the bug**
If the movie title has a comma in it, it won't be shown in the list while searching for it

**To Reproduce**
example : french documentary "Legacy, notre héritage"

1. Search for "Legacy" it won't show up the movie
2. Search for "Legacy," and it will show it up

**Expected behavior**
the movie should appear in the list when searching without the comma

**Desktop (please complete the following information):**
 - OS: Windows 10 on chrome

**Ombi Version (please complete the following information):**
 - Version 4.0.991.0 (docker)
- Media Server : PLEX
- Database Type: SQLite

Thanks !

**Comment by tidusjar** [comment]
This is sort of out of my control, we pass the search term to the external provider, in this case TheMovieDb and they provide the results.
