### ISSUE TITLE
Icon next to name broken when using custom logo

### ISSUE THREAD

**Issue by phairplay** [Ombi-app/Ombi#4031]
**Describe the bug**
When using a custom logo for the front page the icon next to peoples names appears broken.

**To Reproduce**
add a custom logo link

**Expected behavior**
unbroken icon or option to choose a default custom icon

**Screenshots**
![Screenshot 2021-02-05 135320](https://user-images.githubusercontent.com/9025847/107042543-cbc18480-67b9-11eb-93a4-35682ee3fbc3.png)

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Windows

**Ombi Version (please complete the following information):**
 - Version 4.0.1085.0
- Media Server Plex
- Database Type: 

**Additional context**

**Comment by tidusjar** [comment]
Where is this image hosted, the way this works is that if there is an external image provided and the user has no gravatar image then we show the default.

See default image here: https://en.gravatar.com/site/implement/images/

**Comment by phairplay** [comment]
It's hosted on GitHub works as expected on the login screen
I'm adding users without email addresses.

**Comment by tidusjar** [comment]
Yeah the login screen uses the image directly. What you are seeing is a gravatar issue
