### ISSUE TITLE
v4 - Discover tabs not filtering correctly

### ISSUE THREAD

**Issue by DrSeussFreak** [Ombi-app/Ombi#4032]
**Describe the bug**
When I browse to the discover tabs, if I click on movies, tv or combined, when I switch between Popular, Trending and Upcoming, the movies are not filtered correctly.  When I first load the page, it starts me on combined popular, if I click Upcoming, it shows a mixture of popular, trending and upcoming.  Now if I last chose upcoming and I click to see TV only, it will start me on TV Upcoming BUT this is not the right data in the view.  If I change upcoming to popular and then back to upcoming, I am closer, but still have a mixture of older and newer shows.

**To Reproduce**
1. Go to Discover
2. Click on Movies --> Upcoming
3. Click on TV
4. You should be on TV --> Upcoming, but you will see a mixture of old and new shows
5. Stay on TV, click Popular and then Upcoming, you will see a more accurate list of upcoming shows, but still a mixture of older and newer shows
Note: The mixed results are much more prominent on the movies tab

**Expected behavior**
The screen results would be only upcoming shows

**Screenshots**
This screenshot is of me first browsing to TV/Upcoming
![Screen Shot 2021-02-05 at 10 43 24 AM](https://user-images.githubusercontent.com/175500/107062562-0e299800-679f-11eb-817a-a4f1f886bec8.png)

This second screenshot is after I click popular and then upcoming again
![Screen Shot 2021-02-05 at 10 43 34 AM](https://user-images.githubusercontent.com/175500/107062600-184b9680-679f-11eb-8d56-d0c8511377b6.png)

**Logs (Logs directory where Ombi is located)**
n/a

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.10

**Ombi Version (please complete the following information):**
 - Version 4.0.739.0
- Media Server Sonarr, Radarr
- Database Type: SQLite

**Comment by tidusjar** [comment]
Upgrade please!
