### ISSUE TITLE
Requests: FIlter not available for TV Shows

### ISSUE THREAD

**Issue by kylewschmitt** [Ombi-app/Ombi#4033]
**Describe the bug**
Filter options are not available on the TV tab of the requests menu. They work for both Movies and Music, but no buttons appear on the TV Shows tab.

**To Reproduce**
1. Go to 'Requests'
2. Click on 'TV Shows'
3. Filter menu on right is missing

**Expected behavior**
I would expect a filter menu to be available like the other tabs

**Screenshots**
![image](https://user-images.githubusercontent.com/71448220/107080790-bfd8c100-67bf-11eb-9fa4-0fd0145e1fc2.png)
![image](https://user-images.githubusercontent.com/71448220/107080866-d67f1800-67bf-11eb-8cc7-d7313d501570.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Ombi Version (please complete the following information):**
 - Version: 3.0.5223
- Media Server: Plex
- Database Type: SQLite

**Comment by tidusjar** [comment]
I'm not going to add this, please use v4 as the interface has been completly reworked.
