### ISSUE TITLE
Ombi not starting on Mac since version v4.0.1078

### ISSUE THREAD

**Issue by sstuetzel** [Ombi-app/Ombi#4035]
**Describe the bug**
When starting the App Ombi with any release newer than v4.0.1067 my Mac tells me that there is an error with Ombi (exec Unix) and suggest to delete it.
My environment:
Mac Mini M1 with OS 11.2 (Big Sur)
With the v4.0.1067 Ombi (exec Unix) Ombi App is working.

**To Reproduce**

**Expected behavior**
Ombi App should start on Mac with Big Sur

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: [OS 11.2 (Big Sur)]

**Ombi Version (please complete the following information):**
 - Version [v4.0.1078 plus]
- Media Server [Plex]
- Database Type: SQLite

**Comment by sstuetzel** [comment]
When the issue appears I have following log entries:
Feb  6 12:51:05 Svens-Mini-new com.apple.xpc.launchd[1] (com.PlaceTheServer.Ombi[1041]): Service could not initialize: 20D64: xpcproxy + 23712 [839][75A06642-92A3-341F-9E53-0360AAB45CA0]: 0x2
Feb  6 12:51:05 Svens-Mini-new com.apple.xpc.launchd[1] (com.PlaceTheServer.Ombi[1041]): Service exited with abnormal code: 78
Feb  6 12:51:05 Svens-Mini-new com.apple.xpc.launchd[1] (com.PlaceTheServer.Ombi): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Feb  6 12:51:52 Svens-Mini-new com.apple.xpc.launchd[1] (com.PlaceTheServer.Ombi[1057]): removing service since it exited with consistent failure - OS_REASON_EXEC | Gatekeeper policy blocked execution

**Comment by tidusjar** [comment]
They are not ombi logs. Have you tried starting it manually?

**Comment by sstuetzel** [comment]
Same when starting the app manually with ./ombi from terminal, or is there any other Manual way to start in an mac os environment?

**Comment by tidusjar** [comment]
Just manually from a terminal is fine. Just wondering if that works

**Comment by sstuetzel** [comment]
No it doesn't . The Message which appears is something like (have to iTranslate it): "Ombi is broken and can't be opened. It is advisable to transfer the item to trash"

**Comment by sstuetzel** [comment]
When deleting the Ombi file (unix exec) and just replace it with the one from Version v4.0.1067 then I can start the app again. So as described something musst have changed betten the version .1067 and .1078

**Comment by tidusjar** [comment]
The thing is everything between those versions is all frontend changes, I don't understand why this would happen for you. You sure there's nothing changed on your end?

**Comment by sstuetzel** [comment]
Regarding changes: did an update from Big Sur 11.1 to 11.2. Maybe the Gatekeeper has new issues. But I'm still wondering why from Version .1087 upwards it's not working for me. 
Steps i've done so far:
Reinstalled Mac OS -> no change
Deleted all Ombi Files killed the Ombi task. Installed .1090 -> No change
And a few other things....

Anyway I have a working Version with release .1067. Maybe something is broken in the Mac Gatekeeper Os Big Sur and the M1.... Found some issue reports in web regarding this...

**Comment by sstuetzel** [comment]
Finally, it was the Mac Gatekeeper that interrupted the installation. I had to grand access to several files Ombi and I think the .dylib files. This is a kind of dance... clicking open (in the warning) than grand access in the security settings and so on...
