### ISSUE TITLE
Cant login after x Uptime

### ISSUE THREAD

**Issue by stumpyofpain** [Ombi-app/Ombi#4036]
**Describe the bug**
After a while (several hours) i cant login to ombi v4 anymore.
Frontpage shows "wrong password or username"

**To Reproduce**
1. Go to omby login screen
2. insert login data
3. click on login

**Expected behavior**
The ability to login independend of the uptime of ombi.

**Screenshots**
![index](https://user-images.githubusercontent.com/63201947/107123913-b4a99200-68a0-11eb-8c1e-087cc74545ce.jpg)

**Logs (Logs directory where Ombi is located)**
Ombi shows a locked database.
[ombi_bug_login.txt](https://github.com/Ombi-app/Ombi/files/5937192/ombi_bug_login.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bit

**Ombi Version (please complete the following information):**
 - Version . any 4  , using 4.0.1085.0  right now
- Media Server emby, jellyfin, plex
- Database Type: SQLite 

**Additional context**
after reboot of ombi we can login again

ombi is set up to start as a servicee using nssm.

**Comment by tidusjar** [comment]
This is due to SQLite database locking, I suggest you migrate your database to MySQL if possiblehttps://docs.ombi.app/guides/migrating-databases/
