### ISSUE TITLE
Download button overlaps with description of movie / tv show

### ISSUE THREAD

**Issue by virusperfect** [Ombi-app/Ombi#4039]
**Describe the bug**
The download button on the discover page sometimes overlaps with the description of the movie / tv show.

**To Reproduce**
1. Go to discover page
2. Hover over a movie / tv show
3. The download button will sometimes be placed over the description

**Expected behavior**
The download button shouldn't be placed over the description text.

**Screenshots**
https://imgur.com/YPDpj2e

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Windows

**Ombi Version (please complete the following information):**
 - Version 4.0.1090.0
- Media Server: Jellyfin
- Database Type: SQLite 

**Additional context**
The download button changed in order to fix #4005. Even though that issue was fixed, now the button covers the description text. I also don't really like that the button is now only in the bottom left but that's just personal preference. And sorry for being so nitpicky :).

**Comment by tidusjar** [comment]
Should be fixed in the latest version (currently building)

**Comment by virusperfect** [comment]
Yes, thank you.
