### ISSUE TITLE
Loading screen bug

### ISSUE THREAD

**Issue by cjattard** [Ombi-app/Ombi#4042]
**Describe the bug**
Multi coloured Loading screen pops up before ombi UI loads .

**To Reproduce**
1. Load ombi v4 on any platform you see this until the login page loads

**Expected behavior**
Ombi UI loads before this artefact.  

**Screenshots**
![D2AB9BEB-E931-475D-A4A4-919259A9BA71](https://user-images.githubusercontent.com/45669214/107130026-b9cb0900-68c1-11eb-9a29-e399165dd304.jpeg)

**Logs (Logs directory where Ombi is located)**
Not applicable

**Desktop (please complete the following information):**
 - OS: Linux, macOS, IOS

**Ombi Version (please complete the following information):**
 - Version [e.g. 4.0.1095]
- Media Server Plex
- Database Type: SQLite 

**Additional context**

**Comment by tidusjar** [comment]
This report is not enough information to go on, for example look at app.ombi.io and it's loading fine.

**Comment by cjattard** [comment]
Oh it does it there too (see below on iOS at app.ombi.io. It shows for less than a second but the colour is unfortunately super bright so very noticeable. 
![Uploading 900F730D-39ED-4CAB-BC4C-3C0C011506D7.jpeg…]()

**Comment by cjattard** [comment]
Here is a video that might help. 

[Video of bug on demo site (clicking refresh in IOS safari)](https://youtu.be/xKUcuwLHPfg)

**Comment by tidusjar** [comment]
Yeah. This is intended functionality currently
