### ISSUE TITLE
v4 Mobile Notifications not Saving

### ISSUE THREAD

**Issue by jonad0521** [Ombi-app/Ombi#4044]
**Describe the bug**
Adding a user to the new/beta (not legacy) mobile notifications does not save. The Android app links to the Ombi instance, the user appears in the Mobile Notifications section, and a test notification can be sent. When the user is enabled, the the Submit button is pressed, the Successfully saved mobile settings notification appears. However, upon refresh, the user is not enabled. 

No relevant log messages appear in the log for this error, nor errors in the browser console.

**To Reproduce**
1. Download and link beta Ombi Android app to Ombi instance
2. Go to Mobile Notifications
3. Enable user and submit
4. Go back to the Mobile Notifications page or refresh and see that the user is no longer enabled.

**Expected behavior**
The User is enabled for Mobile Notifications.

**Logs (Logs directory where Ombi is located)**
I don't see any error messages in the log, but here's the section after trying to enable the notifications a few times

`2021-02-07 13:15:14.498 -05:00 [Information] Start processing HTTP request "GET" https://raw.githubusercontent.com/tidusjar/Ombi.News/main/README.md`
`2021-02-07 13:15:14.498 -05:00 [Information] Sending HTTP request "GET" https://raw.githubusercontent.com/tidusjar/Ombi.News/main/README.md`
`2021-02-07 13:15:14.509 -05:00 [Information] Received HTTP response headers after 11.1894ms - 200`
`2021-02-07 13:15:14.509 -05:00 [Information] End processing HTTP request after 11.4896ms - 200`
`2021-02-07 13:15:29.427 -05:00 [Debug] Batch acquisition of 0 triggers`
`2021-02-07 13:15:54.060 -05:00 [Debug] Batch acquisition of 0 triggers`
`2021-02-07 13:16:01.363 -05:00 [Information] Start processing HTTP request "GET" https://raw.githubusercontent.com/tidusjar/Ombi.News/main/README.md`
`2021-02-07 13:16:01.363 -05:00 [Information] Sending HTTP request "GET" https://raw.githubusercontent.com/tidusjar/Ombi.News/main/README.md`
`2021-02-07 13:16:01.373 -05:00 [Information] Received HTTP response headers after 10.089ms - 200`
`2021-02-07 13:16:01.373 -05:00 [Information] End processing HTTP request after 10.3728ms - 200`
`2021-02-07 13:16:08.583 -05:00 [Information] Start processing HTTP request "GET" https://raw.githubusercontent.com/tidusjar/Ombi.News/main/README.md`
`2021-02-07 13:16:08.583 -05:00 [Information] Sending HTTP request "GET" https://raw.githubusercontent.com/tidusjar/Ombi.News/main/README.md`
`2021-02-07 13:16:08.597 -05:00 [Information] Received HTTP response headers after 13.6864ms - 200`
`2021-02-07 13:16:08.597 -05:00 [Information] End processing HTTP request after 13.9499ms - 200`

**Desktop (please complete the following information):**
 - OS: Docker in unRAID
 
**Ombi Version (please complete the following information):**
 - Version 4.0.991
- Media Server: Plex
- Database Type: MySQL

**Additional context**

**Comment by tidusjar** [comment]
What do you mean by they are not enabled? How are you checking this?

**Comment by jonad0521** [comment]
I'm looking at the little slider next to the user name in the Mobile notifications section of Ombi. When I click it and it slides to on, it doesn't stick after refreshing the page.

![image](https://user-images.githubusercontent.com/68717785/107159920-087bb000-6961-11eb-934d-0837e49841f6.png)

**Comment by tidusjar** [comment]
Ah, that's just to toggle to send those users a message. If they are in the list, they are enabled.

**Comment by jonad0521** [comment]
Oh! Well I feel silly.

Then I guess now I'm wondering why I'm not getting notifications, but that's a whole bunch of troubleshooting I can do on my own. Thanks for the help.

**Comment by tidusjar** [comment]
The UI could be better for that. I'll look at improving it

**Comment by tidusjar** [comment]
Also I suggest you upgrade to the latest version

**Comment by jonad0521** [comment]
OK, updated to the latest version.

I'm still having trouble with mobile notifications. I can receive the test notification, but only when I already have the app open. It doesn't appear in my notifications if I'm not currently using the app.

**Comment by jonad0521** [comment]
The issue can be closed. New requests notifications don't get sent out if the user is set to Auto Approve.

**Comment by jonad0521** [comment]
And now i'm seeing that this is actually a _setting_ in Ombi. Facepalm
