### ISSUE TITLE
Admin unable to set a different root directory before submitting request

### ISSUE THREAD

**Issue by RyanAStrouse** [Ombi-app/Ombi#4051]
**Describe the bug**
In V3 as an admin I was able to adjust the root folder location before submitting a request. In V4 I am unable to do so, as any request is auto-approved and the option to adjust location is grayed out before a request is submitted.

**To Reproduce**
1. Find a movie or TV show as an admin
2. Click on gear icon, see grayed out "configuration" option

**Expected behavior**
An admin should be able to modify the root folder location before submitting a request.

**Screenshots**
![image](https://user-images.githubusercontent.com/4588529/107760135-4b3ddf00-6cf7-11eb-9039-6add35fd73d2.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.04

**Ombi Version (please complete the following information):**
 - Version 4.0.1104.0
- Media Server Plex
- Database Type: SQLite

**Additional context**
In discord you mentioned this.
"I'll improve it, so I think it can be a dropdown "Add with options" and it will popup the config dialog where you can set the quality profile and root path."

**Comment by twanariens** [comment]
This has been fixed in the latest V4 build of Ombi
