### ISSUE TITLE
V4 - Text exceeds button size

### ISSUE THREAD

**Issue by vsc55** [Ombi-app/Ombi#4053]
**Describe the bug**
The text is longer than the length of the button. 

**To Reproduce**
1. Go to Movie

**Expected behavior**
That the size of the button fits the text that it has inside. 

**Screenshots**
![imagen](https://user-images.githubusercontent.com/13438676/107861795-81d73f00-6e48-11eb-904e-130464271b87.png)

**Ombi Version (please complete the following information):**
 - Version 4.0.1104.0

**Comment by tidusjar** [comment]
Is there alternative text that could be used that would be shorter?

**Comment by vsc55** [comment]
Possible alternative translation to reduce the size "Marcar Disponible".
https://crowdin.com/translate/ombi/13/en-es?filter=basic&value=0#277

**Comment by tidusjar** [comment]
Done!
