### ISSUE TITLE
Navigation Menu Issue

### ISSUE THREAD

**Issue by kylewschmitt** [Ombi-app/Ombi#4055]
**Describe the bug**
Requests, User Management and Preference buttons not functioning. When clicked, they highlight and don't redirect.

**To Reproduce**
1. Login
2. Click any of the buttons mentioned.

**Expected behavior**
Navigation to appropriate page.

**Screenshots**
![image](https://user-images.githubusercontent.com/71448220/108112573-4add7500-7064-11eb-8599-693106d067f7.png)

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Ombi Version (please complete the following information):**
 - Version: 4.0.1112.0 
- Media Server: Plex
- Database Type: SQLite

**Comment by tidusjar** [comment]
I cannot reproduce. 

Can you show if there Are any errors in your browser console? F12.

If so can you press the network tab and then refresh the page and you should see something like
![image](https://cloud.githubusercontent.com/assets/6642220/23088047/eac44abc-f570-11e6-9f23-d2eb022ed059.png)


If you click the red text and then the preview tab like the image above and post the result?

**Comment by kylewschmitt** [comment]
Looks to be so.
![image](https://user-images.githubusercontent.com/71448220/108113459-8d538180-7065-11eb-8525-7cc2ce927249.png)

**Comment by kylewschmitt** [comment]
Just a quick update to help you isolate. The issue does appear to be with the latest DEV release. Built a new container with v4.0.1104 and this issue is gone. 

Hope this helps!

**Comment by kylewschmitt** [comment]
Messing around with settings and noticed my port mapping didnt stick on the container. Set the mapping to random host port and seems to have resolved the issue. 

Sorry for wasting your time!

![image](https://user-images.githubusercontent.com/71448220/108253384-b63c4b00-7127-11eb-84fa-1eb921209293.png)
