### ISSUE TITLE
Segmentation Fault on launch

### ISSUE THREAD

**Issue by Just8Will** [Ombi-app/Ombi#4063]
**Describe the bug**
On running the app it immediately crashes and prints "Segmentation fault" to the terminal.

**To Reproduce**
Install ombi using the steps described here https://docs.ombi.app/guides/installation/ on raspberry pi os lite (up to date as of today)
No errors are produced during installation.
checking the status of the service immediately after installation shows that it is no running.
manually running the executable (/opt/Ombi/Ombi) returns Segmentation Fault.
I have tried this with both the v3 and v4 repos and both produce the same error
current versions as of this post are 3.0.5223 and 4.0.1116

**Expected behavior**
Ombi to launch.

**Screenshots**
![Screenshot_2021-02-20_19-25-54](https://user-images.githubusercontent.com/10267776/108606340-84d6b000-73b1-11eb-978b-3ce9ea1eb236.png)

**Logs (Logs directory where Ombi is located)**
No Logs are produced because it crashes instantly

**Desktop (please complete the following information):**
 Raspberry Pi OS lite on a raspberry pi zero w

**Ombi Version (please complete the following information):**
 - Version 3.0.5223 and version 4.0.1116
- Media Server [e.g. Plex] - never got that far
- Database Type: SQLite  - if that's what the default is

**Comment by Just8Will** [comment]
if there's anything I can do to help narrow down the issue please let me know

**Comment by tidusjar** [comment]
What binaries are you using?

**Comment by Just8Will** [comment]
Thanks for getting back to me.
When I run apt install Omni at one point it says
"Preparing to unpack .../ombi_4.0.1116_armhf.deb ..."

The file /opt/Ombi/Ombi is 112035395 bytes on disk (ls -l)
Is that the information you need?

Could it be that the pi zero is armv6?
