### ISSUE TITLE
V4 -"Auto Delete Available Requests" not working 

### ISSUE THREAD

**Issue by zobe123** [Ombi-app/Ombi#4067]
**Describe the bug**
i have enabled this feature with delete after 1 day, But after 2 or more days avaiable requests are still there with status available.

**To Reproduce**
1. activate this feature
2. nothing happens

**Expected behavior**

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - Linux Ubuntu x64

**Ombi Version (please complete the following information):**
 - Version 4.0.1116.0
- Media Server [e.g. Plex]
- Database Type: SQLite 
- 
**Additional context**

**Comment by tidusjar** [comment]
Can you upload your logs on the day it should have happened?

**Comment by zobe123** [comment]
Sure, but i read the logs and found this:

set available:

> 2021-02-26 11:30:06.303 +01:00 [Debug] Calling Execute on job Plex.IPlexAvailabilityChecker
> 2021-02-26 11:30:08.513 +01:00 [Information] [PAC] - Movie request "The Mortuary Collection - 1112" is now available, sending notification
> 

System.IAutoDeleteRequests says not today:

> 2021-02-28 00:00:00.024 +01:00 [Debug] Calling Execute on job System.IAutoDeleteRequests
> 2021-02-28 00:00:00.028 +01:00 [Debug] Trigger instruction : NoInstruction
> 2021-02-28 00:00:00.028 +01:00 [Debug] Calling Execute on job System.IIssuesPurge
> 2021-02-28 00:00:00.029 +01:00 [Information] Starting Plex Content Cacher Recently Added Scan
> 2021-02-28 00:00:00.029 +01:00 [Information] Starting to cache the content on server "******"
> 2021-02-28 00:00:00.035 +01:00 [Information] Deleting 0 movie requests that have now been scheduled for deletion, All available requests before :02.26.2021 will be deleted

So I will wait for tomorrow, possibly "delete after days of availability" set to 1, means actually 3 days.

**Comment by zobe123** [comment]
my suspicions were correct: 
> 2021-03-01 00:00:00.030 +01:00 [Debug] Calling Execute on job System.IAutoDeleteRequests
> 2021-03-01 00:00:00.037 +01:00 [Information] Starting Plex Content Cacher Recently Added Scan
> 2021-03-01 00:00:00.037 +01:00 [Information] Starting to cache the content on server "*****"
> 2021-03-01 00:00:00.038 +01:00 [Debug] Calling Execute on job System.IIssuesPurge
> 2021-03-01 00:00:00.041 +01:00 [Information] Deleting 1 movie requests that have now been scheduled for deletion, All available requests before :02.27.2021 will be deleted
> 2021-03-01 00:00:00.042 +01:00 [Information] Deleting movie title The Mortuary Collection as it was approved on 01.01.0001 12:00 vorm.
> 2021-03-01 00:00:00.054 +01:00 [Debug] Trigger instruction : NoInstruction
> 2021-03-01 00:00:00.104 +01:00 [Information] Deleting 0 episode requests that have now been scheduled for deletion, All available requests before :02.27.2021 will be deleted
> 2021-03-01 00:00:00.201 +01:00 [Debug] Trigger instruction : NoInstruction
> 2021-03-01 00:00:04.011 +01:00 [Information] Finished Plex Content Cacher, with processed content: 0, episodes: 0. Recently Added Scan: True
