### ISSUE TITLE
Display jumbled after ssl proxy setup

### ISSUE THREAD

**Issue by ehosch** [Ombi-app/Ombi#4068]
**Describe the bug**
Menu items overlay other menu items.

**To Reproduce**
1. Setup nginx ssl proxy
2. Access ombi with https
3. Open menu

**Expected behavior**
Should look the same as http

**Ombi Version (please complete the following information):**
 - Version [4.0.1118.0]

**Comment by tidusjar** [comment]
Working fine for me, https://app.ombi.io/ is also working fine. Need more info
