### ISSUE TITLE
v4 - TV Show marked Available, but still showing in Pending Requests

### ISSUE THREAD

**Issue by soulvoid86** [Ombi-app/Ombi#4071]
**Describe the bug**
I'm using the show WandaVision (2021) as the example here. The show is actively running it's first season, and is on episode 8 of 9. Episode 9 comes out March 5th, 2021. All of the 8 available episodes are marked as available, except episode 9 as it hasn't aired yet. But this has caused Ombi to leave the item in the Processing Requests queue, while it shows as available on the items request page. Screenshots below. This has then caused it to not send an email to the user reporting this show as Available, or Partially Available.

I can mark the request as Available manually, but that will falsely report that all of season 1 is available to the user, and the Ombi interface.

![image](https://user-images.githubusercontent.com/11574738/109396506-f35ec500-78ff-11eb-9e15-8a9acf7c9012.png)

![image](https://user-images.githubusercontent.com/11574738/109396518-01144a80-7900-11eb-95b4-9a90dfa4c8d7.png)

![image](https://user-images.githubusercontent.com/11574738/109396524-07a2c200-7900-11eb-9e4a-fffa2e7f4d53.png)

**To Reproduce**
Have a show that is actively airing, but a full season is not yet available. Unsure if this affects shows with multiple season, as WandaVision is the only one I've noticed this with so far.

**Expected behavior**
I'd expect it to show as Partially Available, or similar, and email the user the it is partially available.

**Screenshots**
Screenshots above.. sorry.

**Logs (Logs directory where Ombi is located)**
N/A

**Desktop (please complete the following information):**
 - OS: Linux Docker running on Portainer.

**Ombi Version (please complete the following information):**
 - Version 4.0.1122.0 - Though I did just updated today from 4.0.7XX
 - Media Server - Plex, and TheTVDB has been my metadata source for 7 years.
- Database Type: SQLite (Please change if using MySQL) - Unsure.

**Additional context**
I'm not sure if this would be considered a bug, feature request, etc. I also saw similar posts, though they were missing critial details, or were marked as WontFix, etc. Figured it'd be best to make my own bug report.

**Comment by BRTPOB** [comment]
I've got the same thing for movies, however it's not only just "Processing" but also movies that exist in Radarr but haven't been downloaded but were approved, or as you stated, items that haven't been approved yet.

**Comment by tidusjar** [comment]
Regarding the TV issue, just must be a wrong check on the details page for that Button, I'll look into it.

With Movies, I'd need a bit more information on your issue as I don't fully understand what you man @BRTPOB

**Comment by BRTPOB** [comment]
Sure thing. Basically, I woke up this morning to Ombi telling me (and a friend) that 4 movies had been successfully downloaded and processed/added to Plex, but they hadn't. One of the movies is still pending approval, one of them has been approved but not downloaded, another was deleted from Radarr altogether.
