### ISSUE TITLE
Spelling error when requesting TV show that has no data yet

### ISSUE THREAD

**Issue by BRTPOB** [Ombi-app/Ombi#4073]
**Describe the bug**
As the subject says, when attempting to request/add a new show that does not currently have any data, there's a spelling error in the lightbox pop up.

**To Reproduce**
1. Login
2. Change Upcoming to TV
3. Click on Star Wars Andor
4. Lightbox with spelling error pops up, which reads "There unfortunatly is no episode data for this show yet! "

**Expected behavior**
Expected message to read as "There unfortunately is no episode data for this show yet!"

**Screenshots**
Not needed.

**Logs (Logs directory where Ombi is located)**
N/A

**Desktop (please complete the following information):**
- OS: Linux Mint 20

**Ombi Version (please complete the following information):**
- Version 4.0.1122.0 
- Media Server Plex
- Database Type: SQLite

**Additional context**

**Comment by BRTPOB** [comment]
Thanks tidusjar, but I left a comment on the commit that by capitalizing the U that's still a spelling error, as it should be "unfortunately" not "Unfortunately", otherwise it looks good.

**Comment by Berserkir-Wolf** [comment]
Easy fix, PR in place for it.

**Comment by Berserkir-Wolf** [comment]
And merged.
