### ISSUE TITLE
Movies added through Ombi that were then deleted in Radarr still show up as requests in Ombi

### ISSUE THREAD

**Issue by BRTPOB** [Ombi-app/Ombi#4076]
**Describe the bug**
When a movie has been added through Ombi, then removed from Radarr, Ombi will not update the requests to then remove said request but instead keep showing them as "Processing."

**To Reproduce**
1. Add a movie (for example Foo Fighters: Live at Glastonbury 2017).
2. Approve the request
3. Switch to Radarr
4. Remove Foo Fighters: Live at Glastonbury 2017 from the list of movies.
5. Go back to Ombi.

**Expected behavior**
Expected Ombi to update and remove the requests that no longer have an item assigned to the particular media downloader.

**Screenshots**
https://imgur.com/a/sHNlwBj

**Logs (Logs directory where Ombi is located)**
Don't think this is required, but will add later if necessary.

**Desktop (please complete the following information):**
 - OS: Ubuntu Docker

**Ombi Version (please complete the following information):**
- Version: 4.0.1122.0
- Media Server: Plex
- Database Type: SQLite

**Additional context**
I don't know if it's related, but I was previously using Ombi v3, which didn't link up to Radarr v3 and I just switched to Ombi v4 and got the linking working again.

**Comment by tidusjar** [comment]
Ombi will not remove a request just because you removed it in Radarr.

The use case for this is that you could remove it from Radarr due to it being the wrong root folder for example. Or finding that movie via other means.
