### ISSUE TITLE
Ombi won't start after installing v4.0.1132

### ISSUE THREAD

**Issue by Xarano-GIT** [Ombi-app/Ombi#4078]
**Describe the bug**
After updating to v4.0.1132, I saw that the ombi process will not start anymore.

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Logs (Logs directory where Ombi is located)**
Log did not contain anything useful that I could see regarding this. SystemCTL status below:

> `● ombi.service - Ombi - PMS Requests System
>    Loaded: loaded (/lib/systemd/system/ombi.service; enabled; vendor preset: enabled)
>    Active: activating (auto-restart) (Result: signal) since Mon 2021-03-01 10:37:54 GMT; 1s ago
>   Process: 6427 ExecStart=/opt/Ombi/Ombi --storage /etc/Ombi/ (code=killed, signal=ABRT)
>  Main PID: 6427 (code=killed, signal=ABRT)`

**Desktop (please complete the following information):**
 - OS: Debian 10

**Ombi Version (please complete the following information):**
 - Version v4.0.1132
- Media Server N/A
- Database Type: SQLite

**Additional context**

**Comment by RobinMol** [comment]
**having same issue:**

502 Bad Gateway since last update, docker logs show following output:

Can't set the base URL because we cannot find the file at /ClientApp/dist/index.html, if you are trying to set a base url please report this on Github!
Unhandled exception. System.Exception: Can't set the base URL because we cannot find the file at /ClientApp/dist/index.html, if you are trying to set a base url please report this on Github!
   at Ombi.Program.SortOutBaseUrl(String baseUrl, SettingsContext settingsDb, GlobalSettings ombiSettingsContent)
   at Ombi.Program.Main(String[] args)
   at Ombi.Program.<Main>(String[] args)

**Comment by JuniperMS** [comment]
I'm having the same issue, too.

**Comment by tidusjar** [comment]
You guys are not passing a baseurl into the startup args or even have one?

**Comment by RobinMol** [comment]
Correct

**Comment by tidusjar** [comment]
Just pushed an update that should help with this.

**Comment by RobinMol** [comment]
at the moment my install is still at 4.0.1131. Think I need to wait until linuxserver picks up the most recent version? Using their docker.

**Comment by RobinMol** [comment]
Checking now If I can contact them on Discord

**Comment by RobinMol** [comment]
Latest update, actually seems issue was already resolved, just pulled latest docker (atm its still 1132). And now Ombi works again.

**Comment by JuniperMS** [comment]
I'll give it a shot once it's published for docker.  Thanks T!

**Comment by Xarano-GIT** [comment]
> Just pushed an update that should help with this.

Seems like I personally misdiagnosed my issue,

After remembering that journalctl is a thing, I checked it and saw I was getting the below:

> `sudo journalctl -u ombi -b -e`
>
> `Mar 01 13:10:42 server Ombi[19919]: Unhandled exception. System.UnauthorizedAccessException: Access to the path /opt/Ombi/ClientApp/dist/index.html' is denied.`
>
> `Mar 01 13:10:42 server Ombi[19919]:  ---> System.IO.IOException: Permission denied`

Checking the permissions of this file shows root as the owner:

 
> `me@server:/opt/Ombi/ClientApp/dist$ ls -l index.html`
>
> `-rw-r--r-- 1 root root 75651 Mar  1 12:33 index.html`
 

So, I chown'd it to ombi

> 
> `me@server:/opt/Ombi/ClientApp/dist$ sudo chown ombi:ombi index.html`
> `me@server:/opt/Ombi/ClientApp/dist$ ls -l index.html`
>
> `-rw-r--r-- 1 ombi ombi 75651 Mar  1 12:33 index.html`
> 

After that, Ombi runs like normal.

**Comment by Xarano-GIT** [comment]
Just updated to v4.0.1134, same issue again with the file permissions.

Seems like /opt/Ombi/ClientApp/dist/index.html is not being changed on install and is reverting back to root:root

**Comment by Nothing4You** [comment]
does ombi try to open that file read-write? in my installation that is not possible as the folder is owned by root. ombi should only need to write in the data dir. i tested that i can read the file without problems as ombi user.

**Comment by enormouspoon** [comment]
> > Just pushed an update that should help with this.
> 
> Seems like I personally misdiagnosed my issue,
> 
> After remembering that journalctl is a thing, I checked it and saw I was getting the below:
> 
> > `sudo journalctl -u ombi -b -e`
> > `Mar 01 13:10:42 server Ombi[19919]: Unhandled exception. System.UnauthorizedAccessException: Access to the path /opt/Ombi/ClientApp/dist/index.html' is denied.`
> > `Mar 01 13:10:42 server Ombi[19919]:  ---> System.IO.IOException: Permission denied`
> 
> Checking the permissions of this file shows root as the owner:
> 
> > `me@server:/opt/Ombi/ClientApp/dist$ ls -l index.html`
> > `-rw-r--r-- 1 root root 75651 Mar  1 12:33 index.html`
> 
> So, I chown'd it to ombi
> 
> > `me@server:/opt/Ombi/ClientApp/dist$ sudo chown ombi:ombi index.html`
> > `me@server:/opt/Ombi/ClientApp/dist$ ls -l index.html`
> > `-rw-r--r-- 1 ombi ombi 75651 Mar  1 12:33 index.html`
> 
> After that, Ombi runs like normal.

I'm running 4.0.1133.0 and chown'ing back to ombi:ombi fixed Ombi not starting up. Now everything works perfectly.

**Comment by Nothing4You** [comment]
as of v4.0.1134 it is indeed working without permissions, however, this seems like a design flaw to me that it tries to update dist files.

**Comment by Xarano-GIT** [comment]
Is this issue possibly related to commit 472803e in release v4.0.1128?

> 472803e Ensure we always update the index page with the new base url

**Comment by enormouspoon** [comment]
I just updated to 1135 (i'm on linux mint 20.1) and Ombi broke again, wouldn't start up. I had to chown the index.html file again before Ombi would start up. Something in the update process reverts index.html back to root:root and breaks.

~$ sudo chown ombi:ombi /opt/Ombi/ClientApp/dist/index.html

**Comment by Nothing4You** [comment]
just tested a few of the the last releases:
- v4.0.1122 working
- v4.0.1128 broken
- v4.0.1135 broken

**Comment by tidusjar** [comment]
So I know what has 'broken' this, so as part of the reverse proxy work due to Angular not supporting this scenario (Dynamic proxy sub path) I've needed to work around the issue, and as part of that work around I now need to write to the Index.html to set the `base href` path.

Can you confirm what systems you are running for it not to have permission after updates?

**Comment by Nothing4You** [comment]
I'm running my own container where the files are world readable, owned by root and ombi is running under a custom user id.
I don't launch the container as root ever so I can't dynamically chown the files.

You should expect the same behavior on any "regular" non-docker install where ombi is installed system wide.

**Comment by Nothing4You** [comment]
A workaround for now could be to not try to write to it if the base url is not set?

**Comment by Nothing4You** [comment]
Looking at the code it looks like that's supposed to happen already.

I'm currently using `ENTRYPOINT ["/ombi/Ombi", "--storage", "/storage"]`, not passing a custom `baseUrl`.

Did that behavior change?
Even before 472803ec316afd2f0a49d3f01abacecd0c143e38 that file was written to in that logic branch.

**Comment by tidusjar** [comment]
Yeah that's fair, I'll make improvements.

**Comment by mrhotio** [comment]
PEOPLE SWITCH TO hotio/ombi   already had the fix immediately after it popped up

tbh I don't know why you'd run any other container besides hotio and linuxserver

**Comment by Nothing4You** [comment]
as already mentioned, I don't launch my containers as root.
That's not really the issue here though imo, this issue is about the fact that ombi requires being able to rewrite "itself" at runtime, which should normally not be needed.
this isn't just an issue with custom docker builds but also for system wide installs.

**Comment by tidusjar** [comment]
I wouldn't call changing a html element rewriting itself. Lsio container doesn't have this issue either. 

If you have an alternative suggestion or solution to the issue I've spends months on and off looking into I'd be really happy to listen.

**Comment by Nothing4You** [comment]
would copying and serving the html from storage be possible?

**Comment by mrhotio** [comment]
Do it like the radarr team does it, serve a string not a file.

**Comment by tidusjar** [comment]
I don't think it would be possible putting it behind the storage parameter. But I can check that.

Regarding to putting it as a string, not sure what you mean by that?

**Comment by Nothing4You** [comment]
I assume declaring the html as a string and returning that on the request instead of delegating it to the static file handler

**Comment by RobinMol** [comment]
using linuxserver docker behind reverse proxy, no base url set, v4.0.1131 didnt start, v4.0.1132 worked fine, now on v4.0.1136 and also works fine. To me it seems case closed :)

**Comment by Nothing4You** [comment]
about serving it from a string - what about loading the file into memory on startup, performing the replacement in memory and sending that updated string to the client when requested instead of reading from disk?
then you can still have the angular generated file but also serve the content dynamically.

**Comment by Xarano-GIT** [comment]
Just updated to the latest version which auto started correctly and didn't have the permission issue, so this is fixed for me.
