### ISSUE TITLE
Very high cpu load and page load times on discover page with tv or combined enabled on mysql

### ISSUE THREAD

**Issue by WeisseTeetasse** [Ombi-app/Ombi#4082]
**Describe the bug**
When accessing the discover page ombi and mysql (mysql more so) produce extremely high cpu load (close to 100%) for a very long time (~15-20 seconds). This only happens when Combined or TV is enabled.
Also the pages takes around 15-20 seconds to fully load.
It is slightly better when i throw 20 cores at the problem instead of 2 but we are still looking at ~10 seconds of high cpu and page load times.

**To Reproduce**
1. Go to discover page with TV enabled
2. observe CPU usage

**Screenshots**
<img width="1834" alt="Screenshot 2021-03-03 at 19 48 28" src="https://user-images.githubusercontent.com/68740702/109856183-7dd55a80-7c59-11eb-84fb-c4d4f24aee20.png">

**Logs (Logs directory where Ombi is located)**
Nothing in logs, neither ombi nor mysql

**Desktop (please complete the following information):**
 - OS: Debian 10 inside LXC on Debian 10

**Ombi Version (please complete the following information):**
 - Version 4.0.1139.0
- Media Server Plex
- Database Type: Mysql

**Comment by Ezzahhh** [comment]
I also experience this, but I'm not sure if it's related that a sync is happening in the background with Emby/Plex

**Comment by tidusjar** [comment]
So just to update you on this, i'm currently working on switching our TV data provider, I believe this will help reduce this. I'm not seeing this issue myself, but I believe this is the cause.

**Comment by WeisseTeetasse** [comment]
> So just to update you on this, i'm currently working on switching our TV data provider, I believe this will help reduce this. I'm not seeing this issue myself, but I believe this is the cause.

Thanks for the update. Could the TV provider be responsible for high load on the mysqld process?
The mysqld in my screenshot is only serving Ombi.

**Comment by tidusjar** [comment]
It's more around the extra processing ombi needs to do to work around issues with that TV provider

**Comment by WeisseTeetasse** [comment]
> It's more around the extra processing ombi needs to do to work around issues with that TV provider

Ok, i'll test it once your switch is live and can report back. Thank you.

**Comment by twanariens** [comment]
The latest version of Ombi V4 (develop) is using the new TV provider. @WeisseTeetasse Are you able to test if that fixes the high CPU loads?

**Comment by WeisseTeetasse** [comment]
> The latest version of Ombi V4 (develop) is using the new TV provider. @WeisseTeetasse Are you able to test if that fixes the high CPU loads?

Do you have a  version number that includes those fixes? I can probably test this weekend.

**Comment by twanariens** [comment]
I would go with the latest develop build. https://github.com/Ombi-app/Ombi/releases/tag/v4.0.1425

**Comment by WeisseTeetasse** [comment]
I tried with 4.0.1425.
The CPU usage is much better, but still maxes out all cores for 3 seconds when displaying TV on the discover page, compared to only displaying movies which only barely registers on cpu usage.

**Comment by twanariens** [comment]
@WeisseTeetasse Do you have "Hide Available Content On The Discover Page" enabled under Settings -> Configuration -> Customization? If so, what happens to the performance when you disable it?

**Comment by WeisseTeetasse** [comment]
I don't have it enabled.

**Comment by twanariens** [comment]
I am assuming the issue lies in the availability check done to input the label on the top right of the content poster.
To check whether a movie is available or not, it has to collect data on 1 row of data in MySQL. This results in almost no resource impact. TV Shows on the other hand are much harder to check the availability. We have retrieve the TV Show from TMDB and check what episodes and seasons are there, then crosscheck with what is available on your Plex. Meaning that on large TV Shows this can cause 100+ queries to check if you have all episodes.

Can you check if your MySQL is resource capped when you open the Discover page with the filter on TV?

**Comment by WeisseTeetasse** [comment]
After enabled and disabling  "Hide Available Content On The Discover Page" it took 10+ sec of 100% CPU usage, which was weird.
So after restarting the service the cpu load is generally lower and does not take 100% anymore but still 2-3 seconds of 60%+ of the 2 cores enabled in that container with the ombi process taking the majority of it. Not exactly sure what you mean by resource capped.

**Comment by twanariens** [comment]
Ombi is querying the MySQL database a lot when the discover page is generated (due to the availability label). If you have only given the MySQL container 1 cpu, Ombi will remain in a "waiting" state until the MySQL instance replies with the requested data. 

So I am wondering how your MySQL container is holding up (performance wise) when Ombi hits it to generate the Discover page.

**Comment by WeisseTeetasse** [comment]
Ombi and mysql share the same container (lxc) with 2 cpus, ombi taking the majority of cpu time. The initial issue occurred when giving it 24 cores too.

**Comment by twanariens** [comment]
@tidusjar Any insights on this?

**Comment by tidusjar** [comment]
No, I'm going to have to do some SQL profiling to see what's going on

**Comment by WeisseTeetasse** [comment]
Quick update:

On the first visit mysqld takes all cpus for 10+ seconds.
On subsequent visits it's only the ombi process that maxes the cpus fir 2 seconds.

**Comment by tidusjar** [comment]
I've made a change to improve this, the first time loading will always be a bigger hit, but after that there should be improvements
