### ISSUE TITLE
Latest version crashes with System.ArgumentException: The path in 'value' must start with '/'

### ISSUE THREAD

**Issue by phillycheeze** [Ombi-app/Ombi#4084]
**Describe the bug**
After upgrading to the lastest version of Ombi on Linux, it fails to start with the following error in logs:

```
Mar 04 21:46:31 plex-media-server Ombi[277275]: Wrote new baseurl at /opt/Ombi/ClientApp/dist/index.html
Mar 04 21:46:31 plex-media-server Ombi[277275]: We are running on http://*:5000
Mar 04 21:46:31 plex-media-server Ombi[277275]: /opt/Ombi
Mar 04 21:46:31 plex-media-server Ombi[277275]: Unhandled exception. System.ArgumentException: The path in 'value' must start with '/'. (Parameter 'value')
Mar 04 21:46:31 plex-media-server Ombi[277275]:    at Microsoft.AspNetCore.Http.PathString..ctor(String value)
Mar 04 21:46:31 plex-media-server Ombi[277275]:    at Microsoft.AspNetCore.Http.PathString.op_Implicit(String s)
Mar 04 21:46:31 plex-media-server Ombi[277275]:    at Ombi.Startup.Configure(IApplicationBuilder app, ILoggerFactory loggerFactory, IServiceProvider serviceProvider)
Mar 04 21:46:31 plex-media-server Ombi[277275]:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wr>
Mar 04 21:46:31 plex-media-server Ombi[277275]:    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, Cultu>
Mar 04 21:46:31 plex-media-server Ombi[277275]:    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
Mar 04 21:46:31 plex-media-server Ombi[277275]:    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
Mar 04 21:46:31 plex-media-server Ombi[277275]:    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass15_0.<UseStartup>b__1(IApplicationBuilder app)
Mar 04 21:46:31 plex-media-server Ombi[277275]:    at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilter>
Mar 04 21:46:31 plex-media-server Ombi[277275]:    at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
Mar 04 21:46:31 plex-media-server Ombi[277275]:    at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
Mar 04 21:46:31 plex-media-server Ombi[277275]:    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
Mar 04 21:46:31 plex-media-server Ombi[277275]:    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
Mar 04 21:46:31 plex-media-server Ombi[277275]:    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
Mar 04 21:46:31 plex-media-server Ombi[277275]:    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
Mar 04 21:46:31 plex-media-server Ombi[277275]:    at Ombi.Program.Main(String[] args)
Mar 04 21:46:31 plex-media-server Ombi[277275]:    at Ombi.Program.<Main>(String[] args)
Mar 04 21:46:31 plex-media-server systemd[1]: ombi.service: Main process exited, code=dumped, status=6/ABRT
Mar 04 21:46:31 plex-media-server systemd[1]: ombi.service: Failed with result 'core-dump'.
```

**To Reproduce**
1. Install previous version of Ombi 4.0
2. Ombi was working for past 7-8 days
3. Upgrade to version 4.0.1142 via Ubuntu Apt Repository
4. See error from journalctl, Ombi will no longer start.

**Expected behavior**
An upgrade does not produce the above.

**Logs (Logs directory where Ombi is located)**
```
2021-03-04 21:48:39.736 -06:00 [Information] Default Quartz.NET properties loaded from embedded resource file
2021-03-04 21:48:39.765 -06:00 [Debug] TaskSchedulingThreadPool configured with max concurrency of 10 and TaskScheduler ThreadPoolTaskScheduler.
2021-03-04 21:48:39.768 -06:00 [Information] Initialized Scheduler Signaller of type: Quartz.Core.SchedulerSignalerImpl
2021-03-04 21:48:39.769 -06:00 [Information] Quartz Scheduler v."3.1.0.0" created.
2021-03-04 21:48:39.769 -06:00 [Information] RAMJobStore initialized.
2021-03-04 21:48:39.771 -06:00 [Information] Scheduler meta-data: Quartz Scheduler (v3.1.0.0) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'Quartz.Core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'Quartz.Simpl.DefaultThreadPool' - with 10 threads.
  Using job-store 'Quartz.Simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2021-03-04 21:48:39.771 -06:00 [Information] Quartz scheduler 'DefaultQuartzScheduler' initialized
2021-03-04 21:48:39.771 -06:00 [Information] Quartz scheduler version: 3.1.0.0
2021-03-04 21:48:39.771 -06:00 [Information] JobFactory set to: Ombi.Schedule.IoCJobFactory
2021-03-04 21:48:39.807 -06:00 [Information] Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2021-03-04 21:48:39.809 -06:00 [Debug] Batch acquisition of 0 triggers
```

**Desktop (please complete the following information):**
`Linux plex-media-server 5.8.0-44-generic #50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Ombi Version (please complete the following information):**
 - Version 4.0.1142
- Media Server Plex
- Database Type: SQLite

**Additional context**

There are a few older issues with the same error message, but none of them mentioned how it was fixed or what caused the issue. One person said they purged the whole installation, but I really want to avoid doing that.

**Comment by tidusjar** [comment]
Are you passing in a base URL?

**Comment by phillycheeze** [comment]
Nope, not configuring the base url. I was using the existing systemd file that comes with Ombi by default and doing an override of it with an additional --host property (via `systemctl override` in Ubuntu) That's the part in the log output above where it says it's running on `http://*:5000` instead of the usual localhost. I didn't touch the baseurl parameter there.

Thinking it was initially the override, I removed the new systemd config file and instead fell back to the existing one. I even tried to start directly via the command line in the /opt/Ombi folder. Everything I tried results in the error above, so I'm thinking it's something stored in the database itself that is now causing it to crash.

**Comment by phillycheeze** [comment]
Unless there is another way to go about it, it seems like an override systemd config (with a host parameter in ExecStart) as well as running updates through the apt repository are incompatible. I tried purging and doing it again and was able to re-create the issue.

Unfortunately I gave up and moved to another tool, so feel free to close the issue. More than happy to share more information if needed though.

**Comment by piraxis** [comment]
I ran into this issue today while updating from build 4.0.721 to 4.0.1403. This is what I was running before:
`./Ombi --host http://127.0.0.1:5000 --baseurl https://my.super.secret.domain --storage /opt/Ombi` and I had the Base Url setting under general configuration empty. After the upgrade, I was getting the previously mentioned error. After playing around with the Debug settings, I saw that the last call was to OmbiSettings db so I decided to mess with the settings. I loaded up the old version again, and set the Base URL to `/`, and tried the new version again. It was still failing to load, so I dropped the baseurl flag and it started working. So my current systems exec looks like: `/opt/Ombi/Ombi --host http://127.0.0.1:5000 --storage /opt/Ombi`

Not sure if that helps with debugging, but that's what I did to fix the problem in my env.

**Comment by twanariens** [comment]
@piraxis Your base url is incorrect. You seem to be entering your application url into your base url, meaning it will fail (because a base url starts with a /). The base url is only needed when a reverse proxy is used WITH a configured location for Ombi. Meaning that if you configured a Reverse Proxy to listen to /ombi (https://my.super.secret.domain/ombi) your baseurl would need to be set to /ombi.

It Ombi should be available when you navigate to https://my.super.secret.domain/ you must leave your base url blank.

**Comment by Altycoder** [comment]
I've just run into this problem but I have my nginx reverse proxy and cloudflare ddns configured with subdomains (e.g. https://ombi.domain.com) not https://domain.com/ombi

So if I set the base url to https://ombi.domain.com or ombi.domain.com I run into this error as the first character isn't a forward slash.

How do I configure the base url for ombi with an "ombi.domain.com" type subdomain?

(I have plex, syncthing and various other services set up and working this way).

**Comment by tidusjar** [comment]
Base URL is only for the following example:

Https://domain.com/ombi

Your base URL would be /ombi

For subdomains, don't use a base URL
