### ISSUE TITLE
Error when requesting: UNIQUE constraint failed: ChildRequests.Id

### ISSUE THREAD

**Issue by JeremyKennedy** [Ombi-app/Ombi#4086]
**Describe the bug**
When requesting a TV Show (in my case, "Everything's Gonna Be Okay" with year 2020 and ID 364109), there is an error in the browser console and nothing happens. Oddly I then tried with Prison Break and had no issue, so it may be specific to this show.

**To Reproduce**
1. Log in to Ombi
2. Search for the show "Everything's Gonna Be Okay" 
3. Click "Request" (or "Request on Behalf Of" and select a user)
4. Click "All Seasons" (or check some seasons and click "Request")
5. Note no change in UI, error appears in console

**Expected behavior**
Expected the request to go through.

**Screenshots**
Not helpful.

**Logs (Logs directory where Ombi is located)**
Browser: https://pastebin.com/uXZZsAyh
Server: https://pastebin.com/7QWX2cuU

**Desktop (please complete the following information):**
Using up-to-date stable Firefox or Chrome on Ubuntu. Initially reported by one of my users, who I think is using Safari on a Mac.

**Ombi Version (please complete the following information):**
- Version: 4.0.991.0
- Media Server: Plex
- Database Type: SQLite

**Additional context**
Restarting Ombi (by recreating the Docker container) had no effect.

**Comment by tidusjar** [comment]
Please upgrade to latest version and try again

**Comment by twanariens** [comment]
Since we haven't heard back in a while, we assume the issue is fixed with the latest version. If not, let us know!
