### ISSUE TITLE
TV Posters Missing When Requesting New Show

### ISSUE THREAD

**Issue by dbowles1975** [Ombi-app/Ombi#4088]
**Describe the bug**
Missing TV posters on Discover - TV page. 

**To Reproduce**
1. Go to 'Discover'
2. Click on 'TV'

**Expected behavior**
Posters for shows should display as they do on the movies page.

**Screenshots**
![ombi](https://user-images.githubusercontent.com/14967573/110190328-b78c9980-7df0-11eb-98b5-f3ef9c154b19.PNG)

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Windows 10 Professional 64-bit
 
**Ombi Version (please complete the following information):**
 - Version 4.0.450.0
- Media Server - Plex
- Database Type: SQLite (Please change if using MySQL)

**Additional context**

**Comment by tidusjar** [comment]
Update, you are 1000 builds behind

**Comment by dbowles1975** [comment]
![Capture](https://user-images.githubusercontent.com/14967573/110206188-3feb5880-7e4a-11eb-8426-f09a687006f5.PNG)

**Comment by tidusjar** [comment]
Please update manually. See the releases for the latest build
