### ISSUE TITLE
Newsletter not working for movies

### ISSUE THREAD

**Issue by drikqlis** [Ombi-app/Ombi#4094]
**Describe the bug**
Newsletter is not sending info about added new movies. Test newsletter sends only info about TV (didn't tested music).

**To Reproduce**
1. Go to Newsletter settings, make sure both TV and movies is turned on.
2. Send test newsletter (last 10 movies/tv shows).
3. Only TV is shown / no movies.

**Expected behavior**
Should send both TV and movies when turned on in settings.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS

**Ombi Version (please complete the following information):**
 - Version: 4.0.1142.0 
- Media Server: Jellyfin
- Database Type: SQLite (Please change if using MySQL)

**Additional context**
Ombi detects movies as available from Jellyfin.

**Comment by tidusjar** [comment]
Need some logs

**Comment by drikqlis** [comment]
Full log, performed operations: 
- clear data and resync for Jellyfin
- manually run cacher for jellyfin
- test newsletter
- trigger newsletter
- update database for newsletter
[log.txt](https://github.com/Ombi-app/Ombi/files/6311318/log.txt)

Still only TV.

**Comment by bigworm** [comment]
Also seeing this behavior..
