### ISSUE TITLE
V4 - Can't approve TV show where status is "In Development"

### ISSUE THREAD

**Issue by pooley182** [Ombi-app/Ombi#4100]
**Describe the bug**
I can't approve requests for TV Shows, if the status of that show is listed as 'In Development', even though it has episodes that are due to air this month.

**To Reproduce**
As a user without the 'AutoApproveTV' permission, request a series that is in development
(current examples I'm seeing issues with are; Loki, The Falcon and The Winter Soldier, Foundation)
As an admin user navigate to Requests > TV Shows. Press the 'Options' button next to the TV Show and the only option in the pop-up is 'Delete Request'

**Expected behavior**
I should be given the usual options to Approve, or Delete the request

**Ombi Version (please complete the following information):**
 - Version 4.0.1116.0
- Media Server Plex
- Database Type: SQLite

**Comment by tidusjar** [comment]
Is this still the case with the latest version of ombi? As we have now changed data providers

**Comment by pooley182** [comment]
I tried to update to check but I seem to have now run into a problem that's preventing me from testing.

I initially lost my additional params for `host` and `baseurl` that are passed to ombi in `/etc/systemd/system/multi-user.target.wants/ombi.service` I restored those but now after starting I get to the login page and after the plex login pop-up and I'm left with a forever spinning login button.

There's a consistent error popping up in the console with a 401 error from `https://my-domain/baseurl/api/v1/token/1885421049`
With the contents
```
{"type":"https://tools.ietf.org/html/rfc7235#section-3.1","title":"Unauthorized","status":401,"traceId":"0HM7KDE7LKME2:00000006"}
```

Any advice on what the cause may be?

**Comment by pooley182** [comment]
Yes, it does appear after updating that I am now able to approve requests even if their data is missing/incomplete.

I just managed to approve a request for the TV series 'Foundation', even though it still had the following series info

\# | Title | AirDate | Status
-- | -- | -- | --
1 | TBA | 01/01/0001 | Processing Request
