### ISSUE TITLE
User (import from Jellyfin) with email set can't login with username

### ISSUE THREAD

**Issue by Plinz** [Ombi-app/Ombi#4102]
**Describe the bug**
I recently set email on a user account. This user was imported from Jellyfin.
After I set the email the user was not able anymore to login with his username but only with the email.

**To Reproduce**
1. Import a user from Jellyfin
2. Set the email of the user from a admin account
4. Try to connect with username

**Expected behavior**
The user should be able to connect with username.
I think Admin should have the possibility to force the authentication with email/username/both from Parameters/Configuration/Authentication

**Desktop (please complete the following information):**
 - OS: Windows

**Ombi Version (please complete the following information):**
 - Version 4.0.1222.0 
- Media Server Jellyfin
- Database Type: SQLite

**Comment by tidusjar** [comment]
So with Jellyfin accounts, we authenticate against the Jellyfin API, so you need to use whatever username/email combination you use to login to jellyfin.
