### ISSUE TITLE
Can't scroll to the right in the User Management page in Chrome on mobile

### ISSUE THREAD

**Issue by tj1816** [Ombi-app/Ombi#4103]
**Describe the bug**
I am not able to scroll to the right in the User Management page

**To Reproduce**
I navigate to the User Management page from the menu on the left

**Expected behavior**
I expect to be able to scroll to the right and edit users.

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/15915222/111199393-f19b2f80-8596-11eb-9af0-ed05e1afefb7.png)

**Desktop:**
 - OS: Windows 10
 - Mobile OS: Android 11 (Pixel 3XL)
 - Chrome Version 89.0.4389.86

**Ombi Version:**
 - Version 4.0.1222.0
- Media Server Plex
- Database Type: SQLite

**Comment by pravardhanreddy** [comment]
I have the same issue. In fact, even on my laptop which has a 4:3 screen, the user management page is not usable coz of the lack of horizontal scrolling.

**Comment by BobVanceReef** [comment]
I also have this exact same issue. Does not work on Safari or Chrome on my iPhone or MacBook. I have full functionality on Chrome on my PC that is hosting Ombi
