### ISSUE TITLE
[V4] Show can not be requested if the External Id for TVDB is not set in the TMDB's page for the show

### ISSUE THREAD

**Issue by cyberden** [Ombi-app/Ombi#4106]
**Describe the bug**
When there the external "TVDB Id" is not set in the TMDB show page, the method GetTvDbId returns 0 and then the GetShowInformation method returns null and the page is not refreshed

**To Reproduce**
1 - Go to "Discover"
2 - search the show "Ovni(s)"
3 - The show is found (1 tile is displayed) but the information can't be retrieved and the tile keeps "loading forever"

**Expected behavior**
Maybe a fallback should be implemented to retrieve the show information from TMDB or using TVDB api.

**Screenshots**
![image](https://user-images.githubusercontent.com/7973581/111341108-7f4f4b80-8679-11eb-87b7-ade3de89f027.png)

**Logs (Logs directory where Ombi is located)**
No log but I debugged the code and what happens is clear, the GetTvDbId method returns 0.

**Desktop (please complete the following information):**
All (including the demo instance)

**Ombi Version (please complete the following information):**
 - Version 4.0.1222.0
- Media Server Plex
- Database Type: SQLite (Please change if using MySQL)

**Additional context**
The issue is with the source data but it shouldn't keep the tile loading forever and a fallback might be doable.

**Comment by tidusjar** [comment]
As discussed, this will be resolved with the next update!
