### ISSUE TITLE
UI issue

### ISSUE THREAD

**Issue by ctml91** [Ombi-app/Ombi#4109]
**Describe the bug**
![image](https://user-images.githubusercontent.com/74685281/111892978-0d0e9c00-89d6-11eb-80b3-ecfdfa2cb8c5.png)
![image](https://user-images.githubusercontent.com/74685281/111892997-29123d80-89d6-11eb-8dd9-9412c83554b6.png)

**To Reproduce**
1. Ombi was presenting a blank screen when launching it out of a sudden 
2. Restarted docker container, issue continued
3. Left and came back next day, UI loaded and was able to login but then started seeing these UI issues

**Desktop (please complete the following information):**
 - OS: CentOS

**Ombi Version (please complete the following information):**
- Version: 
4.0.1255.0
- Media Server: Plex
- Database Type: SQLite

**Comment by dualznz** [comment]
I too am seeing this issue on the latest build so confirmed

**Comment by tidusjar** [comment]
Fixed in 1257
