### ISSUE TITLE
Poster image has malformed link in notification emails

### ISSUE THREAD

**Issue by Pyronious** [Ombi-app/Ombi#4115]
**Describe the bug**
When a user requests a TV show, an email notification is dispatched with a malformed link to the image URL, resulting in a broken image link.

The HTML image link reads:

> img src="/pGFGd6UdCShPrcUO75xSdaC8cko.jpg" alt="Poster" width="400px" text-align="center"

**To Reproduce**
1. Enable email request notifications
2. Request a TV show
3. Examine source of resulting email notification

**Expected behavior**
The poster image in the email should render correctly.

The HTML image link should read:

> img src="https://image.tmdb.org/t/p/original/pGFGd6UdCShPrcUO75xSdaC8cko.jpg" alt="Poster" width="400px" text-align="center"

**Screenshots**
![2021-03-27_14-03-28](https://user-images.githubusercontent.com/1350786/112734883-b2a99a00-8f05-11eb-96d1-9d5631a83630.jpg)

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Ombi Version (please complete the following information):**
 - Version 4.0.1275.0
- Media Server Plex
- Database Type: SQLite

**Comment by tidusjar** [comment]
Fixed in latest version
