### ISSUE TITLE
Anonymous data collection setting not respected

### ISSUE THREAD

**Issue by vkojchevski** [Ombi-app/Ombi#4117]
**Describe the bug**
The setting "Allow us to collect anonymous analytical data e.g. browser used" under Configuration>General is not respected after docker container restart. Reverts to being on after restart even if turned off.

**To Reproduce**
1. Go to Configuration>General>"Allow us to collect anonymous analytical data e.g. browser used"
2. Click on the checkbox to turn off the setting
3. Restart the docker container
4. Setting is turned on back again

**Expected behavior**
Setting should be saved and respected after container restart

**Screenshots**
![image](https://user-images.githubusercontent.com/36865125/112748522-68cfbb00-8fbc-11eb-95b4-6d2fe4bb38e8.png)

**Logs (Logs directory where Ombi is located)**
N/A

**Desktop (please complete the following information):**
 - OS: Unraid 6.8.3
 - linuxserver Ombi docker container

**Ombi Version (please complete the following information):**
 - Version 4.0.991.0
- Database Type: SQLite

**Additional context**
Seems that only that setting isn't kept in a permanent storage or it's a visual bug. I am not sure if this issue should be posted on Linuxservers docker container page or here, but I figured I'd start somewhere.

**Comment by tidusjar** [comment]
It's been fixed in a later version. Upgrade to latest
