### ISSUE TITLE
Android ombi beta app not working

### ISSUE THREAD

**Issue by csihama** [Ombi-app/Ombi#4125]
Hello

**Describe the bug**
After recently ombi v4 server update (last week), the android beta ombi app not working.

**To Reproduce**
1. Recently ombi version install
2. Open Ombi beta android app
3. Error Code: 200
Message: Http failure during parsing for https://my-website.hu(also tried with local lan ip)/api/v2/search/Tv/popular/10/10/images

**Expected behavior**

**Screenshots**
![1024-2276](https://user-images.githubusercontent.com/76595053/113048476-ddfce500-91a2-11eb-85c5-2a3844ff0b0d.png)

**Logs (Logs directory where Ombi is located)**
No errors in ombi server log

**Desktop (please complete the following information):**
 - OS: Android

**Ombi Version (please complete the following information):**
 - Version 4.0.1290.0
- Media Server Plex
- Database SQLite 

**Additional context**
With normal ombi android app (not the beta), no error happen. Works great.
From web browser no problem.

I think the problem is in the JSON code.

**Comment by tidusjar** [comment]
A fix has been pushed to the store. You should get the update soon

**Comment by csihama** [comment]
Hello,

The app store updated today, the problem solved.
But a new problem occured:

When request TV show
the following error happen with the same red ribbon notification:
Error Code: 500
Message: Http failure response for http://my-site.hu/api/v1/request/TV/: 500 Internal Server Error

If need I could create a new issue for this.

Thanks,
Good day

**Comment by tidusjar** [comment]
Yeah ok. Would need to see you logs for this too!
