### ISSUE TITLE
User Management - Quality & Root Path Preferences Blank

### ISSUE THREAD

**Issue by andrew-bengier** [Ombi-app/Ombi#4127]
**Describe the bug**
The "Quality & Root Path Prefernces" is blank when attempting to to make changes for a local user. This is causing the request to be forwarded using the 'any' quality profile in both Sonarr and Radarr

**To Reproduce**
Inside User Management
- When editing a local user
- The component called 'Quality & Root Path Preferences' is empty

**Expected behavior**
Drop down should not be empty.

**Screenshots**
![error](https://user-images.githubusercontent.com/13891981/113089065-e231fe00-91b4-11eb-9a3e-f115b752a9ba.PNG)

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - Currently have ombi running via docker compose file using:
  ombi:
  container_name: ombi
  image: linuxserver/ombi:latest
  restart: unless-stopped
  ports:
  - "1272:3579"
  volumes:
  - C:/server/AppData/Ombi:/config
  - C:/server/AppData/Shared:/share
  environment:
  - PUID=******
  - PGID=******
  - TZ=America/New_York

**Ombi Version (please complete the following information):**
 - Version 3.0.5223 (master)
- Media Server Plex
- Database Type: SQLite (default)

**Additional context**

**Comment by tidusjar** [comment]
I can only assume it's empty because you have not enabled radarr or sonarr. Also you might want to think about updating to v4
