### ISSUE TITLE
Error From Plex: Authentication did not work. Please try again

### ISSUE THREAD

**Issue by WeirDave** [Ombi-app/Ombi#4134]
**Describe the bug**
Despite being able to connect to Plex.tv to grab my server list it generates the following error non-stop as a popup at the bottom of the screen "Error From Plex: Authentication did not work. Please try again"

**To Reproduce**
1. Login to Ombi at localhost:5656
2. Click on '....' If I click on any other settings and come back to "Plex Configuration" the Plex Credentials fields are blank

**Expected behavior**

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 service running with nmms

**Ombi Version (please complete the following information):**
 - Version [e.g. 4.0.958] 4.0.1299.0 
- Media Server [e.g. Plex] Plex
- Database Type: SQLite (Please change if using MySQL)

**Additional context**

**Comment by tidusjar** [comment]
Are you using 2fa with your Plex account?

**Comment by WeirDave** [comment]
No sir. I stopped the service and restarted and now the error message went away but the Plex credentials field still remains blank

**Comment by tidusjar** [comment]
I misunderstood your issue.

> Plex Credentials fields are blank

That is correct, we do not store the Plex Credentials, we only can use them there to help auto populate your server information.
