### ISSUE TITLE
Test message for Telegram notifications not working

### ISSUE THREAD

**Issue by mdangers-DE** [Ombi-app/Ombi#4137]
**Describe the bug**
After setting up the bot token and chat id, trying to send a test message to the channel
is not working even though success is reported in the web ui. In the log, a Bad Request
can be observed. Following the link to the Telegram API address yields a 
"Bad Request: message text is empty"

**To Reproduce**
1. Go to Settings/Telegram
2. Perform basic setup and hit the Test button
3. See success message
4. Observe no new message appearing in the channel and an error in the log file

**Expected behavior**
A test message should appear in the Telegram channel.

**Logs (Logs directory where Ombi is located)**
2021-04-04 10:42:38.276 +02:00 [Error] StatusCode: BadRequest, Reason: Bad Request, RequestUri: https://api.telegram.org/bot1678778818:AAFnVFn0bAslYfCe769gXW-46mBk9dGQLJs/sendMessage

**Desktop (please complete the following information):**
 - OS: Client Windows 10, Firefox 87.0
 - Server: Ombi Docker on unRAID Server

**Ombi Version (please complete the following information):**
 - Version 3.0.5223
- Media Server Emby
- Database Type: SQLite

**Comment by crakila** [comment]
I'm experiencing this bug in `4.0.1394` with the same error as the OP. 
Tested with Discord transport and it works fine. 

**Desktop** 

* OS: Windows 10 Build 19042.985, Vivaldi 3.8.2259.40 
* Server: Ombi Docker on Plesk 18.0.35 Update 1 on Debian 9.13

**Ombi version**

Version: `4.0.1394`
Media Server: Plex
Database Type: SQLite

**Comment by twanariens** [comment]
Should be fixed in the latest release V4.15.2
