### ISSUE TITLE
Ombi Version not showing the correct version after the last release.

### ISSUE THREAD

**Issue by jmackxiii** [Ombi-app/Ombi#4146]
**Describe the bug**
Issue is after upgrading to the latest build (4.0.1332) the web app and android app still show 4.0.1328 and that there is an update . 

**To Reproduce**
I reran the recent update process (unzip the win10x64 and copying over my files then restoring the required files to preserve my settings). I have Ombi running as a Windows Service and I have a script that performs the update process and every update has correctly reflected in the web/app except for this recent release. 

**Expected behavior**
The correct version should be reflected on the web app and android app. 

**Screenshots**
![image](https://user-images.githubusercontent.com/34356542/114181656-c692ca00-990f-11eb-8c3a-d823d6ad8ad1.png)

**Logs (Logs directory where Ombi is located)**
Scanned the logs, I did not see anything that jumped out.. but here is the recent log file
[log-20210409.txt](https://github.com/Ombi-app/Ombi/files/6285801/log-20210409.txt)

**Desktop (please complete the following information):**
Ombi is running on Windows 10x64, also Ombi android app is running on a Pixel 4 with the latest security patch. 

**Ombi Version (please complete the following information):**
 - Version 4.0.1332
- Media Server Latest Plex, Sonarr and Radarr releases
- Database Type: SQLite

**Comment by tidusjar** [comment]
Already fixed this in the latest version

**Comment by jmackxiii** [comment]
A newer version than what is out there right now? I am running the latest release out there now v4.0.1332

**Comment by taylorcox75** [comment]
#4140 Fixed it, but hasn't been built yet

**Comment by jmackxiii** [comment]
Awesome. Thank you for clarifying. Will look forward to the update!
