### ISSUE TITLE
v4 Newsletter sends TV even though TV is turned off in the newsletter settings

### ISSUE THREAD

**Issue by diedrichg** [Ombi-app/Ombi#4148]
**Describe the bug**
In the newsletter settings I have TV shows turned off and yet I keep getting shows in the newsletter email. I've toggled, saved, toggled and TV still comes populated in the email.

**To Reproduce**
1. Go to 'Settings>Notifications>Newsletter'
2. Click on 'Disable TV' to make it active and then click 'submit'
3. Wait for next newsletter
4. Newsletter contains both movies and TV even though TV was turned off. 

**Expected behavior**
TV should not be included in the newsletter since it was disabled in the settings

**Screenshots**
![2021-04-12 18_50_49-Ombi — Mozilla Firefox](https://user-images.githubusercontent.com/9559987/114472478-45ae2980-9bc0-11eb-8edf-d6bfdf2fe2ed.png)

![Screenshot_2021-04-12 Emby Recently Added Movies - diedrichguenther gmail com - Gmail](https://user-images.githubusercontent.com/9559987/114471238-41810c80-9bbe-11eb-92cb-13b14d45a90d.png)

**Logs (Logs directory where Ombi is located)**
[logs.txt](https://github.com/Ombi-app/Ombi/files/6300203/logs.txt)

**Desktop (please complete the following information):**
 - OS: Ubuntu docker, linuxserver/ombi:development

**Ombi Version (please complete the following information):**
 - Version 4.0.1328
- Media Server Emby 4.5.4.0
- Database Type: SQLite

**Additional context**
NA

**Comment by tidusjar** [comment]
This still happening? I can't seem to recreate

**Comment by twanariens** [comment]
Closed due to inactivity
