### ISSUE TITLE
v4 Sends"Your request has been approved" emails when "Do not send Notification if a user has the Auto Approve permission" for TV shows

### ISSUE THREAD

**Issue by jasonlyle88** [Ombi-app/Ombi#4152]
**Describe the bug**
v4 Sends"Your request has been approved" emails when "Do not send Notification if a user has the Auto Approve permission" for TV shows when admin is requesting for another user

**To Reproduce**

1. Log in as admin
2. Make sure "Do not send Notification if a user has the Auto Approve permission" is turned on in settings
3. "Auto Approve Tv" can be on or of for admin (doesn't change anything)
4. Request a Tv show on behalf of another user.
5. Wait for "Your request has been approved" email to come through

**Expected behavior**
No email should be sent.

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Ombi Version (please complete the following information):**
 - Version: 4.0.1338
- Media Server: Plex
- Database Type: SQLite

**Comment by tidusjar** [comment]
This is because the whole request goes through as that other user 😢 Nice spot
