### ISSUE TITLE
Media images not loading correctly

### ISSUE THREAD

**Issue by Lucane** [Ombi-app/Ombi#4157]
**Describe the bug**
- I updated from v4.0.975 to v4.0.1340 and now some posters/thumbnails fail to load.
The logs aren't showing much: mainly information and some unrelated debug entries.
Any ideas what might be causing this?

**Desktop**
 - OS: Windows 10

**Ombi Version**
- Version v4.0.1340 (running as a service)
- Media Server: Plex v1.22.3.4392

**Screenshots**
- Pictures before and after the update:

![4 0 975 0](https://user-images.githubusercontent.com/7999446/115955663-972fb000-a500-11eb-858d-0f472bccea53.png)

![Screenshot 2021-04-24 134746](https://user-images.githubusercontent.com/7999446/115956137-cbf13680-a503-11eb-8dc4-ed79451a66c9.png)

![4 0 1340](https://user-images.githubusercontent.com/7999446/115955666-99920a00-a500-11eb-912e-d93de6ff5c56.png)

![Screenshot 2021-04-24 134807](https://user-images.githubusercontent.com/7999446/115956140-cf84bd80-a503-11eb-91fd-ab5115e027bd.png)

**Comment by tidusjar** [comment]
Clear you cache. Looks like it's cached the old version of code

**Comment by Lucane** [comment]
> Clear you cache. Looks like it's cached the old version of code

That actually worked, thank you! I cleared Ombi's cookies and thought I did a page cache refresh with Ctrl-F5, but clearing all the cache helped.
