### ISSUE TITLE
Scan QR Code then Freeze

### ISSUE THREAD

**Issue by WeirDave** [Ombi-app/Ombi#4160]
**Describe the bug**
I downloaded the new mobile app from the google play store. Clicked on the Scan QR button. Accepted the permissions. Scanned the code which then brings me to an orange OMBI logo and that's it. Nothing else.

**To Reproduce**
1. Go to playstore, downloaded APP
2. Click on Scan QR button
3. Accepted the permissions
4. Frozen Logo after scan

**Expected behavior**
I assume it will log me into my server or at least take me to the correct login screen

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Android

**Ombi Version (please complete the following information):**
 - Version [e.g. 4.0.958] 4.0.1342
- Media Server [e.g. Plex] Plex
- Database Type: SQLite (Please change if using MySQL)

**Additional context**
I will try again using the manual method after uninstalling

**Comment by tidusjar** [comment]
Hi! Is your application URL correct? Can you give me an example of the exact format you are using?

**Comment by WeirDave** [comment]
http://weirdave.myqnapcloud.com:5656/landingpage

**Comment by tidusjar** [comment]
So your application url should not be `/landingpage` so please remove that and the QR code should then work

**Comment by WeirDave** [comment]
That did work Thanks Jamie

**Comment by tidusjar** [comment]
You are welcome!
