### ISSUE TITLE
Cannot enable mobile QR code as user type PlexUser, and cannot log in at all using manually-set Ombi password.

### ISSUE THREAD

**Issue by PaarthShah** [Ombi-app/Ombi#4163]
**Describe the bug**
When going into my profile to view the v4 QR code, it simply shows `Please contact your administrator to enable QR codes`

**To Reproduce**
1. Log in with Plex.
2. Click on username -> Mobile
3. See message, and no QR code.

Manually setting a password for my (admin) account in user management does not allow me to log into Ombi in either the web interface or the v4 mobile app (it returns a 401 in the web interface).

**Expected behavior**
Being able to view the QR code/log in using a simple username/password combo on mobile.

**Screenshots**
![image](https://user-images.githubusercontent.com/20485810/116310647-23d7a980-a75f-11eb-937a-0e8f925d1671.png)

**Desktop (please complete the following information):**
 - OS: Android, Windows 10 (Firefox)

**Ombi Version (please complete the following information):**
 - Version: 4.0.1344 (via docker: `linuxserver/ombi:development`)
- Media Server: Plex
- Database Type: SQLite

**Comment by tidusjar** [comment]
You need to enter your Application URL in the Customization Settings. This should be your externally accessible URL.

E.g. the demo site is running on `https://app.ombi.io/` so that is my Application URL

**Comment by PaarthShah** [comment]
Thank you, that worked! Though I'd generally provide feedback that this wasn't a documented/obvious requirement

**Comment by tidusjar** [comment]
Yeah I'll improve the message! It's not clear you are right
