### ISSUE TITLE
Update notices shown for the wrong branch (showing dev releases on stable)

### ISSUE THREAD

**Issue by aptalca** [Ombi-app/Ombi#4165]
**Describe the bug**
Version in the gui is shown correctly, however, development releases are listed as available updates when the stable version is installed.

**To Reproduce**
1. Set up the linuxserver.io docker container with the `latest` tag
2. 2. Check the Version info in gui

**Expected behavior**
The app needs to detect which branch it's on and display the correct version update info.

**Screenshots**
N/A

**Logs (Logs directory where Ombi is located)**
N/A

**Desktop (please complete the following information):**
 - OS: Unraid with linuxserver.io docker image

**Ombi Version (please complete the following information):**
 - Version: 4.0.1342
- Media Server N/A
- Database Type: SQLite

**Additional context**
For sonarr/radarr, etc. we (linuxserver.io) add a `package_info` file where put various build info into it. The apps then parse that info to detect docker install, version, branch, etc. and take necessary steps (such disabling gui updates if docker image, etc.)
If that would help, we would be happy to do that for ombi docker images as well.
See here for the injection code: https://github.com/linuxserver/docker-sonarr/blob/master/Dockerfile#L32

**Comment by tidusjar** [comment]
Very good point, I forgot about this, Just had a look at that package_info file you create for Sonarr, I think that's a really good idea! 

Yeah would be useful if you could do that for docker!

**Comment by twanariens** [comment]
This has been fixed in the latest release V4.15.2
