### ISSUE TITLE
Background and poster doesn't load

### ISSUE THREAD

**Issue by XenooMorfik** [Ombi-app/Ombi#4166]
Background and poster doesn't load on tv shows when we change personal language.

**To Reproduce**
1. Go to 'profie settings' and change language from english to polski
2. Click on 'discover page' and choose TV tab on right side
3. Click on some 'TV Show' 

**Expected behavior**
User should see background and poster image from selected tv show

**Screenshots**
![poster](https://user-images.githubusercontent.com/81835041/116553183-23bfe100-a8fa-11eb-9e19-aeb540f8d358.png)

**Desktop:**
 -  browser Chrome 90.0.4430.93
 -  system Windows 10 Pro 19041.928

**Ombi Version:**
- Version v4.0.1345
- Media Server Linux 4.14.24-qnap

**Comment by tidusjar** [comment]
This is because when querying the data provider with the supplied language, they do not have any regional assets for that media. I think as an enhancement I could fall back to EN if that is the case.

**Comment by XenooMorfik** [comment]
But Movies work well on TV Shows is problem only
