### ISSUE TITLE
Linux apt repository not updated

### ISSUE THREAD

**Issue by csihama** [Ombi-app/Ombi#4172]
**Describe the bug**
echo "deb https://apt.ombi.app/develop jessie main" | sudo tee /etc/apt/sources.list.d/ombi.list
curl -sSL https://apt.ombi.app/pub.key | sudo apt-key add -
sudo apt update

sudo apt install ombi
Reading package lists... Done
Building dependency tree
Reading state information... Done
ombi is already the newest version (4.0.1338).

I think something broken or not updated since that update (4.0.1338).
I tried reinstall ombi, update the repository list, but nothing help.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 (64 bit)

**Ombi Version (please complete the following information):**
 - Version: 4.0.1347 (manual installed from package)
- Media Server Plex
- Database Type: SQLite

**Additional context**

**Comment by tidusjar** [comment]
We are currently working on moving out deb repo over to another service as we are currently running out of space!

**Comment by psi5asp** [comment]
has this been resolved? I installed as per docs, and got v4.0.1338  but the "About" said upgrade available  (v4.0.1448).

A few hours later, I re-installed as per docs and got the latest v4.0.1338.

Don't know if its perm fixed, or just a reference/caching issue.

**Comment by csihama** [comment]
Hello,

I think it's working, only not all update uploaded in the repository, or not immediately.

Mark

**Comment by twanariens** [comment]
This will be continued in #4505
