### ISSUE TITLE
Last login date in User Management shown in GMT

### ISSUE THREAD

**Issue by douginoz** [Ombi-app/Ombi#4173]
**Describe the bug**
Ombi v4 seems to display the incorrect last login time - possibly showing GMT

**To Reproduce**
1. Create a new user 'testblah'
2. Edit the user to have an email address.  Change Streaming Country to your own. (probably not important)
3. Roles: Auto Approve music, TV, Movies, manage own requests, request everything
4. Save and start up an incognito web session
5. Log in as that new user
6. Check the Ombi User Management page.  The Last Logged In date isn't showing the local date/time. For me it was showing "5/6/2021 1:09 PM" when it's actually Thu May  6 06:09:00 PDT 2021.  I think it's 1pm in the UK (Zulu/GMT).  My local PC and the server that Ombi is on are both ubuntu 20.04 and $ date displays the correct local time (Thu May  6 06:11:00 PDT 2021).

**Expected behavior**
Either show the local server time (which makes sense because the administrator wants to know when the user last logged onto the server), or show the user's local time and indicate that.

**Desktop (please complete the following information):**
 - ubuntu 20.04 on both the desktop and the server

**Ombi Version (please complete the following information):**
 - Ombi Version 4.0.1347 or 1438 (unsure; installing https://github.com/Ombi-app/Ombi/releases/download/v4.0.1348/linux-x64.tar.gz still shows as version 4.0.1347 with an update to 1348 available)
- Database Type: SQLite

**Other info
I thought it might be that incognito mode somehow confuses the actual local time/date but if I google "what time is it" in an incognito session it shows the correct local time.  So that's unlikely.

**Comment by twanariens** [comment]
This issue will be continued in #2925
