### ISSUE TITLE
Requests / TV Request tab does not offer 'Deny' option

### ISSUE THREAD

**Issue by blurb2m** [Ombi-app/Ombi#4175]
**Describe the bug**
There is no option for 'Deny Request' under TV Shows / All Requests

**To Reproduce**
1. Go to 'Sidebar Menu / TV Shows / All Requests'
2. When looking at a TV Show request
3. Click on 'red Options button'
4. The pop-up only has two options 'Delete Request' and 'Approve Request'
5. Observe there is no option to Deny Request.

**Expected behavior**

**Screenshots**
![ombi_deny](https://user-images.githubusercontent.com/18505632/117397795-e98eaa80-aeca-11eb-9527-0d434155bf35.png)

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Docker

**Ombi Version (please complete the following information):**
 - Version 4.0.1349
- Media Server Plex
- Database Type: SQLite 

**Additional context**

**Comment by tidusjar** [comment]
To deny the request, you need to go to the details page and do it in the accordion at the bottom.
