### ISSUE TITLE
Issue with CRON and Newletter

### ISSUE THREAD

**Issue by WeirDave** [Ombi-app/Ombi#4179]
**Describe the bug**
The cron does not seem to actually affect the fire time for newsletters. I changed the fire variable and it didn't impact it

**To Reproduce**
1. Go to settings > system > scheduled tasks
2. Click on newsletter and changed value
3. Hit submit

**Expected behavior**
Cron should change to scheduled time

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 64

**Ombi Version (please complete the following information):**
 - Version [e.g. 4.0.958] v4.0.1349 when the chane was made now using v4.0.1351
- Media Server [e.g. Plex] Plex
- Database Type: SQLite (Please change if using MySQL)

**Additional context**

**Comment by tidusjar** [comment]
You need to restart Ombi after changing a CRON schedule for it to work
