### ISSUE TITLE
Cannot log into mobile app on android after updating to v4

### ISSUE THREAD

**Issue by Joooop** [Ombi-app/Ombi#4182]
**Describe the bug**
After manually updating to v4 (queuing the update from v3 on the servers webpage did nothing) and copying over my previous databases, I cannot log in to my server with my admin account or any local users on the mobile app. I am able to log in via a web browser on the application URL but manual log in attempts in the app result in failed logins. QR code attempts result in the error "Incorrect Ombi Server - The QR Code is incorrect, please speak to your administrator." I have the application URL correctly set in my ombi configuration. 

**To Reproduce**
1. Open app
2. Enter login info for admin / local user
3. Enter my application url 'https://joeplex.ddns.net'
4. Attempt to log in.

**Expected behavior**
A successful log in

**Screenshots**
https://i.imgur.com/LR0RfXN.jpg

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Android
 - Server on Windows 10 64bit

**Ombi Version (please complete the following information):**
 - Version [e.g. 4.0.1351]
- Media Server: Plex
- Database Type: SQLite

**Comment by tidusjar** [comment]
That error indicates that your qr code is not correctly setup. 

Please ensure your application URL is correct, this is under customization settings

**Comment by piratman38** [comment]
Hello,

I have exactly the same issue as Joooop : Since I updated my Android App to V4, I am unable to login on it neither with my credentials, nor QR code.

And my application URL is properly setup.

Hope this is just a minor bug that will be fixed soon :-)

**Comment by tidusjar** [comment]
I've not found a bug in this area, a the issues around this have bas been that ombi has been incorrectly configured. 

You need to make sure your application URL is 100% correct as this is what the app will be using

**Comment by piratman38** [comment]
I tried again and again, and I finally found out that I had to input http:\\myombiaddress.com and not https:\\myombiaddress.com in Application URL to make the QR code working.

Problem solved for me.
Thank you for your quick reply.

**Comment by Joooop** [comment]
> 
> 
> That error indicates that your qr code is not correctly setup.
> 
> Please ensure your application URL is correct, this is under customization settings

I mentioned in the OP that I have checked and double checked that the application URL is correct. I have tried both https and http.

**Comment by tidusjar** [comment]
@Joooop Can you email (tidusjar@gmail.com) or contact me on Discord? 

Ideally I'd like to have a regular user on your server so I can attempt to log in via the app to see what's going on?
