### ISSUE TITLE
App requires reboot when you enter wrong details

### ISSUE THREAD

**Issue by rycore** [Ombi-app/Ombi#4187]
**Describe the bug**
I noticed this with my android and my sibling recently had the same experience on their IOS, but if you make a mistake when entering username, password and/or the URL, for some reason you continue to get the error shown in the screenshot, even after entering the correct data, it only seems to allow you to login after you close the app and re-open it.

**To Reproduce**
1. Open ombi app
2. Enter wrong details
3. Try to enter correct details
4. Still get error.

**Expected behavior**
Ombi app should not require a user to close the app in order to try to login again.

**Screenshot**
I used the beta to reproduce this by changing the username to beta1, then back to beta in order to provide a screenshot.

![Screenshot_20210515-024922_Ombi](https://user-images.githubusercontent.com/49836558/118344838-5982dd80-b528-11eb-913a-452456f96054.jpg)

**Ombi Version (please complete the following information):**
 - Version: latest Android and IOS versions.

**Comment by tidusjar** [comment]
This has been fixed and will be present in the next app update
