### ISSUE TITLE
Mobile Application no longer has Plex User sign in

### ISSUE THREAD

**Issue by figlizzard12** [Ombi-app/Ombi#4188]
As the title explains, the mobile application no longer has an option for Plex User sign in. My application URL doesn't seem to be working.

do i need to create username and password for all users?

**Comment by tidusjar** [comment]
No, the user can scan the QR code in their user profile on ombi and they can log in. Make sure your application URL is correct

**Comment by figlizzard12** [comment]
Application URL is exactly the same as what I use for web access and that
is working fine?

Is there anything else needed to get QR working?

If I scan the code it opens the app but doesn't populate the URL field.

**Comment by tidusjar** [comment]
Please can you email me your domain so I can take a look tidusjar@gmail.com
