### ISSUE TITLE
UI design flaw: Search results containing no poster artwork

### ISSUE THREAD

**Issue by jonnyel** [Ombi-app/Ombi#4189]
**Describe the bug**
Search results without poster artwork display no metadata info.

**To Reproduce**
1. Search for a query that yields results with no poster artwork (e.g. "Play of the Week")

Desktop UI:
2. hover the cursor over one result item that contains no poster artwork to read the title/blurb metadata

Mobile UI:
2. Drag&scroll on one result item, to reveal metadata.

**Expected behavior**
Either:
- results show all metadata along with the poster artwork (as does Sonarr search results)

or:
- only show metadata if no poster artwork exists 

**Screenshots**

![2021-05-15_13-12-41](https://user-images.githubusercontent.com/47300319/118372752-1bfe6e80-b581-11eb-9e3a-d3cc0eefb655.png)

![2021-05-15_13-12-57](https://user-images.githubusercontent.com/47300319/118372750-1b65d800-b581-11eb-969a-1526614ea6b7.png)

![IMG_2753-mobile](https://user-images.githubusercontent.com/47300319/118372825-6ed82600-b581-11eb-8454-ab3226db223f.png)

**Logs (Logs directory where Ombi is located)**
n/a

**Desktop (please complete the following information):**
 - Desktop OS: MacOS 10.15.7 / Brave
 - Mobile OS: iOS 14.5.1 / Safari

**Ombi Version (please complete the following information):**
 - Version 4.0.1358

**Comment by tidusjar** [comment]
Is this a request to basically always show the metadata when there's no artwork? If so that makes total sense

**Comment by jonnyel** [comment]
> Is this a request to basically always show the metadata when there's no artwork? If so that makes total sense

Yes that’s all :)
Thanks for the awesome work btw!
