### ISSUE TITLE
Manage own requests role not working

### ISSUE THREAD

**Issue by jjffnn** [Ombi-app/Ombi#4203]
**Describe the bug**
The user role "Manage own requests" does not appear to work.
I have tried with available, accepted, and pending requests. I have checked in both the app and on the website.
Neither place with any of the statuses get the "options" menu or a delete button.

**To Reproduce**
1. Enable "Manage own requests" on a user.
2. Log in with that user
2.  Don't see "options" or "delete" button on their own requests.

**Expected behavior**
An options menu or delete button for the user so they can delete their own requests.

**Screenshots**
Should not be needed, but can be provided.

**Logs (Logs directory where Ombi is located)**
Can be provided if you deem it is needed.

**Desktop (please complete the following information):**
Settings about sections says:
OS Architecture | X64
OS Description | Linux 4.19.123-feral # 2 SMP Mon May 18 09:01:14 BST 2020

To access it i have used the website in firefox on win10 and the android app.

**Ombi Version (please complete the following information):**
- Version 4.0.1342
- Database Type: SQLite

**Additional context**
I have looked in the docs and in the existing issues and i can't find anything about this being an issue or not being implemented yet and i'm starting to think it's me doing stuff wrong :)

**Comment by Berjou** [comment]
Hi, I can confirm this bug too. This feature worked as expected before, but today one of my user reported this bug to me. Unfortunately, multiple weeks passed since the last time he used ombi, so I'm not sure when exactly this feature was broken.

**Comment by Berjou** [comment]
Also, I'm not sure that it is related to this issue, but this same user started to get its ip ban by my fail2ban service after multiple GET requests on /api/v1/Radarr/{Profiles,RootFolders} returning a 403. The apparition of this problem seems to coincide with the "manage own request" one.

**Comment by tidusjar** [comment]
No, you are correct, i clearly missed this on the UI for the new UI rewrite. I'll get this added back
