### ISSUE TITLE
Mobile Notifications not being received

### ISSUE THREAD

**Issue by piratman38** [Ombi-app/Ombi#4205]
**Describe the bug**
When using Ombi 4.0.1394 in combination with the Android mobile app 2.2.20, Mobile notifications are not sent anymore.
Mobile notifications worked until Mobile app was updated with the new design a couple of months ago.

**To Reproduce**
1. Go to 'Ombi', Click on 'Settings', choose 'Notifications' tab, pick 'Mobile' in drop-down list
2. 'Message' field appears, with 'Send notification' disabled button. 
3. No user selection available.

**Expected behavior**
I expect to see a list of user, pick one in the list, and have 'Send notification' button enable to test the function.
(As it works in 'Legacy Mobile Notifications' menu -> I see the user list, pick one and can send a notification message test. But not notofication are received either)

**Screenshots**
![image](https://user-images.githubusercontent.com/83902713/119254504-eaa42500-bbb6-11eb-99df-abb31ae50210.png)

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Android + 4.0.1394 in docker

**Ombi Version (please complete the following information):**
 - Version 4.0.1394
- Media Server Plex

**Comment by tidusjar** [comment]
Did you enable mobile notifications in the app or deny the app to send you notifications?

**Comment by piratman38** [comment]
Ombi application has all the rights to display notification (Android settings) :
![WhatsApp Image 2021-05-24 at 11 04 04 (1)](https://user-images.githubusercontent.com/83902713/119324549-3e2e7580-bc80-11eb-8d76-f5af23b0640b.jpeg)

But, inside Ombi app, I don't see any option to "enable/disable" notifications :
![WhatsApp Image 2021-05-24 at 11 04 04](https://user-images.githubusercontent.com/83902713/119324618-54d4cc80-bc80-11eb-8d10-b74805b572d3.jpeg)

**Comment by tidusjar** [comment]
Out of curiosity, what happens if you log out and log in?

Does your user then appear on the Ombi mobile notifications page?

**Comment by piratman38** [comment]
I just logged out and in, with both Ombi, and Ombi Android App.
No change : Mobile notification doesn't show any user.

**Comment by tidusjar** [comment]
I've just pushed a mobile update, can you update and re check please?

**Comment by piratman38** [comment]
Hello, I have updated the mobile app to v2.2.22, tried again, but still same issue.

I must tell that I just noticed another thing not working anymore (not due to your last update of yesterday, it didn't work since the v2.2.20) :
From my mobile app, I do not get any content while searching. No result, whatever the keyword is.
I can see the recommended movies and TV shows, I also see the one requested or available on my server, but can't search any content. 

Here are screenshots (Before searching, and after inputing text in search field) :
![1](https://user-images.githubusercontent.com/83902713/120060202-ad2c1580-c056-11eb-84e8-2e117110ac95.jpg)
![2](https://user-images.githubusercontent.com/83902713/120060204-b1583300-c056-11eb-974b-b3f7181204b5.jpg)

**Comment by tidusjar** [comment]
Do you mind creating me an account on your ombi so I can view this on my app? Because this is odd behaviour that I cannot reproduce

**Comment by piratman38** [comment]
Credentials sent to your email address.

On my side, I installed ombi on a different more recent phone, but exact same issue.
(Phones are running under Android 9 and 10)

**Comment by tidusjar** [comment]
Found the issue, 

the domain you had set in your Application URL in the Customization Settings was a domain that was redirecting to another location. Because the QR code tells the app that the domain is what you set in the Application URL it wasn't allowing POST redirects. So basically you need to set your Application URL as the correct Ombi domain and not a redirect.

**Comment by piratman38** [comment]
Thank you very much for your help. It seems to work now.
