### ISSUE TITLE
Landing/Login Page backdrops not loading

### ISSUE THREAD

**Issue by LeviSnoot** [Ombi-app/Ombi#4211]
**Describe the bug**
When you go to the login page for Ombi, the background remains blank. This behaviour is consistent between my instance and the Ombi demo.

**To Reproduce**
1. Go to 'https://app.ombi.io/landingpage'
2. See error

**Expected behavior**
TVDb and TMDb backdrops cycling.

**Screenshots**
![image](https://user-images.githubusercontent.com/13402525/119870187-fb3aff00-bf18-11eb-9f1b-53062a74e144.png)
![image](https://user-images.githubusercontent.com/13402525/119870338-27ef1680-bf19-11eb-8f21-fb6279b1402b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro

**Ombi Version (please complete the following information):**
- Version: 4.0.1402
- Media Server: Jellyfin

**Comment by tidusjar** [comment]
Its due to fanart.tv certificate expiring, just have to wait for them to
renew

**Comment by LeviSnoot** [comment]
Good to know, thanks!
