### ISSUE TITLE
Telegram notification does not work when item is available at radarr

### ISSUE THREAD

**Issue by xiNeRoar** [Ombi-app/Ombi#4212]
**Describe the bug**
Telegram notification only work with request through ombi, which mean any items that directly imported to radarr or sonarr not requested through ombi will not trigger the notification (Request Available). 

**To Reproduce**
1. Add a movie NOT via ombi (directly add in radarr)
2. Movie successfully grabbed and imported
3. Movie show available in ombi
4. Telegram show no notification

**Expected behavior**
Telegram show notification when movie is marked "Available" on ombi.

**Ombi Version (please complete the following information):**
 - Version: 4.0.1342
- Media Server: Jellyfin
- Database Type: SQLite

**Comment by xiNeRoar** [comment]
will there anyone comment on this issue?

**Comment by tidusjar** [comment]
Ombi will only notify on items requested through Ombi. It has never reported the availability for items that have not been requested through Ombi.

This is currently intended behaviour.
