### ISSUE TITLE
Option to Deny Request Missing and hard to find.

### ISSUE THREAD

**Issue by thesugarat** [Ombi-app/Ombi#4217]
**Describe the bug**
When a TV Show or Movie is Pending Approval, clicking on the Options button does not give a Deny Request option. To deny a Movie request you click on Details and right at the top of the page is a Deny or Approve button. If it's a TV Show you have to click on Details then scroll all the way to the bottom, then click on Requests, then drop down the User that made the Request to finally find a Deny Request button.

**To Reproduce**
1. Go to Pending Requests
2. Click on Options
3. See no option to Deny Request

**Expected behavior**
I expect to be able to Deny or Accept a request from the Options button.

**Desktop**
 - OS: Windows 10 X64

**Ombi Version (please complete the following information):**
 - Version 4.0.1403
- Media Server Plex
- Database Type: SQLite

**Additional context**
Love Obmi but this user interface to Approve or Deny Requests is not Admin friendly.

**Comment by tidusjar** [comment]
This is expected behaviour,

the reason behind this is that with TV Shows you can have multiple requests e.g. User A could request Season 1 and User B could request Season 2.

So you need to drill down into the details and manage the TV Requests from there.
