### ISSUE TITLE
V4 Poster aspect ratio keeps changing

### ISSUE THREAD

**Issue by mkanet** [Ombi-app/Ombi#4218]
**Describe the bug**
Posters not displaying correctly.  Aspect ratio of posters changes as the browser size changes.  This causes posters to turn into square; cutting off the poster image.  Posters should only shrink or grow without changing aspect ratio (when web browser is resized)

**To Reproduce**
Resize web browser size

**Expected behavior**
Posters should only grow or shrink when resizing the web browser WITHOUT changing poster aspect ratio.

**WRONG AR**
![Screenshot 06-08-2021 at 01 54 40 PM](https://user-images.githubusercontent.com/811008/121256155-1daa1200-c861-11eb-8d28-d2ec0042f979.png)

Poster aspect ratio should similar to below, regardless of how big/small the web browser size is.  Only poster size should change, not aspect ratio:

**CORRECT AR**
![Screenshot 06-08-2021 at 01 56 35 PM](https://user-images.githubusercontent.com/811008/121256539-85f8f380-c861-11eb-99d9-30aa57c05be0.png)

**Comment by mkanet** [comment]
Thanks, @twanariens.  Can I just paste the code below to Ombi's custom CSS section to see the fix now?

```
.card-skeleton {
   padding: 5px;
}

::ng-deep .p-carousel-item{
  flex: 1 0 200px !important;
}
```

**Comment by mkanet** [comment]
@twanariens thanks for all your hard work.  I noticed that the PR was approved; and, that there is a new pre-release v4.0.1412 from yesterday [here](https://github.com/Ombi-app/Ombi.Releases/releases).  Does that release include your latest PR code?  I tried it just now, but posters still don't maintain their AR.  If I need a special developer build, could you point me to where I can download it from?

**Comment by twanariens** [comment]
That release does not include my PR code unfortunately. As you can see in
the PR, the dev made some comments about my fix (mostly concerning mobile
view issues) that I need to fix.
Will probably do that tonight/tomorrow.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Op do 10 jun. 2021 om 18:40 schreef MKANET ***@***.***>:

**Comment by mkanet** [comment]
> That release does not include my PR code unfortunately. As you can see in the PR, the dev made some comments about my fix (mostly concerning mobile view issues) that I need to fix. Will probably do that tonight/tomorrow. Op do 10 jun. 2021 om 18:40 schreef MKANET ***@***.***>:

Thanks for explaining.  BTW: A related note to the dev's comments...

I noticed that Ombi in general seems not use space very effectively on smaller display areas such as mobile or a smaller desktop in respect to similar web interfaces (Radarr, Sonarr, Petio, Overseer).  Ombi can barely fit 4 posters on a mobile screen (even without the extra-large sidebar).  Maybe, you could look into resizing items on the layout to fit posters more efficiently in general?  Even on my PC desktop web browser, the layout wastes a lot of valuable real estate.

**Ombi:**
![Ombi-640](https://user-images.githubusercontent.com/811008/121592867-16fdd500-c9f0-11eb-9413-e517fc5f0a75.png)

**Petio:**
![petio-640](https://user-images.githubusercontent.com/811008/121592902-20873d00-c9f0-11eb-8f9d-fa62273421ec.png)

**Radarr:**
![Radarr-640](https://user-images.githubusercontent.com/811008/121592928-2846e180-c9f0-11eb-99f6-f20d6a12c0d6.png)
