### ISSUE TITLE
V4 Sidebar too wide

### ISSUE THREAD

**Issue by mkanet** [Ombi-app/Ombi#4219]
Sidebar is way too wide compared to popular interfaces such as Radarr. Sonarr, Plex etc.  Currently, OMBI's sidebar wastes too much space.**  This wasted space could be used for posters instead.  

Please consider using single-word categories.  I.E., `User Management` should be just `Users`.  `Feature suggestions` renamed to `Ideas` or something like that (similar to other apps)
![Wronte](https://user-images.githubusercontent.com/811008/121262907-b8a6ea00-c869-11eb-90ba-da7bda08c9bc.png)

**Below, looks nicer; and, wastes less space.  This is just a rough idea.. something like this:**
![Correct](https://user-images.githubusercontent.com/811008/121262789-88f7e200-c869-11eb-8e7e-2b3c97866623.png)

**Comment by tidusjar** [comment]
Good suggestion! @twanariens what do you think?

**Comment by twanariens** [comment]
Yes. The only issue I am facing atm is the customisable app name. When users use a long name "Special Request Software For Family" it would still stredge the menu to a big width. I need to figure something out for that.

**Comment by mkanet** [comment]
Thanks for considering this suggestion guys.  @twanariens, you could probably just allow the sidebar to increase in width automatically if the customizable app name is unusually long.  It would probably look pretty bad.. but, at least the name wouldn't get truncated.

That reminds me, instead of using a text-based custom app name, maybe you could allow the user to use their custom logo instead similar to how [Overseerr](https://overseerr.dev/) does it.  It would look much nicer than plain text, IMO.

**Comment by mkanet** [comment]
@twanariens now that the PR was approved, how can I upgrade my ombi installation to see these improvements?  Do I need to download the developer build (that's already been built)?  If so, can you point me to where I can download the zip file please?

**Comment by mkanet** [comment]
Looks great!  Thanks again!!
