### ISSUE TITLE
Ombi for Android: Wrong Server Version

### ISSUE THREAD

**Issue by TheSDBux** [Ombi-app/Ombi#4224]
**Describe the bug**
Unable to log into the OMBI for Android app. Either with the manual input or the QR code function.

**To Reproduce**
Manual Input of Designated site URL or Scan of Site Generated QR code.

**Expected behavior**
Login Accepted

**Screenshots**
N/A

**Logs (Logs directory where Ombi is located)**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2

**Ombi Version (please complete the following information):**
 - Version 4.0.1412
- Media Server Plex
- Database Type: SQLite

**Additional context**
Issue only occurred after Android App Update that prompted a update of the server from the v3's

**Comment by tidusjar** [comment]
Email me your URL guy use to login to Ombi and ill check it out. tidusjar@gmail.com
