### ISSUE TITLE
V4 GUI default scale too large

### ISSUE THREAD

**Issue by mkanet** [Ombi-app/Ombi#4226]
Guys, thank you so much for all the recent improvements to the Ombi interface.  Anyway, I wanted to point out that Ombi's interface default scale appears to be unusually large in respect to other similar interfaces on a typical 1920x1080 desktop (at least on my Windows 10 PC).  Currently, it can barely fit 6 posters in my web browser (if I also want to see the sidebar) ..and, have my web browser on the left side of my desktop.

**100% scale:**
![Default1](https://user-images.githubusercontent.com/811008/121793280-6be94900-cbb2-11eb-87f8-21a9f86470e3.png)

The only way I can fix this scaling issue is by adding the below custom CSS code:
```
html {zoom: 84%;}
```
**84% scale:**
![84](https://user-images.githubusercontent.com/811008/121794939-765f0f00-cbc1-11eb-9608-0cfab5470aab.png)

Is this extra-large default scale done intentionally?  Maybe Ombi detects desktop resolution incorrectly.. thinking my desktop is 4K resolution?  

**NOTE:  Forgive the added "dark" color css mod included in the screenshots above.  Even without any color mod at all, the scaling looks exactly the same, only colors are different.** 

**Desktop (please complete the following information):**
 - OS: Windows 10

**Ombi Version (please complete the following information):**
 - Version: 4.0.1420
- Media Server:  Plex 
- Database Type: SQLite

**Comment by twanariens** [comment]
It should look like this:
![image](https://user-images.githubusercontent.com/34845004/121801238-a3013e00-cc36-11eb-937a-1f9312cac043.png)

For a 1920x1080 display. Do you have a scale/zoom activated on your display? (Windows/Mac settings)

**Comment by mkanet** [comment]
Scaling is completely disabled on my Windows 10 desktop.  It's just vanilla 1920x1080p@60Hz.  

Below is what it looks like when sitting on the left side of my desktop at 100% scale.  It looks the same regardless of what web browser I use.  The odd thing is that I can't reproduce this issue with any other web interface (radarr, sonarr, plex, petio, etc) displayed on the same desktop.

Is there a chance the method used to detect desktop size may not be calculating size correctly?

![Screenshot 06-13-2021 at 02 35 39 AM](https://user-images.githubusercontent.com/811008/121802386-e5079100-cbf0-11eb-8f5e-4795a634f713.png)

**Comment by twanariens** [comment]
I am talking about this:
![image](https://user-images.githubusercontent.com/34845004/121802558-42c1ca80-cc3d-11eb-93e8-a2b3625b3998.png)

And I am not sure whether Radarr/Sonarr use a different from of detecting Windows sizes. We use @media calls to change styling based on pixels. But it seems like the browser is reporting back "wrong" pixels.

Can you double check the Windows option I have posted above

**Comment by mkanet** [comment]
> I am talking about this:
> 
> And I am not sure whether Radarr/Sonarr use a different from of detecting Windows sizes. We use @media calls to change styling based on pixels. But it seems like the browser is reporting back "wrong" pixels.
> 
> Can you double check the Windows option I have posted above

![Screenshot 06-13-2021 at 02 49 30 AM](https://user-images.githubusercontent.com/811008/121802627-1fbdf900-cbf2-11eb-9ed3-5092a086ce09.png)

**Comment by twanariens** [comment]
What is your chrome zooming set to:

![image](https://user-images.githubusercontent.com/34845004/121804105-0befb280-cc45-11eb-8943-137e92d49065.png)

**Comment by mkanet** [comment]
> What is your chrome zooming set to:

100%.  I have to change it to 75% for it to fit more posters.

**Comment by twanariens** [comment]
I am trying to wrap my head around this, cause it doesn't make sense. Something is scaling it and it is not Ombi (as you can see per my screenshot). But it still only happens for Ombi (cause you said Sonarr and Radarr are working fine).

Can you check the width of the image posters for me?

**Comment by mkanet** [comment]
@twanariens,  I just viewed Ombi webpage on a completely different Windows 10 PC (my work laptop connected to a 1920x1080 monitor).  **The same exact issue happens.**  I even bypassed my reverse proxy; connecting directly to Ombi service itself on my LAN.

**The poster size is:** **190x285** (when displayed on in the web browser):
![190x285](https://user-images.githubusercontent.com/811008/121823134-11a2c380-cc58-11eb-8e76-3f9a0324607a.png)

Below, is a screenshot from a chrome web browser on my work PC on a 1920x1080 resolution desktop with no scaling in the OS or web browser.  The web browser is on the left half of my desktop:
![Work-PC2](https://user-images.githubusercontent.com/811008/121823232-ce952000-cc58-11eb-9193-89c8876cf760.png)

**Comment by twanariens** [comment]
Thank you for the extensive testing mate! That does help out with a lot of questions I had.

Can you create a test account for me and provide the details + url of ombi in a DM to me? Would like to take a look.

**Comment by mkanet** [comment]
@twanariens Wow!  I can't believe the **_Creator_** of Ombi is going to visit my Ombi server!  I have set you up with a test account on my server.

Forgive my ignorance.  I'm not sure where to DM you.  I couldn't find you on the Ombi Discord channel.  I could only find TidusJar there.  I was able to find you on Reddit.  However, I want to make sure that's where you want me to contact you.

**Comment by twanariens** [comment]
@mkanet I am the "iCare.Kuraki" guy on Discord.

**Comment by twanariens** [comment]
This is how your Ombi looks for me:
![image](https://user-images.githubusercontent.com/34845004/121953745-3bdea900-cd5e-11eb-8b2e-989296a04ff2.png)

**Comment by mkanet** [comment]
@twanariens, yes, that's what it looks like for me too when I display the interface fullscreen.  I almost never display my web browser fullscreen on a 1920x1080 (16x9) desktop.  The scaling issue I'm talking about is when displaying the web browser on either the left-half or right-half of the desktop; just like all my screenshots above.  Windows 10 lets you put apps on the left or right side of the desktop with a `win`+`leftarrow` key combination or `win`+`rightarrow`

You should most likely get a screenshot similar to what I posted in my screenshots.  Once you do, try the same thing with Radarr or any other similar interface...

**Comment by twanariens** [comment]
Okaaaay. Now it all makes sense. But this is more "personal preference" or a feature request then an "issue". 

If you want to "customize" it to your needs you can use the custom css block with the following code:

`@media (min-width: 755px){
    .p-carousel-item {
        flex: 1 0 160px!important;
    }
}`

Now if you want go smaller than 160px, you will also need to change the font size of the overlay:

`@media (min-width: 755px){
    .p-carousel-item {
        flex: 1 0 130px!important;
    }
    .top-left{
        font-size:11px;
    }
    .top-right{
        font-size:11px;
    }
}`

You can decide how it looks :D

**Comment by mkanet** [comment]
Thank you for looking into this.  I tried the CSS code you suggested.  It seems to be specific to just poster size.. which makes the posters look pretty strange.  The issue I mentioned is general scale for the entire Ombi interface (all fonts, images, etc ) in comparison to commonly used interfaces like Radarr, Sonarr, *arr, Plex, Emby, Jellyfin, Overseerr, Petio, etc... pretty much ALL apps that display TV/Movie media posters.

Normally, we can fit **3 rows of posters** in a web browser interface on a typical 1080p display; which is more efficient use of the display area.  With Ombi, it's **2.5 rows** with unusable posters cut off at the bottom.

**Radarr:**
![Radarr](https://user-images.githubusercontent.com/811008/121970256-fc4a9980-cd2a-11eb-8d05-4346136e0d02.png)

**Plex:**
![Plex](https://user-images.githubusercontent.com/811008/121970539-9f9bae80-cd2b-11eb-897e-5ce027380cb0.png)

**Ombi:**
![Ombi](https://user-images.githubusercontent.com/811008/121970266-0076b700-cd2b-11eb-9f9f-8751446c39ea.png)

I was able to use the CSS code below to cure this.  However, I just wanted you to be aware that Ombi is only app that seems to display 2.5 rows of posters with unusually large fonts.
```
html {zoom: 84%;}
```
Anyway, no worries mate.  I just want to be sure you're aware that Ombi is the only app that seems to have this unusual scaling preference. :)

**Comment by twanariens** [comment]
You do have a point though, but that would mean the entire design/layout needs to be converted to `em` instead of `px`. Which is doable, but that would probably need a full rewrite of the design. I will keep it in my mind whenever we are going to redesign new parts to fix this but for now, it is what it is unfortunately

**Comment by mkanet** [comment]
Thank you for considering this suggestion.  You guys are great.  Would you like for me to close this issue?

**Comment by twanariens** [comment]
Yes please :D
