### ISSUE TITLE
App users can't use plex login

### ISSUE THREAD

**Issue by MDHMatt** [Ombi-app/Ombi#4227]
**Describe the bug**
No plex login option on app, plex users can't login unless going via web version first

**To Reproduce**
open app only scan qr and ombi login. 

**Expected behavior**
be great to have a second login like on the web version

**Desktop (please complete the following information):**
 - OS: iOS

**Additional context**
plex auth enabled in web app

**Comment by tidusjar** [comment]
App users can currently login via username and password. They just need to enter in their Plex Credentials.

I will be looking at adding the Plex OAuth into the app going forward.
