### ISSUE TITLE
Play on Plex links malformed

### ISSUE THREAD

**Issue by mindset-tk** [Ombi-app/Ombi#4230]
**Describe the bug**
"Play On Plex" links in movies generate a malformed URL that will not resolve. When opening the link what I see is:
https://app.plex.tv/desktop/#!/server/[MACHINEID]/details?key=library%2Fmetadata%2F30934
but the correct link should be 
https://app.plex.tv/desktop/#!/server/[MACHINEID]/details?key=%2Flibrary%2Fmetadata%2F30934

It is missing a %2F right after "key=".  If I edit the link and add the %2F it works a treat.  I was unable to find anything in the settings to address this issue, but please let me know if it's something simple I missed.  I have verified my token and machineID, I don't _think_ they are incorrect, or it wouldn't pull availability at all.

**To Reproduce**
Pick a movie that is already available on Plex. Plex opens and authenticates but spins forever, never loading the movie page in question.

**Expected behavior**
The movie page opens.

**Desktop (please complete the following information):**
 - OS: Docker 20.10.7 on Ubuntu 20.04.  Using the https://hub.docker.com/r/linuxserver/ombi image to generate my profile.

**Ombi Version (please complete the following information):**
 - Version 4.0.1342 (latest on Dockerhub currently)
- Media Server Plex
- Database Type: SQLite

**Comment by tidusjar** [comment]
Thanks for reporting this and doing the investigation! But this has already been resolved in the develop branch :)

**Comment by mindset-tk** [comment]
Yay! Thanks.
