### ISSUE TITLE
Disable TV in newsletter not working

### ISSUE THREAD

**Issue by brommeltje** [Ombi-app/Ombi#4234]
**Describe the bug**
Disable TV in newsletter not working

**To Reproduce**
Go to newsletter
Enable the Disable TV
Submit
Trigger now

**Expected behavior**
Receive mail without TV series
However Movies and TV series are both in the newsletter

**Screenshots**
NA

**Logs (Logs directory where Ombi is located)**
Daily log attached

**Desktop (please complete the following information):**

**Ombi Version (please complete the following information):**
 - Version 4.0.1342
 - Media Server Emby
 - Database Type: SQLite

**Additional context**
NA
[log-20210622.txt](https://github.com/Ombi-app/Ombi/files/6697092/log-20210622.txt)

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈
