### ISSUE TITLE
V4 Issues with overriding the default Profile Ombi/Radarr

### ISSUE THREAD

**Issue by sstuetzel** [Ombi-app/Ombi#4242]
**Describe the bug**
Hi, in some movies I change the default path when requesting a new movie (with the corresponding function in Ombi). The chosen path is correctly displayed in Ombi under request-list but in Radarr the movie is placed with the default path/folder.
My setup: 2 shared volumes on a NAS, using Ombi 4.0.1430 and Radarr 3.2.2.5080 on a MacMini which has access to the shared folder of the NAS. Could you please check this or maybe give me a hint on how to avoid this. Thanks

**Expected behavior**
Path chosen in ombi should be transferred to Radarr

**Desktop (please complete the following information):**
 - OS: MacOS 11.4

**Ombi Version (please complete the following information):**
 - Version 4.0.1430 
- Media Server Plex
- Radarr 3.2.2.5080 
- Database Type: Sqlite

**Comment by tidusjar** [comment]
So are you changing the root folder in ombi after its been sent to radarr

**Comment by sstuetzel** [comment]
It's not about changing something after the request. I attach some screenshots. 
When requesting a new movie in Ombi I can change the folder via advanced options (in this case to "Movie Kinder"-> Movie Children-> the second folder option)
![Bildschirmfoto 2021-06-27 um 09 23 59](https://user-images.githubusercontent.com/78645839/123536391-559ec980-d72a-11eb-9d61-ee1ed107b206.png)
Checking this via request/details shows the correct folder:
![Bildschirmfoto 2021-06-27 um 09 24 48](https://user-images.githubusercontent.com/78645839/123536450-aadadb00-d72a-11eb-9f61-db2cefb14915.png)
But in Radarr the default folder (mowie2) is stored:
![Bildschirmfoto 2021-06-27 um 09 26 09](https://user-images.githubusercontent.com/78645839/123536469-c47c2280-d72a-11eb-9652-1a0b3e899ecc.png)

BTW: Somehow the added date is also not correct (added on the 27th June and not on the 20th Jan as shown in Radarr:
![Bildschirmfoto 2021-06-27 um 09 25 48](https://user-images.githubusercontent.com/78645839/123536503-dbbb1000-d72a-11eb-998f-f17db42c6f04.png)

**Comment by tidusjar** [comment]
So that seems odd, regarding the added Date, Ombi does not pass over any date that it was added.

Regarding the root folders, I'm not sure as I'm unable to reproduce this.

Can you go into your radarr settings and just refresh your root folders, select a different one as the default and save, then try the same steps again as above (can use a different movie)?

**Comment by sstuetzel** [comment]
It works now. I added another root folder to Radarr and checked that Ombi lists all root folders (via settings/movie/radarr). Didn't change the "default root folder" in Ombi and requested 2 new movies. Each with a diffrent root folder (not the default root folder). Booth movies have been transferred with the correct path, also the added date is now correct. Do you have any explanations regarding this miracle?

**Comment by tidusjar** [comment]
Nope no idea, last night I thought it was something to having an outdated default, but that actually doesn't make sense since you are doing it from the admin popup, can only assume it's some error in radarrs side. Everything we get the root folders, we look them up from radarr
