### ISSUE TITLE
Plex Oauth not closing login window, infinite ombi loading loop

### ISSUE THREAD

**Issue by mediacenterkodi84** [Ombi-app/Ombi#4249]
**Describe the bug**
plex oauth does not auto  close login window after successful login. If user does not close this login window and goes back to ombi leaving said login tab open, ombi does an infinite loading loop till said login screen is closed. On latest dev ombi.

**To Reproduce**
1. Click login with plex
2. Login with plex credentials successfully
3. Go ombi page without closing plex login page
4. Infinite loading loop from ombi until said tab is closed.

**Expected behavior**
Ombi should automatically close the plex login screen after successful login and automatically direct the user back to the ombi app. 

**Screenshots**
Not applicable

**Logs (Logs directory where Ombi is located)**
Let me know if you need these if you can’t reproduce for some reason. I have reproduced this on three machines.

**Desktop (please complete the following information):**
 Ubuntu Server 20.04

**Ombi Version (please complete the following information):**
 - Version 4.0.1442
- Media Server latest public 
- Database Type: SQLite 
**Additional context**
This is frustrating for someone who only uses oauth and no local ombi accts. Have had multiple users say they can’t login but as soon as I tell them to close the login page, issue goes away.

I am using the line below to hide local login access on the login page. Don’t believe this should affect it but throwing it out there anyhow.

.login-buttons button:first-of-type { display: none; }

**Comment by tidusjar** [comment]
It states on the Plex Popup to close it :(
![image](https://user-images.githubusercontent.com/6642220/124984338-fe093380-e030-11eb-9680-f50a307ca7ed.png)


I'll see what I can do

**Comment by mediacenterkodi84** [comment]
I so realize that haha. End users tho, they don’t always read.

**Comment by tidusjar** [comment]
That window above the content in there is provided by Plex so I cannot change it. I will make some improvements to this area

**Comment by mediacenterkodi84** [comment]
Thank you so much! Love the app! Keep up the amazing work!

**Comment by tidusjar** [comment]
Fixed in develop
