### ISSUE TITLE
New Request '+' icon blocks drop down 

### ISSUE THREAD

**Issue by gmoler** [Ombi-app/Ombi#4250]
**Describe the bug**
On a TV show request, go to 'details' and scroll down to the 'requests' section. The '+' symbol blocks the down arrow element.

**To Reproduce**
1. Go to 'Requests'
2. Click on 'Tv Show'
3. Scroll down to the actual request
4. Choose 'details' 
5. Scroll down to the bottom where the 'request' section is
6. Note that the '+' icon blocks the drop down down arrow

**Expected behavior**
The interactive section can either be shrunk horizontally to fit with the '+' button, or you can shrink and relocate the '+' button

**Screenshots**
Attached

**Logs (Logs directory where Ombi is located)**
n/a

**Desktop (please complete the following information):**
 - Reproducible in all browsers

**Ombi Version (please complete the following information):**
 - Version 4.0.1435
- Database Type: SQLite (Please change if using MySQL)

![firefox_0bbIKudTRQ](https://user-images.githubusercontent.com/7731882/125005734-791b1b80-e02a-11eb-9006-2a7f6c722fab.png)

![firefox_pnxKzmYwYT](https://user-images.githubusercontent.com/7731882/125005803-a8318d00-e02a-11eb-9565-09b1ba07cf5e.png)

**Comment by tidusjar** [comment]
You don't actually need to press the arrow to make the accordion expand, it's more of a UI indication, the actual arrow does nothing other than aid visually.
