### ISSUE TITLE
Recently Added Emails: Title text bleeds into description

### ISSUE THREAD

**Issue by nopoz** [Ombi-app/Ombi#4254]
**Describe the bug**
When viewing the recently added emails on Mobile, if the title is longer than one line, it bleeds over into the description text. 

**To Reproduce**
Using Gmail app (2021.05.30.381370072.release) on Android (2280 x 1080 resolution) to view the email. See attached picture for an example.

**Expected behavior**
For the title text to not bleed into the description

**Screenshots**
<img src="https://user-images.githubusercontent.com/460545/125125703-d789dd80-e0ae-11eb-8bec-6ae949a09b1e.jpg" width="500">

**Logs (Logs directory where Ombi is located)**
n/a

**Desktop (please complete the following information):**
n/a

**Ombi Version (please complete the following information):**
 - Version 4.0.1342
- Media Server n/a
- Database Type: n/a

**Additional context**
n/a

**Comment by twanariens** [comment]
This should be fixed in the latest release V4.15.2
