### ISSUE TITLE
Plex links - Not Found 

### ISSUE THREAD

**Issue by Treverr** [Ombi-app/Ombi#4255]
**Describe the bug**
Anytime I try to use the "Play on Plex" button it routes me to the app.plex.tv desktop app but then says "Not Found" I have deleted and reset up the Plex connection, deleted the OmbiExternal.db and set the connection back up but It still does not work. 

**To Reproduce**
1. Go to any movie
2. Click on Play on Plex
3. Not found error

**Expected behavior**
Movie should load

**Screenshots**
<img width="1219" alt="Screen Shot 2021-07-12 at 12 31 15 AM" src="https://user-images.githubusercontent.com/5624521/125248074-7ded0300-e2a8-11eb-8f85-21742a80569e.png">

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.
[log-20210712.txt](https://github.com/Ombi-app/Ombi/files/6799425/log-20210712.txt)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Docker - Linux

**Ombi Version (please complete the following information):**
 - Version [e.g. 4.0.958] 4.0.1430
- Media Server [e.g. Plex] Plex
- Database Type: SQLite 

**Additional context**

**Comment by tidusjar** [comment]
In your Plex Settings, is your Machine Identifier set? 

This field is used to correctly route to the media.

**Comment by Treverr** [comment]
It was set but it was set incorrectly by the set up wizard so I changed it and it works now. Thank you!
