### ISSUE TITLE
"Failed to get push token for push notification" on iOS app

### ISSUE THREAD

**Issue by nemosmithasf** [Ombi-app/Ombi#4257]
**Describe the bug**
Upon opening the app on iOS, I receive this "alert"

"Failed to get push token for push notification, Please enable access to notification!"

However, I don't have any of the push notification settings open. So I can only assume it's a bug?

**To Reproduce**
Open the app

**Expected behavior**
No alert

**Screenshots**

![IMG_9DBAC6E28861-1](https://user-images.githubusercontent.com/14184529/125869237-1cf2d99b-a463-4e16-aa7a-7b022010bdf7.jpeg)

**Logs (Logs directory where Ombi is located)**
none

**Desktop (please complete the following information):**
none

**Ombi Version (please complete the following information):**
Using the latest iOS app, and the Ombi version is 4.0.1430

**Additional context**
none

**Comment by tidusjar** [comment]
This means you have not enabled notifications for the app, is that intended?

**Comment by nemosmithasf** [comment]
Oh, it's an iOS side error. Based on the word "push token", I assumed it was an error between the app and the Ombi sever.

There's a follow-up concern then:
- If iOS notification is disabled, this pop-up occurs every time you open the app. It's essentially preventing users from disabling notification (which is a non-vital feature, so it should be able to be disabled)

Also, perhaps its worth considering reword the error to be more clear? Something like:
"App notification is disabled, please enable in phone settings", or anything which emphasizes that you're talking about the user-side and not server side.

**Comment by tidusjar** [comment]
Yeah valid points. I’ll make the changes!

**Comment by tidusjar** [comment]
This has been resolved
