### ISSUE TITLE
iOS App infinite loading

### ISSUE THREAD

**Issue by NotAUsername4Sure** [Ombi-app/Ombi#4260]
**Describe the bug**
I think i can login to the iOS app (i got past the login screen) but it is loading infinitely

**To Reproduce**
1. Download app
2. Login in any way (qr code, Open app link, manually)
3. Infinite loading

**Expected behavior**
To view my content

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: iOS

**Ombi Version (please complete the following information):**
 - Version 4.0.1430
- Media Server Plex
- Database Type: SQLite
- Installation type : Docker

**Additional context**
I also tried deleting the app and reinstalling, tried longing in from an external network, tried from internal network. My application URL is accessible from outside my network and from inside. The only thing i am suspecting is that ombi is running on custom port 8443, maybe that is something that the app is not expecting on the server URL. Any help/suggestion appreciated

**Comment by tidusjar** [comment]
Email me your ombi URL and I'll take a look tidusjar@gmail.com

**Comment by NotAUsername4Sure** [comment]
My certificate was expired. Updating the certificate solved the issue. @tidusjar thank you for your time and troubleshooting help !
