### ISSUE TITLE
Unable to remove Emby.Jellyfin server - 'Submit' button grey'd

### ISSUE THREAD

**Issue by ghost** [Ombi-app/Ombi#4262]
**Describe the bug**
When removing a Emby/Jellyfin server, one has to press the "Submit" button to submit the removal, however the button is grey'd out. This is particularly an issue when one removes/decommissions their Emby/Jellyfin service/server and needs removing from Ombi

**To Reproduce**
1. Go to "Settings" - "Media Server" - "Emby" (or jellyfin) menu
2. Enable an Emby (or Jellyfin) server
3. Press "Add Server" and add a new server with relevant details, test connection, load server info and submit the settings in Ombi, etc.
4. Naviate anywhere else within Ombi
5. Go back to the Settings - Media Server - Emby (or Jellygfin) page
6. Click on "Remove Server" - visually the settings disappear, however....
7. ** Unable to press the "Submit" button to actually remove the settings
8. Navigate elsewhere in Ombi
9. Go back to the Settings - Media Server - Emby (or Jellygfin) page
10. Emby (or Jellyfin) server still exists 

**Expected behavior**
The Emby/Jellyfin server settings should be removed from Ombi, either when the "Remove Server" option is pressed and the settings visually disappear OR enable the "Submit" button to be pressed after selecting "Remove Server" so the removal can be submitted to Ombi permanently.

**Screenshots**
- Existing Settings:
![image](https://user-images.githubusercontent.com/41772110/126665090-0b0dd75f-a505-49a6-8604-4c762eef93aa.png)

- Removed Server pressed
![image](https://user-images.githubusercontent.com/41772110/126665157-fcf8f59f-4e8b-4211-8a88-6f244286178f.png)

- Re-navigating back, settings are still there:
![image](https://user-images.githubusercontent.com/41772110/126665217-5da0f93b-1f44-4eda-b2fa-febe9c62cadf.png)

**Logs (Logs directory where Ombi is located)**
n/a - this is a HTML issue with the button "Remove Server" function.

**Desktop (please complete the following information):**
 - OS: Linux 5.10.17-v8+ (Arm64)

**Ombi Version (please complete the following information):**
 - Version: 4.0.1448   
- Media Server : Emby or Jellyfin
- Database Type: Sqlite

**Additional context**
Using Opera Version:77.0.4054.277

**Comment by tidusjar** [comment]
Thanks for the report. For now until this is fixed I suggest you do not enable that server as a workaround

**Comment by psi5asp** [comment]
Using the switch to disable it, still does not enable the Submit button.

The only way around it is to use the 'Discover Server Information' to re-discover it - this enables the 'Submit' button, then one can disable/remove it. Even the 'Load Libraries' button doesn't work, just gives this error:

![image](https://user-images.githubusercontent.com/41772110/126729113-2b93bd94-65f5-42e5-bc8b-21e632ebbae8.png)

**Comment by tidusjar** [comment]
Load Libraries has now been fixed

**Comment by Kryptactic** [comment]
Is there an update on when this might be fixed? Having the same issue. I can not enable any of the servers under the EMBY Server configuration.

**Comment by tidusjar** [comment]
Hi sorry but there has been no further progress on this yet.

Please remember that I have a full time (quite demanding) job, a toddler, baby, a wife and a puppy. 
All of my limited free time is usually spent either developing Ombi, fixing bugs on Ombi or providing support with Ombi, keeping in mind that no one is paying me to do this.

Ombi is currently a 1 person development team. 

So if I have not yet got around to this you now know why 😄

**Comment by collateral127** [comment]
I ran into this issue as well - if you're comfortable browsing the sqlite ombisettings.db file, all you need to do is find the offending entry and delete it from the db, then restart Ombi. It should nuke those settings out and you can update them (or not) as you wish.

**Comment by twanariens** [comment]
This will be continued in #4424
