### ISSUE TITLE
No 'Mark Available' option for TV Shows

### ISSUE THREAD

**Issue by jiznon** [Ombi-app/Ombi#4265]
**Describe the bug**
No option to mark tv show as available.

**To Reproduce**
1. Go to any show listed under Requests > TV Shows
2. Click on Options
3. Only option is to Delete Request

**Expected behavior**
A "Mark Available" button like the Movie requests have.

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Windows 10 2004, 10.0.19041

**Ombi Version (please complete the following information):**
- Version 4.0.1448
- Media Server - Plex
- Database Type: SQLite

Thanks!

**Comment by tidusjar** [comment]
If you look at the bottom of the page where the requests are, you can mark available the requests

**Comment by jiznon** [comment]
Thanks! Not use to having to dig so deep compared to how simple it is for movies.
