### ISSUE TITLE
Music Search returning bad data which in turn makes the UI look incomplete

### ISSUE THREAD

**Issue by Fyb3roptik** [Ombi-app/Ombi#4271]
**Describe the bug**
![Screen Shot 2021-07-26 at 4 12 32 PM](https://user-images.githubusercontent.com/339131/127059891-a03f7d20-aacc-4a2a-9a83-690083f22f8c.png)

Searching for an artist (in this case Metallica) renders this on Desktop. 

**To Reproduce**
1. Search for Music only and an artist
2. See bad data being returned

**Expected behavior**
I expect the Artist Name to be present and for album artwork to be present as well.

**Desktop (please complete the following information):**
 - OS: Macos Chrome 92.0.4515.107

**Ombi Version (please complete the following information):**
 - Version 4.0.1449
- Media Server Plex
- Database Type: MySQL

**Comment by Fyb3roptik** [comment]
A little update here. I see you guys are using Musicbrainz instead of audiodb. This is why its so ugly! I will attempt to fork this and provide a PR

**Comment by aka-charos** [comment]
I feel like a necromancer, but I had to revive this issue and ask if there's any plan to show music section some love :)
