### ISSUE TITLE
Missing Jellyfin Movies + no Launcher button

### ISSUE THREAD

**Issue by psi5asp** [Ombi-app/Ombi#4272]
**Describe the bug**
Ombi does not import all Jellyfin enabled library Movies - also running Plex with the same libraries/sources.

**To Reproduce**
1. Setup Plex and Jellyfin with the same library sources
2. Click on Clear Data and Resync (and/or Manually Run Cacher)
3. Spot check several Jellyfin Movies

**Expected behavior**
Both Plex and Jellyfin launch buttons to appear for movies which are avalaible in both Plex and Jellyfin.

**Screenshots**
- Existing Jellyfin Movie
![image](https://user-images.githubusercontent.com/41772110/127102624-64a0551e-83bb-4643-9b71-86810552ad0a.png)

- Found in OmbiDB
![image](https://user-images.githubusercontent.com/41772110/127102681-13c4db1f-9beb-4bb6-86ab-ad200e157f27.png)

- No Launch for Jellyfin on Ombi page:
![image](https://user-images.githubusercontent.com/41772110/127102776-5fb4cc33-5ac7-4574-90b5-623c8aa7e41d.png)

- Confirmed Plex Ombi DB entry:
![image](https://user-images.githubusercontent.com/41772110/127102817-b47df90b-92c7-4049-b217-1ddcf4e4e1c1.png)

**Logs (Logs directory where Ombi is located)**
`[Debug] Calling Execute on job Jellyfin.IJellyfinContentSync
[Debug] Batch acquisition of 0 triggers
[Debug] Batch acquisition of 0 triggers
[Debug] Batch acquisition of 0 triggers
[Debug] Batch acquisition of 0 triggers
[Debug] Batch acquisition of 0 triggers
[Debug] Batch acquisition of 0 triggers
[Debug] Batch acquisition of 0 triggers
[Debug] Batch acquisition of 0 triggers
[Debug] Batch acquisition of 0 triggers
[Debug] Batch acquisition of 0 triggers
[Debug] Batch acquisition of 0 triggers
[Debug] Batch acquisition of 0 triggers
[Debug] Batch acquisition of 0 triggers
[Debug] Batch acquisition of 0 triggers
[Debug] Batch acquisition of 0 triggers
[Debug] Batch acquisition of 1 triggers
[Debug] Batch acquisition of 0 triggers
[Debug] Calling Execute on job Jellyfin.IJellyfinEpisodeSync
[Debug] Trigger instruction : DeleteTrigger
[Debug] Deleting trigger
[Debug] Batch acquisition of 0 triggers
[Debug] Batch acquisition of 0 triggers
[Debug] Batch acquisition of 0 triggers
[Debug] Batch acquisition of 0 triggers
[Debug] Batch acquisition of 0 triggers
[Debug] Batch acquisition of 0 triggers
[Debug] Batch acquisition of 1 triggers
[Debug] Batch acquisition of 0 triggers
[Debug] Calling Execute on job Plex.IPlexContentSyncRecentlyAdded
[Debug] Batch acquisition of 0 triggers
[Debug] Trigger instruction : NoInstruction
[Debug] Batch acquisition of 1 triggers
[Debug] Batch acquisition of 0 triggers
[Debug] Calling Execute on job Plex.IPlexAvailabilityChecker
[Debug] Batch acquisition of 0 triggers
[Debug] Batch acquisition of 1 triggers
[Debug] Batch acquisition of 0 triggers
[Debug] Calling Execute on job Notifications.INotificationService
[Debug] Trigger instruction : DeleteTrigger
[Debug] Deleting trigger
[Debug] Trigger instruction : DeleteTrigger
[Debug] Deleting trigger
[Debug] Batch acquisition of 0 triggers
[Debug] Batch acquisition of 0 triggers
[Debug] Batch acquisition of 0 triggers
[Debug] Batch acquisition of 0 triggers
[Debug] Batch acquisition of 0 triggers
[Debug] Batch acquisition of 0 triggers
[Debug] Batch acquisition of 0 triggers
[Debug] Batch acquisition of 1 triggers
[Debug] Batch acquisition of 1 triggers
[Debug] Batch acquisition of 0 triggers
[Debug] Calling Execute on job Emby.IEmbyContentSync
[Debug] Calling Execute on job Jellyfin.IJellyfinContentSync
[Debug] Trigger instruction : NoInstruction
[Debug] Batch acquisition of 0 triggers
[Debug] Batch acquisition of 0 triggers
[Debug] Batch acquisition of 0 triggers
[Debug] Batch acquisition of 0 triggers
[Debug] Batch acquisition of 0 triggers
[Debug] Batch acquisition of 0 triggers
[Debug] Batch acquisition of 0 triggers
[Debug] Batch acquisition of 0 triggers
`

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 10 (buster)

**Ombi Version (please complete the following information):**
 - Version: 4.0.1449
- Media Server: Jellyfin Version: 10.7.2 / Operating System: Linux / Architecture: X64
- Database Type: SQLite

**Additional context**
Not sure if this is the same with Emby, either standalone or in combo or if it affects any one of the 3.

**Comment by psi5asp** [comment]
The above were imported from existing libraries

This one was a completed request from Ombi - I am unable to check if import Vs completed requests is a factor (too many to check).

![image](https://user-images.githubusercontent.com/41772110/127103636-8fdbf4a5-ad4d-4165-bac7-2a0081fd9335.png)

**Comment by tidusjar** [comment]
I'm curious to what happens when Plex is disabled. Ombi is not really designed to have multiple different media servers enabled. 

Can you disable Plex and delete your ombi external.db and restart ombi and kickk off the jellyfin sync?

**Comment by psi5asp** [comment]
There's good reasons to use more than 1 media server these days, esp with 4k/8k shared transcoding/playing etc. server loads, etc. I presumed Ombi just treats each media server separatly, since they scrape separately and Ombi DB has seperate tables for each with the correct info. Also the webpage seems to handle them fine, with separate buttons.

This issue is unrelated to multi-media server setups, since it still exists even with an isolated Jellyfin (I disabled Plex, removed OmbiExternal.db, rebooted, rescanned, etc) and got the same results except without the Plex buttons now.

- Jellyfin Server entry (same):

![image](https://user-images.githubusercontent.com/41772110/127143614-d90aecf8-a57b-48ad-8226-10bf1d93f095.png)

- Found in Ombi DB after scrape/import

![image](https://user-images.githubusercontent.com/41772110/127143740-c0802a97-bc34-4282-ab69-191065f2e115.png)

- Still no Jellyfin Launcher in Ombi page
![image](https://user-images.githubusercontent.com/41772110/127143901-23bb3eab-66ba-48b4-9fdd-f8ba73a79186.png)


- This one still worked though:
![image](https://user-images.githubusercontent.com/41772110/127143988-54b069d9-2fd9-4f5c-a613-868c0b7bbe76.png)

Note: The Ombi DB for it has 2 entries (because there are 2 versions in Jellyfin - this is deliberate) ....it appears to be related...the Ombi Jellyfin Button is using the highlighted entry since the launch button goes to http:......./web/index.html#!/details?id=**7a4f84af09af3d9cadcddec2649c2841**&serverId=**serverID**

![image](https://user-images.githubusercontent.com/41772110/127145672-f9f08acd-c59c-45f7-a110-9d7edd7e9db5.png)

- Here is another entry that has multiple Jellyin Server versions of the same media - seems to work:

![image](https://user-images.githubusercontent.com/41772110/127146307-40fac938-8a08-40c3-8de7-b9a1e990729c.png)

Note: Ombi Jellyfin Launch button goes to: http://log.onmypc.org:8096/web/index.html#!/details?id=1228fcf3ba6703e14f495719f87d0f71&serverId=**serverID** 

- OmbiDB has:
![image](https://user-images.githubusercontent.com/41772110/127146544-027d14f7-ffe8-40dd-86f3-5e3afa25de83.png)


- Here are single Jellyfin server entries which ave no Ombi Jellyfin launch buttons:

![image](https://user-images.githubusercontent.com/41772110/127146665-f2149e67-a8a1-48c8-8185-b9829e5d8c7e.png)

![image](https://user-images.githubusercontent.com/41772110/127146741-990399d3-14e1-4be6-b502-153859086ad9.png)

![image](https://user-images.githubusercontent.com/41772110/127146799-41410d62-c6fa-4d85-bba4-6f725d21493c.png)


These are all impoted/scapeed/scanned in, no manual 'approvals' done.

**Comment by psi5asp** [comment]
Strange how the webpage does put the Jellyin Launch Button for single Jellyfin server movies/videos, and that multiple versions of the same title do.

Ombi should reognize single movie entries in Jellyfin server, and display the Jellyfin Launch button for that entry. If mulitple versions exist, then perhaps a simple drop-down to click on the relevant version can eventually be implemented - for now, the bug of missing button needs to be fixed first

**Comment by tidusjar** [comment]
Interesting, mind sending me your ombiexternal.db to tidusjar@gmail.com so I can see what’s going on?

**Comment by psi5asp** [comment]
Sent with an example library and a list from Jellyfin server for the examples to check with.

**Comment by psi5asp** [comment]
Appears to be an issue with Jellyfin - I've raised it with them https://github.com/jellyfin/jellyfin/issues/6363

**Comment by tidusjar** [comment]
We have worked out that your metadata in jellyfin is currently incorrectly mapped

**Comment by psi5asp** [comment]
Raised a Jellyfin issue with Jellyfin (i don't expect it to be fixed soon with their 490+ already outstanding)

**Comment by tidusjar** [comment]
Closing this due to not an ombi issue

**Comment by whiteowl3** [comment]
In what way was the metadata incorrectly mapped? I am having issues getting ombi to update availability from jellyfin and suspect an issue.  Id like to rule out this incorrect metadata mapping.

**Comment by tidusjar** [comment]
Basically for some content there was no TheMovieDb IIRC or it was that some movies had incorrect TheMovieDbIds
