### ISSUE TITLE
Mobile App notifications not applied on toggle on

### ISSUE THREAD

**Issue by BeerCrisp** [Ombi-app/Ombi#4276]
**Describe the bug**
When attempting to turn on notifications for the Ombi mobile app, the setting does not apply on the submit button. Notification works when testing via Send Notification button, but toggle on does not stay applied.

**To Reproduce**
1. Go to Settings
2. Click on Notifications
3. Click on Mobile
4. Toggle mobile user to on to receive mobile notifications
5. Click Submit
6. Leave this setting and return
7. Toggle will now have returned to off

**Expected behavior**
Toggle should stay in the on position for mobile users when submitting the setting, thus receiving notifications via mobile app for specific events.

**Screenshots**
![image](https://user-images.githubusercontent.com/41827132/127592830-db78e150-c23a-494e-831d-176fc14cb829.png)
![image](https://user-images.githubusercontent.com/41827132/127592737-af59984c-00e6-470e-88c6-8ab3edd73db4.png)
*usernames removed from screenshots
Toggle > Submit > Exit > Back to screen with no toggle applied

**Logs (Logs directory where Ombi is located)**
N/A

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Ombi Version (please complete the following information):**
 - Version: 4.0.1458
- Media Server: Plex
- Database Type: SQLite

**Additional context**
N/A

**Comment by tidusjar** [comment]
That's not a toggle to turn it in and off. The UI is really bad on that page and it's not clear. 

That's to send. Test message to the users selected. Mobile notifications is always enabled

**Comment by BeerCrisp** [comment]
> That's not a toggle to turn it in and off. The UI is really bad on that page and it's not clear.
> 
> That's to send. Test message to the users selected. Mobile notifications is always enabled

Ah okay, so as an admin if I want to receive a notification when a user requests something how do I make that happen? I currently have auto approve movie / auto approve tv on for all users. But still want visibility when someone requests something.

**Comment by BeerCrisp** [comment]
> > That's not a toggle to turn it in and off. The UI is really bad on that page and it's not clear.
> > That's to send. Test message to the users selected. Mobile notifications is always enabled
> 
> Ah okay, so as an admin if I want to receive a notification when a user requests something how do I make that happen? I currently have auto approve movie / auto approve tv on for all users. But still want visibility when someone requests something.

Hey @tidusjar, just following this one up. Is there a way for me to receive notifications when my other users request movies / tv? Thanks!

**Comment by tidusjar** [comment]
Sorry didn't see these message.

You should get notifications when your users request things if they are regular users, if they are admins then no notifications will be sent.

**Comment by BeerCrisp** [comment]
> Sorry didn't see these message.
> 
> You should get notifications when your users request things if they are regular users, if they are admins then no notifications will be sent.

@tidusjar hmm, I have tested with my partner requesting, she is a regular user with Request Tv, Request Movie, Auto Approve Tv and Auto Approve Movie turned on. 

In my notifications settings I have New Request and Request Approved enabled. Wasn't working through mobile app notifications so I enabled Discord but still no luck with receiving a notification when she requests something.

**Comment by tidusjar** [comment]
Under the Ombi Settings, do you have this enabled?
![image](https://user-images.githubusercontent.com/6642220/128017636-99e764cd-5b8d-449d-af64-791c3153f5df.png)

**Comment by BeerCrisp** [comment]
> Under the Ombi Settings, do you have this enabled?
> ![image](https://user-images.githubusercontent.com/6642220/128017636-99e764cd-5b8d-449d-af64-791c3153f5df.png)

@tidusjar amazing, sorry had never noticed that setting, fixed the issues thanks a lot! 

While I have you I did have one more issue. When managing users and selecting the sonarr / radarr quality profiles and root folders I was having a play around and selected some, though unable to change them back to blank. Reason I would want them blank just so I can alter the quality profile / root folder in the overarching radarr / sonarr settings and all users adopt that one. This is how I had it previouslty but can't change back without having to delete and recreate the user.
