### ISSUE TITLE
Failing to recognise TV Shows that exist in Media Server(s) - Plex

### ISSUE THREAD

**Issue by ghost** [Ombi-app/Ombi#4277]
**Describe the bug**
There are several TV Shows that Ombi does not pickup or recognise from Plex. See examples list at the botton.

 It appears that 
1) Ombi webpage does not display the TV Show properly - It appears to use IMDB ID's (or TheMovieDB ID's) to get the Poster and Cast/Crew list, so 
2) If OmbDB **does not have** an IMDb ID from Plex shows, then it cannot use IMDB for them, and if the MovieDB does not have the info, then if fails to display them. 
3) The Ombi webpage also does not seem to recognise these as "Available" (nor launchable) on the Ombi webpage, even though Plex has them and (more importantly) the Ombi DB (for PlexContent) has the Plex URL to launch them (ie Ombi DB recognises they exist in Plex even though IMDB does not exist in Ombi DB for them.....yet alternatives references TMDb ID and/or TVDbID exist).

**To Reproduce**
Steps to reproduce the behavior for 1) above:
1. Search in Ombi for any of the listed TV Show examples (see below)
2. Click on the TV Show to view it
2. See issues - no Poster and no Cast list, etc.

Steps to reproduce the behavior for 2) above:
1. Ensure Plex has any of the listed TV Show examples (see below)
2. Search in Ombi for any of these examples
3. Click on the TV Show to view it
4. See issues - no 'Avaiable' status nor Plex Launch button

**Expected behavior**
For 1) Ombi webpage should use the other resource ID's as fall-backs if Ombi does not have the IMDb ID's and/or the soruces do not contain any conent (eg no image, no cast list, etc.). So if OmbiDB has NULL for IMDb ID, then Ombi should check for for alternatives, and once found, get data from that source  - if data is missing, then try alternative source.

For 2) & 3) Not sure how Ombi webpage identifies media that exists, however it should have a "Available " status if the entry exists in Ombi DB (matched with a fall-back method to existing Ombi DB ID sources) AND if a URL exists in Ombi DB for it, have a "Launch" button (eg If URL != "" the display the launch button for this media server with the URL to launch with).

This should be the same fall-back method, availability check and button launch for Emby and Jellyfin OmbiDB entries as well.

**Screenshots**
- Example: **Countryfile Spring Diaries** in Plex:
![image](https://user-images.githubusercontent.com/41772110/127726775-bcfdc003-793b-46ef-8912-a9e1e4c112b9.png)

- IMDB = No ID exists
![image](https://user-images.githubusercontent.com/41772110/127727009-47be27b3-115e-43f9-96ae-3cede394efcf.png)

- OmbiDB entry missing IMDB, but still has TVDBID and TheMovieDB ID WITH the Plex URL 
![image](https://user-images.githubusercontent.com/41772110/127726934-3353fed7-8ccc-4c53-a084-6a0df9011d71.png)

- TVDB entry exists, and OmbiDB has the correct TVDB ID for it:
![image](https://user-images.githubusercontent.com/41772110/127727197-ef326c4e-d465-4223-8a24-9e787678755a.png)

- TheMovieDB entry exists, and OmbiDB has the correct TheMovieDB ID for it:
![image](https://user-images.githubusercontent.com/41772110/127727242-3ed2a722-21f1-4a91-acb3-0a342cdec75a.png)

- Ombi Webpage issue exists, both for un-sourced image + crew details (which exist in TVBb source), and does not recognise its available/launchable (Plex URL exists correctly in the OmbiDB to launch with).
![image](https://user-images.githubusercontent.com/41772110/127726970-af633bd8-d18c-4fcd-92b3-99eb87c7f592.png)

Clearly a Ombi Webpage issue, since the OmbiDB has the correct and usable data.

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 10 (buster)

**Ombi Version (please complete the following information):**
 - Version: 4.0.1458 
- Media Server: Plex + Jellyfin
- Database Type: SQLite

**Additional context**
This is the same for each one of these: 
[Ombi-4277-examples.txt](https://github.com/Ombi-app/Ombi/files/6910596/Ombi-4277-examples.txt)

**Comment by psi5asp** [comment]
For the latter issue of missing Launch buttons, to keep things simple I would suggest if the Ombi DB has a URL for the entry, then it should automatically display the appropriate Launch button on the webpage for it.

eg 
If Ombi DB `PlexServerContent `table has `Url `entry, then enabled the "Launch in Plex" button for that item on the webpage

If Ombi DB `EmbyContent` table has a `Url `entry for an item, then enable the "Launch in Emby" button for that item on the webpage.

If Ombi DB `JellyfinContent` table has a `Url` entry for an item, then enable the "Launch in Jellyfin" button for that item on teh webpage.

This method ensures a launch button exists if those items identified in the DB that match the Website search.

This method can also be used to launch any other media in a web-app automatically, like music, etc. if the URL exists in the Ombi DB.

Then the focus can be on how Ombi webpage identifies/matches the DB to the online sources, instead of the follow-on issues such as launching, etc.

**Comment by tidusjar** [comment]
Looks like it’s a matching issue on the ombi end. Can you please send me your ombiexternal.db to tidusjar@gmail.com and I’ll take a look.

**Comment by joe-eklund** [comment]
I noticed today I was having an issue where some shows weren't appearing in Ombi that were available in Plex. I ran a manual full sync and that seemed to fix it for me at least. Not quite sure if it's the same issue in original post though.
