### ISSUE TITLE
Unable to change directory of requests. 

### ISSUE THREAD

**Issue by jimski427** [Ombi-app/Ombi#4280]
**Describe the bug**
While using that app, if I receive a new request, it allows me to go in and adjust the settings and tell it which radarr/sonarr folder I want them to go into. However when I approve the request it puts them in the wrong folder. I've tried clearing app cache, clearing data and logging back in and it's still doing the same thing. I can log into ombi on chrome on my phone and follow the same process and it works as it should

**To Reproduce**
1. Go to mobile app
2. Click on requests
3. Click on option in top right corner to change the directory (already has directory auto filled)
4. Select directory you want movie to go into
5. Approve request.
6. Movie goes to incorrect folder 

**Expected behavior**
Same as website where you can manually direct movies to specific folders. 

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: android 11

**Ombi Version (please complete the following information):**
 - Version 4.0.1449
- Media Server plex
- Database Type: SQLite (Please change if using MySQL)

**Additional context**

**Comment by tidusjar** [comment]
Thanks for the report, i'll take a look

**Comment by tidusjar** [comment]
Looks like setting the quality is fine!

I'll get it fixed for the next update (2.2.27)

**Comment by tidusjar** [comment]
Ok fixed now. Will be in the next update

**Comment by tidusjar** [comment]
Update,

This has made it into the 2.3.0 release which is rolling out now for Android and in review for iOS
