### ISSUE TITLE
Poster Display Size issue with 1-2 selections left in Discovery menu.

### ISSUE THREAD

**Issue by ghost** [Ombi-app/Ombi#4282]
**Describe the bug**
Webpage displays extremely large poster when (it appears to be) only 1-2 popular (movies) exists.

**To Reproduce**
1. Ensure all but 1 popular movie is available
2. Ensure Ombi has "Hide Available" switched on 
3. Go do the "Discover" section
4. See the issue.

**Expected behavior**
Ombi should keep the poster size regardless of how many are listed (even if only 1)

**Screenshots**
- Example using Opera browser, with only 2 popular movies listed.
![image](https://user-images.githubusercontent.com/41772110/127897333-d2570eb1-2aba-48ef-aa36-43a580369581.png)

- Example using Edge:
![image](https://user-images.githubusercontent.com/41772110/127897454-91445b2c-b7b8-498c-bd68-1e21c220e4aa.png)

- Proper display (combined has more to show):
![image](https://user-images.githubusercontent.com/41772110/127897585-fe82906e-57f0-46b4-9552-20ea89216d89.png)

- but when going back even bigger 1 poster only:
![image](https://user-images.githubusercontent.com/41772110/127897671-59f768d7-2d0e-47a0-a05e-60d2115f18a5.png)

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 10 (buster)

**Ombi Version (please complete the following information):**
 - Version: 4.0.1458
- Media Server [e.g. Plex]
- Database Type: SQLite

**Additional context**
Using Opera and Edge browsers

https://streamable.com/z7431z

**Comment by tidusjar** [comment]
This should have been resolved a while ago now, apologies for not updating you
