### ISSUE TITLE
TV Show Posters Not showing with one exception

### ISSUE THREAD

**Issue by jennec** [Ombi-app/Ombi#4284]
**Describe the bug**
TV Show Posters do not appear in the Discovery Page for Popular, Tending, Upcoming, or when viewed with Combined.
When viewing a TV Show (Small pop up window) from any of the pages mentioned the poster does not show.
The Poster and background do show up when viewing TV show Details page indicating the data is there.
No Add blockers or plugins are installed.
Same results happend regardss off which network I browse these pages from.

**To Reproduce**
Steps to reproduce the behavior: Click on any of the pages in described above.

**Expected behavior**
Posters should show up.

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Not sure what you want here? The OS of where Ombi is installed or the client viewing the pages?

**Ombi Version (please complete the following information):**
 - Version 4.0.489.0
- Media Server N/A
- Database Type: SQLite

**Additional context**

**Comment by tidusjar** [comment]
Can you please attach some screenshots? 

Are there any errors in your browser console? F12.

If so can you press the network tab and then refresh the page and you should see something like
![image](https://cloud.githubusercontent.com/assets/6642220/23088047/eac44abc-f570-11e6-9f23-d2eb022ed059.png)


If you click the red text and then the preview tab like the image above and post the result?

Does this also happen on app.ombi.io for you?

**Comment by jennec** [comment]
I did what you asked and I thknkI see the issue.  There is a typo inthe call to stati.tvmaze.com.  Too many S's in HTTPS.

![image](https://user-images.githubusercontent.com/4245161/128016287-30882f85-5f08-458a-a349-c2020b0a38c6.png)

**Comment by tidusjar** [comment]
Oh man you are very very behind. Please update

**Comment by jennec** [comment]
Oh.  I didn;t realise that becasue the "Check for update" button tells me I am on the latest version.

**Comment by jennec** [comment]
Ah, I see the update process is broken.  I'll use the script and retest.
