### ISSUE TITLE
Mobile landing page is broken

### ISSUE THREAD

**Issue by neldonado** [Ombi-app/Ombi#4285]
**Describe the bug**
When I go to Ombi.domain.com on a mobile device the landing page does not scale properly. I tried this on an iPhone 12, 11, and 8+ with the same results. 

**To Reproduce**

Go to the landing page on a mobile device. 

**Expected behavior**
The landing page does not scale, and you can't see half of what you're typing

**Screenshots**
![image](https://user-images.githubusercontent.com/46225185/128528454-614fc462-c43e-44cc-b41d-23a5d6d62749.jpeg)

**Logs (Logs directory where Ombi is located)**

**Desktop (please complete the following information):**
 - OS: iOS14.7 and ios15 using Firefox and safari on all three.

**Ombi Version (please complete the following information):**
 - Version latest 
- Media Server plex
- Database Type: SQLite (Please change if using MySQL)

**Additional context**

**Comment by tidusjar** [comment]
Looks like your application name is pushing out the form... will take a look

**Comment by h3mmy** [comment]
I have the same thing except it's stuck on loading

**Comment by tidusjar** [comment]
@h3mmy sounds like a different issue. Mind raising something?

**Comment by twanariens** [comment]
Should have been fixed in the latest release of ombi V4.15.2
