### ISSUE TITLE
Play on Plex button not working

### ISSUE THREAD

**Issue by Archerofyail** [Ombi-app/Ombi#4289]
**Describe the bug**
If I click the Play on Plex button for movies in the web interface, it just says Not found 

**To Reproduce**
1. Go to a movie that you have available on Plex on Ombi's web interface
2. Click on the Play on Plex button
3. See that it says Not found

**Expected behavior**
1. Go to a movie that you have available on Plex on Ombi's web interface
2. Click on the Play on Plex button
3. The movie details page should show up and allow you to click play

**Screenshots**
![image](https://user-images.githubusercontent.com/2328899/129433244-26e1477e-752b-42bc-bd91-4199d6bd4474.png)

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Linux Manjaro

**Ombi Version (please complete the following information):**
 - Version 4.0.1430
- Media Server: Plex
- Database Type: SQLite

**Comment by tidusjar** [comment]
In your plex settings, is the machine identifier set?

**Comment by Archerofyail** [comment]
No, the Plex sign in on setup wasn't working, so I had to enter the details and grab the plex token manually, and I'm not sure where to find the machine identifier.

**Comment by tidusjar** [comment]
OK, 

if you have filled out the machine identifier now, press the Clear Data and Re-Sync button, all should work then

**Comment by maximelafarie** [comment]
@tidusjar same error as @Archerofyail, even after "Clear Data and Re-Sync" (version 4.22.5)

**Comment by bish0polis** [comment]
I'm seeing this on a simple web browser.  It may be bigger than we think
