### ISSUE TITLE
Can't get library from Plex even with successful connection

### ISSUE THREAD

**Issue by Alex-Goaga** [Ombi-app/Ombi#4294]
**Describe the bug**
Ombi doesn't display / communicate correctly with plex and doesn't display any content found on the server.

**To Reproduce**

**Prerequisites:**
Personally i run a proxmox server that has runs a VM with Ubuntu 20.04.2 LTS that has installed Plex. The content insite of plex is extracted via 2 synologys mapped via smb and the setup works well by its own.
Plex version : Version 1.23.0.4459 

( Side note : I just found about Ombi a few days ago and i gathered the infos from online docs so maybe i may forget something )

On Proxmox i created a lxc container, that runs on : Debian GNU/Linux 10 (buster), based on the image : debian-10-standard_10.7-1_amd64.tar

I've installed docker following this tutorial https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-debian-10

Docker installed via : 
docker run -d \
  --name=ombi \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/Bucharest \
  -p 80:3579 \
  -v /media/ombi:/config \
  --restart unless-stopped \
  ghcr.io/linuxserver/ombi:development

Run the initial setup with a local admin (not via the plex account)

**Actual STR:**

1. Go to settings , add a plex server via account, note that the server is found and the tokens are ready
2. Add your local ip and port
3. Test the connection (succes)
4. Load the libraries select your desires
5. Submit /save 
6. Run any button available in the right section

**Expected behavior**
I understand that i would be able to detect the media from plex or to be able to playit directy on via button "play on plex"

**Logs (Logs directory where Ombi is located)**
[OMBI.zip](https://github.com/Ombi-app/Ombi/files/7025756/OMBI.zip)

**Ombi Version (please complete the following information):**
 - Version latest 4.0.1466   
- Media Server  1.23.0.4459 
- Database Type: SQLite default on the server.

**Additional context**
On Plex logs i can see that Ombi is trying to get the metadata but nothing else happens or it doesn't call for the episodes lists

**What have i tried**
- Deleted several times the container
- Deleted the OmbiExternal.db as mentioned on some issues.
- Restarted the connections between plex and Ombi
- Tried to move the data to MySQL but Ombi fails to run afterwards.
- Tried to downgrade to the "latest" branch still nothing works for plex.
- Destroyed the home firewall for a better connection, still nothing

**What i can do to help**
- I can raise a VM (maybe a windows ) with anydesk / teamviewer and provide a ssh connection to server to give all the access required for devs for more info on the specific case.

Added logs via portainer : 
[ombi_logs_via_portainer.txt](https://github.com/Ombi-app/Ombi/files/7025809/ombi_logs_via_portainer.txt)

**Comment by tidusjar** [comment]
Something seems to have gone wrong with the syncing process, delete your OmbiExternal.db and restart Ombi, that should solve it

**Comment by Alex-Goaga** [comment]
As mentioned above, I already tried that, as your request i've tried the following : 
- While Ombi running, deleted the OmbiExternal.db file, restarted tried to sync, no results
- Stopping Ombi from portainer , deleted the OmbiExternal.db file, restarted tried to sync, no results

Also,
I've updated to the latest dev update 4.0.1468, done again the same steps , no results. same logs.

Any other ideas ?

**Comment by twanariens** [comment]
Are you still experiencing this issue with the latest release: V4.15.2?
Seems like your OmbiExternal.db is build without a necessary table (which should have been fixed in a later release)

**Comment by Alex-Goaga** [comment]
So...using ombi v4.15.4 for a while with a docker container seems to work well (except other random bugs). This issue does no longer occurs. Sorry for late reply
