### ISSUE TITLE
Unable to manage requests for music

### ISSUE THREAD

**Issue by TheCWB** [Ombi-app/Ombi#4302]
**Describe the bug**
Using ombi:development, one is unable to delete requests for music in any of the subcategories. This has been an issue for the last three or more updates. When one clicks options for TV or Movie requests, behavior functions normally. 

**To Reproduce**
1. Request any music
2. Go to Requests > Albums > All Requests
3. Select any requested item in the list > Options
4. The "Delete Request" does not show, but the box at the bottom of the screen tries to become viewable. 

**Expected behavior**
Option to Delete, Mark Approve, Mark Available

**Desktop (please complete the following information):**
 - OS: Windows 10, iOS, MacOS

**Ombi Version (please complete the following information):**
 - Version: 4.0.1466
- Media Server: Plex
- Database Type: SQLite

**Comment by danielyrovas** [comment]
I am also experiencing this issue, cannot manage music/album requests because the box is cutoff on the bottom of the screen.

**Comment by tidusjar** [comment]
I’m aware of the issue. Just not yet had the time to fix it

**Comment by PriamX** [comment]
Also experiencing this issue in 4.3.1 dev.

**Comment by nickuhlig** [comment]
also experiencing this issue on 4.3.2 dev

**Comment by tidusjar** [comment]
Yeah, that expected. I've not yet fixed the issue. Will fix it soon

**Comment by epfaffinger67** [comment]
@tidusjar 

I just downloaded and updated to the newest version 4.7.11 and the issue is still there. Movie and TV requests can be deleted but clicking options on an Album request does nothing and there is no option to delete the requests. Please prioritize this request and fix this bug.

Thanks

**Comment by tykkimies** [comment]
Just updated to latest version 4.35.10 and issue is still present.  The popup window for music requests when click options opens off screen and can't be seen.

**Comment by MintLily** [comment]
another bump?
Yeah, still not present.
