### ISSUE TITLE
[iOS] Keyboard colour scheme does not respect system dark mode option

### ISSUE THREAD

**Issue by SamuelBartik** [Ombi-app/Ombi#4306]
**Describe the bug**
The keyboard colour scheme is white, even if you have dark mode turned on in iOS settings.

**To Reproduce**
1. Set dark mode in iOS system settings.
2. Open Ombi
3. Tap on search icon
4. Tap into a text field to bring up keyboard

**Expected behavior**
The keyboard should be in dark mode, i.e. have dark colour scheme.

**Screenshots**
![github_issue](https://user-images.githubusercontent.com/63553146/131680457-5ce58db4-a737-4727-9fa1-36333d8af0b5.PNG)

**Logs (Logs directory where Ombi is located)**
None

**Desktop (please complete the following information):**
 - OS: iOS 15.0

**Ombi Version (please complete the following information):**
 - Version 2.2.26
- Media Server Jellyfin
- Database Type: SQLite

**Additional context**
None

**Comment by tidusjar** [comment]
Will be fixed in the next release (2.2.27)

**Comment by tidusjar** [comment]
Update,

This has made it into the 2.3.0 release which is rolling out now for Android and in review for iOS
