### ISSUE TITLE
E-mail address that’s manually updated is overwritten when user logs in again.

### ISSUE THREAD

**Issue by qosmio** [Ombi-app/Ombi#4309]
**Describe the bug**

When authentication is set to Plex for users to log in, they have to use their Plex login which is their email address. Problem is, updating a users email on Plex doesn’t change their login username which is the original email.

If I am to update a user’s email, it will get overwritten when they log into Ombi using Plex. I use the email address as the sole notification, and most of the accounts were “mytrashmail” Plex accounts I made for friends and family. They’ve updated their addresses within Plex, but that’s not accessible to Ombi (at least I think how the auth works) 

**Expected behavior**

The “email” address should be populated only on initial login, but if an admin updates it manually, it shouldn’t revert back.

**Ombi Version:**
 - Version :  4.0.1470 (Exists in both 3.0 and 4.0)

**Comment by tidusjar** [comment]
So just to be clear. They have Plex accounts with a bad email, it’s synced with Ombi, they have updated their email address and ombi is not picking up the new email?
