### ISSUE TITLE
Newsletter wrong poster and show info

### ISSUE THREAD

**Issue by dGstone18** [Ombi-app/Ombi#4368]
**Describe the bug**
The weekly newsletter shows an irrelevant poster and show info for one of my shows every week. Specifically it shows a Vice News Reports poster and info for the Doom Patrol show.

**To Reproduce**
Receive weekly newsletter. Clicking the show link directs to a IMDB 404 link.

**Expected behavior**
Show the correct show poster and show data. Link to correct IMDB page.

**Screenshots**
![image](https://user-images.githubusercontent.com/29738423/138488231-6aa389e1-e1b7-4317-823b-99a50d9c63bf.png)

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome Browser

**Ombi Version (please complete the following information):**
 - Version 4.3.0
- Media Server Plex
- Database Type: SQLite 

**Additional context**

**Comment by twanariens** [comment]
Are you still experiencing this issue when you update to the latest version: V4.15.2?
