### ISSUE TITLE
Mass emails not sending correctly

### ISSUE THREAD

**Issue by kris6673** [Ombi-app/Ombi#4377]
**Describe the bug**
I am trying to send mass emails via Ombi, with a @hotmail.com account. I'm trying to send to around 10 people. However it only sends some of them, around 5 at a time. I can then check in my sent emails, that it has not sent to all users. If i send a mass email again, it goes through with 5 more people again. 
I think this is a rate limiting/throttling thing from MS. I have not tested other providers like gmail.
Adding a customizable wait time before sending each email would solve this i think, instead of trying to send all the emails at the same time. 

**To Reproduce**
1: Use Microsoft account for sending email.
2: Select more than 10 users/recipients.
3: Send mass email and check the sender acccounts "Sent" mail.
4: Deselect the users that you can see in the "Sent" mail.
5: Send mass mail. Repeat until no more users are left.

**Expected behavior**
The mass email to be sent to everyone selected.

**Screenshots**
None

**Logs (Logs directory where Ombi is located)**
From Logs dir:
[log-20211101.txt](https://github.com/Ombi-app/Ombi/files/7454724/log-20211101.txt)

Desktop (please complete the following information):

Ombi docker: Linux 5.10.28-Unraid SMP Wed Apr 7 08:23:18 PDT 2021
Ombi Version (please complete the following information):

Version: 4.0.1468
Media Server: Plex
Database Type: SQLite
Please feel free to ask me for additional information if required :)

**Comment by tidusjar** [comment]
Yeah looks like we opened too many connections. How many emails was it being sent to?

Concurrent connections limit exceeded. Visit https://aka.ms/concurrent_sending for more information. 

I think I’ll add some concurrency protection and also an option to send 1 email but all BCC’d too. What do you think?

**Comment by kris6673** [comment]
Thanks for the quick response! 
12 emails were being sent. Seems like 30 emails per minute is the limit for MS.

Sounds good to me, IMO having more options is (almost) always better! 👍
