### ISSUE TITLE
"Latest" release tag not updated to v4.3.2

### ISSUE THREAD

**Issue by Trisky** [Ombi-app/Ombi#4379]
**Describe the bug**
Latest tag in github is [4.0.1468](https://github.com/Ombi-app/Ombi/releases/tag/v4.0.1468)

This prevents the docker image from being updated, it's stuck with 4.0.1468. 
https://github.com/linuxserver/docker-ombi

4.3.x is released as ["pre-release" in github.](https://github.com/Ombi-app/Ombi/releases/tag/v4.3.2)
Is this correct?

**To Reproduce**
1. Go to Settings as admin
2. See installed version as 4.0.1468
3. See Update available notice to 4.3.2

**Expected behavior**
latest tag is applied to 4.3.2 so we can update through the docker image.

Please update the *latest* tag to 4.3.2 ? 

 - Version [e.g. 4.0.1468]

**Comment by tidusjar** [comment]
That’s correct. I’ve not yet pushed the develop branch to master. So you are on the latest build. I plan to push and update stable soon. 

If you want to be on later builds I suggest you use the develop tag

**Comment by Trisky** [comment]
ok, I was confused about what is actually "stable". Will stay on `latest` then.

Thanks!
