### ISSUE TITLE
Ombi shows update available while running latest version

### ISSUE THREAD

**Issue by jcastilloalonso** [Ombi-app/Ombi#4383]
**Describe the bug**
Updated to version 4.3.3 yet Ombi shows in settings page New version available. Upon clicking on it, it shows 4.3.2 as an update which would be incorrect.

**To Reproduce**
1. Update to version 4.3.3
2. Click on Settings
3. In About check Version and press New update Available
4. Check how it offers 4.3.2

**Expected behavior**
No update should be prompted if running latest version

**Screenshots**
![image](https://user-images.githubusercontent.com/37427692/140599774-491f42c4-7e52-43fc-994e-890d5002945d.png)
![image](https://user-images.githubusercontent.com/37427692/140599777-39cb12f7-0d93-49b0-8533-b3833a4ed1a4.png)

**Desktop (please complete the following information):**
 - OS: Linux CentOS 7

**Ombi Version (please complete the following information):**
 - Version 4.3.3
- Media Server Plex
- Database Type: SQLite

**Additional context**
I tried searching debug logs but couldn't find any calls for version check.

**Comment by tidusjar** [comment]
Under settings > general > Ombi. Change your branch
