### ISSUE TITLE
HTTP header Content-Security-Policy 'unsafe-inline'  breaks ombi | Regression

### ISSUE THREAD

**Issue by lord-carlos** [Ombi-app/Ombi#4385]
**Describe the bug**
Current version is broken when your proxy has 'unsafe-inline' as a Security Policy header.
`ERROR EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self' http: https: data: blob: 'unsafe-inline'".`

**To Reproduce**
1. Start latest ombi via docker linuxserver/ombi   latest   0f312e57126f
2. Secure your ombi with a reverse proxy and set CSP header to unsafe-inline
3. `add_header Content-Security-Policy "default-src 'self' http: https: data: blob: 'unsafe-inline'" always;`
4. Open ombi in a browser
5. Site does not fully load, open console and see:

```
ERROR EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self' http: https: data: blob: 'unsafe-inline'".

    at new Function (<anonymous>)
    at main-es2015.48a7d41e0186a00732af.js:1
    at main-es2015.48a7d41e0186a00732af.js:1
    at e (main-es2015.48a7d41e0186a00732af.js:1)
    at Object.getStateGetter (main-es2015.48a7d41e0186a00732af.js:1)
    at it.makeRootSelector (main-es2015.48a7d41e0186a00732af.js:1)
    at main-es2015.48a7d41e0186a00732af.js:1
    at Array.map (<anonymous>)
    at main-es2015.48a7d41e0186a00732af.js:1
    at s.makeRootSelector (main-es2015.48a7d41e0186a00732af.js:1)
```
```
        function Di(t, ...e) {
            t.error(...e)
        }
```

**Expected behavior**
Before a few days ago it worked just fine.
I would expect it to work even with a tighter CSP directive.

**Desktop (please complete the following information):**
 - OS: Client is Windows. But any browser that follows CSP should be affected.

**Ombi Version (please complete the following information):**
 - Sadly I'm not sure. 
 - Docker image:  linuxserver/ombi   latest   0f312e57126f

**Comment by coolyves** [comment]
I have a similar Problem and i think you have this too.
we don't have the "unsafe-eval" in our Content-Security-Policy. When i put this in then its working normal. 
Ombi needs in my case both "unsafe-eval" and "unsafe-inline"

**Comment by tidusjar** [comment]
Is anyone able to pinpoint what version did work and what version broke it?

**Comment by coolyves** [comment]
Sorry I can't really say because I don't use ombi myself often last time someone requested something was on 20th of October. I update my docker (linuxserver.io:latest) automatically and I am now on 4.3.3.

**Comment by tidusjar** [comment]
You sure? Because I broke the proxy on 4.2.5 :/

**Comment by lord-carlos** [comment]
Settings/About says Version 4.2.5
It could be any dependency that has javascript as a string, no? I'm not super into web development.

**Comment by Anthony-Mariotti** [comment]
I have a similar issue when I was setting up my CSP. Version: `lscr.io/linuxserver/ombi:4.9.0-development`

I'm not sure the value specifically of this, but after removing the 'unsafe-inline' from my CSP this is what I came to.

---

[src/Ombi/ClientApp/src/index.html](https://github.com/Ombi-app/Ombi/blame/efe7845dcd2e64070f7ed9d2410c53c0069f9909/src/Ombi/ClientApp/src/index.html#L5)
```
<script type='text/javascript'>window["baseHref"] = '/';</script>
```
This violates `script-src-elem` which defaults back to `default-src` if not set.

---

There are two other immediate CSP errors. I believe these correlate to something being generated.

```
<link rel="stylesheet" href="styles.8fbf4a93d83e0d157368.css" media="print" onload="this.media='all'">
<link rel="stylesheet" href="main.eee26957b4914486ec6e.css" media="print" onload="this.media='all'">
```
Specficially: **onload="this.media='all'"**

This violates `script-src-attr` which defaults back to `default-src` if not set.

---
Policy Snippet (Working):
```
default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'
```

Policy Snippet (Broken):
```
default-src 'self'; script-src 'self'
```

Specific Policy Snippet (Working):
```
default-src 'self'; script-src 'self' 'unsafe-eval'; script-src-elem 'self' 'unsafe-inline'; script-src-attr 'self' 'unsafe-inline'
```

**Comment by coolyves** [comment]
I have now Updated to 4.10.2 and it still doesn't work. 
Is the unsafe-eval and unsafe-inline now required? 

Thanks

**Comment by tidusjar** [comment]
This seems to be a change on the angular side since upgrading. I’ve not had much time to look into this yet as it’s not really at the top priority. I know why this is happening and it’s a workaround I had needed to put in place to get the base url working with the angular front end and the backend. 

For now I’d say this is required. But that could potentially change in the future.
