### ISSUE TITLE
Plex OAuth not working

### ISSUE THREAD

**Issue by SavageAUS** [Ombi-app/Ombi#4396]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**

**Ombi Version (please complete the following information):**
 - Version [e.g. 4.0.958]
- Media Server [e.g. Plex]
- Database Type: SQLite (Please change if using MySQL)

**Additional context**

iPhone 12 iOS 15.0.1
Ombi does not allow me to press the Plex oauth button. Can only login with normal user credentials.

**Comment by tidusjar** [comment]
The app or website? You've really skimped out on as much details as you can here.

Will reopen if you provide more information
