### ISSUE TITLE
Titles on the solicited list only appear in English

### ISSUE THREAD

**Issue by vsc55** [Ombi-app/Ombi#4404]
**Describe the bug**
If we have configured another language such as Spanish, the titles in the requests section appear in English, it does not use the title in Spanish. 

**To Reproduce**
1. Go to Requests List
2. See list

**Expected behavior**
That the titles appear in the list according to the language that we have configured. 
For example, instead of appearing "Venom: Let There Be Carnage (2021)" which is the title in English, appears "Venom: Habrá Matanza" which is the version of the title in Spanish. 

**Screenshots**
![imagen](https://user-images.githubusercontent.com/13438676/141661506-d5006b0d-4d9c-4f86-a4a0-b0bf09386a86.png)

**Ombi Version (please complete the following information):**
 - Version 4.6.4
- Database Type: MySQL

**Comment by tidusjar** [comment]
When this was requested. What language were you in?

**Comment by vsc55** [comment]
Hi @tidusjar,
The language that I had configured is Spanish.
What I have seen is that in several movies this happens, in the "MovieRequests" table the "LangCode" column is defined as a null value.
I have delete the request and create it again and now the column "LangCode" already says "ES" and the title appears correctly.

**Comment by tidusjar** [comment]
No that's not something I want to do. But what we can do is just re lookup the title.

**Comment by sephrat** [comment]
> The problem is that when adding the movie, sometimes the title is only in English. Over time the title already appears in Spanish. Is there a way to create a task that every X time reviews and updates the data, or to create a button to force the update of the data?

What you see is my recent PR https://github.com/Ombi-app/Ombi/pull/4366 doing its job . I suppose your English requests were created in a prior version. Requests are now saved in the dabatase in the language of the user that requested it. I agree with TJ that it's not great, but considering that the user base of one server speaks the same language I believed it to be a quick win and better that the previous solution which defaulted to English.
