### ISSUE TITLE
Plex login redirecting back to Ombi login page

### ISSUE THREAD

**Issue by sebinemeth** [Ombi-app/Ombi#4408]
**Describe the bug**
I am having an issue with the Plex login (kind of the same as #3256 but Plex does not seem to be the problem). When I click on the `Login with Plex` option, the popup is showing the same Ombi login screen (https://ombi.remetelak.com/login/true), not the Plex authentication page. Clicking on the button again opens another popup window and so on. The only error message I could spot was shown on the console of the main window at the moment of clicking the button (the same happens in the popups if clicking the button):

```
ERROR TypeError: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': String contains non ISO-8859-1 code point.
    at main-es2015.e7356ac3ac8b71f9eb18.js:1
    at main-es2015.e7356ac3ac8b71f9eb18.js:1
    at Array.forEach (<anonymous>)
    at d.forEach (main-es2015.e7356ac3ac8b71f9eb18.js:1)
    at t._subscribe (main-es2015.e7356ac3ac8b71f9eb18.js:1)
    at t._trySubscribe (main-es2015.e7356ac3ac8b71f9eb18.js:1)
    at main-es2015.e7356ac3ac8b71f9eb18.js:1
    at s (main-es2015.e7356ac3ac8b71f9eb18.js:1)
    at t.subscribe (main-es2015.e7356ac3ac8b71f9eb18.js:1)
    at main-es2015.e7356ac3ac8b71f9eb18.js:1
```

**To Reproduce**
1. Open login screen
2. Click on `Login with Plex`
3. Popup shows same login screen

**Expected behavior**
Popup should be redirected to Plex authentication page. 

**Screenshots**
-- no additional info in screenshots --

**Logs (Logs directory where Ombi is located)**
Not applicable 

**Desktop (please complete the following information):**
 - OS: MacOS, Android, Win10
 - Browser: Chrome, Firefox

**Ombi Version (please complete the following information):**
 - Version: 4.6.4 develop
- Media Server: Plex
- Database Type: SQLite

**Additional context**
Docker setup (linuxserver/ombi:development), traefik reverse proxy.

**Comment by tidusjar** [comment]
What happens when you do it locally and not through your reverse proxy?

**Comment by sebinemeth** [comment]
> What happens when you do it locally and not through your reverse proxy?

The same thing, the popup keeps redrecting to `<ip>:<port>/login/true`

**Comment by tidusjar** [comment]
And what's In the console of the main browser and the tab ?

**Comment by sebinemeth** [comment]
> And what's In the console of the main browser and the tab ?

The console of the main tab shows the error that I pasted above, the console of the popup tab is empty...

**Comment by tidusjar** [comment]
what's your browsers language set to?

**Comment by sebinemeth** [comment]
> what's your browsers language set to?
Hungarian, so that could be the issue.
Thanks for the fix @tidusjar, is it already on `developer`? I updated to `4.7.8` but the issue is still present...

**Comment by sebinemeth** [comment]
If the problem really is the charset then ISO-8859-1 will still have issues with some characters in Hungarian (ő, ű, etc.). As far as I know [ISO-8859-2](https://en.wikipedia.org/wiki/ISO/IEC_8859-2) (Latin-2) would work for these, but an unicode charset would be even better.

**Comment by tidusjar** [comment]
Can you change your language to English for example. Does it then work for you?

**Comment by sebinemeth** [comment]
I tried to set the browser and ombi app language to english, same behavior...

**Comment by tidusjar** [comment]
Whats your Ombi application Name set to (if you have a custom one?) in Customization Settings

**Comment by sebinemeth** [comment]
Okay, that was it. I had a Unicode bullet in my application name (•, `U+2022`), removing that it works! I can live without that symbol, but still, it would be nice to support Unicode or at least Latin-2. @tidusjar thanks for the support!

**Comment by tidusjar** [comment]
I don't think that's in my control in that case. That's Plex rejecting the HTTP call due to it containing unicode. The only thing I can do is disallow any unicode characters in the Application Name in that case
