### ISSUE TITLE
Android App - Wrong Server Version

### ISSUE THREAD

**Issue by djarbz** [Ombi-app/Ombi#4411]
**Describe the bug**
I recently got a new phone and installed the latest version of the mobile app (2.7.0).
When I enter the URL for my instance or if I use the QR code I get a message stating that I have a wrong server version.
I am currently running v4.3.3, I have also tried v4.4.0.

**To Reproduce**
1. Open app
2. Scan QR Code
3. See Wrong Server Version error

**Expected behavior**
The app should connect to my instance of Ombi

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.
No logs available

**Desktop (please complete the following information):**
 - OS: Android

**Ombi Version (please complete the following information):**
 - Version 4.3.3 & 4.4.0
- Media Server Plex
- Database Type: SQLite

**Additional context**

**Comment by tidusjar** [comment]
Can you please email me (tidusjar@gmail.com) or PM me on discord your ombi url and I’ll take a look what’s going on

**Comment by tidusjar** [comment]
Issue was due to you had Ombi behind Google auth
