### ISSUE TITLE
How to use Ombi with 2FA Plex?

### ISSUE THREAD

**Issue by Massaguana** [Ombi-app/Ombi#4416]
**Describe the bug**
What is the correct way to Connect Ombi with an 2FA Plex Server?

**To Reproduce**

**Expected behavior**
What is the correct way to Connect Ombi with an 2FA Plex Server?

**Screenshots**
![image](https://user-images.githubusercontent.com/15521791/142879407-783448ca-d95b-403c-af66-f1f6e4d1c79a.png)

**Comment by tidusjar** [comment]
wow that takes me back. Please update your Ombi, you are running on a build that's over a year old.
