### ISSUE TITLE
Requests keep getting added to retry queue, but tests come back fine

### ISSUE THREAD

**Issue by Jakesparrow** [Ombi-app/Ombi#4419]
**Describe the bug**
User requests a show, and 9/10 times it says it was unable to add, and it goes to the retry queue, and Sonarr never gets it. 
Connections to Sonarr are successful, and 1/10 times it works fine. 

**To Reproduce**
1. Have user sign in to Ombi
2. Have user request a TV show (Radarr is not having this issue)
3. Show goes to retry queue and does not get added to Sonarr.

**Expected behavior**
The Show to be added to Sonarr

**Screenshots**
![request](https://user-images.githubusercontent.com/17485169/143413624-05558437-6fb8-4df0-8516-eee2f2678a22.PNG)
![About](https://user-images.githubusercontent.com/17485169/143413625-96482831-bacd-4867-897b-bb989e51acb1.PNG)
![Error](https://user-images.githubusercontent.com/17485169/143413627-0a57a7ee-3623-426c-bbf7-dce06dc5713d.PNG)
**Logs (Logs directory where Ombi is located)**

[log-20211124.txt](https://github.com/Ombi-app/Ombi/files/7601697/log-20211124.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64, v19042

**Ombi Version (please complete the following in
 - Version 4.7.4
- Media Server Plex (Sonarr)
- Database Type: SQLite

**Additional context**

**Comment by sephrat** [comment]
Thanks for highlighting the "RequestedByOn" typo. I'll fix that.
As for your actual issue, it might be helpful to tell us what TV show you're trying to add.

**Comment by Jakesparrow** [comment]
Hey, thanks for the fast reply!

A great many, but some are listed in the screenshot (Although hard to see, possibly the dark font on dark mode? Not sure.)

Here are a handful of the more recent:
![Capture](https://user-images.githubusercontent.com/17485169/143416021-2cacc4f7-2c9d-4073-a50b-f67db8db2c67.PNG)

**Comment by tidusjar** [comment]
I think one of the exceptions is being masked here.

Can you ensure your root path/folders and quality profiles are correctly set in the Sonarr Settings in Ombi, and also ensure that if the user who requested has any quality/folders in the user management section, ensure that's also correct. It might be worth just setting them again in ombi and then give requesting something a go?
