### ISSUE TITLE
When editing a User profile wrong user name shows

### ISSUE THREAD

**Issue by moonpie2000** [Ombi-app/Ombi#4423]
**Describe the bug**
user name not correctly displaying when editing a user profile

**To Reproduce**
1. Select Users from main menu
2. Click Edit of a user
3. User name files shows correct user name momentarily but then refreshes with local Admin name

**Expected behavior**
U
![ombi users](https://user-images.githubusercontent.com/42495495/144080418-69828a80-9ba5-4f98-a3be-ef999bc99cf7.jpg)
![ombi donna profile](https://user-images.githubusercontent.com/42495495/144080423-6c1a8446-6464-4f4f-b9f3-b6e5e7a0acb7.jpg)
ser name to reflect user profile being edited

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.04

**Ombi Version (please complete the following information):**
 - Version [e.g. 4.7.5
- Media Server Plex
- Database Type: SQLite

**Additional context**
This has been happening for many versions

**Comment by tidusjar** [comment]
I can't seem to reproduce this. Is potentially your browsers autocomplete filling something in?

Can you try accessing Ombi directly and does it happen?
