### ISSUE TITLE
Power users should not be notified by email of an auto approval

### ISSUE THREAD

**Issue by sephrat** [Ombi-app/Ombi#4431]
**Describe the bug**
As an admin, I receive a "Request Approved" email notification when my own request is (automatically) approved. I believe this is unnecessary noise since there's no reason for my request to be denied given my rights.

**To Reproduce**
1. Setup email notifications for event "Request Approved" 
2. As an admin, request an item
3. You receive a notification stating that your request has been approved

**Expected behavior**
Automatic approvals should not trigger a notification to the user.

**Ombi Version:**
 - Version 4.7.6

**Comment by tidusjar** [comment]
Yeah you make a fair point. Marked as a bug

**Comment by sephrat** [comment]
Looking at the code, the issue seems to narrow down to TV notifications only. I'll work on a fix.
