### ISSUE TITLE
Incorrect admin email for auto-approved user requests

### ISSUE THREAD

**Issue by laur89** [Ombi-app/Ombi#4434]
**Describe the bug**
User w/ following roles made movie & tv request:
![image](https://user-images.githubusercontent.com/4551018/145694644-24c5d3e3-9690-44ae-a54e-1b6f8c551dc5.png)

Admin user email received following mail:
```Hello! The user 'username' has requested the Movie 'movie title'! Please log in to approve this request.```

**To Reproduce**
1. Create regular w/ roles as bolve
2. Request a title w/ said user
3. Verify request was auto-approved
4. Verify admin received email with abovementioned content

**Expected behavior**
Mail content should either indicate that the request was already approved, or not send the mail at all.

**Ombi Version (please complete the following information):**
 - Version 4.3.3, lsio docker image
- Database Type: SQLite

**Comment by tidusjar** [comment]
Settings > Configuration >  General >  Do not send Notifications if a User has the Auto Approve permission

I suggest you enable that

**Comment by laur89** [comment]
Thanks, didn't realize `General` was a clickable button 🤦🏻‍♂️
