### ISSUE TITLE
Not all episodes shown as available

### ISSUE THREAD

**Issue by Sir-Doyle** [Ombi-app/Ombi#4439]
**Describe the bug**
The episodes not showing available. I have 574 eps and Ombi only shows 77 available. to give you more details my series is One piece I have categories it as Saga (not season) in emby.

[Please see this screenshot (Link)](https://dsc.cloud/4f8deb/Screen-Shot-2021-12-15-at-1.02.34-PM.png)
[but in Ombi like this (Link)](https://dsc.cloud/4f8deb/Screen-Shot-2021-12-15-at-3.02.48-PM.png)

**To Reproduce**

In emby:
Create any anime tv folder (e.g. Naruto Shippuden)
Create Season 1
[Add all episodes or (more than the Ombi what said in that season, let's say 50 eps) in the above folder (Link)](https://dsc.cloud/4f8deb/Screen-Shot-2021-12-15-at-3.38.26-PM.png)

In Ombi:
[It will show only 32 eps as available ... it will not continue after 32 (link)](https://dsc.cloud/4f8deb/Screen-Shot-2021-12-15-at-3.40.41-PM.png)

**Ombi Version (please complete the following information):**
Ombi 4.7.8
Media Server: emby
Docker: hotio/ombi

**Comment by tidusjar** [comment]
Yeah, I think this is an issue with how TheMovieDb displays their anime shows vs TvDbId.

This is a bit outside of Ombi's control whilst we are using TheMovieDb for our metadata provider.
