### ISSUE TITLE
Duplicate notifications on iOS

### ISSUE THREAD

**Issue by eddyg** [Ombi-app/Ombi#4440]
I get two of every notification on my phone, even when using the manual "Send Notification" feature, as shown here:

![IMG_7256](https://user-images.githubusercontent.com/3235109/146280294-36dd10ec-ebe4-48b0-83b0-2218d6bcff27.jpg)

The only notifications I have enabled in Ombi are "Mobile".

No log entries are generated for notifications (including the manual one) that I can see.

**Mobile**
 - iOS 15.2
 - App version: 2.8.3

**Ombi Version**
 - Version 4.3.3
 - Database Type: SQLite

Any suggestions on how to debug this? I tried searching the open and closed issues here and in the docs, but didn't see anything.

Thanks!

**Comment by tidusjar** [comment]
Log out of the app and log back in, somehow it's registered your user twice
