### ISSUE TITLE
No options shown for Music requests

### ISSUE THREAD

**Issue by PriamX** [Ombi-app/Ombi#4442]
**Describe the bug**
An apparent UI issue. No options are shown for Music requests. They work for Movies and TV shows, but not for music. 

**To Reproduce**
1. Go to 'Requests/Music'
2. Click on 'Click on Options'
3. No options are shown at the bottom of the screen.

**Expected behavior**
It should show options for Music like it does for Movies and TV shows.

**Screenshots**
Example of it working under Movies:

![image](https://user-images.githubusercontent.com/43935458/146340360-67a13a92-ca60-4642-9b5c-011290a61da8.png)

Example of it not working under Music:

![image](https://user-images.githubusercontent.com/43935458/146340668-cd2b800b-2bd8-408e-be0c-e4c5701256ea.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 96.0.4664.93

**Ombi Version (please complete the following information):**
 - Version: Ombi 4.3.3 (current linuxserver.io docker container)
- Media Server: Plex 1.25.2.5319
- Database Type: SQLite

**Comment by lmsnxt** [comment]
Same issue here. Cannot clean up requests due to this issue. Auto removal of requests after music is available is not working either.

**Comment by tidusjar** [comment]
This was fixed in 3.4.0, this is in develop and has not yet been pushed to master

**Comment by PriamX** [comment]
Fixed verified. I pulled docker linuxserver/ombi:development (4.8.0) and it functioned as expected. Thank you for your help.
