### ISSUE TITLE
The Movie Database Excluded Keywords all show the same

### ISSUE THREAD

**Issue by troycarpenter** [Ombi-app/Ombi#4446]
**Describe the bug**
When I add keywords to the TMD exclusion list and save it, the next time I go into the the screen all the keywords are the same.

**To Reproduce**
1. Go to settings -> configuration -> the movie database
2. Type keywords in the excluded keyword list and select one.  Save.
3. Exit this screen and reenter
4. See all the keywords are now the same.

**Expected behavior**
I expect to see all the keywords I've entered

**Screenshots**
Screen shot as entered:
![ombi-1](https://user-images.githubusercontent.com/8419000/146587937-37866b69-c591-46ba-95ac-a0cad4692798.png)

Screenshot after going back in:
![ombi-2](https://user-images.githubusercontent.com/8419000/146588017-d391da62-e28f-4694-9cc7-83bb87324784.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Ombi Version (please complete the following information):**
 - Version 4.7.11
- Database Type: SQLite

**Comment by sephrat** [comment]
What exactly do you mean by "Exit this screen and reenter"? When I hit F5 it works fine for me with your keywords. It also works if I navigate to another page, then go back to the settings page.
![image](https://user-images.githubusercontent.com/34862846/160433092-ce9c2319-7f38-4148-91d1-547db1a53c79.png)

What browser are you on?

**Comment by sephrat** [comment]
I guess it's already been fixed in 4.11.8
 https://github.com/Ombi-app/Ombi/commit/d3b3316cbac18356b2f6b0912a3deb2c183e6534

**Comment by troycarpenter** [comment]
Yes, I don't see the issue any more with newer versions.

**Comment by troycarpenter** [comment]
Yes, I don't see the issue any more with newer versions.
