### ISSUE TITLE
v4.9.0 Can not see Request Lists via Reverse Proxy NGINX using a web browser

### ISSUE THREAD

**Issue by Zuluwarrior131** [Ombi-app/Ombi#4465]
**Describe the bug**
If I got directly to the server on port 5000 on my local network I can see the Requests lists for Movies and TVs and all pending, awaiting approval etc. Yet when I look at it via my reverse proxy server NGINX v1.14.1 running on Centos8 every thing works except the requests lists, they are blank and all of them. This has only just started since I upgraded to v4.9.0 but means I can not approve any requests via my phone or PC browser when outside my network. Strangely how ever the ombi iOS app on my phone still appears to be working ok.

**To Reproduce**
1. Go to OMBI.mydomain.com
2. Click on Requests TAB
3. Click on any Request list and they are blank

**Expected behavior**
I expected to see the list or requests I had approved in the past and any pending requests but they are blank.

**Screenshots**
![image](https://user-images.githubusercontent.com/61565564/149040816-8eac9001-c4bc-425b-ad72-2397a14c37e7.png).

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Windows 10 using Edge Browser and or Chrome

**Ombi Version (please complete the following information):**
 - Version 4.9.0
- Media Server Plex
- Database Type: SQLite (Please change if using MySQL)

**Additional context**
Every thing works fine on my local network if I go to http://ombi.mydomain.local:5000 and all lists show fine it just appear to not like reverse proxy if I go to https://ombi.mydomain.com then everything BUT the lists works but only on web browsers.

**Comment by sephrat** [comment]
How did you setup your reverse proxy? Have you checked the docs on how to set it up? https://docs.ombi.app/info/reverse-proxy/
Also, is there anything in your browser console or your reverse proxy log?

**Comment by Zuluwarrior131** [comment]
I have tried using both the "# Ombi v4 Subdomain" script as per https://docs.ombi.app/info/reverse-proxy/ and also a more simple section in my proxy.conf file that is just 
	server {
		listen	443 ssl;
		server_name ombi.mydomain.id.au;
		ssl on;

	location / {
		proxy_pass	http://websrv.mydomail.local:5000;
	}
    }
Naturally there is more to the script like 
   ssl_certificate /etc/pki/tls/certs/wildcard_mydomain.crt;
   ssl_certificate_key /etc/pki/tls/private/wildcard_mydomain.key;

however I get the same issue using either script, I have checked my NGINX "access.log" and can not see any obvious issues do you have anything you think I should look for like an error code or something?

Not sure how to check the MS Edge Browser console any help there would also be appreciated.

**Comment by sephrat** [comment]
> however I get the same issue using either script, I have checked my NGINX "access.log" and can not see any obvious issues do you have anything you think I should look for like an error code or something?

Errors should be in error.log by default I believe.

> Not sure how to check the MS Edge Browser console any help there would also be appreciated.

Hit F12 to open DevTools, go to the console tab, then refresh the page to see if anything stands out.

**Comment by tidusjar** [comment]
Are there any errors in your browser console? F12.

If so can you press the network tab and then refresh the page and you should see something like
![image](https://cloud.githubusercontent.com/assets/6642220/23088047/eac44abc-f570-11e6-9f23-d2eb022ed059.png)


If you click the red text and then the preview tab like the image above and post the result?

**Comment by Zuluwarrior131** [comment]
Ok when I try and access the Requests tab I get this error in the browser:
![image](https://user-images.githubusercontent.com/61565564/149240446-4a15f7e2-894d-420a-8435-3a43999030c6.png)

Also this is what I get on the Network tab and clicking on red desc and then preview
![image](https://user-images.githubusercontent.com/61565564/149240908-6a5942cb-89d6-4f1d-a875-90fa47ca3215.png)

**Comment by tidusjar** [comment]
Odd. What's on your server logs?

Can you log out and back in and does it still happen?

**Comment by Zuluwarrior131** [comment]
OK That was strange I had logged out before and logged in but this time i used a local account and its working again. Even if I sign out and then resign in using plex like I had originally it now works. It must have been when I updated and copied the new files for v4.9.0 over the older ones. Strange how it only effected proxy connections and not direct. Thanks Lesson learnt.
