### ISSUE TITLE
Media content may be improperly imported into Ombi

### ISSUE THREAD

**Issue by sephrat** [Ombi-app/Ombi#4472]
**Describe the bug**
If Ombi fetches content from a media server when it isn't done fetching the metadata, it will save the content in the database in an incorrect state:
![image](https://user-images.githubusercontent.com/34862846/149516268-c802762c-8f54-47a9-b3e2-c2bb0634c8c3.png)

Upon the next sync, Ombi considers the content as already added so it won't try to update its information. This ends up in content that can never be marked as available unless you manually run a "Clear data and resync" in Ombi settings.

This causes other issues in another context: if the media was first scanned incorrectly by the media server and you manually correct the identification, Ombi will keep the incorrect state in the database.

**To Reproduce**
1. Add new content to media server
2. Immediately run a sync (after it has detected new content but before the metadata are recognized).
3. Wait for the metadata to be added in the media server and run a new sync
4. The media is not available in Ombi

**Expected behavior**
Ombi should update the media information if it detects a difference.

**Proposed solution**
- Do not add content to the database when its metadata is empty (no external IDs, no episode/season number)
- Update content when there's a difference between the media server state and Ombi internal state (an ID has changed, an episode number was changed, etc. )

**Ombi Version (please complete the following information):**
 - Version 4.9.1
- Media Server Emby

Trying to get some feedback before working on a PR.

**Comment by tidusjar** [comment]
I think the first proposed solution is what we should go with:
Do not add content to the database when its metadata is empty (no external IDs, no episode/season number)

I think having to do a diff on each item is going to be a real pain to do and track. If the user has had a large restructure of their libraries then they should do a clear and re-sync.

But yeah good ideas here 👍

**Comment by sephrat** [comment]
> I think having to do a diff on each item is going to be a real pain to do and track.

This is not tested and I haven't looked into every case though., but can't we just compare existingMovie with movieInfo here:
https://github.com/Ombi-app/Ombi/blob/ad677fa02eb75633014e9c9791c21ed2d6a23229/src/Ombi.Schedule/Jobs/Emby/EmbyContentSync.cs#L245-L248
and if they're not similar, update instead of adding? We already fetch the content details so a simple comparison should do the trick.

Anyway this can be done in two steps, so I'll work on a PR for the first task. Depending on your answer, I may take try something out for the second task and we'll see how it goes.

**Comment by sephrat** [comment]
I suggest to implement my first suggestion (PR incoming) and close this issue. We can open a new issue for the second suggestion, which should fix the issue being that Ombi doesn't update its cache when the media identification is changed on the media server.
