### ISSUE TITLE
[Resolved] Ombi unable to access Radarr API

### ISSUE THREAD

**Issue by pcaston2** [Ombi-app/Ombi#4482]
**Describe the bug**

EDIT: I am noticing there is already something for Radarr V3 in the code, and my version might be outdated, despite it telling me I have the latest version when I try to update. Maybe I just need instructions on updating?

EDIT 2: I have updated to V4 and the API is working. Would be nice if V3 told me there was a newer version.... Oh well. Please close this issue.

The issue I am having is that Ombi is no longer able to speak with Radarr, despite it having worked in the past, and it is still working with Sonarr.

The time that it stopped corresponds roughly with the change to Radarr 4.0.0.5745 - [Remove Legacy API](https://github.com/Radarr/Radarr/commit/b7f379196696c429315d729ca811f4f53c7120f4)

I was not able to manually access the API URLs that were present in the Ombi logs.
eg. http://localhost:7878/api/rootfolder

However, adding /v3 to the API for Radarr allowed it to work as intended, which tells me the API is fine, just the endpoint is wrong
eg.
http://localhost:7878/api/v3/rootfolder?apikey=<#MY_API_KEY#>

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Movies'
3. Click on 'Radarr'
4. Fill out your connection details (localhost, 7878, API key, etc.)
5. Click 'Test Connectivity'
6. Get 'We could not connect to Radarr!'

**Expected behavior**
Get a success message. I realize that ultimately it stopped working due to a change to Radarr, but Ombi should be made to work with the latest releases.

**Logs (Logs directory where Ombi is located)**
```
[Error] StatusCode: NotFound, Reason: Not Found, RequestUri: http://localhost:7878/api/rootfolder
[Error] StatusCode: NotFound, Reason: Not Found, RequestUri: http://localhost:7878/api/profile
[Error] StatusCode: NotFound, Reason: Not Found, RequestUri: http://localhost:7878/api/system/status
[Error] Could not test Radarr
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Controllers.External.TesterController.Radarr(RadarrSettings settings) in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 315
```

**Desktop (please complete the following information):**
 - OS: Windows

**Ombi Version (please complete the following information):**
 - Version: 3.0.4892
- Database Type: SQLite (Please change if using MySQL)

**Comment by tidusjar** [comment]
There was a bug in your v3 version that stopped it reporting new updates.
