### ISSUE TITLE
Available / Approved Banners not showing in Ombi app

### ISSUE THREAD

**Issue by Akury83** [Ombi-app/Ombi#4487]
**Describe the bug**
The “Available” or “Approved” banners are not showing up for some shows in the iOS app.

**To Reproduce**
1. Request show
2. (Show downloads in background and Ombi syncs with Plex)
3. Notification received that show is available
4. Check in Ombi using the app, no ‘Available’ banner displayed, however if you click on the show, it says available.

**Expected behavior**
The ‘Approved’ banner should be displayed while the request is processing, and the ‘Available’ banner should be displayed once the show is available.

**Screenshots**
![084131CC-36E8-428D-9156-585694FB97EC](https://user-images.githubusercontent.com/87064827/152063332-0a8c5a73-4346-4c00-b37a-7df40bab53cc.png)
![0ABF5CC8-8D06-4077-B04D-E50E3CB65FC9](https://user-images.githubusercontent.com/87064827/152063366-cdb9cfdc-5e27-4434-be52-8de9c57236ee.png)
![9EE6C17B-94E7-4B8A-8F05-3DBC042474C8](https://user-images.githubusercontent.com/87064827/152063371-7c1f0419-19db-4537-b9cb-4c900d6dbed3.jpeg)

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS, iOS app ver 2.9.0

**Ombi Version (please complete the following information):**
 - Version 4.10.2, running the hotio/ombi docker image
- Media Server Plex
- Database Type: SQLite (Please change if using MySQL)

**Additional context**
This seems to happen to all new shows since updating to Ombi 4.10.2, from 4.3.3 on the hotio/ombi docker image whether they were requested via ombi or not. I can confirm that it was happening running Ombi 4.10.2 and iOS app ver 2.8.0, but not Ombi 4.3.3 and iOS app ver 2.8.0.
When accessing Ombi via a browser (whether mobile or desktop), it appears to work as intended.

**Comment by Akury83** [comment]
Apologies, forgot to mention that Movies are unaffected

**Comment by tidusjar** [comment]
Is it only when searching?

**Comment by Akury83** [comment]
Hello, and thanks for replying :)

It appears so, when browsing it appears that the banners are there. As an example:

![322D6677-E821-4014-A6F1-0ACB0853C871](https://user-images.githubusercontent.com/87064827/152071712-81cd589a-b4c8-4445-9823-d460dacc9eea.png)
![A5B1A52C-CBBD-4B03-B27E-76905D8B790E](https://user-images.githubusercontent.com/87064827/152071731-07bc90d0-2466-4601-95e8-73d0ff41037b.png)

**Comment by tidusjar** [comment]
Thanks. I’ll fix it in the next release.

**Comment by Akury83** [comment]
Sweet, thanks for all of your hard work 😃

Just out of curiosity, is it a bug with the app or with Ombi itself?

**Comment by tidusjar** [comment]
I'm pretty sure it's a bug in the app :)

**Comment by tidusjar** [comment]
Fixed in v2.9.1 which will be released in the next week

**Comment by Akury83** [comment]
Hey sorry to be a pain, has v2.9.1 been released for iOS yet? It’s not in the App Store.. Also, I’m happy to be a tester for new releases if you have a TestFlight link and would like the help
