### ISSUE TITLE
API can't delete movie requests

### ISSUE THREAD

**Issue by sbrudenell** [Ombi-app/Ombi#4489]
**Describe the bug**
I can't delete movie requests via the API.

Deleting TV requests works, and deleting movie requests as an admin user works.

**To Reproduce**
```python
>>> import requests
>>> r = requests.delete("https://redacted/api/v1/Request/movie/1354", headers={"ApiKey": "redacted"})
>>> r.status_code
200
>>> r.json()
{u'errorMessage': None, u'errorCode': u'NoPermissions', u'result': False, u'message': None, u'isError': True, u'requestId': 0}
```

In this case `1354` is a real movie request, however I get the same result if I use a nonexistent request id.

**Expected behavior**
* The API should be able to delete requests
* The API should return a 4xx/5xx status code for an error (I expect an error HTTP status code if and only if `isError` is `true`)

**Screenshots**
N/A

**Logs (Logs directory where Ombi is located)**
No logs seem to be emitted in this case

**Desktop (please complete the following information):**
 - OS: `linuxserver/ombi` docker image digest `4af461a53663`

**Ombi Version (please complete the following information):**
- Version: 4.10.2
- Media Server: Plex
- Database Type: SQLite

**Additional context**
N/A

**Comment by tidusjar** [comment]
The error code states that you do not have permission. How are you authenticating?

**Comment by sbrudenell** [comment]
with an API key. See my example

Is there some way to manipulate the permissions of the API user? I tried to find this, but didn't come up with anything.

**Comment by tidusjar** [comment]
Just looked at the code and it was a bug, Fixed in develop :)

**Comment by sbrudenell** [comment]
Thanks. Any chance you can figure out which versions are affected? It's not super clear to me from the code.

**Comment by tidusjar** [comment]
That area of the code is pretty old and doesn't really need to change much, so you can just assume it's a lot of versions. Version [v4.11.3](https://github.com/Ombi-app/Ombi/releases/tag/v4.11.3) contains the fix
