### ISSUE TITLE
Ombi Only "Monitoring" Latest Season in Sonarr (All Seasons Requested)

### ISSUE THREAD

**Issue by Firetop** [Ombi-app/Ombi#4496]
**Describe the bug**
When using Ombi's TV Shows "All Season" button to request all the seasons from Sonarr, Ombi does not "Monitor" every season in Sonarr.; it only monitors the "latest" season in Sonarr and does a one time search for the older seasons.

This is an issue if Sonarr only finds a 720p copy of the older season on the first search; and then an upgrade to 1080p is available later on; it will not be monitoring to upgrade to the better copy. Or if it fails to find a copy on the first search; but a copy becomes available; it will not download it.

**To Reproduce**
1. Go to Ombi and Request the TV Series 'Suits' all Seasons.
2. Verify in Sonarr, and only 'Suits Season 9' will be monitored. (The rest is a one time search and not actively monitored.)

**Expected behavior**
Expected behavior is if a user requests all seasons from Ombi; it monitors all seasons in Sonarr as well as run a search.

**Screenshots**
![image](https://user-images.githubusercontent.com/1971404/152630073-344fed62-9918-4a46-990e-b683252ee9e7.png)
![image](https://user-images.githubusercontent.com/1971404/152630074-10dbb14f-987d-4363-be86-4df6178ff77c.png)

**Logs (Logs directory where Ombi is located)**
N/A nothing in logs look applicable. Says it send successfully.

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2 (19044.1503)

**Ombi Version (please complete the following information):**
 - Version 4.10.2 and 4.11.3 
- Media Server: Plex Version 1.25.4.5487 
- Database Type: SQLite

**Additional context**
I tested on Sonarr version: 3.0.6.1451 (nightly) and version: 3.0.6.1342 (master) and the problem continues on both versions indicating it's a problem with how Ombi is sending the request to Sonarr.

It seems to have started after this fix: https://github.com/Ombi-app/Ombi/issues/4459

**Comment by tidusjar** [comment]
Was this show already in sonarr, or did Ombi add the show?

**Comment by sephrat** [comment]
I've noticed this as well. Only the latest (4th) season was added when the full series was requested.
Ombi added the show, it was not already in Sonarr. 
Also noticed that on an existing series, requesting for the 1st and 2nd seasons resulted in only the 2nd season to be monitored. Might be a different issue though. I had planned to investigate this further before raising an issue.

**Comment by Firetop** [comment]
> Was this show already in sonarr, or did Ombi add the show?

Suits in my example above was added by Ombi, it did not exist in Sonarr before.
Although; as @sephrat mentioned above. Someone did request seasons 10 to 15 of Foresic Files which DID exist in Sonarr before; and a similar issue is also found and only the latest is added/Monitored on Sonarr.

I was also not sure if that was the same or a separate issue; but i was confident enough to post about the primary issue of Suits seeing it was being added by Ombi from the get-go and seemed related to the change 20 days ago: https://github.com/Ombi-app/Ombi/issues/4459

**Comment by Firetop** [comment]
@tidusjar To confirm my theory that it was related to that change; I downgraded just now from Ombi Version 4.11.3 back down to Ombi Version 4.9.1 and confirm my expected results now returned as expected.

I will stay on 4.9.1 until this is fully resolved. I do now unfortunately believe the issue of https://github.com/Ombi-app/Ombi/issues/4459 returned but I rather have everything than not enough as people bother me too much when they can't find something they requested and space is not an issue.

**Comment by tidusjar** [comment]
Thanks for confirming and the extra information!

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈

**Comment by Firetop** [comment]
> This has been fixed in the develop branch! 🎉 🎈 Release v4.11.5

Many Thanks! Tested it and everything is working correctly now for requests for all seasons or single seasons are user and admin!

Amazingly fast turnaround!
