### ISSUE TITLE
Ombi API to delete a specific movie request stopped working

### ISSUE THREAD

**Issue by harrv** [Ombi-app/Ombi#4512]
**Describe the bug**
With some release between November 2021 and January 2022 the Ombi API to delete a specific movie request stopped working.

**To Reproduce**
1. Obtain the id of the request you want to delete. This is the id that Ombi uses internally for that specific request. As far as I know the ids are not visible in the UI, so you'll need to either peek inside the database or use one of the Ombi APIs that return movie requests. For example, if someone has requested a movie called "Marry Me" I could use this curl command to call the Ombi API that will return the full request JSON, including the "id": `curl -X GET "http://<IP_ADDR>:3579/api/v1/Request/movie/search/Marry%20Me" -H "ApiKey: <API_KEY>"`
2. Call the API to delete that request. For example, if the request id is 337, the following curl command will call the API to delete that request: `curl -X DELETE "http://<IP_ADDR>:3579/api/v1/Request/movie/337" -H "ApiKey: <API_KEY>"`
3. Notice that the API call returns a JSON body in the response: `{"result":false,"message":null,"isError":true,"errorMessage":null,"errorCode":"NoPermissions","requestId":0}`. If you call the same curl command in step 2 with the `-I` option you will see the HTTP headers on the result, which indicate it returned `200 OK`. So, it's accepting my API call to do the delete, returning `200 OK` meaning the delete worked, but it didn't, and there is that odd JSON body describing some error that occurred.
4. Check in the UI or by using the command in step 1 above and you will see the request did not get deleted.

**Expected behavior**
I expect the API call to return `200 OK` (like it is) or `204 No content`. There should be no JSON body returned for a successful delete--the status code tells the story.

If there _is_ a legitimate reason that the call failed, then I would expect a result code in the 400 or 500 ranges, and in that case it would be appropriate to also return a JSON body describing the details of the error.

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Docker on Linux (image is latest: linuxserver/ombi:v4.10.2-ls114)

**Ombi Version (please complete the following information):**
 - Version: 4.10.2
- Media Server: Emby Server version 4670
- Database Type: MySQL

**Additional context**

**Comment by tidusjar** [comment]
This has already been fixed: https://github.com/Ombi-app/Ombi/releases/tag/v4.11.3
