### ISSUE TITLE
Watch on Plex missing [help wanted]

### ISSUE THREAD

**Issue by 60plus** [Ombi-app/Ombi#4529]
**Describe the bug**
After adding 4k Movie or series "Watch on Plex" button dont work

**To Reproduce**
1. Add 4k Movie/Series
2. Click on Movie/Series
3. Scroll down to "Watch on Plex"
4. Watch on Plex is missing

**Expected behavior**
see this button:
![obraz](https://user-images.githubusercontent.com/73450566/156039543-ee298f09-a21c-4865-9412-fdb1bdb709e0.png)
but only this is available:
![obraz](https://user-images.githubusercontent.com/73450566/156039732-4e32c113-11ab-492c-9d91-03b2f0668e54.png)

**Screenshots**
4K Movie
![obraz](https://user-images.githubusercontent.com/73450566/156040253-79356f67-1140-45e1-ad96-6308ce1bc109.png)
1080p Movie
![obraz](https://user-images.githubusercontent.com/73450566/156040320-cedad833-2de4-4916-910d-12617580eaa8.png)

**Logs (Logs directory where Ombi is located)**
No logs

**Desktop (please complete the following information):**
 - OS: W11 64bit

**Ombi Version (please complete the following information):**
 - Version 4.13.0
- Media Server PLEX
- Database Type: SQLite
- 
**Additional context**
...

**Comment by tidusjar** [comment]
Thanks I’ll take a look! The 4K work as a LOT of work, so these little things can be easy to miss

**Comment by 60plus** [comment]
> Thanks I’ll take a look! The 4K work as a LOT of work, so these little things can be easy to miss

Also availability marker is missing in 4K Movies/Series

1080p Movie
![obraz](https://user-images.githubusercontent.com/73450566/156078048-f4b82bb0-9e1f-4ee4-b987-746489f19ec0.png)

4K Movie
![obraz](https://user-images.githubusercontent.com/73450566/156078109-5901d910-b6ea-4319-aece-0e4bc8783e80.png)
![obraz](https://user-images.githubusercontent.com/73450566/156078146-a98d89d8-2cc6-4409-9cd9-11a4a1fc5347.png)

**Comment by tidusjar** [comment]
These issues has been fixed in the develop branch! 🎉 🎈
