### ISSUE TITLE
Auto delete available requests schedule job is not removing available requests

### ISSUE THREAD

**Issue by jaretclifton** [Ombi-app/Ombi#4530]
**Describe the bug**
Auto delete available requests schedule job is not removing available requests no matter what frequency the cron task is set to.

**To Reproduce**
1. Go to Settings -> System -> Scheduled Tasks and adjust the cron for Auto Available Request Deletion to run at any given time you want
2. Request a movie or show and have it fulfilled and marked as available
3. Monitor log files to ensure the auto remove job is fired
4. Check available requests list to see none have been removed

**Expected behavior**
All available requests should be removed from the available requests list for both Movies and TV Shows

**Logs (Logs directory where Ombi is located)**
No log messages showing errors

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 18.04

**Ombi Version (please complete the following information):**
 - Version [e.g. 4.0.958] 4.13.0
- Media Server [e.g. Plex] Plex
- Database Type: MySQL

**Comment by tidusjar** [comment]
What is your auto delete setting? How many days after availability do you have it set to?

**Comment by jaretclifton** [comment]
I've tried anywhere from 15 minutes to 24 hours. I can see the trigger fire in the log files at the correct time from the cron entry (whatever I specify, save, restart Ombi) but nothing is actually removed.

**Comment by tidusjar** [comment]
I mean have you actually enabled the setting? Under configuration > general

**Comment by jaretclifton** [comment]
Yes it is enabled. I can try toggling it off, save, restart, on, save, restart if that would help.

**Comment by tidusjar** [comment]
Mind posting a screenshot of those settings?

**Comment by mLgz0rn** [comment]
> > I got the same issue, and have had it for a while. Both on stable and dev build.
> > Auto Delete Available Requests is enabled and set to 0. I have also tried 1 but even after 1 week items are not removed.
> 
> Are you referring to the Settings -> Configuration -> General -> Delete After Days of Availability? Or are you referring to the cron entry "Auto Available Request Deletion"?

The setting.
Only thing I could see in the log when it ran the 

[Debug] Calling Execute on job System.IAutoDeleteRequests
[Debug] Trigger instruction : NoInstruction

However, I decided to start from scratch, purging everything and reinstalling ombi.
So gonna see how it goes.

**Comment by twanariens** [comment]
> > I got the same issue, and have had it for a while. Both on stable and dev build.
> > Auto Delete Available Requests is enabled and set to 0. I have also tried 1 but even after 1 week items are not removed.
> 
> Are you referring to the Settings -> Configuration -> General -> Delete After Days of Availability? Or are you referring to the cron entry "Auto Available Request Deletion"?

If you have set the "Auto Delete Available Requests" to 0 it will not work. The number is the amount of days the request is marked as available before deletion. If set to 1, it will delete them after 1 day.

The Cron you are referring to is when the job runs in the background to check that setting and check if it needs to delete anything. 

Once you have set the "Delete After Days of Availability" please do restart your Ombi since only then the changes will take effect.

**Comment by mLgz0rn** [comment]
> > > I got the same issue, and have had it for a while. Both on stable and dev build.
> > > Auto Delete Available Requests is enabled and set to 0. I have also tried 1 but even after 1 week items are not removed.
> > 
> > 
> > Are you referring to the Settings -> Configuration -> General -> Delete After Days of Availability? Or are you referring to the cron entry "Auto Available Request Deletion"?
> 
> If you have set the "Auto Delete Available Requests" to 0 it will not work. The number is the amount of days the request is marked as available before deletion. If set to 1, it will delete them after 1 day.
> 
> The Cron you are referring to is when the job runs in the background to check that setting and check if it needs to delete anything.
> 
> Once you have set the "Delete After Days of Availability" please do restart your Ombi since only then the changes will take effect.

I guess the documentation is wrong then ?
https://docs.ombi.app/settings/ombi/

`Auto Delete Available Requests¶
This will auto delete requests which have been marked available for 'x' days.
If the days are set to 0 then it will delete all requests after the job runs. If it's set to 1 then it will delete available requests after they have been available in the system for a day.`

And I know that the cron is suppose detect and delete available items if the setting is set.
Which it is, but guess if 0 is not working as according to you, then that's why.
But that's just not how it's described in the documentation

**Comment by twanariens** [comment]
I see that now. Just wanted to check first before changing the documentation. Have you had any change to test the new value?

**Comment by mLgz0rn** [comment]
> I see that now. Just wanted to check first before changing the documentation. Have you had any change to test the new value?

Yeah, after changing it to 1 it seems to delete now 👍

**Comment by twanariens** [comment]
I have added a PR to the documentation to be changed. Thanks for checking!

**Comment by Kazz3r24** [comment]
For as long as I've been using Ombi (years), this option has never worked... I have mine set to 1 and requests once available never get deleted.
