### ISSUE TITLE
The JSON value could not be converted to NzbDrone

### ISSUE THREAD

**Issue by Mikepoplas** [Ombi-app/Ombi#4531]
**Describe the bug**
Cannot add requests to Radarr

**To Reproduce**

1. Add a new request
2. Check radarr o Ombi logs to check the rerror

**Expected behavior**
Request added to radarr without errors

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.
Ombi log:
`
2022-03-02 14:21:14.221 +01:00 [Error] StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://192.168.1.247:7878/api/v3/movie`

Radarr log
`{

  "$.minimumAvailability": {

    "errors": [

      {

        "errorMessage": "The JSON value could not be converted to NzbDrone.Core.Movies.MovieStatusType. Path: $.minimumAvailability | LineNumber: 0 | BytePositionInLine: 326."

      }

    ],

    "validationState": "invalid",

    "isContainerNode": false

  }

`}``

**Desktop (please complete the following information):**
 - OS: Windows 10
**Ombi Version (please complete the following information):**
 - Version 4.13.2   
- Media Server Plex Jellyfin
- Database Type: SQLite 

**Additional context**

No reverse proxy, no base url defined on settings

**Comment by sephrat** [comment]
What Default Minimum Availability did you set for Radarr in Ombi?
Chances are you were using Predb which has been deprecated in Radarr. We removed the option from Ombi (https://github.com/Ombi-app/Ombi/issues/4450) but you need to set it to a new value.

Also, what's your Radarr version?

**Comment by Mikepoplas** [comment]
Thanks septat, that solved it. Anyway Radarr version is  4.0.5.5977

Regards
