### ISSUE TITLE
Logo is Distorted / Stretched on iOS mobile browser

### ISSUE THREAD

**Issue by petertadrous** [Ombi-app/Ombi#4549]
**Describe the bug**
When accessing Ombi on mobile iOS, the Logo is has a stretched height that takes up most of the screen. This happens on both the safari browser and on a third party app designed to emulate desktop browsing. This also happens whether the default logo is used or a custom logo url is given. Have tried with square images over 500px in height or just 120px; same results.

**To Reproduce**
1. Use a mobile iOS device
2. Go to your Ombi instance from browser, i.e. `http://localhost:ombiport/`
3. Log in
4. See the stretched logo

**Expected behavior**
Logo is not stretched, but remains square

**Screenshots**
Here is a [screenshot of the issue on iPhone 12 Pro Max, Safari](https://i.imgur.com/5Gfuo5R.png). Here is a [screenshot of the same phone on a desktop browser app](https://i.imgur.com/RmMeGu2.png) (the "Request Desktop Site" on Safari does not work).

**Logs (Logs directory where Ombi is located)**
No logs

**Desktop (please complete the following information):**
 - OS: iOS 14.3

**Ombi Version (please complete the following information):**
- Version 4.10.2
- Running in hotio's docker container on Synology DS920+

**Additional context**
I've tested this on an android phone and the logo looked fine. I've also tried to fiddle with the custom CSS but I've never done that before so haven't made much progress.

**Comment by twanariens** [comment]
@petertadrous Can you try and add the following custom css:

`
.profile-img{
object-fit:cover;
}
`

**Comment by petertadrous** [comment]
@twanariens I have updated the custom css to this and I still have the same results when accessing via Safari on my iPhone. I've also logged out and back in with another user account with the same results

**Comment by twanariens** [comment]
Hm. Seems like safari is being a %$@. 
Can you try:

`.profile-img{ max-height:40px; max-width:40px; width:auto !important; }`

**Comment by petertadrous** [comment]
@twanariens this worked! Both in Safari, and on a third party desktop browsing app. It no longer shows the stretched icon and actually shows the correct size

**Comment by twanariens** [comment]
Cool! Will add this css to Ombi whenever I get the change to it!
