### ISSUE TITLE
Issues with "Play on Jellyfin" button

### ISSUE THREAD

**Issue by elightcap** [Ombi-app/Ombi#4571]
**Describe the bug**
After adding a Jellyfin server, several issues come up
1. Movies show a 'Play on Emby' button instead of 'Play on Jellyfin'
2. The correct button shows up for TV Shows, but clicking on it directs the browser to localhost:8096 instead of the url specified in the Jellyfin config

**To Reproduce**
1. Go to 'Settings>>Media Server>>Jellyfin'
3. Click on 'Enter details for server and enable'
4. Go to any available Show or movie
5. Click 'Play on Jellyfin'(or Play on Emby if it is a movie)
6. See error

**Expected behavior**
Correct button shows up, directs user to proper URL when button is clicked

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Browser client

**Ombi Version (please complete the following information):**
 - Version - 4.15.4-development
- Media Server - Jellyfin
- Database Type: SQLite 

**Additional context**

**Comment by sephrat** [comment]
Can you try to "Clear Data And Resync" from the Jellyfin configuration page and see if that fixed it?
First issue was fixed in 4.15.0 but you need to refresh the cache.
2nd issue is most likely a cache issue too (you probably set your jellyfin hostname after Ombi cached the shows).

**Comment by elightcap** [comment]
Totally missed the 4.15.0 release, this can be closed now, thanks!
