### ISSUE TITLE
Remote Display

### ISSUE THREAD

**Issue by WeirDave** [Ombi-app/Ombi#4574]
**Describe the bug**
Unable to display the program in browser or APP

**To Reproduce**
1. Go to 192.168.0.1:5656
2. Nothing displays
3. Go to localhost:5656
4. See the program just fine

**Expected behavior**
I expect that it displays through the website remotely

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 64bit

**Ombi Version (please complete the following information):**
 - Version [e.g. 4.0.958] 4.15.4
- Media Server [e.g. Plex] Plex
- Database Type: SQLite (Please change if using MySQL)

**Additional context**
It was working and no longer works. I tried to uninstall and re-install to no avail

**Comment by tidusjar** [comment]
`localhost` is working as you are hosting it on your machine that you are accessing it on. If you want to access it via your internal IP then you need to use your IP for that machine. this is not really a ombi issue. Check firewall etc.
