### ISSUE TITLE
.NET Runtime Errors while using MySQL on Windows

### ISSUE THREAD

**Issue by vladtepz** [Ombi-app/Ombi#4578]
**Describe the bug**
There are many, (1x per hour), .NET Runtime Errors being logged, while using MySQL on Windows in my Event Viewer.

**To Reproduce**
Run Ombi on Windows using MySQL database.

**Expected behavior**
No errors...

**Screenshots**
![image](https://user-images.githubusercontent.com/1252146/162226188-c34ed311-71b3-46a1-9b1f-a29f8ed5a3b8.png)

**Logs (Logs directory where Ombi is located)**
Nothing applicable in the logs.

**Desktop (please complete the following information):**
 - OS:	        Windows 11 Pro
 - Version:	21H2
 - OS build	22000.593

**Ombi Version (please complete the following information):**
 - Version: 4.16.0 ( Not a 4.16.0 issue. Happens on all versions since I've started using Ombi with MySQL )
- Media Server: Emby v.4.6.7.0
- Database Type: MySQL v.8.0.27 (Current) | 10.4.19-MariaDB (Tested)

**Additional context**

I've noticed this issue for a while, since migrating to MySQL, unfortunately haven't had a chance to report until now.

**Comment by vladtepz** [comment]
Yes. Radarr v.4.0.5.5981

**Comment by Lucane** [comment]
Experiencing the exact same issue here. Ombi version v4.22.0. MySQL database version v8.0.27.

![image](https://user-images.githubusercontent.com/7999446/180588982-4f78f92b-6567-4721-b41e-bdef3c01d8ee.png)

**Comment by sephrat** [comment]
This was fixed in v4.35.19
