### ISSUE TITLE
Ombi not finding/cacheing TV Shows Only

### ISSUE THREAD

**Issue by mihcox** [Ombi-app/Ombi#4593]
**Describe the bug**

**To Reproduce**
1. Go to Settings -> Media Server
2. Click on Manually Run Full Sync
3. Review logs to see errors for every entry in my TV collection

**Expected behavior**
Should sync all TV shows like normally

**Logs (Logs directory where Ombi is located)**
Few log snippits:

2022-04-12 00:00:00.256 -05:00 [Warning] Exception thrown when attempting to cache the Plex Content in server "BigRig"
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: [. Path 'MediaContainer.Metadata[0].Rating', line 1, position 1806.

2022-04-12 02:00:05.229 -05:00 [Error] Exception when adding tv show "Billions"
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: [. Path 'MediaContainer.Metadata[0].Rating', line 1, position 1462.

2022-04-12 02:00:41.341 -05:00 [Warning] The episode title "Turn It Upside Down" we cannot find the parent series. The episode grandparentKey = 98585, grandparentTitle = "Elementary"

**Desktop (please complete the following information):**
 - Running on UnRaid - LinuxServer version

**Ombi Version (please complete the following information):**
 - Version 4.10.2
- Media Server Plex
- Database Type: SQLite 

**Additional context**

**Comment by tidusjar** [comment]
This has been fixed in the develop version of Ombi, you can use the develop tag for the LSIO docker image

**Comment by mihcox** [comment]
Great, do I need to stay on this version long term?
