### ISSUE TITLE
Some movies aren't being passed to Radarr (Bad Request)

### ISSUE THREAD

**Issue by dr3am37** [Ombi-app/Ombi#4602]
**Describe the bug**
Some Movies aren't passed to Radarr

**To Reproduce**
1. Request Freddy got fingered or Saving Grace

**Expected behavior**

**Screenshots**

**Logs (Logs directory where Ombi is located)**
https://pastebin.com/FK67BRsW

**Desktop (please complete the following information):**
 - OS: Unraid

**Ombi Version (please complete the following information):**
 - Version 4.16.11
- Plex
- Database Type: SQLite

**Additional context**

**Comment by sephrat** [comment]
You most likely have the same issue as reported here: https://github.com/Ombi-app/Ombi/issues/4531
See my reply there for how to fix it.

**Comment by dr3am37** [comment]
Can confirm setting OMBI to "Announced" as minimum availability did solve the issue, problem was I had it set to nothing before, consider making Announced the default or requiring the user to choose one.

Thanks!

**Comment by clambin** [comment]
two years later, but FYI got hit by the same problem as well.  looking at my Radarr config, indeed minimum availability was indicated as a mandatory parameter, but I managed to save my settings without it being set.  bug?
