### ISSUE TITLE
Request made from Plex Watchlist doesn't trigger notification

### ISSUE THREAD

**Issue by dr3am37** [Ombi-app/Ombi#4603]
**Describe the bug**
Request made from Plex Watchlist doesn't trigger notification

**To Reproduce**
1. Add to Watchlist

**Expected behavior**
When a request is imported from the watchlist a notification will be sent out as if the user added it himself

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Unraid

**Ombi Version (please complete the following information):**
 - Version 4.16.11
- Plex
- Database Type: MySQL

**Additional context**

**Comment by tidusjar** [comment]
Did your user log out and back in after the main update?

**Comment by dr3am37** [comment]
The user is me and I didn't have Ombi before the last update, logged in and out several times and my user is a Plex user.
Plex settings has the option enabled and it works (stuff get requested, just not notified when processed as opposed to manually requesting in Ombi)

**Comment by tidusjar** [comment]
Your user the admin?

**Comment by Gwindalmir** [comment]
I noticed the same thing, new install of Ombi, never used anything before 4.16.x.
However, I only tried it with one show, which already ended many years ago.

Since it didn't work, I wasn't going to rely on it, and didn't try further.

**Comment by tidusjar** [comment]
Users with the Admin or Power User role in Ombi don't get notifications, this is normal behaviour

**Comment by trickinit** [comment]
Sorry this is a bit old but I just came across this issue too. I have a user that's able to add to their watchlist via Plex and their requests come through in Ombi. The problem is that I receive no notification when requests are submitted this way. If that same user logs into Ombi and manually submits a request, I get a notification so I can either approve or deny the request.
