### ISSUE TITLE
Movies with only 4k available aren't getting the general available flag

### ISSUE THREAD

**Issue by dr3am37** [Ombi-app/Ombi#4607]
**Describe the bug**
When a movie has a normal version it gets flagged as available, when it only has 4k available it doesn't get flagged as generally available.

**To Reproduce**
1. Request 4k version without a normal version

**Expected behavior**
Whether you have only a normal version or a 4k one the movie/series should be marked as available.

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**

**Ombi Version (please complete the following information):**
 - Version v4.16.11
- Plex
- Database Type: MySQL

**Additional context**

**Comment by dr3am37** [comment]
![unknown](https://user-images.githubusercontent.com/91037083/163732928-94e606ac-f183-4a53-8b3a-b9ec2526fb37.png)
![unknown](https://user-images.githubusercontent.com/91037083/163732929-5045c515-2c26-41f0-9833-b861d733e2c3.png)

**Comment by dr3am37** [comment]
4k is enabled in settigns

**Comment by dr3am37** [comment]
what my screenshot tried to convey is that only having a 4k version of the film doesn't get the whole thing marked as available while 1080p does
![image](https://user-images.githubusercontent.com/91037083/163737667-956af3b5-c01b-45a1-ab6d-f1a13b984f72.png)

In contrast, this movie only has 1080p and gets marked as available
![image](https://user-images.githubusercontent.com/91037083/163737674-5f946161-7852-4da2-9015-a690cdac2e2c.png)

which results in the general available indicator not being shown even though a 4k is available
![image](https://user-images.githubusercontent.com/91037083/163737681-0462edac-6b27-499c-94ec-af3a9bd5ff85.png)

**Comment by xweskingx** [comment]
It looks like this was fixed by https://github.com/Ombi-app/Ombi/pull/4702
