### ISSUE TITLE
Requests are not flagged as available when the movie in Emby is in 4K and 4K feature is disabled

### ISSUE THREAD

**Issue by sephrat** [Ombi-app/Ombi#4610]
**Describe the bug**
I have 4K feature disabled. When a request is made and it results in the movie being available in 4K, the request is never flagged as 'available'.

While debugging, it seems we ignore the 4K content because the request is not a 4K one. 
https://github.com/Ombi-app/Ombi/blob/develop/src/Ombi.Schedule/Jobs/Emby/EmbyAvaliabilityChecker.cs#L81
This does not take into accounts setups which do not use the 4K feature.

This seems to happen on Emby only, Jellyfin works fine.
I think it works in Jellyfin because for some reason Jellyfin API says it's not a 4K movie: Has4K is false and Quality is not null.
https://github.com/Ombi-app/Ombi/blob/develop/src/Ombi.Schedule/Jobs/Jellyfin/JellyfinAvaliabilityChecker.cs#L114
I haven't tested this part extensively, this may be specific to the movie I'm looking at.

**To Reproduce**
1. Have 4K feature disabled
2. Request a movie
3. Have it available in 4K in Emby
4. Request is never fulfilled upon sync

**Expected behavior**
Request is fulfilled regardless of the quality of content when 4K feature is disabled.

**Ombi Version (please complete the following information):**
 - Version: current develop
- Media Server: Emby 4.7.0.35, Jellyfin 10.7.7

I'd be happy to fix it myself but I'm not sure of the approach to take. Should we check the 4K feature toggle (not a fan of the overcomplication) or be smarter than that?

**Comment by tidusjar** [comment]
We should just do the same things as we do here: https://github.com/Ombi-app/Ombi/blob/develop/src/Ombi.Schedule/Jobs/Plex/PlexAvailabilityChecker.cs#L186
