### ISSUE TITLE
External link showing on local network

### ISSUE THREAD

**Issue by dhbtfs** [Ombi-app/Ombi#4618]
**Describe the bug**
I have Ombi on my server (local network) and added to my website for Reverse Proxy. Added the link to ombi settings but if I access it on my desktop PC it still shows External link rather than local network link.

**To Reproduce**
1. Go to Settings
2. Click on Media Servers
3. Click on Jellyfin
4. Add your external link to: External Facing Hostname

**Expected behavior**
To have show my internal ip when I click on Watch on Jellyfin rather than external one if I am using it on same network.

**Screenshots**
-

**Logs (Logs directory where Ombi is located)**
-

**Desktop (please complete the following information):**
PC-Debian

**Ombi Version (please complete the following information):**
 - Version [e.g. 4.0.958]
- Media Server: Jellyfin
- Database Type: SQLite

**Additional context**
-

**Comment by sephrat** [comment]
Ombi only supports one URL and does not distinguish whether you're on LAN or WAN. 
My recommendation would be to set the external URL in Ombi and have your local network support your external domain name through DNS or something.

**Comment by dhbtfs** [comment]
Why not add some sort of whitelist ip so if its one of those ips, it would show the internal address rather than external?!

**Comment by tidusjar** [comment]
I’d suggest raising a feature request
