### ISSUE TITLE
Unable to view more than one page of results with Advanced Search

### ISSUE THREAD

**Issue by agentsnoop** [Ombi-app/Ombi#4629]
**Describe the bug**
Advanced Search only seems to return one page of results

**To Reproduce**
1. Go to 'filter' on discover
2. Enter 2021 for 'Year of Release'
3. Only the first 20 results are shown (one page)

**Expected behavior**
When more than one page of results is returned, an ability to navigate to other pages

**Screenshots**
N/A

**Logs (Logs directory where Ombi is located)**
N/A

**Desktop (please complete the following information):**
 - OS: Windows

**Ombi Version (please complete the following information):**
 - Version: 4.19.1
- Media Server: Plex
- Database Type: SQLite

**Comment by xweskingx** [comment]
It looks like this was addressed by: https://github.com/Ombi-app/Ombi/pull/4693
You can now load more results by scrolling
