### ISSUE TITLE
A lot of unwanted Arab suggestions

### ISSUE THREAD

**Issue by loadamasta** [Ombi-app/Ombi#4632]
**Describe the bug**
Ombi shows a lot of Arab entries. Language is not set to any Arab language and I don't have at any time preferred some Arab TV-shows or movies nor did I request those.

**Expected behavior**
No arab entries.

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Mac OS

**Ombi Version (please complete the following information):**
 - Version 4.16.12
- Media Server Plex
<img width="598" alt="Ombi 2022-04-28 17-41-47" src="https://user-images.githubusercontent.com/66960049/165793380-835f70db-5401-464b-8ef2-097230dedcac.png">

<img width="397" alt="Ombi 2022-04-28 17-42-14" src="https://user-images.githubusercontent.com/66960049/165793369-33220480-aa86-4754-8356-bde6486a5639.png">

- Database Type: SQLite

**Additional context**

**Comment by sephrat** [comment]
Ombi is the reflection of TMDB, and TMDB shows a lot of arabic shows recently: https://www.themoviedb.org/tv
We've added a new filter in Ombi to allow you to restrict the original language to mitigate this issue: https://github.com/Ombi-app/Ombi/pull/4619
But in the end it's not really an issue with Ombi.
