### ISSUE TITLE
default_tv_poster.png loading from root domain instead of defined sub-directory

### ISSUE THREAD

**Issue by heinstrom** [Ombi-app/Ombi#4635]
**Describe the bug**

In my setup Ombi is configured in `https://sub.domain.com/ombi/` -- this sub-directory has basic HTTP Authentication disabled, hoever `https://sub.domain.com/` has basic HTTP auth enabled. 

When logging into Ombi, I get a 401 error on **default_tv_poster.png**.

**To Reproduce**
1. Host Ombi in a subdirectory with HTTP Auth disabled, on a root domain with HTTP Auth enabled.
2. Login
3. A basic HTTP auth window will pop up.
4. Look in browser console to see 401 error for **`https://sub.domain.com/images/default_tv_poster.png`**

**Expected behavior**
The request for `default_tv_poster.png` should be to **`https://sub.domain.com/ombi/images/default_tv_poster.png`** not **`https://xxxxxxxxxx/images/default_tv_poster.png`**

**Screenshots**

**Logs (Logs directory where Ombi is located)**
Summary
URL: **https://mydomain/images/default_tv_poster.png**
Status: 401
Source: Network
Address: myIP:443
Initiator: 
main.31bddab8d994889d.js:1:1348534

Request
:method: GET
:scheme: https
:authority: mydomain
:path: /images/default_tv_poster.png
Accept: image/webp,image/png,image/svg+xml,image/*;q=0.8,video/*;q=0.8,*/*;q=0.5
Accept-Encoding: gzip, deflate, br
Host: mydomain
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15
Accept-Language: en-US,en;q=0.9
Referer: https://mydomain/ombi/discover
Connection: keep-alive

Response
:status: 401
Content-Type: text/html
Date: Tue, 03 May 2022 03:07:17 GMT
Www-Authenticate: Basic realm="Private Property"
Server: nginx/1.21.6

**Desktop (please complete the following information):**

**Ombi Version (please complete the following information):**
 - Version [e.g. Latest]
- Media Server [e.g. Plex]
- Database Type: SQLite (Please change if using MySQL)

**Additional context**
I would presume on a default Ombi install that this is throwing a 404 error if there is no HTTP Auth on the root domain. 

Looks like it might be an issue with this mapping: https://github.com/Ombi-app/Ombi/blob/f16c4e07582377c5a4b1edfb4a3648582c6328a0/src/Ombi/ClientApp/src/app/issues/issueDetails.component.ts#L51

**Comment by heinstrom** [comment]
Confirmed that I get a 404 after performing HTTP Auth :) 

Summary
URL: https://mydomain/images/default_tv_poster.png
Status: 404
Source: Network
Address: 108.21.65.88:443
Initiator: 
main.31bddab8d994889d.js:1:1348534

**Comment by Rewels** [comment]
I am also having the same issue, it is causing my Reverse Proxy to constantly prompt for 401 Authentication.

**Comment by tidusjar** [comment]
Is it on certain pages?

**Comment by Rewels** [comment]
> Is it on certain pages?

As soon as you login to Ombi and hit the Discover page it pops up. Doesn't look to be effecting any of the other pages
