### ISSUE TITLE
No Movies or Shows showing up on dashboard or via searching

### ISSUE THREAD

**Issue by jmackxiii** [Ombi-app/Ombi#4640]
**Describe the bug**
The landing page shows no movies or shows and no search works for any user, multiple computers, and even the phone app does the same thing. Whole host of dotnet errors in the event viewer. Not sure when this began but it's occurring now with version 4.20 on Windows 10 x64 with MySQL (not a recent SQL migration)

**To Reproduce**
Happens on any computer, any user, any browser

**Expected behavior**
Movies and Shows are searchable and the dashboard works as intended. 

**Screenshots**
NA

**Logs (Logs directory where Ombi is located)**
Snippit of event viewer logs.. can provide full OMBI logs if needed
RequestPath: /ombi/api/v2/search/Tv/anticipated/0/17

Something bad happened, ErrorMiddleware caught this

Exception: 
MySqlConnector.MySqlException (0x80004005): Unknown column 'j.Has4K' in 'field list'

**Desktop (please complete the following information):**
WIndows 10 x64

**Ombi Version (please complete the following information):**
 - Version 4.20.0
- Media Server Plex
- Database Type: MySQL

**Additional context**

**Comment by jmackxiii** [comment]
Happy to provide full log files and event viewer content if needed.. But it seems as there is a missing database component? Was an update script not run on the databases/tables?

**Comment by jmackxiii** [comment]
I see a real common occurrence in the Ombi logs with this
MySqlConnector.MySqlException (0x80004005): Unknown column 'p.Has4K' in 'field list'
So my gut says this has been an issue since the update adding 4k support.. Is there a SQL script I can run to update things on my end?

**Comment by tidusjar** [comment]
Can you provide the output to the `__EFMigrationsHistory` table?

**Comment by jmackxiii** [comment]
Thanks for you help in Discord.
