### ISSUE TITLE
TV shows are showing "processing request" when no request exists

### ISSUE THREAD

**Issue by ddevenport** [Ombi-app/Ombi#4641]
**Describe the bug**
Users are attempting to request TV shows and will see "processing request" for certain seasons on TV shows that haven't been requested or downloaded. This is causing them to click on the button to request all seasons, unnecessarily filling up my hard drive.

**To Reproduce**
1. Request Life Below Zero and check seasons 5 and 6. This isn't consistent across all shows and may just be specific to my Ombi instance, so I'm not sure this will reproduce elsewhere.

**Expected behavior**
Seasons that don't have an existing request or haven't been downloaded should give the option to request them, rather than show processing request.

**Screenshots**
![image](https://user-images.githubusercontent.com/22359002/167276021-76c55b74-1b3e-4e8c-8bfa-60cacbdd1573.png)

**Logs (Logs directory where Ombi is located)**
N/A

**Desktop (please complete the following information):**
Windows 10.0.19043

**Ombi Version (please complete the following information):**
- Version 4.20.0
- Media Server Plex
- Database Type: SQLite

**Comment by tidusjar** [comment]
Is it monitored in Sonarr?

**Comment by ddevenport** [comment]
When troubleshooting it I completely removed it from Sonarr, then restarted the Ombi service (not sure when it pings Sonarr or how it determines that status). That changed it so that previously unavailable seasons were available, but some seasons still had processing request.

How is that status determined? Knowing that I could probably troubleshoot better and provide better feedback.

**Comment by tidusjar** [comment]
If it’s monitored in sonarr then it’s “processing”. Removing sonarr from Ombi won’t change that once it’s been cached in Sonarr. If you have removed it from sonarr for example, then it will recache after a set amount of time and put it back to Not Requested

**Comment by SickProdigy** [comment]
I'm having a similar issue with sonarr, figure I'd post here. 

All movies that are in my library show as "Requested" like someone has already requested it. I do have all the shows monitored in sonarr. Should I unmonitor them if they are finished and have ended?

**Comment by tidusjar** [comment]
Yeah if you don’t want Ombi to show as requested.
