### ISSUE TITLE
Sonarr search each individual episode for anime when request one or all season pack

### ISSUE THREAD

**Issue by samos667** [Ombi-app/Ombi#4651]
**Describe the bug**
Ombi used with sonnar, when serie is considered as anime, request each episode individually even when one or all season is request

**To Reproduce**
0: Setup Ombi + Sonarr
1: Find serie qualified as anime (tested with "Demon Slayer" and "Samurai Camploo", With Acarne I think is considered as TV show so he request entiere season pack)
2: Request one or all seasons
3: Check request in Sonarr

**Expected behavior**
I would like when I select one ore all season pack Ombi request to Sonarr season and not each episode individually.

**Screenshots**
Ombi does correctly when I ask him for a season of a TV shows:
![168299022-892a820a-f6d2-4563-975f-925bea82a8d8](https://user-images.githubusercontent.com/50653464/168303056-8d31f3e5-0d26-45f8-90f5-94093316e57b.png)
![168299279-5427900d-a15c-423c-a417-08c1a4d0e005](https://user-images.githubusercontent.com/50653464/168303197-9dd78301-7e3f-43b5-b880-a3af4c102707.png)

But not when request season of anime serie:
![168299440-66e832e2-3e87-460d-8205-3a8913c1ca6c](https://user-images.githubusercontent.com/50653464/168303348-4ecb8055-048e-4ecc-a4c8-fc9b7d342137.png)
![168299594-5a003513-c766-4f2a-89b5-bc3a75854901](https://user-images.githubusercontent.com/50653464/168303408-2093ce79-d9f0-4447-a56b-55b577e01c21.png)
![168299621-702057cf-6780-41d8-89ee-2ae220a5ffdd](https://user-images.githubusercontent.com/50653464/168303427-13653966-e240-4f4d-a95c-1aaf19e64641.png)

**Desktop**
 - Ombi docker: https://hub.docker.com/r/linuxserver/ombi/

**Ombi Version:**
 - Version: 4.16.12
- Media Server: Jellyfin
- Database Type: MySQL (also tested with another setup from friend using SQLite)

**Comment by samos667** [comment]
I know why now, when Ombi request anime to Sonarr he select "anime" series type to Sonnar instead "standard" so Sonnar even when requesting a season or more it searches the episodes individually.
![image](https://user-images.githubusercontent.com/50653464/168446909-2303a933-ff8a-4a65-aa37-9b1d7c213705.png)
![image](https://user-images.githubusercontent.com/50653464/168446927-542c3ced-2261-4626-9c51-48ecbc3e717a.png)

**Comment by samos667** [comment]
I think use standard type for anime shouldn't be a problem. To be honest I don't see the benefit to set another type than standard.

**Comment by tidusjar** [comment]
This is expected behaviour. 
A lot of people rely on this current behaviour that any Anime requests use the Sonarr `Anime` type.
