### ISSUE TITLE
Plex media sync failing when encountering media with missing video info

### ISSUE THREAD

**Issue by bhedtke** [Ombi-app/Ombi#4657]
**Describe the bug**
plex media sync fails when encountering a movie with missing metadata.

**To Reproduce**
Add video to plex that has missing metadata information in file. Plex will then be missing several attributes in the Media tag xml

**Expected behavior**
Ideally, an issue would be raised with the movie/episode, but skipping and adding a warning in the logs would be an quick way to triage.

**Screenshots**

**Logs (Logs directory where Ombi is located)**
2022-05-19 20:27:48.261 -05:00 [Error] Exception when adding new Movie "Mr. Holmes"
System.NullReferenceException: Object reference not set to an instance of an object.
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.MovieLoop(PlexServers servers, Mediacontainer content, HashSet`1 contentToAdd, Dictionary`2 contentProcessed) in /home/runner/work/Ombi/Ombi/src/Ombi.Schedule/Jobs/Plex/PlexContentSync.cs:line 317

**Desktop (please complete the following information):**
 - OS: Docker in unraid 

**Ombi Version (please complete the following information):**
 - Version 4.20.0
- Media Server Plex
- Database Type: SQLite

**Additional context**

**Comment by tidusjar** [comment]
Do you have an example of the XML or any idea what attributes are missing?

**Comment by bhedtke** [comment]
I unfortunately resolved the issue in plex by replacing the file and rescanning without saving the old xml first. I do remember the media tag missing nearly every attribute. 
Example: <Media id="101538">.  I did try to reproduce this but didn't have success.

**Comment by tidusjar** [comment]
That sounds like a bug in Plex. Thanks for reporting it. I’ll have a dig around in the Ombi code to see if I can prevent it from stopping the scan
