### ISSUE TITLE
Partial request button not showing

### ISSUE THREAD

**Issue by Reddax** [Ombi-app/Ombi#4658]
**Describe the bug**
Request button not showing for some partially available shows, even though it says 'Partially Available' at the top.
(Initially raised on reddit, posting on here for better tracking - https://www.reddit.com/r/Ombi/comments/ux0jhk/partial_request_not_showing/)

When searching for these shows that do not have the request button, on the search screen, they are showing 'Available' rather than Partially Available in the search.

**To Reproduce**
1. Have a partially available show, in my case I have season 1 of "Only Murders In the Building."
2. No request button to request the second season.

**Expected behavior**
The request button should be available to request the missing season/episodes

**Screenshots**
![image](https://user-images.githubusercontent.com/1349626/170505610-92b22052-206e-43c0-a964-e755fff70c76.png)
![image](https://user-images.githubusercontent.com/1349626/170505657-22d3c79f-5544-4001-8888-391069ea718f.png)

![image](https://user-images.githubusercontent.com/1349626/170505943-ddbdb25c-19ad-4543-b6f9-cddad6ae79c8.png)

**Logs (Logs directory where Ombi is located)**
Don't think there's anything in logs, can post if required.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11

**Ombi Version (please complete the following information):**
 - Version [e.g. 4.0.958] 4.16.12 
- Media Server [e.g. Plex] Plex
- Database Type: SQLite (Please change if using MySQL)

**Additional context**
Clicking the tickboxes for the missing episodes/seasons does nothing. There's no button to request.

**Comment by tidusjar** [comment]
I can't seem to reproduce, you should be able to check the checkboxes next to the episode to also request
