### ISSUE TITLE
Not showing some available media on "Discover" page, AND "Play on Emby" redirects to some bogus page....

### ISSUE THREAD

**Issue by Nostradamus1973** [Ombi-app/Ombi#4659]
**Description of bug**

Ombi(4.20.0) is not showing some available media on "Discover" page, AND "Play on Emby" redirects to some bogus page....

**To Reproduce**
1.Go to Discover page and view releases(Morbius/Ambulance) that are known to be in my collection.

- Expected behavior: They should be listed as available.
- Actual behavior: They are not listed as being available.

2. Then, Click on on previously mentioned releases.

- Expected behavior: Releases should be properly displayed as being in my collection.
- Actual behavior: Releases ARE properly displayed as being in my collection.
- 
3. Click on "Play on Emby" for any available media.

- Expected behavior: The site should redirect to the proper emby play address.
- Actual behavior: Ombi redirects to some bogus site. To me, it looks like the port is missing and instead of bringing me to a http addy, it brings me to a https one instead.

4. The Ombi Android app(latest rev from Play Store) has the same problem of not showing the available media, however, it DOES play the any given media file properly through emby. 
 
My thoughts are there's a address forwarding problem with the "Play on Emby" problem related to the port and/or https redirects, meaning, I'm noticing port 8096 is not in the address and instead of bring me to a http addy for emby to play, it brings me to a https one instead.

**Screenshots**
See attached screenshots

**Logs (Logs directory where Ombi is located)**
See attached logs.

**Desktop (please complete the following information):**
 - OS: Kubuntu 20.04 LTS
**Ombi Version (please complete the following information):**
 - Version: 4.20.0
- Media Server Emby
- Database Type: SQLite
![Screenshot_20220526_143637](https://user-images.githubusercontent.com/36576365/170681773-bbc023d5-de78-406d-b0e1-23c83a6fb87a.png)
![Screenshot_20220526_143608](https://user-images.githubusercontent.com/36576365/170681775-b5e6462b-eb86-4388-989d-0239f67e5479.png)
![Screenshot_20220526_143536](https://user-images.githubusercontent.com/36576365/170681779-2a2444c5-5045-4ba5-a712-f9d570132fb4.png)

[Nostradamus1973-error-log5-27-22-ombi.txt](https://github.com/Ombi-app/Ombi/files/8785914/Nostradamus1973-error-log5-27-22-ombi.txt)

**Comment by tidusjar** [comment]
> Ombi redirects to some bogus site. To me, it looks like the port is missing and instead of bringing me to a http addy, it brings me to a https one instead.

Check your emby settings page in Ombi to ensure your externally facing hostname at the bottom is correct. After that please run the Clear data and resync button.

**Comment by Nostradamus1973** [comment]
I did that more than half a dozen times already with different address variations, even getting desperate and adding the port which I think shouldn't be necessary, but I did it anyways.
All with the same results.

**Comment by tidusjar** [comment]
So the URL that is behind the `Play on Emby` button comes from the Externally Facing Hostname. That's stamped in the database when we find media. That's why it's important after updating that URL to Clear and Resync.

Feel free to email me a screenshot of the settings
