### ISSUE TITLE
.NET Runtime Errors 'Ombi.Store.Context.MySql.SettingsMySqlContext'

### ISSUE THREAD

**Issue by Spaatz1402** [Ombi-app/Ombi#4660]
**Describe the bug**
I keep getting repeated errors in the Event Viewer of Windows 11 indicating an issue with MySQL.  I use the MySQL database type to run Ombi per recommendation.  "System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. "

**To Reproduce**
1.)  Go to Event Viewer
2.)  See error(s) (Critical)

**Expected behavior**
No errors filling up my event logs?

**Logs (Logs directory where Ombi is located)**
No logs referencing error have been made in Ombi.

**Screenshots**
```
Category: Microsoft.EntityFrameworkCore.Query
EventId: 10100

An exception occurred while iterating over the results of a query for context type 'Ombi.Store.Context.MySql.SettingsMySqlContext'.
System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()

Exception: 
System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
```
**Desktop (please complete the following information):**
 - OS: Windows 11 Pro, 64 Bit, Nightly Build

**Ombi Version (please complete the following information):**
 - Version 4.20.1
- Media Server Plex 4.76.1
- Database Type: MySQL

**Additional context**
Thousands of these errors in the event log.

**Comment by Berserkir-Wolf** [comment]
That almost looks like Ombi is trying to undertake a new copy of a task before an old one finished - have you edited any of your [cron schedules](https://docs.ombi.app/settings/jobs/) in Ombi itself?

**Comment by Firetop** [comment]
I have these errors as well; and yes I have modified some of the cron schedules in Ombi.

**Comment by Firetop** [comment]
The error was in the Ombi logs for me though: https://github.com/Ombi-app/Ombi/issues/4726
