### ISSUE TITLE
sonarr anime series type error

### ISSUE THREAD

**Issue by LuckyPuppy514** [Ombi-app/Ombi#4663]
**Describe the bug**
request anime but sonarr series type was standard

**To Reproduce**
1. search anime like: The Greatest Demon Lord Is Reborn as a Typical Nobody
2. Click on 'Request'
3. Go to sonarr and you will see series type: Standard

**Expected behavior**
sonarr series type should be anime while request anime

**Screenshots**
![image](https://user-images.githubusercontent.com/53246532/171041899-2eeae085-0372-4b6a-a380-355cc6a0b986.png)

**Ombi Version (please complete the following information):**
 - Version latest
 - Version arm64v8-development-v4.15.0-ls248
 - Version 4.20.1-development
- Media Server [Docker]
- Database Type: SQLite

**Additional context**
I also try the latest version in windows but fail 
until i change version to v4.0.1468 in docker and it work

**Comment by tidusjar** [comment]
There’s not much I can do here. We use the categories from TheMovieDb to set if it’s an anime. 

So it needs fixing on TheMovieDb end

**Comment by LuckyPuppy514** [comment]
thanks for answer, but it wasn't due to TheMovieDb.
it work good with v4.10.2 in docker, but fail with v4.16.2 or other version after v4.10.2.

i found the reason: 
if language set to chinese, request anime the series type in sonarr will be standard
but when i change to english, it work well
![image](https://user-images.githubusercontent.com/53246532/171088007-ad6e5d87-458b-4819-a85e-05ada18a56bf.png)
