### ISSUE TITLE
"Request on behalf of"-user dropdown has blanks

### ISSUE THREAD

**Issue by grimsan55** [Ombi-app/Ombi#4664]
**Describe the bug**
When requesting a movie and use the dropdown to select a user it contains blank rows. I have all my users synced from Plex. The second screenshot posted has his or her users synced from Emby.

**Expected behavior**
I expect to see my users and not a blank line

**Screenshots**
https://i.imgur.com/myJwaQR.png
https://i.imgur.com/I3lGzJ6.png
![myJwaQR](https://user-images.githubusercontent.com/8499989/171044938-184c7268-8f24-49be-aa99-fb3a33c68c60.png)
![I3lGzJ6](https://user-images.githubusercontent.com/8499989/171044935-34301dd5-58a7-4413-99db-e92ef148bb0f.png)

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Ombi Version (please complete the following information):**
 - Version 4.20.1
- Plex
- Database Type: SQLite

**Additional context**
This should be a newly introduced bug, cause the user that has a blank space in the dropdown, i usually request from quite frequently.

**Comment by tidusjar** [comment]
This has been fixed in develop
