### ISSUE TITLE
sonarr anime series type error when language in chinese

### ISSUE THREAD

**Issue by LuckyPuppy514** [Ombi-app/Ombi#4666]
**Describe the bug**
request anime but sonarr series type was standard when language in chinese

**To Reproduce**
1. search anime like: The Greatest Demon Lord Is Reborn as a Typical Nobody
2. Click on 'Request'
3. Go to sonarr and you will see series type: Standard

**Expected behavior**
sonarr series type should be anime while request anime

**Screenshots**
![image](https://user-images.githubusercontent.com/53246532/171041899-2eeae085-0372-4b6a-a380-355cc6a0b986.png)

**Ombi Version (please complete the following information):**
 - Version 4.16.12
- Media Server [Docker]
- Database Type: SQLite

**Additional context**
thanks for answer #4663, but it wasn't due to TheMovieDb.

i found the reason: 
if language set to chinese, request anime the series type in sonarr will be standard
but when i change to english, it work well
![image](https://user-images.githubusercontent.com/53246532/171088007-ad6e5d87-458b-4819-a85e-05ada18a56bf.png)

_Originally posted by @LuckyPuppy514 in https://github.com/Ombi-app/Ombi/issues/4663#issuecomment-1141636515_

**Comment by tidusjar** [comment]
This is outside of Ombi, This is an issue on TheMovieDb, it seems that they are not categorising the show correctly in another language
