### ISSUE TITLE
Plex OAuth not functioning

### ISSUE THREAD

**Issue by PiJiNWiNg** [Ombi-app/Ombi#4676]
**Describe the bug**
Whenever users other than myself (admin) try to login into Ombi via mobile or desktop using plex authentication it says "You have successfully signed in. You may now close the window." The window, doesn't auto close and it doesn't log into ombi. Attempting to go directly to the ombi page afterward results in the error "You are not authenticated with ombi" on the login page.

**To Reproduce**
1. Select "Sign in with Plex"
2. Sign in
3. Successful sign in confirms
4. Plex authentication site sits idle on confirmation page

**Expected behavior**
Auto redirect from Plex authentication screen to Ombi homepage

**Screenshots**
N/A

**Logs (Logs directory where Ombi is located)**
2022-06-13 12:53:55.797 -07:00 [Debug] Batch acquisition of 0 triggers
2022-06-13 12:54:01.552 -07:00 [Error] StatusCode: NotFound, Reason: Not Found, RequestUri: https://plex.tv/api/v2/pins/1920508506
2022-06-13 12:54:01.552 -07:00 [Error] Code: '1020' : 'Code not found or expired'
**(This repeats many times)**

**Desktop (please complete the following information):**
 - OS: Windows 10, Android, iOS

**Ombi Version (please complete the following information):**
 - Version: 4.7.11
- Media Server: Plex
- Database Type: SQLite 
- Server OS: Debian

**Additional context**
I recently built this server and I've not had this working yet. As I mentioned, oddly Plex OAuth works or me but not for my other users.

**Comment by tidusjar** [comment]
So the reason that would happen is if the Plex user has not been imported into Ombi, OR that plex user has the role of `Disabled`

**Comment by PiJiNWiNg** [comment]
@tidusjar @gaetanperrin 
That seemed to resolve my issue. Performed the following steps to fix:
1. Settings/Configuration/User management - Toggled Import Plex Users - Save
2. Toggled appropriate 'Default Roles' (Request Movie and Request Tv in my case)
3. Clicked 'Run Importer' at the bottom of that page
4. Selected 'Users' on the left, verified users imported and had correct roles
5. Tested successfully

I will say that coming from v3 importing the users was not required for the Plex oAuth to function, which is why I missed this in my initial config. In fact if I remember correctly, importing those users just created a username/password login for those users as opposed to using Plex to authenticate.

Thanks for the direction!
