### ISSUE TITLE
OMBI UNRAID docker app broken after the latest update

### ISSUE THREAD

**Issue by E-Man68** [Ombi-app/Ombi#4679]
**Describe the bug**
After UNRAID Docker OMBI app updated a few days ago, now my OMBI server is stuck at the Wizard screen. My OMBI server was working perfectly prior to the update.

**To Reproduce**
1. Go to 'Docker..'
2. Click on 'Update all Dockers'
3.  Launch OMBI
4. the OMBI LOGON screen briefly flashes, then goes to Wizard screen
5. just stuck at Wizard in loop ... no matter what you enter on the wizard pages it cycles back to the 1st wizard page with various errors 

**Expected behavior**
After the update I expected just to logon onto OMBI as usual.

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: UNRAID 6.9.2

**Ombi Version (please complete the following information):**
 - Version: linuxserver/ombi:v4.16.12-ls127 (latest version at time of this writing)
- Media Server : Plex  ... I have Jellyfin installed on my UNRAID server, but chose not to integrate it with OMBI 
- Database Type: SQLite on maria DB docker container

**Additional context**
I've tried all combinations to get past this wizard screen.  I've seen various errors.  authenticate with PLex token no longer works in the wizard.  I can manually enter my plex logon credentials to connect to plex in the wizard, but the next step to creat a  new local OMBI Admin account does not work.  on the next screen when I click finish it always loops back to the start of the wizard.  With various error messages ...

for new local admin account --> error "user needs to setup email"
for my known ombi local admin account -->  error user alraedy exists"

I've also seen errors message stating it can't log me onto my plex server, but yet I can log into plex with same credentials from other apps.

sounds like the whole authtication process is messed up.

I know my OMBI DB on my maria DB server is fine .... has all the tables.
and I do have the database.json file in my ombi appdata folder pointing to the IP of my Maria DB server with the correct instance, username and password.  

This was all working before.

**Comment by tidusjar** [comment]
It sounds like your database has gotten into a strange state or perhaps the settings are no longer there for some reason. 

The best way to fix this without losing your data would be to update the database and set the `Wizard` flag in the `GlobalSettings` table to true. 

To do this grab the string output from this query:

```
SELECT Content FROM `GlobalSettings` WHERE SettingsName = 'OmbiSettings';
```

Take that string and change `"Wizard": false` to `"Wizard": true` and then update the record:

```
Update GlobalSettings SET Content = 'NEWSTRING'
```

Where `NEWSTRING` is the updated `Content`

**Comment by tidusjar** [comment]
If you MariaDB instance that's inside the `database.json` file doesn't have the `GlobalSettings` table then the databases have not been setup correctly.

What does your `database.json` look like?

**Comment by E-Man68** [comment]
Strange .. this was working for several weeks until I updated a few days back.


This is the contents of the database.json …. All I did was modify the original with my ip and PW …


{
    "OmbiDatabase": {
        "Type":"MySQL",
        "ConnectionString":"Server=”the ip address of my unaid server running maria db”;Port=3306;Database=Ombi;User=ombi;Password=My Password"
    },
    "SettingsDatabase": {
        "Type":"sqlite",
        "ConnectionString":"Data Source=Settings.db"
    },
    "ExternalDatabase": {
        "Type":"sqlite",
        "ConnectionString":"Data Source=External.db"
    }
}



I assumed that was all I needed to modify.


It seemed to work as on first run as it connected to the empty OMBI DB I created on maria server and populated the ombi DB with the tables.  And everything on OMBI was working for weeks.  History, requests, users & e-mails etc …

All working amazingly.   ☺  Until updates.



Thanks,

E


BTW for future updates is there a proper process.  Ie\ on UNRAID sometimes half or more of my docker containers get update weekly.  I usually choose update all.  Not sure how the update order is determined but this is what I have been doing for the past year.

Should I be shutting down …

·         Maria DB

·         Plex

·         OMBI


And then update them one at a time and which order ?

Or was this just a hiccup when the last updates were applied ?

**Comment by tidusjar** [comment]
Ok the fact that you are using half MariaDB and the other half SQLite is not something that I would recommend. 

But it does explain quite a lot. So your Ombi instance is getting it's settings from the `OmbiSettings.db` file on your file system, when you upgraded it's possible that you deleted/lost that database? 

Because that would make Ombi think that it needs to start all over again.

If you send me your OmbiSettings.db to tidusjar@gmail.com I can edit the database and fix that for you, but going forward I suggest that you try and switch to using a full setup using MySql/MariaDB
