### ISSUE TITLE
"You are not authenticated with Ombi" After sign in with Plex 

### ISSUE THREAD

**Issue by wipzcream** [Ombi-app/Ombi#4681]
**Describe the bug**
When sign in with plex it shows a pop-up "You are not authenticated with Ombi" and Ombi cannot access it for a few minutes.

**Screenshots**
<img width="1680" alt="Screen Shot 2565-06-30 at 20 09 49" src="https://user-images.githubusercontent.com/108471483/176813269-b20ab7b3-3eea-42ce-a3c5-8442f4a574dd.png">

**Logs (Logs directory where Ombi is located)**
[Ombi Logs.txt](https://github.com/Ombi-app/Ombi/files/9024705/Ombi.Logs.txt)

**Ombi Version (please complete the following information):**
 - Version 4.16.12
- Media Server: Plex version 1.27.1.5916
- Database Type: SQLite 
- Unraid OS version: 6.10.3

**Comment by tidusjar** [comment]
This means that your Plex user has not been imported into Ombi or you have the Disabled role.

**Comment by wipzcream** [comment]
I already imported a user from plex and it show the same

**Comment by tidusjar** [comment]
Is the user disabled? Do they have the disabled role?

**Comment by wipzcream** [comment]
The user is not disabled because I share my plex media with a new user and the Users menu on Ombi it has new user information and I already enable plex oauth

**Comment by tidusjar** [comment]
There is a role in Ombi called 'Disabled' does the user in question have that role?

Can you screenshot the user on the User management page and post it here? (feel free to scribble out the email)

**Comment by wipzcream** [comment]
Yes he does. please kindly see a screenshot below 

<img width="1277" alt="Screen Shot 2565-07-01 at 18 11 25" src="https://user-images.githubusercontent.com/108471483/176884649-945d42be-075e-440a-abc4-d31d6ec9d7ac.png">

<img width="1387" alt="Screen Shot 2565-07-01 at 18 20 41" src="https://user-images.githubusercontent.com/108471483/176885087-a58675b3-eb25-4435-b711-7fdaa592361a.png">

**Comment by wipzcream** [comment]
I have removed 'Disabled' in the user roll it work !!, thank you for your support and so sorry for my error

**Comment by SecurityForces702** [comment]
I am having the same error after Updating... only thing is I am the administrator and cannot even login to check the "Disabled" setting or anything.  So I am like 100% locked out as of right now.

**Comment by blckassassin** [comment]
Same problem here.  locked out of admin account.

**Comment by quinnell** [comment]
Having the same issue. Cannot log into my admin account. Just throws a "You are not authenticated with Ombi" error after successfully authenticating with Plex

**Comment by tidusjar** [comment]
If you are using Plex to log in. Ensure that your Plex user is in the user management page as a Plex user type and not a local user type.

**Comment by SecurityForces702** [comment]
Yup using Plex user in the user management page….

It use to work and then one day totally stopped working...

**Comment by quinnell** [comment]
I discovered my problem. The Local user I've been using for years has always been tied to my Plex OAuth. However, it lost that link after I changed the username.

I was able to use MySQL to add the admin role to another user and reset the local password.  After running import, it's pulling my Plex account under the new username.

**Comment by ramymounir** [comment]
> Is the user disabled? Do they have the disabled role?

who are they? how dodo I know If the user is disabled? how or where duo I enable it please?
