### ISSUE TITLE
An attempt was made to access a socket in a way forbidden by its access permissions

### ISSUE THREAD

**Issue by xSetrox** [Ombi-app/Ombi#4682]
**Describe the bug**
When trying to request a movie as myself, I get an error for both raw.githubusercontent.net:443 and webservice.fanart.tv:445 saying "an attempt was made to access a socket in a way forbidden by its access permissions".
The request never goes into "failed requests" nor does it show up anywhere in requests at all. When I click the button to request it just constantly shows the spinning circle animation on the title art.

**To Reproduce**
1. Be logged in as admin
2. Request any movie or show
3. Check log and see the error

**Expected behavior**
The movie should successfully be requested

**Screenshots**
N/A, just a log suffices

**Logs (Logs directory where Ombi is located)**
https://gist.github.com/xSetrox/1e5b952453be028deb6ebd8f6588231a

**Desktop (please complete the following information):**
 - OS: Windows 10

**Ombi Version (please complete the following information):**
- Version 4.21.0
- Media server: Plex
- Database Type: SQLite

**Comment by tidusjar** [comment]
This is probably because your web server is not allowing Web Socket connections. It's fine if you do not want to allow it, and it will not cause any issues for Ombi
