### ISSUE TITLE
TV Show/Movie Poster not showing due to extra '/' in URL

### ISSUE THREAD

**Issue by Reddax** [Ombi-app/Ombi#4685]
**Describe the bug**
I've found a few shows/films where the poster image doesn't load, and it's because the image url has an extra '/' in it.

**To Reproduce**
1. Search for 'the unforgiven' (This can be reproduced on the Ombi Demo site, too.)
2. You'll see that the images haven't loaded.
3. Go into the browser developer mode(F12) and use the select an element tool on a movie.
4. For the CardImage element, if you copy the url, you'll notice it has an extra '/' in it, for example; https://image.tmdb.org/t/p/w300//nOazqRGdagQejQe3BFUCJZXtD3l.jpg
if you load the URL, it doesn't work. If you take out the extra '/' after 300, it works. Example;'
https://image.tmdb.org/t/p/w300/nOazqRGdagQejQe3BFUCJZXtD3l.jpg

**Expected behavior**
Image should load, but won't because of the extra '/' in the url.

**Ombi Version (please complete the following information):**
 - Version [e.g. 4.0.958] 4.16.12
- Media Server [e.g. Plex] Plex
- Database Type: MySQL

**Comment by tidusjar** [comment]
Turns out it's nothing to do with the additional `/`. Looks like TheMovieDB have gone in harder with their rate limiting
