### ISSUE TITLE
Provide a flag for missing users on Plex Server

### ISSUE THREAD

**Issue by ChrisColotti** [Ombi-app/Ombi#4688]
Was asked to add here from Discord channel but...

While Ombi tries to remove stale users I've seen sometimes they remain and have to do manual cleanup.  Tautulli solves this with a simple yellow flag that states "User not found on plex Server" when it does a user API pull.  This can help speed up user Management when you clean up sharing on your plex account or a user removes themselves so Ombi is always up to date with the same users even if needed to be done manually.  The stale users will be easy to find.

**Comment by ChrisColotti** [comment]
@tidusjar I did add as an official "feature" as well since this had been auto closed LOL

**Comment by ChrisColotti** [comment]
I do know it's not cleaning out missing users I tested removing someone the other day.  Tautulli shows them as missing, but the same user is still listed in the Ombi DB.  This can definitely use a little tweaking to either automatically or manually keep things lined up.  Thanks for everything!

**Comment by sephrat** [comment]
Added in v4.29.0
