### ISSUE TITLE
SSO with Header Authentication - Authelia

### ISSUE THREAD

**Issue by olaxe** [Ombi-app/Ombi#4695]
**Describe the bug**
Cannot authenticate using the SSO with Header Authentification from Authelia and at the same time, using the API login from the native Ombi App (Android)

**To Reproduce**
Enable the Header Authention in Ombi / Settings / Configuration / Authentication
Authelia works fine and at the Reverse Proxy level, I have added: REMOTE_USER
I can make it works with Remote-User

If I try to connect using the Ombi application, it doesn't work anymore because the /api needs to be excluded from Authelia at the RP level. If I exclude /api, the Header Authentication doesn't work anymore.

**Expected behavior**
Know a way to add the location API with the Authelia information without blocking the authentication using the Ombi application
on the mobile.

**Desktop (please complete the following information):**
 - OS: Linux / Chromium

**Ombi Version (please complete the following information):**
 - Version 4.16.12
- Media Server Jellyfin
- Database Type: MySQL

**Comment by tidusjar** [comment]
See https://docs.ombi.app/settings/authentication/#enable-authentication-with-header-variable

**Comment by ModdingFriendly** [comment]
Hey @tidusjar 👋 

I've tried setting this up and I've ran into the same issue as the above. I can't appear to get this working with or without authorising the `/api` path. 

![Untitled](https://github.com/Ombi-app/Ombi/assets/6255266/91c5b164-ee25-4685-8a11-16b1e8226105)


If I decode the auth headers I get the same token from `/api/v1/token/header_auth`  & `/api/v1/Request/movie/remaining` but  Request, Radarr & Sonarr return 401's I know it's not a lot of information but can you think of anything obvious that I'd be missing from Ombi or Authentik that's causing these to fail?

**Comment by iamnague** [comment]
Hi, I'm wondering if this behavior has been solved ? I'd like setting up authentik for human authentication, and keep android app working.
