### ISSUE TITLE
Images not loading correctly

### ISSUE THREAD

**Issue by screamjojo** [Ombi-app/Ombi#4698]
**Describe the bug**
Sometimes images do not load, I need to reload the page with F5.
I delete ombiexternal.db and restart but don't work.
Same problem on chrome with my phone.

**To Reproduce**

**Expected behavior**
Pictures need to load

**Screenshots**

![ombi](https://user-images.githubusercontent.com/71469935/180668815-f3575477-cfe0-48b1-94b2-40582abfaef3.PNG)

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Docker

**Ombi Version (please complete the following information):**
 - Version 4.22.0
- Media Server : Plex
- Database Type: SQLite (Please change if using MySQL)

**Additional context**

**Comment by tidusjar** [comment]
Are there any errors in your browser console? F12.

If so can you press the network tab and then refresh the page and you should see something like
![image](https://cloud.githubusercontent.com/assets/6642220/23088047/eac44abc-f570-11e6-9f23-d2eb022ed059.png)


If you click the red text and then the preview tab like the image above and post the result?

**Comment by screamjojo** [comment]
Thanks for your reply,
the preview tab is blank :( 
But when I check the timing tab the "waiting for server response" is very long when an images won't load.
Here screenshoots : 


![1](https://user-images.githubusercontent.com/71469935/180763383-48ddacae-cf91-4594-9a5d-05e16fcd4d1c.PNG)
![2](https://user-images.githubusercontent.com/71469935/180763394-a4546c2d-dae2-477d-8c9d-7ea15298e506.PNG)

**Comment by tidusjar** [comment]
Thanks! What’s the http status code for the red ones?

**Comment by screamjojo** [comment]
Like that ? : 

![3](https://user-images.githubusercontent.com/71469935/180785865-528ce755-1d5c-4932-bb2e-ce5793f28f20.PNG)

**Comment by tidusjar** [comment]
This is fixed

**Comment by screamjojo** [comment]
Thanks !!
