### ISSUE TITLE
Unable to Delete Jellyfin Server

### ISSUE THREAD

**Issue by TheDadNerd** [Ombi-app/Ombi#4705]
**Describe the bug**
In the media server settings of Ombi, once a Jellyfin server is added it can't be removed or disabled. 

**To Reproduce**
1. Have a Jellyfin server connection setup
2. Go to settings - media server- jellyfin
3. Try to delete the server or toggle the "Enable" button. 
4. Submit button is greyed out and when you leave this page and come back the server returns and is back to being enabled

**Expected behavior**
Jellyfin would be disabled or deleted

**Desktop (please complete the following information):**
 - OS: running in docker, accessing via Chrome browser

**Ombi Version (please complete the following information):**
 - Version 4.16.12
- Media Server: Plex (trying to remove old Jellyfin
- Database Type: MySQL

**Comment by NX211** [comment]
+1

**Comment by sephrat** [comment]
Should be fixed in v4.29.0
