### ISSUE TITLE
Request not sent to Radarr

### ISSUE THREAD

**Issue by stevenatherton42** [Ombi-app/Ombi#4709]
**Describe the bug**
Movies requests are being processed by Ombi and show as "processing request" but do not get sent to Radarr. Sonarr requests are being processed correctly.

**To Reproduce**
1. Request movie
2. Movie shows as "processing request"
3. Movie does not get added to Radarr

**Expected behavior**
I expected the movie to be added to Radarr, processed and and downloaded

**Logs (Logs directory where Ombi is located)**
Log file attached

**Desktop (please complete the following information):**
 - OS: Windows 10

**Ombi Version (please complete the following information):**
 - Version 4.22.3
- Media Server: Plex
- Database Type: SQLit

[log-20220730.txt](https://github.com/Ombi-app/Ombi/files/9226544/log-20220730.txt)

**Comment by tidusjar** [comment]
In your log its saying that Ombi is timing out when talking to radarr.
Double check your hostname and ip etc

**Comment by stevenatherton42** [comment]
Thank you. Seems maybe the problem is with radarr. I've noticed when I open
radarr it takes a few minutes to load library
