### ISSUE TITLE
Version notifier says there's a development release update for the stable branch build

### ISSUE THREAD

**Issue by Gwindalmir** [Ombi-app/Ombi#4714]
**Describe the bug**
The version notifier shows updates for the wrong branch.
Being on the stable branch (currently 4.16.12), shows there's an update available on the develop branch (4.22.1).

**To Reproduce**
1. Install OMBI 4.16.12 (used docker in this case)
2. Click on Settings
3. Look at Version row (wait a few seconds, or refresh)
4. See it says "New Update Available"

**Expected behavior**
If the current version is on the stable branch, it should not show pre-release versions as available updates.

**Screenshots**
![image](https://user-images.githubusercontent.com/1127170/182531205-9f51bc29-e9d8-47e5-bdc6-5e176f86fc09.png)
![image](https://user-images.githubusercontent.com/1127170/182532815-8e750391-4a00-4755-bf2d-c13c79fe15a0.png)

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: OpenMediaVault 5.6.26-1

**Ombi Version (please complete the following information):**
- Version 4.12.16 (running in Docker, [lscr.io/linuxserver/ombi:latest](https://hub.docker.com/r/linuxserver/ombi))
- Media Server: Plex
- Database Type: SQLite

**Comment by tidusjar** [comment]
In the ombi general settings, change your branch. It's cached but when the cache expires it will show the correct version

**Comment by Gwindalmir** [comment]
Ah thanks, for some reason my branch was set to Develop. I didn't even realize it was an option, I just though it was based on the version I installed.
