### ISSUE TITLE
Radarr and Sonarr Settings "We could not connect to ..."

### ISSUE THREAD

**Issue by piratman38** [Ombi-app/Ombi#4717]
**Describe the bug**
Movies and Series requests are being processed by Ombi and show as "processing request" but do not get sent to Radarr and Sonarr. When checking the settings of Radarr and Sonarr, the "Check connectivity" button results in a failure message "We could not connect to Radarr" and "We could not connect to Sonarr".
I double checked my Host and Port, and everthing is fine.
It worked well with this settings for month, but suddenly it stopped, after an update of all Ombi, Radarr and Sonarr.

**To Reproduce**
1. Request movie or serie
2. Movie or serie shows as "processing request"
3. Movie does not get added to Radarr / Serie does not get added to Sonarr

**Expected behavior**
I expected the movie or serie to be added to Radarr, processed and and downloaded

**Logs (Logs directory where Ombi is located)**
[log-20220805.txt](https://github.com/Ombi-app/Ombi/files/9270482/log-20220805.txt)

**Desktop (please complete the following information):**
 - OS: Linux 4.19.0

**Ombi Version (please complete the following information):**
- Version 4.16.12
- Media Server: Plex
- Database Type: SQLite

**Additional context**
- Radarr : Version 4.1.0.6175
- Sonarr : Version 3.0.8.1507

**Comment by tidusjar** [comment]
It’s saying the connection is being refused. What this means is Ombi cannot connect to them. I suggest you check your firewalls or try maybe an ip address or something g.

**Comment by piratman38** [comment]
Thank you for your prompt reply. 
The issue is solved : I use Radarr, Sonarr and Lidarr as dockerzied applications. Therefore, the port displayed in their Settings/General tab will always be the default port and refers to the port in the container.
It is mapped to a different port on the host machine.
I have just learnd something.

Thank you again for your good work
