### ISSUE TITLE
New version available even just upgraded to the last one

### ISSUE THREAD

**Issue by kikyalex** [Ombi-app/Ombi#4719]
**Describe the bug**
Using Ombi in docker from LinuxServer (https://github.com/linuxserver/docker-ombi)
I've just upgraded to the last version available now, 4.22.5 but I still see the "New Update Available" message in /Settings/About

**To Reproduce**
1. Go to /Settings/About page
2. Check message  "Version 4.22.5    (New Update Available)" 
3. It leads me to 4.22.4 (pre-release) even I have installed 4.22.5

**Expected behavior**
The message "(New Update Available)" should not be displayed if I have a newer version than the latest pre-release.

**Screenshots**
![image](https://user-images.githubusercontent.com/3935070/183215791-f2d4c02e-a8ad-4f4c-9d83-0aa180d0f68a.png)

![image](https://user-images.githubusercontent.com/3935070/183216852-682e2f94-e39f-489c-8ad4-7add67c8e44f.png)

**Logs (Logs directory where Ombi is located)**
I think this is not needed

**Desktop (please complete the following information):**
 - OS: Ubuntu 2022.4 
 - Install: Docker version https://github.com/linuxserver/docker-ombi latest ( v4.22.5-ls130 Build-date:- 2022-08-05T14:38:26-05:00)

**Ombi Version (please complete the following information):**
 - Version: 4.22.5
- Media Server: Plex
- Database Type: SQLite (default one)

Edit: Added second image

**Comment by sephrat** [comment]
Fixed in v4.28.1
