### ISSUE TITLE
Recently requested image doesn't fallback to default image when no poster found on discover page

### ISSUE THREAD

**Issue by sephrat** [Ombi-app/Ombi#4730]
**Describe the bug**
I have a film that Fanart TV has no image for (922705).
During the page loading, that film has a nice placeholder image and background.
![image](https://user-images.githubusercontent.com/34862846/184091347-77b8f92e-9448-4199-a04a-caac35153d3b.png)

After Ombi returned that no image is found, the placeholder image is removed and the background is black:
![image](https://user-images.githubusercontent.com/34862846/184091382-703c769f-ec5b-4a41-80b8-f57841c3ccb3.png)

On a side note, can't we make it so that the poster defaults to the one from TMDB if not found from Fanart TV?

**Comment by andcbii** [comment]
I assume this is why a few movies don't have images under my Recently Requested. I hope this gets fixed as the missing pictures really annoy me.
