### ISSUE TITLE
No content showing on webpage via reverse proxy as opposed to localhost

### ISSUE THREAD

**Issue by richard-lee-863** [Ombi-app/Ombi#4732]
**Describe the bug**
When accessing Ombi via reverse proxy:

- There are no posters showing in the Trending etc.. categories on the Discovery home page.
- Requests page is empty
I thought it was a corrupted database, but after a fresh install, i noticed all these things work fine when accessing ombi via localhost and port. ie: http://localhost:5000

**To Reproduce**
1. Set up personal domain to access remotely
2. Set up ombi base url
3. Set up reverse proxy
4. Access Ombi webpage via localhost and port
5. Compare to Ombi webpage accessed via custom domain and reverse proxy

**Expected behavior**
I would expect to see up to date poster art in the Popular, Trending, Upcoming sections of the Discover homepage. 

**Screenshots**
**Localhost:**
<img width="801" alt="ombi_localhost" src="https://user-images.githubusercontent.com/43104957/184523320-6bef3c87-d396-47c0-9ee5-5fdac38985ee.PNG">

**Reverse Proxy**
<img width="1518" alt="ombi_reverseproxy" src="https://user-images.githubusercontent.com/43104957/184523321-16715e48-5714-4e24-9ebd-f51e73274eb0.PNG">

**Logs (Logs directory where Ombi is located)**
Lots of errors around caching with Plex and other services. Not sure if relevant.

**Desktop (please complete the following information):**
 - Windows 10 64bit

**Ombi Version (please complete the following information):**
- Version [4.22.5]
- Media Server [Plex]
- Database Type: SQLite

**Additional context**
Using Caddy for reverse proxy management.
Other apps like Sonarr, Radarr etc.,. work just fine. 
It did used to work fine many versions ago, but i haven't looked at it for at least a year now. 
Ombi base url set to: /ombi

**Comment by tidusjar** [comment]
Take a look here: https://docs.ombi.app/info/reverse-proxy/

There's no current issue with any reverse proxy setups

**Comment by richard-lee-863** [comment]
Does Caddy v2 have to be used for it to work properly? Didn't realize till just now that Caddy 2 is released. Will have to look at upgrading soon. 
I'm currently using v1 as follows:
```
proxy /ombi 127.0.0.1:3579 {
   transparent
}
```

But seem to run into errors with:
` [ERROR 499 /ombi/images/favicon/favicon.ico] context canceled`
