### ISSUE TITLE
Watchlist cron drops user auth token causing console 'fail' spam

### ISSUE THREAD

**Issue by datacenterdude** [Ombi-app/Ombi#4734]
**Describe the bug**
[Suspicion] With Watchlist tracking enabled, it prevents a user from having to log into Ombi.  Which is great!  Unfortunately, if the user doesn't auth to Ombi with Plex credentials, I suspect the auth token can be dropped over time and Watchlist sync stops happening, results in errors/fails when the cron runs on schedule.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/11467789/185499481-62201719-8aad-4e86-800b-af1c866d3b85.png)

**Logs (Logs directory where Ombi is located)**
Multiple times, repeating, every time the cron runs for Watchlist sync:

> 2022-08-18 00:00:01.799 -07:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://metadata.provider.plex.tv/library/sections/watchlist/all

**Desktop (please complete the following information):**
 - OS: Win10

**Ombi Version (please complete the following information):**
 - Version 4.23.1
- Media Server Plex
- Database Type: SQLite 

**Additional context**

**Comment by tidusjar** [comment]
There's now a button on the Plex Settings screen to view the Watchlist sync status of all your plex users in the development builds
