### ISSUE TITLE
Stuck in wizard loop after migration from sqlite to mysql "Looks like there is an existing user!"

### ISSUE THREAD

**Issue by megapearl** [Ombi-app/Ombi#4747]
**Describe the bug**
Stuck in wizard loop after migrating from sqlite to mysql with error at the end of the wizard "Looks like there is an existing user!"

**To Reproduce**
Follow instructions on: https://docs.ombi.app/guides/migrating-databases/

**Expected behavior**
Login after succesful migration.

**Screenshots**
![image](https://user-images.githubusercontent.com/3420660/188031264-89cd002e-4867-4d4f-9509-e8d6b92f6d8f.png)

**Logs (Logs directory where Ombi is located)**

**Desktop:**
- OS: PhotonOS 5.10.118-14.ph4-esx
- Ombi Version: 4.22.5
- Media Server: Plex 1.28.2.6151
- Database Type: MySQL 8.0.30 (Protocol v10)

**Additional context**
The MySQL db is populated, the files database.json and migration.json do exist and are containing the right information.
I can login fine with phpMyAdmin using the same credentials as Ombi.

**Comment by tidusjar** [comment]
Looks like the database is not fully migrated, I suggest you try again with a backup or jump on the Discord where some guys could help
