### ISSUE TITLE
Discrepancy between Sonarr and Ombi series data between sources

### ISSUE THREAD

**Issue by cybersteel8** [Ombi-app/Ombi#4748]
**Describe the bug**
For one specific TV Show, Columbo, the data between TVDB and TMDB are different.
Ombi seems to use TMDB for series data, but Sonarr uses TVDB by default.
TMDB for Columbo:  https://www.themoviedb.org/tv/873-columbo
TVDB for Columbo: https://thetvdb.com/series/columbo
In particular, look at Season 10.

The problem here is that a user requested this TV show, and all the episodes, so when it was added to Sonarr I did successfully get every episode. But because half of Season 10 are actually listed as Specials, those episodes are not considered available in Ombi since those Season 10 episodes don't exist in Sonarr at all. So I can technically *never* mark this series as Available due to Sonarr and Ombi being misaligned.

**Expected behavior**
Ombi's data source to match Sonarr's to align series/episode lists so that obtained episodes are marked as Available appropriately.

**Screenshots**
![image](https://user-images.githubusercontent.com/17291212/188342403-82b5f960-cf1f-4c23-be05-8646b3d3ba70.png)
![image](https://user-images.githubusercontent.com/17291212/188342430-2d717182-2d30-47bd-a54b-58cb09a87baa.png)
![image](https://user-images.githubusercontent.com/17291212/188342474-3c0a6f41-b71e-4012-aff8-815fa149d82d.png)

**Ombi Version:**
 - Version: 4.22.5
- Media Server: Plex
- Database Type: SQLite

**Additional context**
Using docker image [linuxserver/ombi](https://hub.docker.com/r/linuxserver/ombi/) on Unraid 6.10.3

**Comment by tidusjar** [comment]
Currently there are no plans to switch the underlying data provider to TVDB
