### ISSUE TITLE
Plex Auth Page not appearing after clicking to log in with plex auth

### ISSUE THREAD

**Issue by almulder** [Ombi-app/Ombi#4756]
**Describe the bug**
I have imported users from Plex, They try to sign in with plex auth, a new window opens and its the ombi login page again, plex login auth page never appears.

Also if they are imported from plex, and they use the ombi login and use forgot password, it sends them to plex to reset password. If they are a local user it sends them to ombi to reset password.

**To Reproduce**
impost plex users
change to allow plex auth
logoout
try logging in with plex auth, new screen loads with ombi login screen again and again every time they click plex auth login option
try loggin in with local user using the plex auth same issue

use same user to reset password so they can log in as ombi user and sends them to plex to reset plex password (Via the email)
if a local ombi user tries to reset password it goes to the ombi password reset screen (Via Email)

**Expected behavior**
If they are a plex user or not, I expect plex auto to allow them to login via plex if they are a ombi user. and have the screen go to the plex auth screen

if they go to reset password and they would be directed to ombi password page

**Desktop (please complete the following information):**
 - OS: Unraid

**Ombi Version (please complete the following information):**
 - Version 4.25.1 (Same happened on previous versions)
- Media Server: Plex Version 4.87.2
- Database Type: SQLite 

**Additional context**
I have swag setup so I can access ombi outside of network. Emails and external access all work as intended. Just cant get plex auth to work.

**Comment by tidusjar** [comment]
> They try to sign in with plex auth, a new window opens and its the ombi login page again, plex login auth page never appears.

This is usually down to some reverse proxy issues. Please see https://docs.ombi.app/ for further instructions.

> use same user to reset password so they can log in as ombi user and sends them to plex to reset plex password (Via the email)
if a local ombi user tries to reset password it goes to the ombi password reset screen (Via Email)

This is 100% expected functionality. How do you think that Ombi can reset the password for an account that it does not own?
