### ISSUE TITLE
Radarr movies added in raddar and then removed still show as approved in Ombi

### ISSUE THREAD

**Issue by almulder** [Ombi-app/Ombi#4760]
**Describe the bug**
I have many movies in radarr, they currently show as approved in ombi, I removed several of the movies in radarr, yet the movies continue to show as approved in ombi.

**To Reproduce**
In radarr add a movie, wait for ombi to run the cron job, status changes to approved, remove movie from radarr, wait for ombi's cron job to run, check movie still shows as approved.

**Expected behavior**
If a movies is removed from radarr, movie should nolonger be approved in ombi, if movie was removed and blocked in radarr ombi should show as rejected. 
Movie removed from radarr and not blocked, ombi should show it as request again.

I suspect the same issue will happen with sonarr (No verified)

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Unraid

**Ombi Version (please complete the following information):**
 - Version 4.22.5
- Media Server Plex
- Database Type: SQLite (Please change if using MySQL)

**Comment by tidusjar** [comment]
The movie will show as not requested after the job runs to scan radarr. It’s not instant.

**Comment by almulder** [comment]
Ya I know its not instant, hows it refreshes every 15min via cron, but looks like it took 2 hours as now its finally like it should be, sorry figured it would work every 15 mins (When the cron job runs) now I know. :) Thanks for being on top of things.
