### ISSUE TITLE
Newsletter

### ISSUE THREAD

**Issue by WeirDave** [Ombi-app/Ombi#4762]
**Describe the bug**
The newsletter is no longer working

**To Reproduce**
1. Go to Notifications > Newsletter > 
2. Click on Test or Trigger Now
4. Newsletter is not sent. I double checked the email function was working

**Expected behavior**
The newsletter to be generated manually or automatically

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**

**Ombi Version (please complete the following information):**
 - Version 4.27.0
- Media Server - Plex
- Database Type: SQLite (Please change if using MySQL)

**Additional context**
Tried to to toggle on and off and made sure to run update database too. Nothing is making it work

**Comment by tidusjar** [comment]
Please include logs.
What are you expecting to happen? Have you connected your media server?

Have you filled in your Email SMTP details under the email notification page?

**Comment by WeirDave** [comment]
Yes this is a server that has been running for a few years. SMTP test was completed and passed.
[log-20220920.txt](https://github.com/Ombi-app/Ombi/files/9612123/log-20220920.txt)
[log-20220919.txt](https://github.com/Ombi-app/Ombi/files/9612124/log-20220919.txt)
[log-20220918.txt](https://github.com/Ombi-app/Ombi/files/9612125/log-20220918.txt)
[log-20220917.txt](https://github.com/Ombi-app/Ombi/files/9612126/log-20220917.txt)
[log-20220916.txt](https://github.com/Ombi-app/Ombi/files/9612127/log-20220916.txt)

**Comment by tidusjar** [comment]
Looks like your issue is nothing to do with the newsletter, but the Plex sync itself

> StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: http://192.168.0.251:32400/library/sections

Ombi is no longer authorized to access your Plex instance.

This is probably after the Plex leak and everyone changed their passwords. Follow this: https://docs.ombi.app/guides/changing-plex-password/
