### ISSUE TITLE
Respect newlines on the mass email editor

### ISSUE THREAD

**Issue by lyz-code** [Ombi-app/Ombi#4763]
**Describe the bug**
The mass email sender doesn't respect the `\n` in the messages so the next message:

```
this
is
a
test
```
Will get transformed into:

```
this is a test
```

When writing long emails with many paragraphs this is inconvenient, as they are all joined into one big paragraph.

**To Reproduce**
1. Go to 'Mass Email'
2. Write the snippet
3. See the preview or send it to yourself

**Expected behavior**
Newlines are respected

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Debian

**Ombi Version (please complete the following information):**
 - Version 4.22.5
- Media Server 
- Database Type: SQLite

**Additional context**

**Comment by tidusjar** [comment]
It supports HTML, so use break lines
