### ISSUE TITLE
[Bug] Language list is empty for common users

### ISSUE THREAD

**Issue by Phenek** [Ombi-app/Ombi#4782]
**Describe the bug**
When an user had the [Power User role](https://docs.ombi.app/info/user-roles/).
The language list is empty for common users, on the on behalf  pop-up when making a request

**To Reproduce**
1. Take a simple user with the [Power User role](https://docs.ombi.app/info/user-roles/)
2. Go to request a random TV Show
3. Try to select the language on the on behalf popup.
4. The language list is empty.

**Expected behavior**
The request URL: https://xxxx.xxxx.xxx.net/ombi/api/v1/Sonarr/v3/languageprofiles/
should be called like in admin.

**Screenshots**
![Screenshot 2022-10-21 at 21 25 14](https://user-images.githubusercontent.com/4518686/197274712-4bba1b0f-ae09-4261-aa01-190d8ff87aa1.png)

**Desktop (please complete the following information):**
 - OS: Web

**Ombi Version (please complete the following information):**
 - Version Ombi 4.22.5

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈
