### ISSUE TITLE
baseUrl (sometimes) not honored when loading images/default_tv_poster.png

### ISSUE THREAD

**Issue by BowlesCR** [Ombi-app/Ombi#4792]
**Describe the bug**
References to the default tv/movie (and probably music) poster image don't include the baseUrl correctly, causing them to 404 when served via reverse-proxy.

Oddly, it seems to eventually work correctly after several retries. My SWAG is some kind of race condition preventing proper initialization of baseUrl near this bit of code... https://github.com/Ombi-app/Ombi/blob/e604c17604694a6afdabf32a1d05662f4d454419/src/Ombi/ClientApp/src/app/components/image/image.component.ts#L39

**To Reproduce**
1. Discover page
2. Open developer console
3. Scroll Upcoming section until an item appears without a poster image
4. Observe repeated 404 attempts to load from `/images/` instead of `/<baseUrl>/images/` before eventually loading the correct URL.
5. Continuing to scroll will eventually trigger the same issue again.

**Expected behavior**
Properly honor the baseUrl setting

**Desktop (please complete the following information):**
 - OS: Linux (Fedora 37) - Firefox 105

**Ombi Version (please complete the following information):**
- Version: 4.29.2
- Media Server: Emby 4.8.0.16
- Database Type: MariaDB

**Additional context**
Nginx configured as reverse proxy with `/ombi/` baseUrl. Nginx, Ombi, and Emby are all Docker containers on the same host.

**Comment by sephrat** [comment]
This was later reported as https://github.com/Ombi-app/Ombi/issues/4845 and fixed subsequently.
