### ISSUE TITLE
Language Bug in Movie and Series

### ISSUE THREAD

**Issue by Soldize** [Ombi-app/Ombi#4795]
**Describe the bug**
I set everything to German in the settings. In the films and series, everything is in German only the description is in English. 
On the 3th Screenshot you see all in German, only the red one is English!?

I know that if the selected language is not available, TMDB back to English. Also German Movies in english 

**To Reproduce**
1. Go to Settings, Configuration, General
2. Click on Language and set it to Deutsch
3. Go to Settings, Configuration, The Moviedatabase
4. Click on Original Language and set it to German
5. Click on Entdecken
6. Search for a Movie or Series
7. All is in German only the Description is in English

**Expected behavior**
I have reinstall and restart the hole Serversystem --> no change

**Screenshots**
![2](https://user-images.githubusercontent.com/13279377/200177035-4f2f8f73-e6f2-4ecf-8791-71863e011a15.png)
![1](https://user-images.githubusercontent.com/13279377/200177038-0b5f1149-960f-4191-9abf-cfe2966462b5.png)
![Unbenannt](https://user-images.githubusercontent.com/13279377/200177039-77dbe792-ccb8-45df-9175-2412fe96a817.png)

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-52-generic x86_64) 

**Ombi Version (please complete the following information):**
 - 4.22.5
- Media Server is Emby
- Database Type: SQLite (Please change if using MySQL)

**Additional context**

**Comment by tidusjar** [comment]
All of the results are cached including the language, so after changing you need to wait for the cache to expire
