### ISSUE TITLE
Mobile/Android: Partial TV notifications go to owner/wrong user

### ISSUE THREAD

**Issue by mindset-tk** [Ombi-app/Ombi#4797]
**Describe the bug**
When other users on my Ombi instance request incomplete seasons, I get the "partially available" notification on my Android app.  I don't get other user notifications for complete season requests, and I am the owner/admin of the Ombi server.

**To Reproduce**

1. Another user requests a TV series that is incomplete (not all episodes aired)
2. The currently available episodes download and push to my Plex with Radarr
3. On my Android phone, I will recieve a push notification stating that "My TV request is partially available!" with a list of seasons and episodes. I updated the language to include the username for the request, and it shows the other user's name in the push notification*

*Aside, the default language on this request of "Your TV request is now partially available! Season {PartiallyAvailableSeasonNumber} Episodes {PartiallyAvailableEpisodeNumbers}!" should probably be updated to include  {Title} somewhere, but this is irrelevant to the issue at hand.

**Expected behavior**

- The other user should receive an email and/or push notification. I should not, as it is not my request.  
- Alternatively, as Admin I should have a setting that allows me to choose whether I want to see all notifications for other users in the android app, so I know when any request is filled; This should be toggleable to avoid flooding admins with notifications.

**Screenshots**
Note: I updated the notification verbage to `{UserName}: Your TV request is now partially available! {Title} Season {PartiallyAvailableSeasonNumber} Episodes {PartiallyAvailableEpisodeNumbers}!` for this so I could gather more details.  "User \# 1" is not me.

![image](https://user-images.githubusercontent.com/53205683/201447861-6507c3c0-78cd-4299-b971-bfb6f245bab3.png)

**Logs (Logs directory where Ombi is located)**
Logs do not seem to indicate anything here.

**Desktop (please complete the following information):**
 - OS: Android 13 on Pixel 6 Pro

**Ombi Version (please complete the following information):**
 - Version: Docker/4.22.5 - Android/2.12.2
- Media Server: Plex
- Database Type: SQLite

**Additional context**
I don't have any other users on my server using the mobile app.  I am doubtful any would be willing to pay the $3 (this is not a complaint about its cost)

**Comment by tidusjar** [comment]
Regarding your first point, that would only happen if you have logged in as that user who did the request on the mobile device. I suggest you log out and then back in. 

About receiving all user notifications, that’s not something I am planning to do unless more users want this.

**Comment by mindset-tk** [comment]
> Regarding your first point, that would only happen if you have logged in as that user who did the request on the mobile device. I suggest you log out and then back in.

That's just it - I get partial TV notifications for *every* user on the ombi.  None have ever been logged into my mobile app. I also get all my own notifications as ususal. I do not recieve an email notification - logs for my mail server indicate that the user was sent that notification as usual. 

I will perform a logout/login and full reinstall of the app and have a user attempt the same test to verify.

> About receiving all user notifications, that’s not something I am planning to do unless more users want this.

No problem at all. It's not something I need.

**Comment by mindset-tk** [comment]
Updating to note that reinstall and logout/login on the mobile app had no effect. I still receive partial TV notifications for other users.

**Comment by tidusjar** [comment]
Nevermind, found it

**Comment by mindset-tk** [comment]
Yes, only partial. Thank you!

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈
