### ISSUE TITLE
Music Searches are Terrible ???

### ISSUE THREAD

**Issue by AltairWolfe** [Ombi-app/Ombi#4809]
**Describe the bug**
Am I missing something obvious?  I keep thinking there's a setting that is affecting how music searches operate, but music seems to be the least documented feature currently.  I have the worst time trying to find ANY music on the Ombi search.  Type an artist and I probably won't get any albums BY that artist.  Type an album... and I probably won't get that album.

**To Reproduce**
1. For example...
2. Got to search bar
3. Type 'Purple Rain'
4. Hit enter.  LOL

**Expected behavior**
You what comes up?  The movie "Prince and the Revolution: Live" which only mentions Purple Rain in the synopsis.  You know what DOESN'T come up?  The freaking album PURPLE RAIN.  ROFL

**Screenshots**
![image](https://user-images.githubusercontent.com/33189756/203459962-aaf4a5cc-8d49-4402-a5a1-a2eba60c05b3.png)

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: I'm running Windows 10 and the most current Chrome

**Ombi Version (please complete the following information):**
 - Version [e.g. 4.0.958]  4.25.0
 - Server FreeBSD 13.1-RELEASE-p1 FreeBSD 13.1-RELEASE-p1 n245406-814eb095751 TRUENAS
- Media Server [e.g. Plex]  N/A
- Database Type: SQLite (Please change if using MySQL)

**Additional context**
So feel free to roast me when somebody tells me the obvious.  SMH

**Comment by tidusjar** [comment]
There's ongoing background work to sort this out, it's going on... but slowly

**Comment by tidusjar** [comment]
https://github.com/Ombi-app/Ombi/tree/feature/music-rework
