### ISSUE TITLE
Ombi Android app crashes without Google Play Store

### ISSUE THREAD

**Issue by Enlinks** [Ombi-app/Ombi#4813]
**Describe the bug**
When attempting to request content with the Ombi Android app, if the Google Play Store is not installed or disabled the app will crash however the content request does go through.

**To Reproduce**
1. Disable Google Play Store
2. Request content
3. App crashes, but the request does go through

**Expected behavior**
App shouldn't crash in the event the Google Play Store being unavailable.

**Screenshots**
N/A

**Logs (Logs directory where Ombi is located)**
Unsure how to get logs from the mobile app.

**Desktop (please complete the following information):**
 - OS: Android 13 running GrapheneOS

**Ombi Version (please complete the following information):**
 - Version 4.22.5 Docker, 2.12.2 app
- Media Server Plex
- Database Type: MariaDB

**Additional context**
N/A

**Comment by tidusjar** [comment]
The app is only available via the google play store, without it this is not a supported scenario

**Comment by Enlinks** [comment]
Seems like a very off limitation. Yes I bought and downloaded the app through the play store on my work profile and then transferred it to my regular profile.

I also attempted jus downloading it on my regular profile with the same problem.

Literally no other app I have has this issue, both paid and free.
