### ISSUE TITLE
Ombi not compatible with Sonarr v4 yet?

### ISSUE THREAD

**Issue by dthienn** [Ombi-app/Ombi#4814]
**Describe the bug**
Can't connect to Sonarr v4.

Pressing the Test Connectivity button, results in error: Please check your entered values
Pressing the Load Qualities button, results in error:
```
fail: Ombi.Api.Api[1000]
      StatusCode: NotFound, Reason: Not Found, RequestUri: http://192.168.2.163:8989/api/profile
```
Pressing the Load FOlders button, results in error:
```
fail: Ombi.Api.Api[1000]
      StatusCode: NotFound, Reason: Not Found, RequestUri: http://192.168.2.163:8989/api/rootfolder
```

I also tried to enable V3, but the endpoints seem to have changed in Sonarr v4.

**Expected behavior**
For Ombi to be able to connect to Sonarr

**Desktop (please complete the following information):**
 - OS: Synology DSM

**Ombi Version (please complete the following information):**
- Ombi: 4.22.5
- Sonarr: 4.0.0.178

**Comment by dthienn** [comment]
That did the trick, thank you very much!

**Comment by alneven** [comment]
@dthienn does ombi works for you with sonarr v4? for me it connects but cannot add series from ombi to sonarr
