### ISSUE TITLE
ombi slowing down PMS

### ISSUE THREAD

**Issue by sfreek76** [Ombi-app/Ombi#4817]
1. Run PMS and start ombi
2. Use PMS which is slow now
3. Restart Machine (MacMini)
4. PMS only runs for about half an hour, then hangs

**Expected behavior**
very strange issue here using your app (4.22.5) as a package on a synology NAS with DSM Version 1.29.2.6364 in conjunction with Plex (PMS) on a MacMini M1 with MacOS Monterey: As soon as I start ombi my PMS gets very slow in response and if I do a restart of whole machine, PMS runs only for half an hour, then goes unresponsive even if I turn off ombi. I already had this issue a week ago and only fix was to reinstall MacOS and PMS and leave ombi switched off. Also did extensive examination with the guys from Plex, but no issue which could explain this odd behaviour could be found since PMS does not crash but goes unresponsive...

**Screenshots**

**Logs (Logs directory where Ombi is located)**
No logs on PMS side since it does not crash, it goes unresponsive
[ombi-log.pdf](https://github.com/Ombi-app/Ombi/files/10125729/ombi-log.pdf)

**Desktop (please complete the following information):**
 - Synology DSM 7.1.1-42962 with Ombi
 - Latest Version of MacOS Monterey 12.6.1 (21G217) with PMS 1.29.2.6364

**Ombi Version (please complete the following information):**
 - Version [4.22.5]
- Media Server [Plex 1.29.2.6364x]
- Database Type: SQLite (Please change if using MySQL)

**Comment by tidusjar** [comment]
Does it happen when Plex is not enabled in Ombi?

**Comment by sfreek76** [comment]
Thanks for your reply! I will test it again on weekend when I have more time...

**Comment by sfreek76** [comment]
Had time to test it and it's a bit of a mystery. As mentioned I had problems a week ago with PMS not running longer as half an hour. Only re-install of OS and PMS did help. Now for ombi and PMS I thought it could have an impact but I can't reproduce it for sure to say with certainty that ombi has an impact. One time I think it has because as soon ombi is running, PMS gets slughish, but I did a restart again two days ago an PMS and ombi are running smoothly since then... So I'm sorry for opening this bug report with something that I can't reproduce for sure!

**Comment by tidusjar** [comment]
No problem. It does sound oddd. Any further issues just comment

**Comment by sfreek76** [comment]
Thanks a lot!
