### ISSUE TITLE
App 'Request Error null' - iOS

### ISSUE THREAD

**Issue by Shadow229** [Ombi-app/Ombi#4831]
**Describe the bug**
iOS app throws an error when requesting any tv show. The error shows regardless of what the request is for (full season/single episode/etc) but only on tv shows - movie requests work fine. 

Once the error throws, the show gets marked as requested in ombi, but the request never gets sent through to sonarr. 

**To Reproduce**
1. Request any tv show in the iOS app. 

**Expected behavior**
A green 'success' banner and the request be sent to sonarr to pick up. 

**Screenshots**
![Screenshot_20221219-080231](https://user-images.githubusercontent.com/55843220/208379162-75c5c19e-faf3-4dcd-81ef-6ddb05f6a3ec.png)

**Desktop (please complete the following information):**
 - OS: iOS

**Ombi Version (please complete the following information):**
 - Version 4.33.0
- Media Server Plex
- Database Type: SQLite

**Comment by tidusjar** [comment]
Does this happen when on the web?

**Comment by Shadow229** [comment]
Just tested - it looks like it happens on the web too:

![image](https://user-images.githubusercontent.com/55843220/208431655-297c240a-088f-4f6b-b071-e80b7b772830.png)

**Comment by tidusjar** [comment]
Ok. Not an app issue in that case but a server issue. 

What’s in your logs when that happens?

**Comment by Shadow229** [comment]
The important bit was:

System.Exception: Language profile does not exist

looks like I had no default language selected in my profile

![image](https://user-images.githubusercontent.com/55843220/208434205-a702b571-bd20-4930-8130-8285337cf51c.png)

Not sure if this is new or its just somehow dropped out from when I set it up a long time back? Either way, setting the default as above has fixed it. 

Thanks!
