### ISSUE TITLE
Ombi not connecting to Sonarr - gives an error in console

### ISSUE THREAD

**Issue by TechGuyAlabama** [Ombi-app/Ombi#4832]
**Describe the bug**
When I attempt to connect to locally hosted Sonarr, it is saying that "We could not connect to Sonarr!". This is a new setup on a new Windows 2022 computer.

**To Reproduce**
1. Ombi
2. TV
3. Sonarr
4. Add settings:
    I've tried:
    http://localhost
    localhost
    127.0.0.1
    With/without Advanced enabled
    With/without Scan availability enabled

**Expected behavior**
Should connect to the local Sonarr app. 

**Screenshots**
https://i.postimg.cc/YqPzvt78/s1.png
https://i.postimg.cc/zfZwkpVg/s2.png

**Logs (Logs directory where Ombi is located)**
https://pastebin.com/f2DwNYdN

**Desktop (please complete the following information):**
 - OS: Windows Server 2022

**Ombi Version (please complete the following information):**
 - Version:  4.32.3 
- Media Server: PLEX
- Database Type: SQLite 

**Additional context**

**Comment by TechGuyAlabama** [comment]
I have reviewed both the wiki and faq.

**Comment by tidusjar** [comment]
Sonarr version?

**Comment by tidusjar** [comment]
Also have you set up any quality profiles in sonarr?

**Comment by TechGuyAlabama** [comment]
Sorry, my Sonarr version is 3.0.9.1549.

I left the defaults for the quality, if I'm understanding correctly.

https://i.postimg.cc/D0WCtw1F/s3.png

**Comment by doxsys** [comment]
Having the same issue as well. Updated Ombi and Sonarr to the latest versions and Ombi will no longer connect to Sonarr. This is running 

https://pastebin.com/XE59ReSU

**Comment by tidusjar** [comment]
Hmmm. Can you guys press test button, a quality profile should appear?

**Comment by doxsys** [comment]
Just get a "Could not connect to Sonarr" message after test and quality profiles never appear.

**Comment by TechGuyAlabama** [comment]
Yup, same here.

**Comment by NX211** [comment]
Same Issue when I updated Sonarr and Ombi. Sonarr Version 4.0.0.293 using the linuxserver.io Docker image. The linuxserver.io Docker Image of Ombi that I'm running is 4.22.5. Everything is running on an Ubuntu Server 22.04 host. Radarr works perfectly as does Lidarr both with the latest versions from the linuxserver.io Docker images. 
I am getting an error in the UI that reads, "Please check your entered vaules" the logs show this error when trying to load profiles or root folders.
`ombi.1.m8li5p44v5xl@blacktalon    | fail: Ombi.Api.Api[1000]
ombi.1.m8li5p44v5xl@blacktalon    |       StatusCode: NotFound, Reason: Not Found, RequestUri: http://sonarr:8989/api/profile
ombi.1.m8li5p44v5xl@blacktalon    | fail: Ombi.Api.Api[1000]
ombi.1.m8li5p44v5xl@blacktalon    |       StatusCode: NotFound, Reason: Not Found, RequestUri: http://sonarr:8989/api/rootfolder
`
I may have to adjust the log level as I do not see any errors in the log related to the connection test.

**Comment by tidusjar** [comment]
To use sonarr v4 you need to use the develop version of Ombi

**Comment by TechGuyAlabama** [comment]
ty for the response tidusjar but how do I "git" that?

I tried:
git clone -q --branch=develop https://github.com/tidusjar/Ombi.git C:\projects\requestplex
but ended up with the source instead of the compiled code. Where do I find the compiled developer version?
Thank you!

**Comment by NX211** [comment]
@tidusjar thank you. I switched to the development tag and everything works perfectly. Thank you for the awesome project!

**Comment by TechGuyAlabama** [comment]
@nx211 can you tell me where you got it? I'm new to GitHub so I'm kind of lost.  Thank you!

**Comment by NX211** [comment]
@TechGuyAlabama Are you running Docker Desktop on Windows ? How are you running Sonarr and Ombi ?

**Comment by TechGuyAlabama** [comment]
I'm running it straight up on windows server 2022. I have git for windows installed, both desktop and command line.

Thanks for the assist.

**Comment by NX211** [comment]
@TechGuyAlabama you will want to use git checkout in order to switch to the development branch. Google will have some good guides for using git checkout to switch branches.

**Comment by TechGuyAlabama** [comment]
Sorry, I know I'm a scrub. I am on W2022 Server running on IIS so much of this is greek to me, just trying to learn it.

git clone --recursive --branch develop https://github.com/Ombi-app/Ombi.git

I'm getting the source code, which I suppose, is to be expected. Am I suppose to compile this version or is there a compiled version that I can get latest from, instead?

**Comment by lightmaster** [comment]
Any update on how to get the develop version installed? If I click "download" under the develop part in the Github readme, it sends me to a page that says the last develop version was 2 years ago and isn't available anymore. If I try to checkout the develop branch, I get a bunch of source code. I am currently running pre-release version 4.35.4 that was released 16 hours ago.

**Comment by tidusjar** [comment]
Look at the release page on GitHub.
