### ISSUE TITLE
SVG of icon?

### ISSUE THREAD

**Issue by loganmarchione** [Ombi-app/Ombi#4834]
Hello there! 👋

I'm the maintainer of [homelab-svg-assets](https://github.com/loganmarchione/homelab-svg-assets) and would like to add the [Ombi icon](https://github.com/Ombi-app/Ombi/blob/develop/src/Ombi/wwwroot/images/favicon/android-chrome-512x512.png) to my project. However, I didn't see any brand guidelines or a vector (SVG) version of the icon. Could you please provide one or both of these?

Thanks, and keep up the good work!

**Comment by tidusjar** [comment]
Hello, I don't have a SVG to hand, but I do have a .ai file if that helps?

**Comment by loganmarchione** [comment]
That should probably work. Was it in the repo and I missed it?

**Comment by tidusjar** [comment]
It's not! I'll add it

**Comment by tidusjar** [comment]
https://github.com/Ombi-app/Ombi/blob/develop/assets/Ombi-icon.ai

**Comment by loganmarchione** [comment]
Thank you!
