### ISSUE TITLE
Plex authentication allows login as local user when Plex username is the same as local username

### ISSUE THREAD

**Issue by Grandfather-Paradox** [Ombi-app/Ombi#4835]
**Describe the bug**
When a local user's username is the same as a Plex username, using the Plex authentication API allows you to login as that local user, despite the account being a local account that has its own password.

**To Reproduce**
1. Create a local user with the same username as a Plex account you have access to
2. Log in using the Plex API

**Expected behavior**
The Plex API should only work for logging into Plex user accounts, not local user accounts.

**Desktop (please complete the following information):**
 - OS: Same behavior regardless of OS

**Ombi Version (please complete the following information):**
 - Version: 4.22.5
- Media Server: Plex
- Database Type: MySQL

**Comment by tidusjar** [comment]
Are there two accounts in the user management page with the same username?

**Comment by Grandfather-Paradox** [comment]
> Are there two accounts in the user management page with the same username?

Nope, there aren't.

**Comment by tidusjar** [comment]
And the user that’s being logged in. On the user management page, what is the user type?

**Comment by Grandfather-Paradox** [comment]
> And the user that’s being logged in. On the user management page, what is the user type?

Local user.

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈
