### ISSUE TITLE
Black text on black background in /Settings/FailedRequests

### ISSUE THREAD

**Issue by flyize** [Ombi-app/Ombi#4836]
**Describe the bug**
Black text on black background in /Settings/FailedRequests

**To Reproduce**
1. Go to /Settings/FailedRequests (I assume with a dark Windows theme)

**Expected behavior**
Being able to read text ;)

**Screenshots**
![image](https://user-images.githubusercontent.com/131196/209691062-f647cda6-2b8e-45f6-9599-0c115b45f02b.png)

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: Edge on Windows

**Ombi Version (please complete the following information):**
 - Version 4.33.1

**Comment by teambvd** [comment]
The same thing occurs Firefox, as well as all chromium variants I've tested. One interesting thing I'd found was that enabling the [Dark Reader](https://addons.mozilla.org/en-US/firefox/addon/darkreader/) plugin actually seems to clean it up - usually it just inverts the coloration of backgrounds and the like, making sites that are already 'dark' swap to white/bright.

**Comment by gold007eye** [comment]
Any updates on this.  I am seeing the same issue with the following specs:

**Desktop (please complete the following information):**

    OS: Windows 10 | Firefox 110.0.1 (64-bit)

**Ombi Version (please complete the following information):**
  4.35.8

![image](https://user-images.githubusercontent.com/4365462/224098297-79d597fb-7fa4-4490-a380-2a882901e32e.png)

**Comment by twanariens** [comment]
Try and add this in the Custom CSS box under settings -> configuration -> customization

`.table{
color:#FFF;
}`

**Comment by flyize** [comment]
Heh, didn't know we could add custom CSS. Nice!

**Comment by gold007eye** [comment]
> Try and add this in the Custom CSS box under settings -> configuration -> customization
> 
> `.table{ color:#FFF; }`

Thanks for that information.  Will this affect any other Custom CSS that I already have in that Custom CSS section?

**Comment by gold007eye** [comment]
This was the only thing I had in there to disable the Local Login Button:
```
/* This  will hide the Local Login button */
.login-buttons button:first-of-type { display: none; }
```

**Comment by PalasX** [comment]
This also affects the newsletter page, making the "submit", "test", "update database", and "trigger now" buttons nearly unreadable.
this can be resolved with
`.mat-button-wrapper{ color:#FFF; }`

**Comment by gold007eye** [comment]
> This also affects the newsletter page, making the "submit", "test", "update database", and "trigger now" buttons nearly unreadable. this can be resolved with `.mat-button-wrapper{ color:#FFF; }`

Thanks for that info. I never used that page so missed it, but added the css you gave just to be safe :)

**Comment by gold007eye** [comment]
@tidusjar Would it be possible to included these few changes above hard-coded into a future release by chance?  Thanks for all the hard work you do on this project we appreciate it 💯
