### ISSUE TITLE
default_tv_poster.png not taking into account base url and causing 401 errors

### ISSUE THREAD

**Issue by Rewels** [Ombi-app/Ombi#4845]
**Describe the bug**
After logging into Ombi, when you hit the Discover page it tries to load the default_tv_poster.png for items without a poster but Ombi doesn't take the base url into consideration so instead of https://example.com/ombi/images/default_tv_poster.png it tries to load https://example.com/images/default_tv_poster.png.

This causes 401 Errors to occur and also prompts for Authentication as I use logins for my reverse proxy on my main url.

**Screenshots**
![image](https://user-images.githubusercontent.com/37768610/211873817-cd171b23-4ec0-4c63-9138-68e8170fee42.png)

**OS**: Ubuntu 16.04.7 LTS

**Ombi Version**:
Version 4.35.2
Media Server: Plex
Database Type: MySQL

**Comment by TheCatster** [comment]
I'm having this same issue, except that the 401 errors occur on everything. Ombi is completely unusable. I use Caddy v2 and Authentik with Header Auth and it crippled my Ombi instance. I cannot access any page.

![Screenshot 2023-06-26 133518](https://github.com/Ombi-app/Ombi/assets/32912305/844919bc-da2e-4108-8170-bde74939b673)

**Comment by sephrat** [comment]
@TheCatster This is not the same issue. Are you using a reverse proxy that might add an authentication layer?
If not, please raise a new issue.
