### ISSUE TITLE
Not be able to delete quality profile

### ISSUE THREAD

**Issue by J4gQBqqR** [Ombi-app/Ombi#4850]
**Describe the bug**
A quality profile is deleted in Sonarr, yet it still shows up in OMBI's Sonarr setup page, not able to do anything about it.

**To Reproduce**
1. Go to Sonarr
2. Delete one of quality profiles
3. Go back to OMBI
4. See the previous deleted quality profile still exits and there is nothing can be done on it.

**Screenshot**
![图片](https://user-images.githubusercontent.com/77554817/212484373-03c82eeb-a87c-4dfd-9796-4dfa60f60741.png)
The Quality Profiles (Anime) shown above is already deleted.

**Expected behavior**
The deleted profile should be gone after a sync or there is a manual button to delete it.

**Ombi Version (please complete the following information):**
- Version 4.22.5
- Database Type: SQLite

**Comment by tidusjar** [comment]
Ombi keeps a reference. Press load profiles and then it will requery sonarr.

**Comment by J4gQBqqR** [comment]
No, load profiles do not refresh and delete that entry it still persists. That is why I opened this ticket. Please reopen it.

**Comment by tidusjar** [comment]
The list comes directly from sonarr. That means that sonarr is still returning the language profile. 

I’ll check to see if I can reproduce

**Comment by tidusjar** [comment]
Cannot reproduce, when pressing the load quality profiles button, the deleted profile is removed from the list
