### ISSUE TITLE
Request not getting sent to Radarr if default minimum availability is set to PreDb #4851

### ISSUE THREAD

**Issue by IYZaytsev** [Ombi-app/Ombi#4852]
**Describe the bug**
Request not getting sent to Radarr if default minimum availability is set to PreDb
Changing the default minimum availability to Physical / Web fixes the issue

**To Reproduce**
1. In Ombi go to Setting->Movies->Radarr
2. Set default minimum availability to PreDb
3. Add a movie to Ombi and approve it
4. Movie requests will never show up in Radarr.

**Expected behavior**
Requests should be sent to radarr once approved in Mobi

**Screenshots**
NA

**Logs (Logs directory where Ombi is located)**
Radarr log 
2023-01-19 20:22:29.8|Info|RssSyncService|RSS Sync Completed. Reports found: 26, Reports grabbed: 0
2023-01-19 21:03:23.6|Error|Radarr.Api.V3.Movies.MovieController.AddMovie (Radarr.Api.V3)|{
  "$.minimumAvailability": {
    "errors": [
      {
        "errorMessage": "The JSON value could not be converted to NzbDrone.Core.Movies.MovieStatusType. Path: $.minimumAvailability | LineNumber: 0 | BytePositionInLine: 327."
      }
    ],
    "validationState": "invalid",
    "isContainerNode": false
  }
}

**Desktop (please complete the following information):**
 - OS:  Ubuntu 22.04.1 LTS

**Ombi Version (please complete the following information):**
 - Version 4.7.11
- Media Server Plex
- Database Type: SQLite

**Additional context**
Radarr version: 4.3.2.6857

**Comment by sephrat** [comment]
PreDb is not an option in Radarr anymore.
That setting was removed from Ombi a year ago. You need to upgrade.

See https://github.com/Ombi-app/Ombi/issues/4450
