### ISSUE TITLE
Upcoming movies

### ISSUE THREAD

**Issue by mrwestside12** [Ombi-app/Ombi#4853]
Upcoming movies is awful on here. Titanic was on there today. Why hasn't this been fixed?

**Comment by sephrat** [comment]
It's reflecting what TMDB shows; https://www.themoviedb.org/movie/upcoming
Titanic shows because someone has set a release date for it in 2023: https://www.themoviedb.org/movie/597-titanic/releases
There's nothing obvious we can do on Ombi side.
