### ISSUE TITLE
Users are able to see other users' requests in spite of having the option to prevent this enabled.

### ISSUE THREAD

**Issue by jaretclifton** [Ombi-app/Ombi#4854]
**Describe the bug**
Users are able to see other users' requests in spite of having the option to prevent this enabled. Toggling the setting doesn't work either.

**To Reproduce**
1. Enable functionality to prevent users from seeing other users requests.
2. Login as any user and check the requests list on any page.
3. Requests from other users are displayed.

**Expected behavior**
Only requests from the logged in user should be displayed.

**Desktop (please complete the following information):**
 - OS: All

**Ombi Version (please complete the following information):**
 - Version 4.35.3
- Media Server Plex
- Database Type: MySQL

**Comment by tidusjar** [comment]
The user that can see the other requests, what are their roles in the user management page?

**Comment by jaretclifton** [comment]
Auto Approve Movie
Auto Approve TV
Manage Own Requests
Request TV
Receives Newsletter
Request Movie

**Comment by tidusjar** [comment]
do you mean the recently requested section on the discover page?

**Comment by jaretclifton** [comment]
Correct. Thanks for the quick turn around!
