### ISSUE TITLE
No mobile notifications, no base URL

### ISSUE THREAD

**Issue by jkurelek** [Ombi-app/Ombi#4857]
**Describe the bug**
Same issue as https://github.com/Ombi-app/Ombi/issues/4205, except I'm using an Nginx reverse proxy with a subdomain (e.g., ombi.mydomain.com) so I have nothing set in the Base URL field. I've also tried single forward slash, still my mobile client doesn't show up in the Notifications > Mobile Notifications list

** Mobile:**
 - OS: Android, App version 2.12.2

**Ombi Version:**
 - Version: 4.22.5 running in linuxserver/ombi docker on Unraid
 - Nginx reverse proxy, can post server block if needed

**Edit** 
I also have the application URL set correctly (e.g. https://ombi.mydomain.com)

Thanks!

**Comment by tidusjar** [comment]
PM me on discord or email me tidusjar@gmail.com your full URL and I'll take a look.

**Comment by jkurelek** [comment]
Sent

**Comment by jkurelek** [comment]
Logging in isn't the issue, its that I am not receiving notifications on the app. If you go to settings > notifications > mobile you'll see that no device has been registered even though you've logged in through the app.

**Comment by tidusjar** [comment]
My device would have been removed because I logged out, let me recheck

**Comment by tidusjar** [comment]
Just did it, my device is appearing and I just sent myself a test message and it came through straight away
![image](https://user-images.githubusercontent.com/6642220/215786022-94a97a20-1c37-4a25-9292-382526e069aa.png)

**Comment by jkurelek** [comment]
Hmmm, yes I see it now. So why won't my mobile app show up? I just reinstalled the app and logged back in and my client still doesn't show up. Are there any logs I can capture in the Android app?

**Comment by tidusjar** [comment]
is there any logs in Ombi around the time you logged in via the app?

**Comment by jkurelek** [comment]
No, just logged in and out a few times and nothing is logged.

**Comment by tidusjar** [comment]
So if you log out, Ombi will clear down the notifications for that mobile device. As soon as you log in and ensure the mobile has granted push notifications for the app, the user should show. 

If the mobile device has not allowed push notifications, the user will not appear.

**Comment by jkurelek** [comment]
Aha, that was the issue. I had granted the app notifications permission after I had logged in. Perhaps a pop-up when you first launch the app asking for notification permission would solve similar mix-ups in the future?
