### ISSUE TITLE
Mac Mini M2 - Autostart Issue

### ISSUE THREAD

**Issue by jrohnerx** [Ombi-app/Ombi#4859]
**Describe the bug**
I've successfully installed Ombi to /opt/Ombi. I can manually open up Terminal and type in "cd /opt/Ombi" and then "/opt/Ombi/Ombi" and all works. However, I want to set it up to automatically start on startup. I tried the command "/opt/Ombi/Ombi RunAtLoad WorkingDirectory /opt/Ombi" as documented in the installation guide, but it fails with the error:

> Unhandled exception. System.IO.FileNotFoundException: The configuration file 'appsettings.json' was not found and is not optional. The expected physical path was '/Users/plex/appsettings.json'.

It seems that I have to manually type in "cd /opt/Ombi" each time I run this. Does the "WorkingDirectory /opt/Ombi" part of the RunAtLoad command not actually set the working directory to that path?

**To Reproduce**
1. Open Terminal
2. Type in command "/opt/Ombi/Ombi RunAtLoad WorkingDirectory /opt/Ombi"

**Expected behavior**
I expect Ombi to start and also autostart on future logins

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.2

**Ombi Version (please complete the following information):**
 - Version: 4.35.5
- Media Server: Plex
- Database Type: SQLite

**Additional context**

**Comment by tidusjar** [comment]
I don't have a Mac so i'm unable to try or do anything here. 

Ombi expected the working directory to be the place where all of the ombi files are.
There are windows users that have done this successfully.

Looking at the docs, this should be working fine, I'd suggest having a read: https://docs.ombi.app/guides/installation/#mac-autostart

Keep in mind that the docs are also community sourced.

Thank you
