### ISSUE TITLE
Newletter: Only "Now Available" requested TV Shows displaying, not the ones added manually into Sonarr

### ISSUE THREAD

**Issue by Mavyre** [Ombi-app/Ombi#4862]
**Describe the bug**
Using Sonarr and Jellyfin, only TV Shows requested by users that are now abailable are printed out when generating the newsletter. Movies added directly to Radarr and newly available in Jellyfin without being requested in Ombi are displayed correctly in the newsletter.

**To Reproduce**
1. Add some TV shows directly to Sonarr
2. Send newsletter
3. TV Shows only displays

**Expected behavior**
All the new TV Shows should be displayed, weather they are added through Ombi or Sonarr directly. This should have the exact same behaviour than Movies (with Radarr).

**Logs (Logs directory where Ombi is located)**
None applicable found

**Desktop:**
 - OS: Not applicable

**Ombi Version:**
- Version: 4.35.5
- Media Server: Jellyfin 10.8.8
- Database Type: SQLite

**Additional context**
While writing this issue, it seems that some other TV shows are missing, but I can't confirm until the next newsletter (might have appeared just before I used the "Update Database" feature to init the Newsletter).

**Comment by sephrat** [comment]
The newsletter content only relies on what's physically on your media server. It doesn't matter how or why it got there. Whether the TV show was requested by Ombi can't influence the behaviour you describe. It must be something else.

What does your metadata look like on Jellyfin for the TV shows that won't show up in your newsletter? Can you compare it with a TV show that did show up?
Is there anything in Ombi log when the newsletter is generated?
