### ISSUE TITLE
Items show as approved but don't change to available

### ISSUE THREAD

**Issue by Shadow229** [Ombi-app/Ombi#4865]
**Describe the bug**
If an item is requested (not 4K) and a 4K version gets downloaded, the status never updates to available

**To Reproduce**
1. Request a standard profile movie, but allow standard profile in radarr to grab 4k
2. when 4k has downloaded, check back against the title in ombi

**Expected behavior**
Would expect the status to show available regardless of what quality is available

**Screenshots**
on the discover page titles show as approved
![image](https://user-images.githubusercontent.com/55843220/217817752-6796f41f-0a8f-4802-91a5-8118d4647764.png)

but the title is completed and available - 4k check can be seen in the title detail
![image](https://user-images.githubusercontent.com/55843220/217817839-6736e733-2cc2-48dc-b7df-c57c511be7dc.png)

**Desktop (please complete the following information):**
 - OS: unraid

**Ombi Version (please complete the following information):**
 - Version 4.35.6
- Media Server Plex
- Database Type: SQLite

**Comment by tidusjar** [comment]
This is now how the 4K functionality is intended to be used. 

The whole point of the 4K work is so you can have two instances of Radarr, a standard instance running and a 4K Radarr instance running.
