### ISSUE TITLE
Disable login background images when using Ombi in a Docker container

### ISSUE THREAD

**Issue by amymowatt** [Ombi-app/Ombi#4868]
Would love to be able to disable login background images when using Ombi in a Docker container.

**Comment by tidusjar** [comment]
Why?

**Comment by amymowatt** [comment]
Showing images that a user doesn't own the copyright to on a domain isn't going to end well in some countries, especially now bots go trawling for infringing use of images. Not to mention it just slows down the page load pointlessly.

I can appreciate why some people might like it, it's just not for me.
