### ISSUE TITLE
"You are not authenticated with Ombi" After sign in with Plex

### ISSUE THREAD

**Issue by lastlink** [Ombi-app/Ombi#4870]
**Describe the bug**
Unable to log into ombi using plex sso after update to latest version 
4.35.8. 

**Screenshots**
![ombi_failed](https://user-images.githubusercontent.com/6679425/220963860-da9961ea-a959-4aa9-95d5-b61e4d7b5400.PNG)
![ombi_plex_server](https://user-images.githubusercontent.com/6679425/220963865-509f0126-7c30-4303-b5ab-f496bd1cad11.PNG)

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.
[omb_log_20230223.txt](https://github.com/Ombi-app/Ombi/files/10815735/omb_log_20230223.txt)

**Desktop (please complete the following information):**
 - OS: iphone, and windows edge browser

**Ombi Version (please complete the following information):**
 - Version 
4.35.8
- Media Server Plex
- Database Type:  MySQL

**Additional context**
Definetely an issue w/ latest release. I changed back to latest stable 
4.22.5 and login works again.

I'm using docker btw. ombi:latest, ombi:development

**Comment by tidusjar** [comment]
Is your user in the ombi users list?

**Comment by Firetop** [comment]
> Is your user in the ombi users list?

I'm currently getting this with my Admin account and am kinda locked out of my own Ombi session right now lol

**Comment by Firetop** [comment]
Downgraded to v4.34.1 and still have the issue... Seems to me that somehow my Admin Ombi account linked to Plex got deleted in one of the updates, not sure which one or how to fix this without blowing it at all away and starting again from zero....

**Comment by Firetop** [comment]
I would relate this to: https://github.com/Ombi-app/Ombi/issues/4793 

since I didn't manually delete my Admin account; but the Admin account is now missing and I get the error listed above when trying to sign in.

**Comment by Firetop** [comment]
I managed to fix get myself back in by modifying the database table for my TestUser to give it Admin access, and then logged in with that and recreated my regular Admin user.

![image](https://github.com/Ombi-app/Ombi/assets/1971404/31449431-30c1-4980-a38d-31d8c1a72046)

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈
