### ISSUE TITLE
ombi + authentik + swag not working

### ISSUE THREAD

**Issue by sukeyisme** [Ombi-app/Ombi#4878]
**Describe the bug**
ombi + authentik + swag not working

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**

**Ombi Version (please complete the following information):**
 - Version [e.g. 4.0.958]
- Media Server [e.g. Plex]
- Database Type: SQLite (Please change if using MySQL)

**Additional context**

**Comment by twanariens** [comment]
No information so unable to provide support
