### ISSUE TITLE
Android Mobile App no longer offers Quality/Profiles

### ISSUE THREAD

**Issue by Casper042** [Ombi-app/Ombi#4884]
**Describe the bug**
Recent update to Ombi seems to no longer offer Quality or Profiles to Super Users via Mobile App.
Have an alternate profile for films in a different language.
This works fine in the web UI, but the Android App isn't showing this screen anymore.
When you click Request, you used to get a 2nd screen asking for Quality, On Behalf of User, Path, etc.
Now it just says Request Submitted and no longer prompts.

**To Reproduce**
Use Super User to request Movie via Radarr by using Ombi Android App.

**Expected behavior**
Popup Screen asking for further settings before Request is submitted.

**Screenshots**
Hard to screenshot something that is no longer there.

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**
Android 
Both my and a friend's phones.
I'm on Android 13 and Mobile app is 2.14.1

**Ombi Version (please complete the following information):**
 - Version [e.g. 4.35.10]
- Media Server [e.g. Plex + Radarr]
- Database Type: Build into Docker, so SQLite)

**Additional context**
Just ran my docker-compose pull and up-d script the other day.
It had been maybe 3+ weeks since I last ran it.
Plex/Ombi/Radarr/Sonarr all updated.

Mobile app hasn't updated since Feb 8th 2023
Ombi app itself updated 2 days ago as noted via Docker.

**Comment by tidusjar** [comment]
I cannot reproduce this. Ensure they they have the correct roles

**Comment by ristein** [comment]
same here on web. only admins can choose quality profile since few months

**Comment by tidusjar** [comment]
This report for this bug is for the mobile app. If you are having a different issue, please raise a new issue on github
