### ISSUE TITLE
"You are not authenticated with Ombi" After sign in with Plex

### ISSUE THREAD

**Issue by mkanet** [Ombi-app/Ombi#4892]
**Describe the bug**
When I sign in with plex, it shows the pop-up "You are not authenticated with Ombi" over and over again.  This started happening after I recreated my Plex server (identical server name, IP, etc).

**Screenshot**
![Screenshot 04-01-2023 at 06 04 17 PM](https://user-images.githubusercontent.com/811008/229325074-2570982e-90a3-4cd1-a18d-bd4e6c5b71d0.png)

**Logs (Logs directory where Ombi is located)**
[log20230401.txt](https://github.com/Ombi-app/Ombi/files/11130914/log20230401.txt)

**Desktop (please complete the following information):**
 - OS: [Win11 22H2]

**Ombi Version (please complete the following information):**
 - Version [4.35.10 ]
- Media Server [Plex]
- Database Type:  Sqlite

NOTES:  
-I already verified that the user does **not** have a Disabled role.  
-I can authenticate using my plex account for other similar services like Tautilli without issues.

**Comment by aj3x** [comment]
I had the same issue. Try re-importing your users from Plex, if your username on Ombi doesn't match the user on Plex it doesn't work.
I deleted my user first but I'm not sure that is necessary.

If that doesn't work, I had also deleted and re-added the Plex server on Ombi.

**Comment by Alenux55** [comment]
Looks like the issue was that my Ombi.db file (located at /opt/Ombi) was erased during the upgrade. Luckily, it was automatically backed up before the upgrade so I was able to restore it. I can now log into Ombi with both Plex accounts and with my local admin account.

**Comment by mkanet** [comment]
@Alenux55 was able to also recover mine doing the same thing. Thanks for tip!  Now I can authenticate both ways again.
