### ISSUE TITLE
Repeating MySQL Error

### ISSUE THREAD

**Issue by jacobq11** [Ombi-app/Ombi#4905]
**Describe the bug**
MySQL Error. A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext.

**To Reproduce**
1. read the logs

**Expected behavior**
No errors

**Screenshots**
![image](https://user-images.githubusercontent.com/3047639/232090970-6f06a4c7-1656-43e2-8ead-baae895ca65a.png)

**Logs (Logs directory where Ombi is located)**
Log posted above

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Ombi Version (please complete the following information):**
 - Version 4.35.15
- Media Server Plex
- Database Type: MySQL

**Additional context**

**Comment by tidusjar** [comment]
This should now be fixed in develop as part of  https://github.com/Ombi-app/Ombi/commit/de4baade9f87248d77106ff1a313a498870f4fb3
