### ISSUE TITLE
Power Users - Blank Page - 403 Sonarr/Radarr 

### ISSUE THREAD

**Issue by thorin8k** [Ombi-app/Ombi#4906]
**Describe the bug**
When a user accesses the application with "Power User" permisson some 403 errors happens on Sonarr / Radarr calls and after that, the user can only see a white screen (when reloading)

**To Reproduce**
1. Login with a user with "Power User" permisson
2. Check inspector for 403 logs on `/api/v1/Settings/Sonarr` and `/api/v1/Settings/Radarr`
3. Reload screen
4. Now you can only see a white screen until you clear your browser data (session)

Extra: I also saw that this kind of users cannot select any profile/quality options when requesting something if they are power users.

**Expected behavior**
This 403 error should not broke the entire website, also they should be allowed to choose 

**Screenshots**
<img width="670" alt="image" src="https://user-images.githubusercontent.com/50626175/232238726-3bf5d4cc-2acf-445a-bb26-ef768acddc27.png">

<img width="540" alt="image" src="https://user-images.githubusercontent.com/50626175/232239060-55b97173-23e8-4697-a3dc-878ae8c0cf6e.png">

**Desktop (please complete the following information):**
 - OS: Windows 11 / 10

**Ombi Version (please complete the following information):**
 - Version 4.35.10
- Media Server Emby
- Database Type: SQLite 

**Additional context**
Second screenshot shows the modal without the profile selection inputs.

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈
