### ISSUE TITLE
Ombi source images referenced using insecure http

### ISSUE THREAD

**Issue by oregonpillow** [Ombi-app/Ombi#4923]
**Describe the bug**
When accessing Ombi on Firefox i get a warning "Parts of this page are insecure".

**Version**
Ombi v4.35.10

Sure enough, when i inspect the page contents in developer mode i can see that it's using http for pulling images:

<img width="389" alt="Screenshot 2023-05-09 at 12 24 15" src="https://github.com/Ombi-app/Ombi/assets/53374403/38a5d656-3d94-4a6f-873d-dcad260876e9">

For reference I'm using the linuxserver/ombi image, but i don't expect this to be affected by that. Correct me if i'm wrong.

Any advice appreciated.

**Comment by Grandfather-Paradox** [comment]
Are you using nginx as a reverse proxy? If so, you can add `add_header Content-Security-Policy "upgrade-insecure-requests; block-all-mixed-content;";` to your config. Attempting to load insecure content should be fixed on the dev end, but this will mitigate the issue in the meantime. It will block the content from loading if it can't upgrade the connection to HTTPS.

**Comment by oregonpillow** [comment]
@Grandfather-Paradox that fixed it, thanks! Should I should mark this issue as closed or not, since this is a band-aid fix?

**Comment by tidusjar** [comment]
We will replace all http with https, I thought we did most of them but looks like we missed a few out

**Comment by sephrat** [comment]
I believe this is because fanart used to return https URLs. Sometimes they turn it off for some reason.
