### ISSUE TITLE
OMBI [APP] don't recognize https url

### ISSUE THREAD

**Issue by gandalf764** [Ombi-app/Ombi#4951]
**Describe the bug**
there is a problem with configuring the app on a https server.
I have installed ombi via the swizzin script and this involves reaching ombi via the https protocol.
Unfortunately the app doesn't recognize the valid url and I can't use it.
Trying again by manually installing ombi then with http protocol, in this case the app has no problems,
I kindly ask if you could activate the url resolution with https protocol for the android app.
Thank you

**To Reproduce**
1. install ombi under https server
2. try to connect the app

**Expected behavior**
when i enter my server url in the android app, the server is recognized and i can use the app

**Screenshots**
![image](https://github.com/Ombi-app/Ombi/assets/41706025/d13acc67-4ac7-4022-b8eb-0a5df6d0fac4)

**Logs (Logs directory where Ombi is located)**
If applicable, a snippet of the logs that seems relevant to the bug if present.

**Desktop (please complete the following information):**

**Ombi Version (please complete the following information):**
 - Version [e.g. 4.39.1]
- Media Server plex
- Database Type: SQLite

**Additional context**

**Comment by tidusjar** [comment]
The app works perfectly fine with https. I’m using it with https. It’s likely that you don’t have a valid certificate

**Comment by Darkassassin07** [comment]
Https is not the issue as I'm using it as well.

I did have trouble getting set up as the 'https://' portion MUST be lowercase and android had auto capitalized it, though that doesn't seem to be the issue in your screenshot.


Verify you can reach ombi via a regular web browser on the same device, then copy and paste the url to be sure it's valid.


You can also use the QR code in your user profile (login via a browser, then click your user icon) as long as you've set your server url in settings>customization.

**Comment by gandalf764** [comment]
problem solved by registering a domain and installing a valid certificate..
Thank you
