### ISSUE TITLE
Deleting a request make its unable to be requested again.

### ISSUE THREAD

**Issue by Sevyn13** [Ombi-app/Ombi#4956]
**Describe the bug**
Deleting a request make its unable to be requested again. I accidentally deleted a request. When I search for the movie and try to request it again it is stuck in a state that says requested but it is not in the request list. I cannot do anything with the movie now. On the movie page it just shows a red button that says Requested.

**To Reproduce**
1. Go to request list
2. Click on delete request
3. Search for movie that you just deleted the request for
4. Click on movie

**Expected behavior**
There should be a button to request the movie

**Desktop (please complete the following information):**
 - OS: Win 10

**Ombi Version (please complete the following information):**
 - Version 4.39.1
- Media Server Plex]
- Database Type: SQLite

**Comment by sephrat** [comment]
You cannot request a movie if it's already monitored in Radarr. We consider in that case that it was requested manually.
