### ISSUE TITLE
Users without 4K permissions can request 4K movies

### ISSUE THREAD

**Issue by Pyronious** [Ombi-app/Ombi#4957]
**Describe the bug**
Users who have the "Request 4K Movie" role disabled can request 4K movies.

**To Reproduce**

1. Use a user account with "Request 4K Movie" role disabled
2. Search for a movie
3. From search results, click the "Request" banner at the bottom of the movie poster

Observed behavior:
A pop-up appears with choices for "Request" and "Request 4K"

Expected behavior:
Only the "Request" button should be available

Screenshots:
User does not have "Request 4K Movie" role enabled:
![YZsxF4Njfo](https://github.com/Ombi-app/Ombi/assets/1350786/b8c6170a-3859-4b75-9345-d72ddce4db45)

User can see and interact with "Request 4K" button:
![File](https://github.com/Ombi-app/Ombi/assets/1350786/07be3575-bb7c-42c4-ad4a-000cd1539b3e)

Example of requested 4K movie:
![AIdsgWtyKh](https://github.com/Ombi-app/Ombi/assets/1350786/751744f1-1f5d-4bbb-8eec-e97b87516e03)

**Logs (Logs directory where Ombi is located)**
There were no log entries on the date the request was made.

**Desktop (please complete the following information):**
 - OS: iOS (Safari)

**Ombi Version (please complete the following information):**
 - Version 4.39.1
- Media Server Plex
- Database Type: SQLite

**Comment by tws101** [comment]
Yes, 

We need an Auto Approve 4K 
as opposed to Auto Approve Movie (Doing both)
