### ISSUE TITLE
Plex Server Settings Revert after Webpage Refresh

### ISSUE THREAD

**Issue by MeCJay12** [Ombi-app/Ombi#4958]
**Describe the bug**
Any changes to the Plex Media Server connection settings in Ombi is reverted after a web page refresh. This includes changing the settings for the server (name, hostname/IP), deleting the server, and adding a new server. It seems to be stuck on the first server configured which, in my case, is at the wrong IP.

**To Reproduce**
1. Create database.json file
```
cat /mnt/Docker/Ombi/database.json
{
    "OmbiDatabase": {
        "Type":"MySQL",
        "ConnectionString":"Server=MySQL;Port=3306;Database=Ombi;User=Ombi;Password=password"
    },
    "SettingsDatabase": {
        "Type":"MySQL",
        "ConnectionString":"Server=MySQL;Port=3306;Database=Ombi;User=Ombi;Password=password"
    },
    "ExternalDatabase": {
        "Type":"MySQL",
        "ConnectionString":"Server=MySQL;Port=3306;Database=Ombi;User=Ombi;Password=password"
    }
}
```
2. Run docker container
```
docker run -d \
	--restart always \
	--network better_bridge \
	--name Ombi \
	-v /mnt/Docker/Ombi/:/config \
	-e TZ="America/New_York" \
	linuxserver/ombi
```
3. Go through first run wizard either adding or skipping the Plex settings here
4. Go to Media Server > Plex and change the server settings. 
5. Refresh the page and settings will revert to whatever was configured in the wizard originally

**Expected behavior**
Setting changes should persist until modified by the user

**Screenshots**
Test server created:
![image](https://github.com/Ombi-app/Ombi/assets/43658705/b6f4821a-7f68-4347-9660-30683c297447)

After Refresh:
![image](https://github.com/Ombi-app/Ombi/assets/43658705/997a2058-a2e9-467a-a35e-afa645688451)

**Logs (Logs directory where Ombi is located)**
No sure what's applicable

**Desktop (please complete the following information):**
 - OS: Windows 11

**Ombi Version (please complete the following information):**
- Version: 4.39.1
- Media Server: Plex 1.32.3.7192
- Database Type: MySQL

**Additional context**

**Comment by MeCJay12** [comment]
Quick update:

Manually editing the record in the database is persistent

**Comment by tidusjar** [comment]
Did you press the submit button on the page?

**Comment by MeCJay12** [comment]
JFC

**Comment by tidusjar** [comment]
I assume that was the issue?

**Comment by MeCJay12** [comment]
Yes. I was clicking submit on the individual server settings but not again in the larger media server settings. I spent way too long troubleshooting this.
