### ISSUE TITLE
iPhone mobile app displaying wrong server version - will not allow login

### ISSUE THREAD

**Issue by antoniobalonieo** [Ombi-app/Ombi#4976]
**Describe the bug**
iOS app version 2.14.0 displays 'Wrong Server Version. The URL you are using looks to be incorrect, please verify that it's the correct server'. server is accessible via direct url

**To Reproduce**
1. Open Ombi app on iOS
2. type server url
3. click next 
4. error message appears at top of app
5. scanning QR code produces same message

**Expected behavior**
expected to be logged into my Ombi 

**Desktop (please complete the following information):**
 - OS: iOS 16.5.1

**Ombi Version (please complete the following information):**
 - Version 4.42.1
- Media Server Plex 
- Database Type: SQLite

**Comment by tidusjar** [comment]
Email me your Ombi url and I’ll take a look.

**Comment by antoniobalonieo** [comment]
I tried to login again today and it just worked. not sure what had changed but lets blame DNS.
