### ISSUE TITLE
Ombi doesn't sync plex servers using credentials

### ISSUE THREAD

**Issue by aluvare** [Ombi-app/Ombi#4980]
### Summary

I'm trying to connect plex as media server and I cannot discover my plex server:

![image](https://github.com/Ombi-app/Ombi/assets/16783660/53268395-441d-40d4-a715-185113c60220)

### Ombi Version

4.39.1

### What platform(s) does this occur on?

Docker

### What database are you using?

SQLite (Default)

**Comment by tidusjar** [comment]
Need the logs.

**Comment by oOStroudyOo** [comment]
Sorry if it feels like I'm patronizing you.
Sometimes technical people can overlook the simple things. I do it myself sometimes.

Does your container / host definitely have internet connection?
Also on Plex, if you go to Settings and click General under your Server name, does it show that you've claimed the server?

Have you tried manually adding the server on Ombi using server IP and etc?
