### ISSUE TITLE
Publish app in f-droid

### ISSUE THREAD

**Issue by ristein** [Ombi-app/Ombi#4984]
### Summary

I'm used to finding open-source software on f-droid, not on google.
Would be great if Ombi could be there too

### Ombi Version

4.39.1

### What platform(s) does this occur on?

Linux

### What database are you using?

SQLite (Default)

**Comment by tidusjar** [comment]
No current plans to release outside the Google Play Store

**Comment by sephrat** [comment]
Also, Ombi mobile app is not open source.
