### ISSUE TITLE
Plex Friend not being imported

### ISSUE THREAD

**Issue by Arnauec** [Ombi-app/Ombi#4989]
### Summary

I have two Friends on Plex, I'm able to successfully import one (and if I delete it it gets re-imported as expected), but the other one won't get imported.

The only difference I can see in them is that one has a Name and an username (failed import), and the other only has a username. But I doubt this is it.

<img width="1790" alt="image" src="https://github.com/Ombi-app/Ombi/assets/90959322/63dfa2f1-472a-4938-9b44-4fce21c5c4a0">

<img width="1551" alt="image" src="https://github.com/Ombi-app/Ombi/assets/90959322/467fe48d-4dfa-48cd-8667-323e9a6c0ab7">

Any configuration or permission on my friend side that I should be aware of? When I trigger the User Import it runs successfully and no logs are generated.

Also worth mentioning, the friend that isn't syncing has its own NAS and we are sharing them between us. The friend that was successfully imported only has access to my shared folders.

Thank you!

### Ombi Version

 4.39.1

### What platform(s) does this occur on?

Docker

### What database are you using?

SQLite (Default)

### Relevant log output

```shell
When I run the User Import there are no logs being generated related with the import.
```

**Comment by tidusjar** [comment]
That is odd. 

I would have expected some logs when running the importer to tell you why it didn’t import. 

Can you run the importer manually and check the logs?

**Comment by vghoost360** [comment]
same problem here have it for a few days now reinstalled everything on docker even have used new configs for plex and ombi but it will not import new registerd users that have signed up the last 3 months or so checked users in yml no difference with other users only thing making them differend is there sign up date

**Comment by tidusjar** [comment]
What versions you all running?

**Comment by TheDarkOne96** [comment]
I have the same issue, no logs are generated when the importer function is called.
I can still see the missing users using this link: https://plex.tv/api/users?X-Plex-Token=PLEX_TOKEN

**Comment by klepp0906** [comment]
same issue.  super weird.   wife was in my ombi until some seemingly random point a day or two ago.   only things i recall changing in the last few days was removing some items from her watchlist on plex.   (watchlist request is set up)  

now she's not there and no matter how many times or ways i try to run the importer she isnt coming back lol.

**Comment by tidusjar** [comment]
That’s helpful, thank you.

**Comment by tidusjar** [comment]
Can someone try the new build?

**Comment by tidusjar** [comment]
@klepp0906 are you able to send me the output from the API call?

**Comment by klepp0906** [comment]
sure, will have to run it again RQ.  ill pastebin it and PM you in discord or?

**Comment by tidusjar** [comment]
Ok, found the issue.

The Plex API can report users as "Home" users if they were a pure home user and then converted to a non-managed account.
I recently added a check to not add home users by checking the `HomeUser` attribute from the API, thinking that it would only be true for pure home users.

I've now removed that check and it will all work as it previously did.

**Comment by Arnauec** [comment]
Hey @tidusjar, I can confirm that it works, I'll close the issue. Thank you very much! When can we expect a release? Running the docker version and would be more convenient to just pull it :)
