### ISSUE TITLE
Landing Page with Text Causes Continue Button to not be visible.

### ISSUE THREAD

**Issue by OcifferAction** [Ombi-app/Ombi#5046]
### Summary

I only have a few sentences on my landing page, but on smaller phones it blocks out the continue button for my users to log in. I'm unable to scroll any further down. On my higher resolution Galaxy 21 I can see the continue button, but I have to keep the message very short. I've attached a screenshot from my phone.
[https://imgur.com/UJV6woK](https://imgur.com/UJV6woK)

### Ombi Version

4.43.5

### What platform(s) does this occur on?

Linux

### What database are you using?

SQLite (Default)

**Comment by ExtremeFiretop** [comment]
I can confirm this is still an issue with the current version of Ombi, I just noticed this on Ombi 
4.43.21 for Windows.

**Comment by ExtremeFiretop** [comment]
@OcifferAction 

This is fixed as of version 4.43.22
