### ISSUE TITLE
TMDB API token is broken 

### ISSUE THREAD

**Issue by ahaverty** [Ombi-app/Ombi#5077]
### Summary

TMDB requests are failing
This token is reporting as invalid.
https://github.com/Ombi-app/Ombi/blob/develop/src/Ombi.TheMovieDbApi/TheMovieDbApi.cs#L31

### Ombi Version

4.43.11

### What platform(s) does this occur on?

Windows

### What database are you using?

SQLite (Default)

**Comment by tidusjar** [comment]
The token ombi uses is working fine
