### ISSUE TITLE
Ombi over http using Android app Issue

### ISSUE THREAD

**Issue by sunnyd24** [Ombi-app/Ombi#5097]
### Summary

**Cannot connect to Ombi server using URL `http://192.168.1.50:5000/` which previously worked in Android App.**
**Error shown in Android app is "Wrong Server Version".**

Ombi server version: 4.43.14 (Windows 11)
Android App version: 2.17.2 (cannot rollback to previous version using Play Store)

### Ombi Version

Ombi server version: 4.43.14 (Windows 11) & Android App version: 2.17.2

### What platform(s) does this occur on?

Windows

### What database are you using?

SQLite (Default)

### Relevant log output

```shell
Nothing in server logs about this issue.
```

**Comment by ryanjoachim** [comment]
Confirming the same behavior as of the 03/11/24 app update. Exact same server, OS, and app versions.

Navigating to the existing Application URL from a browser redirects correctly and I am able to sign in (in Chrome and Firefox).

The `Open Mobile App` button/link in the browser does still open the Ombi app, but no server details are passed through.

**Comment by sunnyd24** [comment]
http seems to be working OK with android app v2.15.2.

**Comment by vesper1978** [comment]
Same issue here. Sever version is 4.43.11, and Android app version is 2.17.2.

**Comment by samcroft7** [comment]
Same issue here. Server version is 4.43.5 and Android app version is 2.17.2

**Comment by ElRobinio** [comment]
Also experiencing the same issue, tried on 2 different mobile devices and both experience the same issue.

Thought it was me at first, as I have NGINX setup with both https and http available, and recently I'd configured HTTP Strict Transport Security which breaks http in the browser until the HSTS policy is deleted. However removed this form NGINX, reinstalled the app on the phones, still the same.

**Comment by tidusjar** [comment]
This was resolved
