### ISSUE TITLE
Mobile App not working

### ISSUE THREAD

**Issue by drewzherenow** [Ombi-app/Ombi#5098]
### Summary

Hello, 

I have been running Ombi for quite some time now and love every bit of it. I am having an issue though with trying to access it through the app. Everything works with the browser, but unfortunately, the app on iphone does not work when trying to connect to the url or using the qr code method. I keep getting a error stating, Wrong Server Version "The url you are using looks to be incorrect, please verify that its the correct server."

I have made sure that I am fully updated on the Ombi Server and I used another computer thinking that there may be a software incompatibility with the new update. Please Help. 

### Ombi Version

4.43.14

### What platform(s) does this occur on?

Windows

### What database are you using?

SQLite (Default)

**Comment by Starstrike** [comment]
Make sure you have the latest version of the app as this was just recently fixed and rolled out to the stores.
