### ISSUE TITLE
iOS app reports wrong server version.

### ISSUE THREAD

**Issue by jhawk44** [Ombi-app/Ombi#5100]
### Summary

Others in the subreddit have reported this, seems to be affecting Android as well.  I was unable to connect with the mobile app this morning.  I troubleshooted my account, which was not the cause.  I noticed that was a ways behind on updates (sorry, I don't recall the exact version I was on before).  I downloaded the current x64 version as of 3-24-24.  Upon installation and replacement of my backed up db files, I am still unable to connect.  Though now it tells me that my server version is wrong.

Per recommendations of others on reddit, I attempted to delete the app, re-install it, then use the QR code to log in the first time.  This does not resolve the issue.  I have my users leveraging the web version for now, but most REALLY prefer the mobile client.  Please let me know if there is anything I can do to help.

### Ombi Version

4.43.14

### What platform(s) does this occur on?

Windows

### What database are you using?

SQLite (Default)

**Comment by Yob42** [comment]
Same

**Comment by Groodles** [comment]
I have the same issue but with 4.43.5 (Latest Stable)

**Comment by OptimiStick** [comment]
Same, running version 4.43.5 , http with :port defined , no reverse proxy / SSL.  IOS app reports wrong server version, browser works fine.

**Comment by Starstrike** [comment]
App updates should be available in the stores that fix this issue.

**Comment by anon1y4012** [comment]
I'm having the same issue, up to date on both server and iOS client side. Any thoughts?

**Comment by OptimiStick** [comment]
> I'm having the same issue, up to date on both server and iOS client side. Any thoughts?
the updated client app fixed my issue.

**Comment by anon1y4012** [comment]
> > I'm having the same issue, up to date on both server and iOS client side. Any thoughts?
> 
> the updated client app fixed my issue.

Yeah, doesn't do anything for me. Uninstalled, reinstalled, etc.

Neither the QR, nor the URL works.

**Comment by tidusjar** [comment]
Send me your Ombi url to tidusjar@gmail.com

**Comment by anon1y4012** [comment]
Apologies, this was simply a port forwarding issue. Don't be like me, check your ports.

**Comment by OptimiStick** [comment]
Glad you got it fixed!
