### ISSUE TITLE
App (iOS & Android) crashes when selecting all episodes via "Select Season" in season on request

### ISSUE THREAD

**Issue by ghotso** [Ombi-app/Ombi#5111]
### Summary

When I want to request a TV-Show in one of the Ombi Apps (happens on both for me, iOS and Android app) and click on + Episodes for requesting specific episodes/seasons, and then on + again in the upper right corner to select "Select Season" the app crashes every time. 
<img width="645" alt="Screenshot_iPhone_2024-04-28_0438" src="https://github.com/Ombi-app/Ombi/assets/168240713/c9bd19e4-69e3-411b-b619-0b345b74cd79">

Nothing to find in logfile about that, but can provide if needed. 

### Ombi Version

4.43.5

### What platform(s) does this occur on?

Docker

### What database are you using?

SQLite (Default)

**Comment by tidusjar** [comment]
Just taking a look now, I can repro it.

Will push out an OTA fix soon

**Comment by tidusjar** [comment]
Fixed.

Open the app, force close and it will download the new update.

**Comment by ghotso** [comment]
Nice, it is working like a charm now.
Thanks for the really quick fix! 🤯
