### ISSUE TITLE
Missing arm64 develop artifact

### ISSUE THREAD

**Issue by aptalca** [Ombi-app/Ombi#5116]
### Summary

It seems the ci workflow failed to upload the arm64 tarball for the latest develop build, v4.43.20:

https://github.com/Ombi-app/Ombi/actions/runs/9086772100/job/24973373239

Can it be rerun?

Thanks

### Ombi Version

v4.43.20

### What platform(s) does this occur on?

Docker

### What database are you using?

SQLite (Default)

**Comment by tidusjar** [comment]
Very odd! I’ll sort it!

**Comment by tidusjar** [comment]
It’s there now
