### ISSUE TITLE
Hello! The user '---' has requested --- but it could not be added. This has been added into the requests queue and will keep retrying

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [Ombi-app/Ombi#5125]
### Summary

Some of requests get stuck like in title of this issue. I made sure that API keys are correct and I tested connections from ombi and it said `Successfully connected to Sonarr!` as example. So why it keeps doing this?

### Ombi Version

4.43.5

### What platform(s) does this occur on?

Docker

### What database are you using?

SQLite (Default)

**Comment by tidusjar** [comment]
This only happens when we we cannot send it to Sonarr. Need some logs

**Comment by EsmailELBoBDev2** [comment]
> This only happens when we we cannot send it to Sonarr. Need some logs

sure but as I can't provide logs of the error itself as I really do not know when it happens, I will send whole log...https://privatebin.net/?3ab9af0fa0030067#CS73eSpNsUJKLWPJNPKuZXSXWBinUKEJSLufX6uVF6RL
___
IT seems 
```
ombi  | 2024-07-01T03:55:57.481487666Z       StatusCode: BadRequest, Reason: Bad Request, RequestUri: http://sonarr:8989/api/v3/series/
```
Which is weird because some pass and when I test connection to  sonarr in ombi I get 
![image](https://github.com/Ombi-app/Ombi/assets/28893833/6d281908-04df-4c56-bb25-782d9299ac06)

**Comment by tidusjar** [comment]
You haven't selected a default root folder. That's the problem. Set that and it will work going forward

**Comment by EsmailELBoBDev2** [comment]
> You haven't selected a default root folder. That's the problem. Set that and it will work going forward

oh but I did select them before and it used to work, weird it dissected from itself..but thanks!

**Comment by EsmailELBoBDev2** [comment]
> You haven't selected a default root folder. That's the problem. Set that and it will work going forward

sorry to bother again but already requested (and failed to add) content, will be auto added or do I need to re-add them?

**Comment by tidusjar** [comment]
It will get auto added. It's in a queue and will retry in a few hours

**Comment by EsmailELBoBDev2** [comment]
Hello, The issue is still there not sure why...
![image](https://github.com/Ombi-app/Ombi/assets/28893833/66861075-56d9-4f30-b5f5-5c88bfd8d846)
https://privatebin.net/?a4191b110df57d4f#ETkFzHiM1X8BqMMiPLyvwguYat8akxDXLKcnYrcxTZ6W
