### ISSUE TITLE
email notification test failing

### ISSUE THREAD

**Issue by jhmc93** [Ombi-app/Ombi#5126]
### Summary

I keep getting an error when testing the notifications for my emails
my logs are below:
![Screenshot 2024-07-03 132834](https://github.com/Ombi-app/Ombi/assets/50001717/48d7a518-24fd-4b79-8f99-76effbde48c1)

### Ombi Version

4.43.5

### What platform(s) does this occur on?

Docker

### What database are you using?

SQLite (Default)

**Comment by tidusjar** [comment]
Are you sure that your settings are correct for your email provider? e.g ports are correct?

**Comment by jhmc93** [comment]
I'm using google so I've set up it using the 2fa app password as documented and the right port which is 587 and host which is smtp.gmail.com

**Comment by tidusjar** [comment]
I just set it up using GMail to ensure nothing has broke and it's working for me.

The test will fail if there are no admin users with an email address (Check the user management page). But it's working for me using the following:
![image](https://github.com/Ombi-app/Ombi/assets/6642220/a70a4695-c59e-4b7b-b3c6-087541f52cb8)

**Comment by jhmc93** [comment]
Do u have 2FA on your gmail?, here’s my setup:
[
![IMG_0791](https://github.com/Ombi-app/Ombi/assets/50001717/6fa0f385-296f-4d2a-9f96-28e036d7a4a9)
![IMG_0790](https://github.com/Ombi-app/Ombi/assets/50001717/4deff8be-75b1-4cd2-90d9-3a86d8337b38)
](url)

**Comment by tidusjar** [comment]
Yes, 2fa is also setup. Try changing your email sender to match your username. As something could be blocked on the google side as it looks like your spoofing another address

**Comment by jhmc93** [comment]
I will drop you a message later, to tell you the results, as right now I have to go out, so that’s why my screenshots in my last post where off my phone. But I’ll be back in contact in about an hour

**Comment by jhmc93** [comment]
I'm still having the same problem. I'm wondering if it could be pfsense blocking it?

**Comment by tidusjar** [comment]
Error is there at the bottom

> User 'jhmc931' has no email address set on their user profile.

**Comment by jhmc93** [comment]
It’s not the error. That was a test one to see if it was pfsense, for the one I’ve posted on this issue board is a different machine. With only one user. What I showed in previous screenshots. So nothing to do with that error u said. :)

**Comment by jhmc93** [comment]
Can anyone help if not I’ll just have to try something else

**Comment by tidusjar** [comment]
The original error just indicates that it timed out while talking to the SMTP provider. I cannot reproduce this and is likely an environmental issue with Ombi talking to that SMTP server.

**Comment by jhmc93** [comment]
Turns out it was my vpn (Surfshark). I had a an idea to pass through the server bypassing my vpn and it all worked, thanks for your help
