### ISSUE TITLE
Requests > TV Shows page is missing features and options that the Requests > Movies page has

### ISSUE THREAD

**Issue by Wheau** [Ombi-app/Ombi#5128]
### Summary

The `Requests > Movies` and `Requests > TV Shows` do not have the same features and options, specifically:

1. The `Requests > Movies` page has a column of checkboxes to select multiple requests simultaneously, but the `Requests > TV Shows` page does not.
2. On the `Requests > Movies` page, clicking the `Options` button on a request yields four choices: `Approve Request`, `Deny Request`, `Mark Available`, and `Delete Request`. However, on the `Requests > TV Shows` page, the button only reveals one choice: `Delete Request`.

See the attached screenshots. These differences are present in every subsection (e.g., `All Requests`, `Pending Requests`, etc.) and persist across three desktop browsers (Chrome, Firefox, and MS Edge) and a mobile browser (Safari on iPhone).

![Requests  - Movies page](https://github.com/Ombi-app/Ombi/assets/175263137/031bdbc3-98e9-4288-ae73-29b5c120ec25)
![Requests - TV Shows page](https://github.com/Ombi-app/Ombi/assets/175263137/8bcb943b-1a64-4843-8b4f-4e7303f30ab8)
![Requests - Movies - Options](https://github.com/Ombi-app/Ombi/assets/175263137/e9ffbc87-8e9a-4532-b42f-eebd2787783a)
![Requests - TV Shows - Options](https://github.com/Ombi-app/Ombi/assets/175263137/147abd92-4df7-409b-90a2-806d6a0f6e7a)

### Ombi Version

 4.43.22

### What platform(s) does this occur on?

Docker

### What database are you using?

SQLite (Default)

**Comment by tidusjar** [comment]
This is expected behaviour. 

Because you bc an have multiple requests of the same show they show as one grouping on the pages you are on.

**Comment by tidusjar** [comment]
Maybe I don’t understand, can you please upload a screenshot?

**Comment by Wheau** [comment]
Sure thing, here are two screenshots in which I clicked on the `Options` button of one of the requests. I put red arrows to point out the differences and show what the `TV Shows` page is missing.

![Ombi - Requests - Movies](https://github.com/Ombi-app/Ombi/assets/175263137/9714c40f-7d0c-4078-88b2-1d1e4544cce4)
![Ombi - Requests - TV Shows](https://github.com/Ombi-app/Ombi/assets/175263137/ca3d133b-e99b-4be8-993b-f732f30757d0)

**Comment by tidusjar** [comment]
Ah yes ok. They are not available for tv currently. 

To manage the request for tv you need to go into the show and scroll to the bottom. This is not a bug, but intended behaviour

**Comment by Wheau** [comment]
I see, then could we change this to a feature request? The checkbox column and the additional `Options` choices are extremely convenient for managing movie requests.

**Comment by tidusjar** [comment]
How would it behave when a TV Show has multiple requests under it? 

e.g. 
User 1 has requested Season 2
User 2 has requested Season 4

**Comment by Wheau** [comment]
The checkbox column and addition three `Options` choices are still missing. See the screenshot below.

<img width="1183" alt="Screenshot 2024-07-11 153143" src="https://github.com/user-attachments/assets/2ee5b4f7-b0d0-47d9-98fd-1fd61eb0832e">

In case it's helpful, here is a comparison of an empty `Movies` request list and an empty `TV Shows` request list. The `Movies` pages still show the checkbox column, whereas the `TV Shows` pages do not.

<img width="1194" alt="Screenshot 2024-07-11 155033" src="https://github.com/user-attachments/assets/f55e4db6-0fff-4e86-8a36-6bd71de7bbaf">
<img width="1196" alt="Screenshot 2024-07-11 160520" src="https://github.com/user-attachments/assets/4d33bc97-c132-4c04-94e6-b6eec9c94986">

**Comment by DJHanceNL** [comment]
Yea i came here for this. i had 100+ movies requests and 100+ tv shows. 

movies where gone in 2 clicks, but to remove the tv shows i had to do it manually 100 times
