### ISSUE TITLE
Re-request Issue in Ombi: Film/Series Not Downloaded After Deletion and Re added to plex watchlist

### ISSUE THREAD

**Issue by An0malija** [Ombi-app/Ombi#5170]
### Summary

Description:

There appears to be an issue with re-requesting films or series through Ombi. When a user (any user) requests a movie or series, it successfully downloads and is added to Plex (using Radarr/Sonarr for automation). However, if the movie or series is later deleted from the disk, Radarr/Sonarr, and Ombi (including the request being removed), and then another user tries to request the same movie or series after a few months, Ombi doesn't recognize or pick up the request from Plex’s Watchlist.

Steps to reproduce:
User A requests a movie/series through Ombi.
Radarr/Sonarr successfully downloads it, and the movie/series is added to Plex.
After a couple of months (or hours, days), the movie/series is deleted from the disk, Radarr/Sonarr, and Ombi (request is fully removed).
A few months later (or hours, days), User B requests the same movie/series through Ombi.
Ombi does not detect or process the request, even though it no longer exists in the library or automation tools.
Expected Behavior:
When the movie or series is re-requested by a different user after it has been deleted from the system, Ombi should recognize the request and trigger the download via Radarr/Sonarr.

Current Behavior:
Ombi does not seem to recognize the re-request of the same content and does not trigger Radarr/Sonarr to download it again.

Environment:
Ombi version: Latest
Plex version: Latest
Radarr version: Latest
Sonarr version: Latest
OS: Ubuntu Server 20.04 (Docker)
Logs:
Please let me know if further logs are required for troubleshooting this issue.

Thank you!

### Ombi Version

4.44.1  (latest)

### What platform(s) does this occur on?

Docker

### What database are you using?

SQLite (Default)

**Comment by tidusjar** [comment]
Thanks for the detailed report. 

A few questions 

1. when you say the second user is requesting it, you mentioned via the watchlist. Is this the scenario? The second user adds it to the watchlist and then it’s not being added?

1. how was the original request added? 

1. Is the request still present in Ombi?

**Comment by An0malija** [comment]
Hei,

Yes, we are discussing the Plex watchlist integration with Ombi. Essentially, a movie or TV show can only be added once to Plex, and it is then grabbed by Ombi and sent to Radarr/Sonarr. When you completely delete this movie/TV show from the disk, including from Radarr/Sonarr with history also deleted, from the Plex watchlist, and the request deleted in Ombi, all data for the movie/TV show is removed.

However, there is no way for this movie/TV show to be grabbed again from the Plex watchlist. It will not be sent to Radarr/Sonarr again. The request does not appear in Ombi anymore for a movie/TV show that was once added and then deleted from everywhere. If you manually click and request it in Ombi, it will download again.

For this reason, I have to use Overseerr. With Overseerr, it works as expected: you put a movie on the Plex watchlist, it gets downloaded, and then you delete the movie from everywhere. When you or another user adds it to the Plex watchlist again, it gets grabbed and downloaded again. This functionality does not work for me with Ombi, but it is essential because why keep a 400GB TV show on disk if nobody watches it? If someone wants it in the future, why is it not grabbed from the Plex watchlist and downloaded again?

We use the Plex watchlist because it is the only option for people who are not very tech-savvy, like my father. It’s best to have one application that contains everything.

**Comment by An0malija** [comment]
Great, so with the new update, this will work? I’ll try it out once the patch is released. It’s good that I asked here. On the Discord Ombi channel, they said it’s not meant for adding, deleting, and then re-adding things over time.
